'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js'])run(path.join(root,'assets',f));
run(path.join(root,'assets','intake-v2.1.js'));run(path.join(root,'assets','intake-v5.3.js'));run(path.join(root,'assets','intake-v5.4.js'));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V54,I=global.OBOL_INTAKE_V54,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v5.4 initializes current release state in its historical layer',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.4.0');assert.strictEqual(s.obolVersion,'5.4.0');assert.strictEqual(s.ui.dashboard54.showCanonicalAdvance,true);});
test('v5.4 advances five partial persistence sections without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[57,44,26,0,45,80]);assert.strictEqual(M.advancedKeys.length,5);});
test('all v5.4 persistence owners meet the delivery-ready floor',()=>{const r=C.cardReadiness52(lanes);for(const id of M.cardIds){const c=card(id),row=r.byCard[id];assert(c&&c.evidence45&&c.evidence45.source==='v5.4',id);assert(row&&row.ready,id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);assert(c.report47&&c.report47.traceable,id);}});
test('forged ticket proof creates ticket material but never privilege',()=>{let p=I.proof54('diamond-ticket54','impacket-ticketer -request ...','Saving ticket in analyst.ccache');assert(p.success&&p.facts.includes('persistence.diamond_ticket')&&p.facts.includes('kerberos.tickets'));assert(!p.facts.includes('access.admin'));p=I.proof54('sapphire-ticket54','impacket-ticketer -request -impersonate admin ...','Saving ticket in admin.ccache');assert(p.success&&p.facts.includes('persistence.sapphire_ticket'));});
test('Skeleton Key and custom SSP require explicit success output',()=>{let p=I.proof54('skeleton-key-lifecycle54','mimikatz.exe "misc::skeleton"','misc::skeleton startup');assert(!p.success);p=I.proof54('skeleton-key-lifecycle54','mimikatz.exe "misc::skeleton"','Skeleton Key patch applied: OK');assert(p.success&&p.facts.includes('persistence.skeleton_key'));p=I.proof54('custom-ssp-lifecycle54','mimikatz.exe "misc::memssp"','memssp loaded OK');assert(p.success&&p.facts.includes('persistence.custom_ssp'));});
test('DCShadow proof requires explicit directory readback marker',()=>{let p=I.proof54('dcshadow-lifecycle54','mimikatz.exe "lsadump::dcshadow /push"','DCShadow push started');assert(!p.success);p=I.proof54('dcshadow-lifecycle54','Get-ADUser demo -Properties Description','SamAccountName : demo\nDescription : obol-v54-proof');assert(p.success&&p.facts.includes('persistence.dcshadow'));});
test('dashboard exposes historical v5.4 canonical delta and corrected v5.3 milestone',()=>{const d=C.northStarDashboard54(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance54.delta,5);assert.strictEqual(d.canonicalAdvance54.toImplemented,57);assert(d.milestones.some(x=>x.release==='v5.4'&&x.implemented===57));assert(d.milestones.some(x=>x.release==='v5.3'&&x.implemented===52));});
test('README sync generator remains derived from the live Build Next model after later releases',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('OBOL-BUILD-NEXT:START'));assert(/Canonical methodology:\*\* \d+\/127 fully implemented \(\d+%\)/.test(out));assert(out.includes('North Star Dashboard → Build Next'));});
test('v5.4 release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['methodology-v5.4.js','dashboard-v5.4.js','core-v5.4.js','intake-v5.4.js','app-v5.4.js','obol-v5.4.css'])assert(idx.includes(x),x);assert(wf.includes('Run v5.4 regression suite'));assert(wf.includes('Check README Build Next synchronization'));assert(/Current release: \*\*v\d+\.\d+\*\*/.test(readme));assert(readme.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(changelog.includes('## v5.4'));});
test('sanitized export retains historical v5.4 behavior and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.4 tests passed`);
