'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V73,P=global.OBOL_PROJECT_V73,S=global.OBOL_SOURCE_DELIVERY_V73;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.3 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.3.0');assert.strictEqual(s.obolVersion,'7.3.0');assert.strictEqual(C.currentProjectModel,C.projectModel73);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard73);assert.strictEqual(p.release,'v7.3');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[108,19,0,0,85,100]);});

test('mitm.md is atomized into ten complete source units with one explicit supersession',()=>{const ids=['mitm.listen','mitm.ntlm-self-relay','mitm.ntlm-ldaps','mitm.ntlm-smb','mitm.ntlm-http','mitm.ntlm-mssql','mitm.ntlm-netlogon','mitm.kerberos-http','mitm.kerberos-smb','mitm.kerberos-ldaps'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'mitm.md',id);assert.strictEqual(u.auditedIn,'7.3',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.strictEqual(unit('mitm.ntlm-self-relay').auditStatus,'superseded');for(const id of ids.filter(x=>x!=='mitm.ntlm-self-relay'))assert.strictEqual(unit(id).auditStatus,'modeled',id);const f=C.sourceFidelity73(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[4,17,16,34,51,51,0]);assert.strictEqual(f.completePct,100);});

test('only the frozen MITM listening parent advances while relay parents retain historical completion',()=>{const listen=section('mitm.listen');assert(listen);assert.strictEqual(listen.status,'implemented');assert.strictEqual(listen.advancedIn,'7.3');assert.strictEqual(listen.sourceDepthAudit62.status,'modeled');assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['mitm.listen']);const ntlm=section('mitm.ntlm-relay');assert.strictEqual(ntlm.status,'implemented');assert.strictEqual(ntlm.advancedIn,'5.6');const krb=section('mitm.kerberos-relay');assert.strictEqual(krb.status,'implemented');assert.notStrictEqual(krb.advancedIn,'7.3');});

test('Build Next leaves MITM and proceeds into authenticated source inventory',()=>{const q=C.buildNext73(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,19,19]);assert(q.rows.length===19);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'authenticated.md');assert(!q.rows.some(x=>x.file==='mitm.md'));for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);});

test('MITM source units reuse mature owners and add dedicated v7.3 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('mitm.')),id);assert(c.evidence45&&c.evidence45.source==='v7.3',id);assert(c.report47&&c.report47.evidenceProfile,id);assert(c.executionContext73,id);}assert(unit('mitm.ntlm-smb').ownerCardIds.includes('ntlm-relay'));assert(unit('mitm.kerberos-http').ownerCardIds.includes('kerberos-relay60'));assert(unit('mitm.ntlm-http').ownerCardIds.includes('adcs-esc8-65'));});

test('source-delivery normalizes v7.3 owners without rewriting historical relay canonical state',()=>{assert(S);assert.deepStrictEqual(S.reconciled,[]);assert(S.reviewedHistorical.includes('mitm.ntlm-relay'));assert.strictEqual(section('mitm.ntlm-relay').advancedIn,'5.6');assert(!card('llmnr-responder').orange44||card('llmnr-responder').orange44.label!=='Validate MITM / relay paths');for(const [id,key] of [['mitm-listen-73','mitm.listen'],['ntlm-ldaps-relay-73','mitm.ntlm-relay'],['ntlm-http-relay-73','mitm.ntlm-relay'],['ntlm-mssql-relay-73','mitm.ntlm-relay'],['ntlm-netlogon-relay-73','mitm.ntlm-relay']])assert.deepStrictEqual(card(id).orange44.canonicalKeys,[key],id);const area=(global.OBOL_METHODOLOGY_V41.areas||[]).find(x=>x.id==='mitm');assert(area);const summary=(area.nodes||[]).find(x=>x.id==='relay');assert(summary&&summary.coverage==='implemented');for(const id of ['mitm-listen','mitm-ntlm-ldap','mitm-ntlm-smb','mitm-ntlm-http','mitm-ntlm-mssql','mitm-ntlm-netlogon','mitm-kerberos']){const n=(area.nodes||[]).find(x=>x.id===id);assert(n,id);assert.strictEqual(n.coverage,'implemented',id);}});

test('MITM Evidence keeps listener, relay, mutation, material, access, execution, and privilege separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.3.js'));const I=global.OBOL_INTAKE_V73;let p=I.proof73('mitm-listen-73','sudo responder -I eth0 -v','[SMB] NTLMv2-SSP Client   : 10.0.0.25\n[SMB] NTLMv2-SSP Username : CORP\\alice');assert.deepStrictEqual(p.facts,['hash.netntlm','credential.candidate']);p=I.proof73('ntlm-ldaps-relay-73','impacket-ntlmrelayx -t ldaps://dc -smb2support --add-computer TEMP$ Pass --delegate-access','Authenticating against ldaps://dc as CORP/alice SUCCEED\nAdding new computer with username TEMP$\nDelegation rights modified successfully!');assert.deepStrictEqual(p.facts,['relay.ntlm_ldaps','ad.computer_added','ad.rbcd_configured']);p=I.proof73('ntlm-http-relay-73',"certipy relay -target 'http://ca/certsrv/certfnsh.asp' -template Machine",'Saved certificate and private key to machine.pfx');assert.deepStrictEqual(p.facts,['relay.ntlm_http','certificate.material']);p=I.proof73('ntlm-mssql-relay-73','impacket-ntlmrelayx -t mssql://sql -smb2support -socks','Authenticating against mssql://sql as CORP/alice SUCCEED\nSOCKS session added');assert.deepStrictEqual(p.facts,['relay.ntlm_mssql','relay.socks']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('project model exposes the v7.3 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[51,51,0,4,16,19]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'authenticated.md');assert.strictEqual(p.recent[0].release,'v7.3');assert(p.details.sourceWave73);});

test('README generator remains structurally synchronized with current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:** 19 items'));assert(out.includes('**Canonical methodology:** 108/127 fully implemented (85%)'));assert(out.includes('**Orange source fidelity:** 4/17 source files atomized, 16/34 partial baselines decomposed, 51/51 inventoried atomic units fidelity-complete'));assert(out.includes('authenticated.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.3',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.3 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.3.js','methodology-v7.3.js','source-delivery-v7.3.js','project-model-v7.3.js','core-v7.3.js','intake-v7.3.js','app-v7.3.js','obol-v7.3.css'])assert(idx.includes(x),x);assert(runtime.includes('source-delivery-v7.3.js'));assert(!idx.includes('dashboard-v7.3.js'));assert(readme.includes('Current release: **v7.3**'));assert(changelog.includes('## v7.3'));assert(fs.existsSync(path.join(root,'docs','v7.3.md')));});

test('sanitized export advances to v7.3 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.3.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.3 tests passed`);
