'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V69,P=global.OBOL_PROJECT_V69;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v6.9 historical adapter and milestone remain intact',()=>{assert.strictEqual(typeof C.projectModel69,'function');assert.strictEqual(P.version,'6.9.0');assert.strictEqual(P.release,'v6.9');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[99,28,0,0,78,100]);assert.deepStrictEqual(P.sourceWave.delivered,['adcs.esc5','adcs.esc6','adcs.esc11']);});

test('v6.9 delivered units remain fidelity-complete after later releases',()=>{for(const id of ['adcs.esc5','adcs.esc6','adcs.esc11']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.9',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity69(lanes);assert.strictEqual(f.files.total,17);assert.strictEqual(f.partialBaseline.total,34);assert(f.files.atomized>=1);assert(f.partialBaseline.atomized>=7);assert(f.total>=19);assert(f.complete>=14);assert(f.complete<=f.total);assert(f.pending>=0);});

test('PKI-object ACL and CA-misconfiguration parents remain reconciled',()=>{for(const key of ['adcs.pki-object-acl','adcs.ca-misconfig']){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'6.9',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['adcs.pki-object-acl','adcs.ca-misconfig']);});

test('current Build Next no longer contains v6.9 delivered units',()=>{const q=C.buildNext69(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);for(const id of P.sourceWave.delivered)assert(!q.rows.some(x=>x.key===id),id);assert(q.sourceFidelity>=0);});

test('ESC5 owner separates CA backup material from forged certificate material',()=>{const c=card('adcs-esc5-69');assert(c);assert(c.commands.some(x=>String(x.run).includes('certipy ca')&&String(x.run).includes('-backup')&&x.operatorSurface40==='kali'));assert(c.commands.some(x=>String(x.run).includes('-backup')&&String(x.run).includes('-sspi')&&x.operatorSurface40==='windows'));assert(c.commands.some(x=>String(x.run).includes('certipy forge')&&String(x.run).includes('-ca-pfx')));assert(c.produces.includes('adcs.ca_private_key_material'));assert(c.produces.includes('adcs.golden_certificate'));assert(c.evidence45&&c.evidence45.source==='v6.9');assert(c.report47&&c.report47.evidenceProfile);});

test('ESC6 and ESC11 owners preserve execution-context and relay boundaries',()=>{const esc6=card('adcs-esc6-69'),esc11=card('adcs-esc11-69');assert(esc6&&esc11);assert(esc6.commands.some(x=>x.operatorSurface40==='kali'&&String(x.run).includes('-upn')));assert(esc6.commands.some(x=>x.operatorSurface40==='windows'&&String(x.run).includes('-sspi')));assert(esc11.commands.some(x=>String(x.run).includes("rpc://{{ca_target}}")&&x.tool==='certipy'));assert(esc11.commands.some(x=>x.tool==='ntlmrelayx'&&String(x.run).includes('ICPR')));assert(esc11.commands.some(x=>x.tool==='certipy'&&String(x.run).includes('auth -pfx')));assert(esc6.report47&&esc11.report47);});

test('v6.9 Evidence keeps CA keys, certificates, relay, access, and privilege separated',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v6.9.js'));const I=global.OBOL_INTAKE_V69;let p=I.proof69('adcs-esc5-69',"certipy ca -ca CORP-CA -backup",'Saved certificate and private key to CORP-CA.pfx');assert.deepStrictEqual(p.facts,['adcs.ca_private_key_material']);p=I.proof69('adcs-esc5-69',"certipy forge -ca-pfx CORP-CA.pfx -upn administrator@corp.local",'Saved forged certificate to administrator_forged.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.golden_certificate']);p=I.proof69('adcs-esc6-69',"certipy req -ca CORP-CA -template User -upn administrator@corp.local",'Got certificate\nSaved certificate and private key to administrator.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc6_certificate']);p=I.proof69('adcs-esc11-69',"certipy relay -target rpc://ca.corp.local -ca CORP-CA",'Listening on 0.0.0.0:445');assert.strictEqual(p.success,false);p=I.proof69('adcs-esc11-69',"certipy relay -target rpc://ca.corp.local -ca CORP-CA",'Got certificate\nSaved certificate and private key to dc01.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc11_relay_certificate']);for(const x of p.facts)assert(!['access.admin','access.system','foothold.windows','access.cross_domain','objective.domain_admin','capability.dcsync'].includes(x));});

test('v6.9 source-wave metadata remains historical while current Build Next output stays structurally valid',()=>{assert.deepStrictEqual([P.sourceWave.fidelityBefore,P.sourceWave.fidelityAfter,P.sourceWave.fidelityTotal],[11,14,19]);const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('Current live queue'));assert(out.includes('inventoried atomic units fidelity-complete'));assert(out.includes('Highest-priority live items'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract remains valid after v6.9',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v6.9 release wiring remains present and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.9.js','methodology-v6.9.js','project-model-v6.9.js','core-v6.9.js','intake-v6.9.js','app-v6.9.js','obol-v6.9.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v6.9.js'));assert(changelog.includes('## v6.9'));assert(fs.existsSync(path.join(root,'docs','v6.9.md')));});

test('sanitized export tracks the current release while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v6.9 tests passed`);
