'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V80,P=global.OBOL_PROJECT_V80;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}function unit(id){return (F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return !!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.0 historical milestone remains complete while the current model may advance',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(P.version,'8.0.0');assert.strictEqual(P.release,'v8.0');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[127,0,0,0,100,100]);assert.strictEqual(p.canonical.implemented,127);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);assert.strictEqual(s.obolVersion,C.VERSION);});

test('v8.0 completed the final three frozen baselines with four terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,4);assert.deepStrictEqual(P.sourceWave.modeled,['crack-hash.pxe-sccm-aes128','low-hanging.zerologon-check','persistence.add-da-membership']);assert.deepStrictEqual(P.sourceWave.superseded,['low-hanging.zerologon-reset']);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.auditedIn,'8.0',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity80(lanes);assert.strictEqual(f.partialBaseline.atomized,34);assert.strictEqual(f.partialBaseline.total,34);assert(f.files.atomized>=9);assert.strictEqual(f.files.total,17);assert(f.complete>=194);assert(f.total>=194);assert.strictEqual(f.pending,0);});

test('PXE, Zerologon, and ADD DA parents retain their v8.0 advance and conservative owners',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['crack_hash.pxe','low_hanging.zerologon','persistence.add-da']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'8.0',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert(unit('crack-hash.pxe-sccm-aes128').ownerCardIds.includes('pxe-naa61'));assert(unit('low-hanging.zerologon-check').ownerCardIds.includes('zerologon-check'));assert(unit('persistence.add-da-membership').ownerCardIds.includes('acl-group-membership-72'));});

test('unsafe Zerologon reset remains explicitly superseded and absent from the operator command surface',()=>{const u=unit('low-hanging.zerologon-reset'),c=card('zerologon-check');assert.strictEqual(u.auditStatus,'superseded');assert(/destructive|machine-account/i.test(u.reason));assert(c&&c.commands&&c.commands.length);assert(!c.commands.some(x=>/cve-2020-1472-exploit\.py/i.test(String(x.run||''))));assert(c.commands.some(x=>/zerologon-scan/i.test(String(x.run||''))));});

test('mature v8.0 owners retain source-matched PXE cracking and reversible Domain Admin membership commands',()=>{assert(hasRun('pxe-naa61',/hashcat -m 19850 -a 0/));assert(hasRun('acl-group-membership-72',/net group "Domain Admins" .*\/add \/domain/));assert(hasRun('acl-group-membership-72',/net group "Domain Admins" .*\/delete \/domain/));for(const id of P.sourceWave.delivered){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic80||[]).includes(id),owner+' lineage for '+id);}}});

test('v8.0 file-inventory transition remains historical while the live queue may shrink',()=>{assert.deepStrictEqual(P.sourceWave.fileInventoryQueue,['low_access.md','crack_hash.md','low_hanging.md','persistence.md','dom_admin.md','know_vuln_auth.md','trusts.md','valid_user.md']);const q=C.currentProjectModel(C.newState(),lanes).buildNext;assert(q.total>=0);assert(q.total<=8);assert((q.rows||[]).every(x=>x.kind==='source-file-inventory'));});

test('current project model preserves v8.0 source accounting as a floor',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=194);assert(p.source.atomicTotal>=194);assert.strictEqual(p.source.atomicPending,0);assert(p.source.filesAtomized>=9);assert.strictEqual(p.source.baselinesAtomized,34);assert((p.recent||[]).some(x=>x.release==='v8.0')||P.release==='v8.0');});

test('README generator remains a structural live projection after v8.0',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.0 historical release wiring remains complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.0.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.0.js','methodology-v8.0.js','project-model-v8.0.js','core-v8.0.js','app-v8.0.js','obol-v8.0.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.0.js','methodology-v8.0.js','project-model-v8.0.js','core-v8.0.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.0.js'));assert(!idx.includes('intake-v8.0.js'));assert(releaseDoc.includes('# Obol v8.0'));});

test('sanitized export tracks the current version while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.0 historical tests passed`);
