'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process'),os=require('os');
global.window=globalThis;global.DOMParser=function(){};const root=path.join(__dirname,'..');function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
const data=['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js'];
const core=['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js'];
for(const f of data)run(path.join(root,'data',f));for(const f of core)run(path.join(root,'assets',f));for(const f of ['intake-v2.1.js','intake-v5.3.js','intake-v5.4.js','intake-v5.5.js','intake-v5.6.js','intake-v5.7.js','intake-v5.8.js','intake-v5.9.js','intake-v6.0.js','intake-v6.1.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V61,I=global.OBOL_INTAKE_V61,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v6.1 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'6.1.0');assert.strictEqual(s.obolVersion,'6.1.0');assert.strictEqual(s.ui.dashboard61.showReleaseQuality,true);});
test('v6.1 closes five canonical gaps without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[92,34,1,0,72,99]);assert.strictEqual(M.advancedKeys.length,5);});
test('Build Next remains quality-clean before the final canonical gap',()=>{const q=C.buildNext52(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.total],[0,0,1,1]);assert.strictEqual(q.rows[0].label,'Parent-to-child trust paths');});
test('all v6.1 canonical sections have delivery-ready owners',()=>{const ready=C.deliveryReadiness52(lanes);for(const key of M.advancedKeys){const row=ready.rows.find(x=>x.key===key);assert(row&&row.status==='implemented'&&row.ready,key);}for(const id of M.cardIds){const c=card(id);assert(c&&c.evidence45&&c.evidence45.source==='v6.1',id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);assert(c.report47&&c.report47.traceable,id);}});
test('PXE keeps discovery, hash material, and NAA credentials separate',()=>{let p=I.proof61('pxe-naa61','python3 pxethief.py 1','PXE deployment found on Distribution Point DP01');assert(p.success&&p.facts.includes('sccm.pxe')&&!p.facts.includes('credential.reusable'));p=I.proof61('pxe-naa61','python3 pxethief.py 5 boot.var','$sccm$PXE$HASH');assert(p.success&&p.facts.includes('hash.sccm_pxe')&&!p.facts.includes('credential.reusable'));p=I.proof61('pxe-naa61','python3 pxethief.py 2 10.0.0.5','NetworkAccessUsername: LAB\\naa\nNetworkAccessPassword: TrainingOnly123!');assert(p.success&&p.facts.includes('credential.reusable')&&!p.facts.includes('access.admin'));});
test('TimeRoast output remains offline material below access',()=>{let p=I.proof61('timeroast61','python3 timeroast.py 10.0.0.10 -o roast.txt','$sntp-ms$USER$HASH');assert(p.success&&p.facts.includes('hash.timeroast')&&!p.facts.includes('credential.reusable')&&!p.facts.includes('access.cross_domain'));p=I.proof61('timeroast61','hashcat -m 31300 roast.txt wordlist','Recovered 1/1');assert(p.success&&p.facts.includes('credential.candidate')&&!p.facts.includes('access.admin'));});
test('child-to-parent trust material and tickets remain below cross-domain access',()=>{let p=I.proof61('trust-child-parent61',"impacket-secretsdump -just-dc-user 'ROOT$' CHILD/u:p@dc",'trust nthash: 0123456789abcdef0123456789abcdef');assert(p.success&&p.facts.includes('trust.secret_material')&&!p.facts.includes('access.cross_domain'));p=I.proof61('trust-child-parent61','impacket-ticketer -nthash x trustfakeuser','Saving ticket in trustfakeuser.ccache');assert(p.success&&p.facts.includes('kerberos.tickets')&&!p.facts.includes('access.cross_domain'));});
test('external trust validation requires a separate successful service interaction for access',()=>{let p=I.proof61('trust-external61','Get-DomainTrust -Domain a.local','TrustType: External TrustDirection: Bidirectional');assert(p.success&&p.facts.includes('trust.external')&&!p.facts.includes('access.cross_domain'));p=I.proof61('trust-external61','KRB5CCNAME=t.ccache impacket-smbclient -k -no-pass B/u@host','Type help for list of commands');assert(p.success&&p.facts.includes('access.cross_domain')&&!p.facts.includes('access.admin'));});
test('dashboard exposes v6.1 progress and release quality',()=>{const d=C.northStarDashboard61(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance61.toImplemented,92);assert.strictEqual(d.gapWave61.remainingGaps,1);assert.strictEqual(d.releaseQuality61.clean,true);assert(d.milestones.some(x=>x.release==='v6.1'&&x.implemented===92));assert(d.milestones.some(x=>x.release==='v6.0'&&x.implemented===87));});
test('release quality gate passes the live v6.1 model',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 1 canonical gaps'));});
test('release PR validator accepts v6.1 contract and rejects wrong branch',()=>{const tool=path.join(root,'tools','validate-release-pr.js'),eventPath=path.join(os.tmpdir(),'obol-v61-pr-event.json'),body='## Summary\n'+('Release summary. '.repeat(50))+'\n## Canonical methodology accounting\n92/127.\n## Conservative Evidence boundaries\nProof stays bounded.\n## Release wiring\nWired.\n## Regression coverage\nCovered.\n## Compatibility\nCompatible.';fs.writeFileSync(eventPath,JSON.stringify({pull_request:{head:{ref:'release/obol-v6.1'},title:'Obol v6.1 — canonical gap reduction',body}}));let r=cp.spawnSync(process.execPath,[tool],{cwd:root,env:{...process.env,GITHUB_EVENT_NAME:'pull_request',GITHUB_EVENT_PATH:eventPath},encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);fs.writeFileSync(eventPath,JSON.stringify({pull_request:{head:{ref:'build/obol-v6.1'},title:'Obol v6.1 — wrong branch',body}}));r=cp.spawnSync(process.execPath,[tool],{cwd:root,env:{...process.env,GITHUB_EVENT_NAME:'pull_request',GITHUB_EVENT_PATH:eventPath},encoding:'utf8'});assert.notStrictEqual(r.status,0);fs.unlinkSync(eventPath);});
test('live CI event satisfies the release PR contract',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js')],{cwd:root,env:process.env,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});
test('v6.1 release wiring is complete',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['methodology-v6.1.js','dashboard-v6.1.js','core-v6.1.js','intake-v6.1.js','app-v6.1.js','obol-v6.1.css'])assert(idx.includes(x),x);assert(readme.includes('Current release: **v6.1**'));assert(changelog.includes('## v6.1'));assert(fs.existsSync(path.join(root,'docs','v6.1.md')));assert(fs.readFileSync(path.join(root,'tests','run-v6.1-tests.js'),'utf8').includes('validate-release-pr.js'));});
test('README Build Next generator is wired through v6.1',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('1 canonical gaps'));assert(out.includes('92/127 fully implemented (72%)'));assert(out.includes('Parent-to-child trust paths'));});
test('sanitized export advances to v6.1 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v6.1 tests passed`);
