'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const cp=require('child_process');

const root=path.join(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const run=args=>cp.spawnSync(process.execPath,args.map((part,idx)=>idx===0?path.join(root,part):part),{cwd:root,encoding:'utf8'});

const sandbox={window:{},globalThis:null};
sandbox.globalThis=sandbox.window;
vm.createContext(sandbox);
for(const rel of ['data/current-release.js','data/product-hardening/product-hardening-queue.js','data/product-hardening/work-packages.js','data/product-hardening/item-test-contracts.js'])vm.runInContext(read(rel),sandbox,{filename:rel});
const release=sandbox.window.OBOL_CURRENT_RELEASE;
const identity=sandbox.window.OBOL_RELEASE_IDENTITY;
const q=sandbox.window.OBOL_PRODUCT_HARDENING;
const workPackages=sandbox.window.OBOL_PRODUCT_HARDENING_WORK_PACKAGES;
const contracts=sandbox.window.OBOL_PRODUCT_HARDENING_TEST_CONTRACTS;
assert(release&&identity&&q&&workPackages&&contracts,'v9.4 release identity, queue, work packages, and contracts load');
assert.strictEqual(release.version,'9.4.0');
assert.strictEqual(release.label,'v9.4');
assert.strictEqual(release.phase,'product-hardening');
assert.strictEqual(release.orangeBaseline,'v8.8');

for(const id of ['cc-report-version','qa-version-test']){
  const item=q.items.find(candidate=>candidate.id===id);
  assert(item,'version trust item remains in durable queue: '+id);
  assert.strictEqual(item.status,'complete',id+' is complete');
  const contract=contracts.contracts[id];
  assert(contract&&contract.acceptance.length&&contract.validationCommands.length&&contract.proofFiles.length,id+' has item-specific Definition of Done');
  for(const rel of contract.proofFiles)assert(fs.existsSync(path.join(root,rel)),id+' proof file exists: '+rel);
}
assert.strictEqual(q.tracks.find(t=>t.id==='critical-correctness').complete,3,'critical correctness advances to three completed items');
assert.strictEqual(q.tracks.find(t=>t.id==='testing-qa').complete,1,'testing/QA records the completed version identity gate');
assert.strictEqual(q.totals().complete,4,'product-hardening completed total advances by both version trust items');
assert.strictEqual(q.buildNext(1)[0].id,'cc-link-contrast','Product Build Next advances to dark-theme link contrast');
assert.strictEqual(workPackages.validate(q).length,0,'coherent work-package schema remains valid');
const rec=workPackages.recommend(q);
assert(rec&&rec.id==='accessibility-contrast-focus','next recommended package moves to accessibility/contrast/focus');
assert(rec.entryItem&&rec.entryItem.id==='cc-link-contrast','recommended package begins with the highest-priority queued item');
for(const id of ['cc-link-contrast','ux-keyboard-focus','qa-contrast-test'])assert(rec.liveItems.some(item=>item.id===id),'accessibility package carries live item '+id);

const stale=[
 '# Penetration Test Report — Draft',
 '',
 '**Generated:** 2026-08-31  ',
 '**Obol:** v8.8  ',
 '**Workspace schema:** 8.8.0',
 '',
 '```text',
 '**Obol:** v2.0',
 'Generated by Obol v2.0 inside operator evidence',
 '```',
 '',
 '---',
 '_Generated by Obol v8.8 from operator-recorded ledger state. Review every statement before delivery._'
].join('\n');
const normalized=identity.normalizeReportMarkdown(stale);
assert(normalized.includes('**Obol release:** v9.4'),'report metadata uses current release');
assert(!/^\*\*Obol:\*\*\s*v8\.8\s*$/m.test(normalized),'stale report-owned version metadata is removed');
assert(normalized.includes('_Generated by Obol v9.4 from operator-recorded ledger state.'),'report footer uses current release');
assert(normalized.includes('**Workspace schema:** 8.8.0'),'workspace schema identity remains distinct');
assert(normalized.includes('**Obol:** v2.0')&&normalized.includes('Generated by Obol v2.0 inside operator evidence'),'operator evidence payload is not rewritten');
assert.strictEqual(identity.normalizeReportMarkdown(normalized),normalized,'report normalization is idempotent');
const exported={schemaVersion:'8.8.0',obolRelease:'9.2.0',obolReleaseLabel:'v9.2'};
identity.stampState(exported);
assert.deepStrictEqual({obolRelease:exported.obolRelease,obolReleaseLabel:exported.obolReleaseLabel,schemaVersion:exported.schemaVersion},{obolRelease:'9.4.0',obolReleaseLabel:'v9.4',schemaVersion:'8.8.0'});

const app=read('assets/app-v8.8.js');
const preflight=read('tools/release-preflight.js');
const readme=read('README.md');
const hardening=read('docs/PRODUCT-HARDENING.md');
const releaseDoc=read('docs/v9.4.md');
assert(app.includes('window.OBOL_RELEASE_IDENTITY')&&app.includes('i.normalizeReportMarkdown(md)')&&app.includes('i.stampState(safe)'),'live app consumes centralized report/export release identity helpers');
assert(preflight.includes("run('version trust surfaces',['tools/validate-version-identity.js'])"),'preflight permanently gates version trust surfaces');
assert(readme.includes('Current release: **v9.4**'),'README current release is synchronized');
assert(readme.includes('**Recommended work package:** **Contrast and Focus Quality Pass**'),'README Product Build Next advances to the accessibility package');
assert(hardening.includes('## Version trust surfaces')&&hardening.includes('v9.4 completes `cc-report-version` and `qa-version-test`'),'product-hardening docs record the version trust milestone');
assert(releaseDoc.includes('# Obol v9.4')&&releaseDoc.includes('cc-report-version')&&releaseDoc.includes('qa-version-test'),'release doc records both completed queue items');
for(const forbidden of ['data/project-model-v9.4.js','assets/core-v9.4.js','assets/app-v9.4.js','assets/obol-v9.4.css'])assert(!fs.existsSync(path.join(root,forbidden)),'no fake v9.4 runtime overlay: '+forbidden);

for(const command of [
 ['tools/validate-version-identity.js'],
 ['tools/validate-current-release.js'],
 ['tools/validate-product-hardening-queue.js'],
 ['tools/validate-asset-references.js'],
 ['tools/sync-current-release.js','--check'],
 ['tools/sync-product-build-next.js','--check'],
 ['tools/validate-release-pr.js','--repo-only','--release-version=9.4']
]){
  const result=run(command);
  assert.strictEqual(result.status,0,(result.stderr||result.stdout||'').trim());
}

console.log('v9.4 Version Trust Surfaces regression tests passed.');
