'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V78,P=global.OBOL_PROJECT_V78;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.8 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.8.0');assert.strictEqual(s.obolVersion,'7.8.0');assert.strictEqual(C.currentProjectModel,C.projectModel78);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard78);assert.strictEqual(p.release,'v7.8');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[122,5,0,0,96,100]);});

test('lat_move.md is atomized into thirty-eight modeled source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,38);assert.deepStrictEqual(P.sourceWave.superseded,[]);assert.strictEqual(P.sourceWave.modeled.length,38);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'lat_move.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.8',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity78(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[9,17,29,34,187,187,0]);assert.strictEqual(f.completePct,100);});

test('only SOCKS and certificate parents advance while historical lateral-movement parents retain milestones',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['lat_move.socks','lat_move.certificate']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.8',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}for(const key of P.sourceWave.historicalCanonicalDeepened){const h=section(key);assert(h,key);assert.strictEqual(h.status,'implemented',key);assert.notStrictEqual(h.advancedIn,'7.8',key);}assert.strictEqual(section('lat_move.mssql').advancedIn,'4.3');});

test('Build Next leaves lat_move.md and proceeds into low-access source inventory',()=>{const q=C.buildNext78(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,5,5]);assert.strictEqual(q.rows.length,5);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'low_access.md');assert.strictEqual(q.rows[0].key,'low_access.webdav');assert(!q.rows.some(x=>x.file==='lat_move.md'));});

test('lateral-movement units reuse mature owners and add focused v7.8 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('lat_move.')),id);assert(c.evidence45&&c.evidence45.source==='v7.8',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext78,id);}assert(unit('lat-move.plain-psexec').ownerCardIds.includes('lateral-exec'));assert(unit('lat-move.opth-gettgt').ownerCardIds.includes('kerberos-tickets'));assert(unit('lat-move.kerb-proxychains').ownerCardIds.includes('relay-socks-78'));assert(unit('lat-move.socks-dcsync').ownerCardIds.includes('dcsync'));assert(unit('lat-move.cert-certipy-unpac').ownerCardIds.includes('certificate-movement-78'));assert(unit('lat-move.mssql-links').ownerCardIds.includes('mssql-access'));});

test('lateral-movement Evidence keeps material, authentication, access, execution, and privilege separate',()=>{global.OBOL_INTAKE_V77={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.8.js'));const I=global.OBOL_INTAKE_V78;let p=I.proof78('relay-socks-78',"proxychains impacket-mssqlclient -windows-auth 'corp/alice'@10.0.0.10 -no-pass",'SQL>');assert.deepStrictEqual(p.facts,['db.mssql_access']);p=I.proof78('relay-socks-78',"proxychains impacket-atexec -no-pass 'corp/alice'@10.0.0.10 'whoami'",'corp\\alice');assert.deepStrictEqual(p.facts,['remote.execution']);p=I.proof78('relay-socks-78',"proxychains impacket-smbexec -no-pass 'corp/alice'@10.0.0.10",'nt authority\\system');assert.deepStrictEqual(p.facts,['remote.execution','access.system']);p=I.proof78('certificate-movement-78','certipy auth -pfx alice.pfx -dc-ip 10.0.0.5','Got TGT\nSaved credential cache to alice.ccache');assert.deepStrictEqual(p.facts,['kerberos.tickets']);p=I.proof78('certificate-movement-78','certipy auth -pfx alice.pfx -dc-ip 10.0.0.5','Got hash for alice: 0123456789abcdef0123456789abcdef');assert.deepStrictEqual(p.facts,['credential.ntlm_hash']);for(const x of ['objective.domain_admin','capability.dcsync','access.admin'])assert(!p.facts.includes(x));});

test('project model exposes the v7.8 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[187,187,0,9,29,5]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'low_access.md');assert.strictEqual(p.next.key,'low_access.webdav');assert.strictEqual(p.recent[0].release,'v7.8');assert(p.details.sourceWave78);});

test('README generator remains structurally synchronized with the current model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('low_access.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.8',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.8 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v7.8.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.8.js','methodology-v7.8.js','project-model-v7.8.js','core-v7.8.js','intake-v7.8.js','app-v7.8.js','obol-v7.8.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.8.js'));assert(runtime.includes('methodology-v7.8.js'));assert(runtime.includes('project-model-v7.8.js'));assert(runtime.includes('core-v7.8.js'));assert(!idx.includes('dashboard-v7.8.js'));assert(readme.includes('Current release: **v7.8**'));assert(releaseDoc.includes('# Obol v7.8'));});

test('sanitized export advances to v7.8 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.8 tests passed`);
