'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V74,P=global.OBOL_PROJECT_V74;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.4 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.4.0');assert.strictEqual(s.obolVersion,'7.4.0');assert.strictEqual(C.currentProjectModel,C.projectModel74);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard74);assert.strictEqual(p.release,'v7.4');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[111,16,0,0,87,100]);});

test('authenticated.md is atomized into nineteen complete source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,19);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'authenticated.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.4',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity74(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[5,17,18,34,70,70,0]);assert.strictEqual(f.completePct,100);});

test('only the three frozen authenticated partial parents advance',()=>{const advanced=['authenticated.auto-scan','authenticated.coerce','authenticated.known-vulns'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.4',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);for(const key of P.sourceWave.historicalCanonicalDeepened){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.notStrictEqual(s.advancedIn,'7.4',key);}});

test('Build Next leaves authenticated.md and proceeds into SCCM source inventory',()=>{const q=C.buildNext74(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,16,16]);assert.strictEqual(q.rows.length,16);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'sccm.md');assert(!q.rows.some(x=>x.file==='authenticated.md'));for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);});

test('authenticated source units reuse mature owners and add focused v7.4 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('authenticated.')),id);assert(c.evidence45&&c.evidence45.source==='v7.4',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext74,id);}assert(unit('authenticated.bloodhound-ce').ownerCardIds.includes('bloodhound-collect'));assert(unit('authenticated.adcs').ownerCardIds.includes('adcs-enumeration55'));assert(unit('authenticated.sccm').ownerCardIds.includes('sccm-enum'));assert(unit('authenticated.kerberoast').ownerCardIds.includes('kerberoast'));for(const id of M.knownVulnerabilityOwners){const c=card(id);assert(c,id);assert((c.atomic74||[]).includes('authenticated.known-vulns-route'),id);}});

test('authenticated Evidence keeps enumeration, posture, coercion, access, execution, relay, and privilege separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.4.js'));const I=global.OBOL_INTAKE_V74;let p=I.proof74('authenticated-classic-enum-74',"nxc smb 10.0.0.10 -u 'alice' -p 'pass' --users",'sAMAccountName: alice\nsAMAccountName: bob');assert.deepStrictEqual(p.facts,['ad.user_list']);p=I.proof74('ad-posture-scan-74','PingCastle.exe --healthcheck --server corp.local','PingCastle Healthcheck report saved to ad_hc_corp.local.html');assert.deepStrictEqual(p.facts,['ad.posture_assessed']);p=I.proof74('authenticated-coercion-74',"coercer.py -d corp.local -u alice -p pass -t dc01 -l 10.0.0.5",'Coercion trigger success over RPC');assert.deepStrictEqual(p.facts,['coerce.candidate']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync','relay.success','credential.available'])assert(!p.facts.includes(x));});

test('project model exposes the v7.4 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[70,70,0,5,18,16]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'sccm.md');assert.strictEqual(p.recent[0].release,'v7.4');assert(p.details.sourceWave74);});

test('README generator remains structurally synchronized with current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:** 16 items'));assert(out.includes('**Canonical methodology:** 111/127 fully implemented (87%)'));assert(out.includes('**Orange source fidelity:** 5/17 source files atomized, 18/34 partial baselines decomposed, 70/70 inventoried atomic units fidelity-complete'));assert(out.includes('sccm.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.4',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.4 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.4.js','methodology-v7.4.js','project-model-v7.4.js','core-v7.4.js','intake-v7.4.js','app-v7.4.js','obol-v7.4.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.4.js'));assert(runtime.includes('methodology-v7.4.js'));assert(runtime.includes('project-model-v7.4.js'));assert(!idx.includes('dashboard-v7.4.js'));assert(readme.includes('Current release: **v7.4**'));assert(changelog.includes('## v7.4'));assert(fs.existsSync(path.join(root,'docs','v7.4.md')));});

test('sanitized export advances to v7.4 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.4 tests passed`);
