'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','review-v2.7.js'])run(path.join(root,'assets',f));
for(const f of ['nmap-v2.js','nmap-v2.3.js','nmap-v3.1.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,N=global.OBOL_NMAP;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v3.1 initializes discovery state and version',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.1.0');assert.strictEqual(s.obolVersion,'3.1.0');assert.strictEqual(s.ui.discovery31.profile,'discover');});
test('primary workflow promotes Discover without adding navigation clutter',()=>{assert.strictEqual(C.NAVIGATION30.primary.length,5);const d=C.NAVIGATION30.primary.find(x=>x.id==='boxes');assert(d);assert.strictEqual(d.label,'Discover');assert(/Nmap/i.test(d.help));});
test('empty workspace resumes at Nmap host discovery',()=>{const s=C.newState(),o=C.workspaceOverview31(s,[],s.activeContext);assert.strictEqual(o.stage,'discover');assert.strictEqual(o.next.href,'#/boxes');assert(/discovery/i.test(o.next.label));});
test('manually added host with no evidence is directed to baseline scanning',()=>{const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'box',ports:[]});s.activeContext={type:'host',id:'h1'};const o=C.workspaceOverview31(s,[],s.activeContext);assert.strictEqual(o.stage,'scan');assert.strictEqual(o.discovery.activeScanned,false);});
test('Nmap builder creates distinct discovery, full, and service commands',()=>{const discover=C.buildNmapCommand31({profile:'discover',target:'10.10.10.0/24'});assert(discover.includes('-sn'));assert(discover.includes('-n'));assert(discover.includes("-oA 'scans/discovery'"));const full=C.buildNmapCommand31({profile:'full',target:'10.10.10.10'});assert(full.includes('-p-'));assert(full.includes('--min-rate 1000'));const service=C.buildNmapCommand31({profile:'service',target:'10.10.10.10'});assert(service.includes('-sC'));assert(service.includes('-sV'));});
test('custom ports override profile port scope instead of duplicating it',()=>{const cmd=C.buildNmapCommand31({profile:'full',target:'10.10.10.10',ports:'80,443,445'});assert(cmd.includes('-p 80,443,445'));assert(!cmd.includes('-p-'));});
test('Nmap -sn normal output retains live hosts with no port rows',()=>{const text='Nmap scan report for 10.10.10.1\nHost is up (0.021s latency).\nNmap scan report for dc01.lab.local (10.10.10.2)\nHost is up (0.033s latency).\nNmap done: 256 IP addresses (2 hosts up) scanned';const r=N.parse(text);assert.strictEqual(r.hosts.length,2);assert.strictEqual(r.hosts[0].ip,'10.10.10.1');assert.strictEqual(r.hosts[1].hostname,'dc01.lab.local');assert.deepStrictEqual(r.hosts[0].ports,[]);});
test('normal Nmap service output still preserves open ports',()=>{const text='Nmap scan report for box.lab (10.10.10.20)\nHost is up.\nPORT    STATE SERVICE VERSION\n22/tcp  open  ssh     OpenSSH 9.2\n445/tcp open  microsoft-ds\n';const r=N.parse(text);assert.strictEqual(r.hosts.length,1);assert.strictEqual(r.hosts[0].ports.length,2);assert(r.facts.includes('smb.reachable'));});
test('v3.1 app and CSS wire a functional Nmap launchpad into Home and Discover',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v3.1.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v3.1.css'),'utf8');for(const token of ['Nmap launchpad','buildNmapCommand31','applyNmapScan','enhanceHome31','viewBoxes=function','Ingest discovered hosts'])assert(app.includes(token),token);for(const token of ['.discovery31','.generated31','.scan-badge31','.intake-discovery31'])assert(css.includes(token),token);});
test('index preserves the v3.1 layer when a later release becomes current',()=>{const src=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(src.indexOf('core-v3.1.js')>src.indexOf('core-v3.0.js'));assert(src.indexOf('nmap-v3.1.js')>src.indexOf('nmap-v2.3.js'));assert(src.indexOf('app-v3.1.js')>src.indexOf('app-v3.0.js'));assert(src.includes('obol-v3.1.css'));});
test('sanitized export retains v3.1 state and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.1 tests passed`);
