'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V84,P=global.OBOL_PROJECT_V84,F84=global.OBOL_ORANGE_FIDELITY_V84;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.4 historical milestone remains complete while the current model may advance',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.strictEqual(P.version,'8.4.0');assert.strictEqual(P.release,'v8.4');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[127,0,0,0,100,100]);assert.strictEqual(p.canonical.implemented,127);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('v8.4 completed persistence.md with fifteen new units plus inherited Add Domain Admin accounting',()=>{assert.strictEqual(P.sourceWave.delivered.length,15);assert.strictEqual(F84.newAuditedIds.length,15);assert.strictEqual(F84.fileAuditedIds.length,16);assert.strictEqual(F84.newModeled.length,14);assert.strictEqual(F84.newRejected.length,1);for(const id of F84.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'persistence.md',id);assert.strictEqual(u.sourceSha,'a652fea306b91f887bb7b0deec751d9f6d711d5d',id);assert.strictEqual(u.auditedIn,'8.4',id);assert(['modeled','rejected'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const inherited=unit('persistence.add-da-membership');assert(inherited);assert.strictEqual(inherited.auditedIn,'8.0');assert(F84.fileAuditedIds.includes(inherited.id));const f=C.currentProjectModel(C.newState(),lanes).source;assert(f.filesAtomized>=13);assert.strictEqual(f.baselinesAtomized,34);assert(f.atomicComplete>=258);assert.strictEqual(f.atomicPending,0);});

test('persistence source families remain implemented and mapped to mature owners',()=>{for(const key of ['persistence.add-da','persistence.golden-ticket','persistence.silver-ticket','persistence.dsrm','persistence.skeleton-key','persistence.custom-ssp','persistence.golden-cert','persistence.diamond-ticket','persistence.sapphire-ticket','persistence.dc-shadow','persistence.acl-persistence']){let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key===key)s=x;assert(s,key);assert.strictEqual(s.status,'implemented',key);}for(const id of F84.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic84||[]).includes(id),owner+' lineage for '+id);}}});

test('Golden and Silver Ticket source variants are corrected rather than copied blindly',()=>{assert(hasRun('golden-ticket',/impacket-ticketer -aesKey .* -domain-sid .* -domain /));assert(hasRun('golden-ticket',/kerberos::golden \/user:.* \/domain:.* \/sid:.* \/aes256:/));assert(hasRun('silver-ticket',/kerberos::golden \/sid:.* \/domain:.* \/target:.* \/service:.* \/aes256:/));assert(hasRun('silver-ticket',/impacket-ticketer -nthash .* -domain-sid .* -domain .* -spn /));assert(card('golden-ticket').sourceCorrection84);assert(card('silver-ticket').sourceCorrection84);const imp=unit('persistence.silver-impacket-nthash');assert(imp&&imp.sourceCorrection);assert.strictEqual(imp.sourceCorrection.pinnedOmission,'-spn');});

test('DSRM, Custom SSP, and Golden Certificate source details have explicit verification or artifact handling',()=>{assert(hasRun('dsrm-persistence',/New-ItemProperty .*DsrmAdminLogonBehavior/));assert(hasRun('dsrm-persistence',/Get-ItemProperty .*DsrmAdminLogonBehavior/));assert(hasRun('dsrm-persistence',/Set-ItemProperty .*prior_value/));assert(hasRun('credential-subsystem-persistence',/type C:\\Windows\\System32\\kiwissp\.log/));assert(hasRun('credential-subsystem-persistence',/del C:\\Windows\\System32\\kiwissp\.log/));assert(hasRun('golden-certificate',/certipy forge .* -subject/));});

test('advanced ticket source authentication inputs are explicitly treated as alternatives',()=>{const diamond=unit('persistence.diamond-ticket'),sapphire=unit('persistence.sapphire-ticket');assert(diamond&&diamond.sourceCorrection);assert(sapphire&&sapphire.sourceCorrection);assert(/alternative/i.test(diamond.sourceCorrection.authentication));assert(/alternative/i.test(sapphire.sourceCorrection.authentication));assert(card('advanced-forged-tickets').sourceCorrection84);});

test('source-empty DCShadow and ACL headings are modeled while the trailing ellipsis is rejected',()=>{const dc=unit('persistence.dcshadow-heading'),acl=unit('persistence.acl-manipulation-heading'),tail=unit('persistence.trailing-ellipsis');assert.strictEqual(dc.auditStatus,'modeled');assert.strictEqual(acl.auditStatus,'modeled');assert.strictEqual(tail.auditStatus,'rejected');assert.deepStrictEqual(tail.ownerCardIds,[]);assert(/non-actionable placeholder/i.test(tail.reason));assert.strictEqual(P.sourceWave.rejected.length,1);});

test('persistence proof boundaries keep artifacts below authentication, execution, and privilege',()=>{for(const id of F84.newAuditedIds){const u=unit(id);assert(/not authenticated access|not.*execution|separate/i.test(u.evidenceBoundary),id);}assert(/saved ccache proves forged ticket material only/i.test(card('golden-ticket').commands.find(x=>/impacket-ticketer -aesKey/.test(String(x.run))).note));assert(/registry state is persistence configuration only/i.test(card('dsrm-persistence').commands.find(x=>/Get-ItemProperty/.test(String(x.run))).note));assert(/certificate material only/i.test(card('golden-certificate').commands.find(x=>/-subject/.test(String(x.run))).note));});

test('v8.4 four-file queue remains historical while the live queue may shrink',()=>{assert.deepStrictEqual(P.sourceWave.fileInventoryQueue,['dom_admin.md','know_vuln_auth.md','trusts.md','valid_user.md']);const q=C.currentProjectModel(C.newState(),lanes).buildNext;assert(q.total>=0);assert(q.total<=4);assert((q.rows||[]).every(x=>x.kind==='source-file-inventory'));});

test('current project model preserves v8.4 source accounting as a floor',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=258);assert(p.source.atomicTotal>=258);assert.strictEqual(p.source.atomicPending,0);assert(p.source.filesAtomized>=13);assert.strictEqual(p.source.baselinesAtomized,34);assert((p.recent||[]).some(x=>x.release==='v8.4')||P.release==='v8.4');});

test('README generator remains a structural live projection after v8.4',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.4 historical release wiring remains complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.4.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.4.js','methodology-v8.4.js','project-model-v8.4.js','core-v8.4.js','app-v8.4.js','obol-v8.4.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.4.js','methodology-v8.4.js','project-model-v8.4.js','core-v8.4.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.4.js'));assert(!idx.includes('intake-v8.4.js'));assert(releaseDoc.includes('# Obol v8.4'));});

test('current sanitized export still redacts secrets after v8.4',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.4 historical tests passed`);
