'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V72,P=global.OBOL_PROJECT_V72,S=global.OBOL_SOURCE_DELIVERY_V72;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.2 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.2.0');assert.strictEqual(s.obolVersion,'7.2.0');assert.strictEqual(C.currentProjectModel,C.projectModel72);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard72);assert.strictEqual(p.release,'v7.2');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[109,18,0,0,86,100]);});

test('acl.md is atomized into sixteen complete source units',()=>{const ids=['acl.dcsync','acl.shadow-credentials','acl.group-membership','acl.group-owner-dacl','acl.computer-rbcd','acl.computer-shadow','acl.user-password','acl.user-targeted-kerberoast','acl.user-shadow','acl.user-logon-script','acl.ou-inheritance','acl.ou-gplink','acl.gmsa','acl.laps','acl.gpo','acl.dns-admin'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'acl.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.2',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity72(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[3,17,16,34,41,41,0]);assert.strictEqual(f.completePct,100);});

test('seven frozen partial ACL parents advance and existing implemented parents stay implemented',()=>{const advanced=['acl.shadow-credentials','acl.group-control','acl.computer-control','acl.user-control','acl.ou-control','acl.gmsa','acl.gpo'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.2',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);for(const key of ['acl.dcsync','acl.laps','acl.dns-admin'])assert.strictEqual(section(key).status,'implemented',key);});

test('Build Next leaves ACL and proceeds to relay / MITM source inventory',()=>{const q=C.buildNext72(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,18,18]);assert(q.rows.length===18);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'mitm.md');assert.strictEqual(q.rows[0].label,'Credential/hash listening');for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);});

test('ACL source units reuse strong existing owners and add dedicated v7.2 owners',()=>{assert(unit('acl.dcsync').ownerCardIds.includes('dcsync'));assert(unit('acl.laps').ownerCardIds.includes('laps-read'));assert(unit('acl.computer-rbcd').ownerCardIds.includes('delegation-rbcd-71'));for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('acl.')),id);assert(c.evidence45&&c.evidence45.source==='v7.2',id);assert(c.report47&&c.report47.evidenceProfile,id);assert(c.executionContext72,id);}assert(card('acl-shadow-credential-72').atomic72.length===3);});

test('source-delivery overlay exposes detailed ACL map nodes and cleanup markers',()=>{assert(S);const area=(global.OBOL_METHODOLOGY_V41.areas||[]).find(x=>x.id==='acl');assert(area);const summary=(area.nodes||[]).find(x=>x.id==='acl-control');assert(summary&&summary.coverage==='implemented');for(const id of S.detailNodeIds){const n=(area.nodes||[]).find(x=>x.id===id);assert(n,id);assert.strictEqual(n.coverage,'implemented',id);}assert(card('acl-group-owner-dacl-72').commands.some(x=>/OBOL_ACL_OWNER_RESTORED/.test(String(x.run))));assert(card('acl-group-owner-dacl-72').commands.some(x=>/OBOL_GROUP_DACL_RESTORED/.test(String(x.run))));assert(card('acl-ou-inheritance-72').commands.some(x=>/OBOL_OU_DACL_RESTORED/.test(String(x.run))));});

test('ACL Evidence keeps rights, mutation, credentials, access, privilege, and cleanup separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.2.js'));const I=global.OBOL_INTAKE_V72;let p=I.proof72('acl-group-membership-72',"Add-ADGroupMember -Identity 'HelpDesk' -Members 'user1'; Get-ADGroupMember -Identity 'HelpDesk'",'Name SamAccountName objectClass\nuser1 user1 user');assert.deepStrictEqual(p.facts,['ad.group_membership_changed']);p=I.proof72('acl-group-owner-dacl-72',"impacket-owneredit -action write -new-owner original -target group domain/user:pass && echo OBOL_ACL_OWNER_RESTORED",'OwnerSid modified successfully!\nOBOL_ACL_OWNER_RESTORED');assert.deepStrictEqual(p.facts,['ad.acl_owner_restored']);p=I.proof72('acl-ou-inheritance-72',"impacket-dacledit -action restore -file old.bak domain/user:pass && echo OBOL_OU_DACL_RESTORED",'DACL restored successfully\nOBOL_OU_DACL_RESTORED');assert.deepStrictEqual(p.facts,['ad.acl_restored']);p=I.proof72('acl-gmsa-read-72',"nxc ldap 10.0.0.10 -u user -p pass --gmsa",'svc_sql$ NTLM: 0123456789abcdef0123456789abcdef');assert.deepStrictEqual(p.facts,['credential.ntlm_hash','credential.candidate']);p=I.proof72('acl-gpo-control-72',"Set-GPRegistryValue -Name Test; Write-Output OBOL_GPO_WRITE_PROVED",'OBOL_GPO_WRITE_PROVED');assert.deepStrictEqual(p.facts,['ad.gpo_modified']);p=I.proof72('acl-dnsadmin-72','sc.exe \\\\dns01 stop dns && sc.exe \\\\dns01 start dns && echo OBOL_DNS_SERVICE_RESTARTED','OBOL_DNS_SERVICE_RESTARTED');assert.deepStrictEqual(p.facts,['ad.dns_service_restarted']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('project model exposes the v7.2 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[41,41,0,3,16,18]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'mitm.md');assert.strictEqual(p.recent[0].release,'v7.2');assert(p.details.sourceWave72);});

test('README generator remains structurally synchronized with current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('Current live queue: 18 items'));assert(out.includes('Canonical methodology: 109/127 fully implemented (86%)'));assert(out.includes('Orange source fidelity: 3/17 source files atomized, 16/34 partial baselines decomposed, 41/41 inventoried atomic units fidelity-complete'));assert(out.includes('Credential/hash listening'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.2',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.2 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.2.js','methodology-v7.2.js','project-model-v7.2.js','core-v7.2.js','intake-v7.2.js','app-v7.2.js','obol-v7.2.css'])assert(idx.includes(x),x);assert(runtime.includes('source-delivery-v7.2.js'));assert(!idx.includes('dashboard-v7.2.js'));assert(readme.includes('Current release: **v7.2**'));assert(changelog.includes('## v7.2'));assert(fs.existsSync(path.join(root,'docs','v7.2.md')));});

test('sanitized export advances to v7.2 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.2.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.2 tests passed`);
