'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V81,P=global.OBOL_PROJECT_V81,F81=global.OBOL_ORANGE_FIDELITY_V81;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.1 historical milestone remains complete while the current model may advance',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.strictEqual(P.version,'8.1.0');assert.strictEqual(P.release,'v8.1');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[127,0,0,0,100,100]);assert.strictEqual(p.canonical.implemented,127);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('v8.1 completed low_access.md as a seventeen-unit source wave',()=>{assert.strictEqual(P.sourceWave.delivered.length,17);assert.strictEqual(F81.auditedIds.length,17);assert.strictEqual(F81.modeled.length,12);assert.strictEqual(F81.superseded.length,5);assert.strictEqual(F81.filesAtomizedAfter,10);assert.strictEqual(F81.partialBaselinesAtomizedAfter,34);assert.strictEqual(F81.totalComplete,211);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'low_access.md',id);assert.strictEqual(u.sourceSha,'8744d9b137338bb1fa99d26bc257aa50ef490e5e',id);assert.strictEqual(u.auditedIn,'8.1',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}});

test('v8.1 preserves earlier low-access local exploit and WebDAV atoms while closing the file',()=>{for(const id of ['low-access.local-exploit-smbghost','low-access.local-exploit-serioussam','low-access.webdav-coercion']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditedIn,'7.9',id);assert.strictEqual(u.sourceFile,'low_access.md',id);}assert((F.atomizedFiles||[]).includes('low_access.md'));assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,[]);});

test('legacy low-access variants remain explicitly superseded rather than silently dropped',()=>{for(const id of ['low-access.applocker-mshta','low-access.uac-wsreset','low-access.uac-msdt','low-access.seimpersonate-roguepotato','low-access.seimpersonate-remotepotato0']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'superseded',id);assert(u.reason&&u.reason.length>80,id);}});

test('mature v8.1 owners retain the useful source-matched command deltas',()=>{assert(hasRun('applocker-bypass58',/icacls C:\\Windows\\Temp/));assert(hasRun('windows-enum',/Invoke-PrivescCheck -Extended/));assert(hasRun('stored-credentials',/findstr \/si "pass"/));assert(hasRun('seimpersonate',/PrintSpoofer64\.exe -c/));assert(hasRun('seimpersonate',/obol-printspoofer-whoami\.txt/));for(const id of P.sourceWave.delivered){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic81||[]).includes(id),owner+' lineage for '+id);}}});

test('v8.1 source commands retain conservative discovery and privilege boundaries',()=>{assert(/candidate condition/i.test(card('applocker-bypass58').commands.find(x=>/icacls C:\\Windows\\Temp/.test(String(x.run))).note));assert(/leads/i.test(card('windows-enum').commands.find(x=>/Invoke-PrivescCheck -Extended/.test(String(x.run))).note));assert(/credential candidate only/i.test(card('stored-credentials').commands.find(x=>/findstr \/si "pass"/.test(String(x.run))).note));assert(/only explicit NT AUTHORITY.*SYSTEM output/i.test(card('seimpersonate').commands.find(x=>/PrintSpoofer64\.exe -c/.test(String(x.run))).note));});

test('v8.1 seven-file queue remains historical while the live queue may shrink',()=>{assert.deepStrictEqual(P.sourceWave.fileInventoryQueue,['crack_hash.md','low_hanging.md','persistence.md','dom_admin.md','know_vuln_auth.md','trusts.md','valid_user.md']);const q=C.currentProjectModel(C.newState(),lanes).buildNext;assert(q.total>=0);assert(q.total<=7);assert((q.rows||[]).every(x=>x.kind==='source-file-inventory'));});

test('current project model preserves v8.1 source accounting as a floor',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=211);assert(p.source.atomicTotal>=211);assert.strictEqual(p.source.atomicPending,0);assert(p.source.filesAtomized>=10);assert.strictEqual(p.source.baselinesAtomized,34);assert((p.recent||[]).some(x=>x.release==='v8.1')||P.release==='v8.1');});

test('README generator remains a structural live projection after v8.1',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.1 historical release wiring remains complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.1.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.1.js','methodology-v8.1.js','project-model-v8.1.js','core-v8.1.js','app-v8.1.js','obol-v8.1.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.1.js','methodology-v8.1.js','project-model-v8.1.js','core-v8.1.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.1.js'));assert(!idx.includes('intake-v8.1.js'));assert(releaseDoc.includes('# Obol v8.1'));});

test('current sanitized export still redacts secrets after v8.1',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.1 historical tests passed`);
