'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,D=global.OBOL_DASHBOARD_V49,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
test('v4.9 initializes current release and single-dashboard preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.9.0');assert.strictEqual(s.obolVersion,'4.9.0');assert.strictEqual(s.ui.dashboard49.showContext,true);assert.strictEqual(s.ui.dashboard49.showBacklog,true);assert.strictEqual(s.ui.dashboard49.showTrend,true);assert.strictEqual(D.version,'4.9.0');});
test('v4.9 preserves the pinned Orange source and strict v4.8 canonical baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.upstream.northStar,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('single dashboard exposes hard-number metrics with their denominators',()=>{const s=hostState(),d=C.northStarDashboard49(s,lanes,s.activeContext);assert.strictEqual(d.coverage.sections,127);assert.strictEqual(d.coverage.implemented,52);assert.strictEqual(d.coverage.coveragePct,41);assert.strictEqual(d.coverage.representedPct,80);assert(d.mappedCards>20);assert(d.metrics.length>=8);for(const m of d.metrics){assert(Number.isFinite(m.value),m.id);assert(m.value>=0&&m.value<=100,m.id);assert(Number.isFinite(m.count),m.id);assert(Number.isFinite(m.total),m.id);}assert.strictEqual(d.sourceFiles,17);});
test('operator-loop dashboard composes runnable GUI and Evidence contracts instead of inventing a new denominator',()=>{const d=C.northStarDashboard49(hostState(),lanes);assert(d.contracts.mappedCards>0);assert.strictEqual(d.contracts.runReady<=d.contracts.mappedCards,true);assert.strictEqual(d.contracts.evidenceReady<=d.contracts.mappedCards,true);assert.strictEqual(d.contracts.loopReady<=d.contracts.mappedCards,true);assert.strictEqual(d.contracts.adjustableCommands+d.contracts.fixedCommands,d.contracts.commands);assert.strictEqual(d.contracts.loopPct,Math.round(d.contracts.loopReady/d.contracts.mappedCards*100));});
test('execution dashboard audits all Orange-mapped commands and preserves platform distinctions',()=>{const a=C.executionMetadataAudit49(lanes);assert(a.commands>0);assert(a.explicit>0);assert.strictEqual(a.explicit+a.fallback,a.commands);assert(a.kali>0);assert(a.windows>0);assert(a.target>0);assert.strictEqual(a.explicitPct,Math.round(a.explicit/a.commands*100));assert(a.rows.some(x=>x.source==='audited-v4.8'));});
test('decision path and reporting dashboard metrics are based on live mappings',()=>{const d=C.northStarDashboard49(hostState(),lanes);assert(d.decisionPath.linkedSections>0);assert(d.decisionPath.stagedSections>0);assert(d.decisionPath.stagedSections<=d.decisionPath.linkedSections);assert.strictEqual(d.reporting.traceable,d.reporting.mapped);assert.strictEqual(d.reporting.tracePct,100);assert(d.reporting.findings>0);assert(d.reporting.pathOnly>0);});
test('tool-review dashboard keeps pending review debt explicit',()=>{const a=C.toolReviewAudit49(lanes);assert(a.total>0);assert.strictEqual(a.reviewed+a.pending,a.total);assert.strictEqual(a.reviewedPct,Math.round(a.reviewed/a.total*100));assert((a.counts.keep||0)>0);assert((a.counts.supplement||0)>0);});
test('canonical backlog is source-file complete and sorted by remaining gaps',()=>{const d=C.northStarDashboard49(hostState(),lanes);assert.strictEqual(d.backlog.length,17);for(let i=1;i<d.backlog.length;i++){const a=d.backlog[i-1],b=d.backlog[i];assert(a.gap>b.gap||a.gap===b.gap&&a.partial>=b.partial||a.gap===b.gap&&a.partial===b.partial); }assert(d.backlog.some(x=>x.file==='sccm.md'));assert(d.backlog.some(x=>x.file==='persistence.md'));});
test('active-context dashboard is isolated and carries decision/report progress',()=>{const s=hostState();s.hosts.push({id:'h2',ip:'10.10.10.20',name:'LAB2',hostname:'LAB2',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});C.recordActivity(s,{cardId:'silver-ticket',context:{type:'host',id:'h1'},result:'success',command:'fixture',evidence:'fixture',outcomeFacts:['persistence.silver_ticket']});const a=C.northStarDashboard49(s,lanes,{type:'host',id:'h1'}).active,b=C.northStarDashboard49(s,lanes,{type:'host',id:'h2'}).active;assert.strictEqual(a.mappedSuccesses,1);assert.strictEqual(b.mappedSuccesses,0);assert.strictEqual(a.decision.stage.id,'persistence');assert.strictEqual(b.decision.stage.id,'identity');assert(a.reportRows>=1);assert.strictEqual(b.reportRows,0);});
test('v4.9 UI consolidates Home health into one North Star dashboard without new primary navigation',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v4.9.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v4.9.css'),'utf8');for(const x of ['Project North Star dashboard','One place for the hard numbers','Run → paste → interpret → decide','Canonical backlog','Release trend','Open dashboard'])assert(app.includes(x),x);for(const x of ['.northstar-dashboard49','.dash-metrics49','.dash-backlog49','.dash-context49','.dash-trend49'])assert(css.includes(x),x);assert(app.includes('.orange-home42,.sccm-home46,.persistence-home48'));});
test('release wiring README docs and CI include v4.9 and preserve the single-dashboard North Star requirement',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.9.md'),'utf8');assert(idx.includes('Obol v4.9'));assert(idx.includes('dashboard-v4.9.js'));assert(idx.includes('core-v4.9.js'));assert(idx.includes('app-v4.9.js'));assert(idx.includes('obol-v4.9.css'));assert(wf.includes('Run v4.9 regression suite'));assert(readme.includes('## Obol v4.9'));assert(readme.includes('single dashboard'));assert(readme.includes('hard numbers and percentages'));assert(readme.includes('All of this applies both now and retroactively'));assert(readme.includes('proper GUI based toggles'));assert(readme.includes('operating from Kali or from a Windows host'));assert(readme.includes('improving "Next Steps"'));assert(readme.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/hard numbers and percentages/i.test(notes));});
test('sanitized export retains v4.9 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.9.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.9 tests passed`);
