'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V75,P=global.OBOL_PROJECT_V75;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.5 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.5.0');assert.strictEqual(s.obolVersion,'7.5.0');assert.strictEqual(C.currentProjectModel,C.projectModel75);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard75);assert.strictEqual(p.release,'v7.5');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[117,10,0,0,92,100]);});

test('sccm.md is atomized into twenty-three complete source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,23);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'sccm.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.5',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity75(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[6,17,24,34,93,93,0]);assert.strictEqual(f.completePct,100);});

test('only the six frozen SCCM partial parents advance',()=>{const advanced=['sccm.elevate1','sccm.elevate2','sccm.elevate3','sccm.takeover2','sccm.creds2','sccm.creds5'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.5',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);for(const key of P.sourceWave.historicalCanonicalDeepened){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.notStrictEqual(s.advancedIn,'7.5',key);}});

test('Build Next leaves sccm.md and proceeds into admin.md source inventory',()=>{const q=C.buildNext75(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,10,10]);assert.strictEqual(q.rows.length,10);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'admin.md');assert(!q.rows.some(x=>x.file==='sccm.md'));for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);});

test('SCCM source units reuse mature owners and add focused v7.5 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('sccm.')),id);assert(c.evidence45&&c.evidence45.source==='v7.5',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext75,id);}assert(unit('sccm.recon-sccmhunter').ownerCardIds.includes('sccm-enum'));assert(unit('sccm.pxe-naa').ownerCardIds.includes('pxe-naa61'));assert(unit('sccm.dp-http-policies').ownerCardIds.includes('sccm-credential-recovery'));assert(unit('sccm.admin-exec-sharpsccm').ownerCardIds.includes('sccm-admin-exec'));assert(unit('sccm.cleanup-device').ownerCardIds.includes('sccm-cleanup-post'));});

test('SCCM Evidence keeps preparation, relay, credentials, access, execution, privilege, and cleanup separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.5.js'));const I=global.OBOL_INTAKE_V75;let p=I.proof75('sccm-force-client-push-75','SharpSCCM.exe invoke client-push -mp sccm.corp.local -sc P01 -t 10.0.0.5','Client push request successfully invoked');assert.deepStrictEqual(p.facts,['sccm.client_push_requested']);p=I.proof75('sccm-site-system-relay-75','ntlmrelayx.py -tf targets.txt -smb2support','Authenticating against smb://10.0.0.20 as CORP/SCCM$ SUCCEED');assert.deepStrictEqual(p.facts,['relay.success']);p=I.proof75('sccm-policy-request-75','SharpSCCM.exe get secrets -r temp -u TEMP$ -p Pass123!','NetworkAccessUsername: CORP\\naa\nNetworkAccessPassword: Secret!');assert.deepStrictEqual(p.facts,['sccm.policy_material','credential.candidate']);p=I.proof75('sccm-site-db-creds-75','sccmdecryptpoc.exe deadbeef','Decrypted username CORP\\svc_sccm password Winter2026!');assert.deepStrictEqual(p.facts,['credential.candidate']);for(const x of ['access.admin','access.system','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('project model exposes the v7.5 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[93,93,0,6,24,10]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'admin.md');assert.strictEqual(p.recent[0].release,'v7.5');assert(p.details.sourceWave75);});

test('README generator remains structurally synchronized with current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:** 10 items'));assert(out.includes('**Canonical methodology:** 117/127 fully implemented (92%)'));assert(out.includes('**Orange source fidelity:** 6/17 source files atomized, 24/34 partial baselines decomposed, 93/93 inventoried atomic units fidelity-complete'));assert(out.includes('admin.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.5',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.5 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.5.js','methodology-v7.5.js','project-model-v7.5.js','core-v7.5.js','intake-v7.5.js','app-v7.5.js','obol-v7.5.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.5.js'));assert(runtime.includes('methodology-v7.5.js'));assert(runtime.includes('project-model-v7.5.js'));assert(!idx.includes('dashboard-v7.5.js'));assert(readme.includes('Current release: **v7.5**'));assert(changelog.includes('## v7.5'));assert(fs.existsSync(path.join(root,'docs','v7.5.md')));});

test('sanitized export advances to v7.5 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.5.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.5 tests passed`);
