'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V80,P=global.OBOL_PROJECT_V80;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}function unit(id){return (F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return !!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.0 initializes the stable current project model at complete canonical breadth',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.0.0');assert.strictEqual(s.obolVersion,'8.0.0');assert.strictEqual(C.currentProjectModel,C.projectModel80);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard80);assert.strictEqual(p.release,'v8.0');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.0 completes the final three frozen baselines with four terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,4);assert.deepStrictEqual(P.sourceWave.modeled,['crack-hash.pxe-sccm-aes128','low-hanging.zerologon-check','persistence.add-da-membership']);assert.deepStrictEqual(P.sourceWave.superseded,['low-hanging.zerologon-reset']);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.auditedIn,'8.0',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity80(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[9,17,34,34,194,194,0]);assert.strictEqual(f.completePct,100);});

test('PXE, Zerologon, and ADD DA parents advance and retain conservative owners',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['crack_hash.pxe','low_hanging.zerologon','persistence.add-da']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'8.0',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert(unit('crack-hash.pxe-sccm-aes128').ownerCardIds.includes('pxe-naa61'));assert(unit('low-hanging.zerologon-check').ownerCardIds.includes('zerologon-check'));assert(unit('persistence.add-da-membership').ownerCardIds.includes('acl-group-membership-72'));});

test('unsafe Zerologon reset is explicitly superseded and not added to the operator command surface',()=>{const u=unit('low-hanging.zerologon-reset'),c=card('zerologon-check');assert.strictEqual(u.auditStatus,'superseded');assert(/destructive|machine-account/i.test(u.reason));assert(c&&c.commands&&c.commands.length);assert(!c.commands.some(x=>/cve-2020-1472-exploit\.py/i.test(String(x.run||''))));assert(c.commands.some(x=>/zerologon-scan/i.test(String(x.run||''))));});

test('mature owners expose source-matched PXE cracking and reversible Domain Admin membership commands',()=>{assert(hasRun('pxe-naa61',/hashcat -m 19850 -a 0/));assert(hasRun('acl-group-membership-72',/net group "Domain Admins" .*\/add \/domain/));assert(hasRun('acl-group-membership-72',/net group "Domain Admins" .*\/delete \/domain/));for(const id of P.sourceWave.delivered){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic80||[]).includes(id),owner+' lineage for '+id);}}});

test('Build Next transitions from frozen baselines to eight whole-file inventories',()=>{const q=C.buildNext80(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,8,8]);assert(q.rows.every(x=>x.kind==='source-file-inventory'));assert.deepStrictEqual(q.rows.map(x=>x.file),P.sourceWave.fileInventoryQueue);assert.strictEqual(q.rows[0].file,'low_access.md');});

test('project model exposes v8.0 phase and source accounting',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[194,194,0,9,34,8]);assert.strictEqual(p.phase.id,'whole-file-source-inventory');assert.strictEqual(p.next.file,'low_access.md');assert.strictEqual(p.recent[0].release,'v8.0');assert(p.details.sourceWave80);});

test('README generator reflects the v8.0 current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 8 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 9/17 source files atomized, 34/34 partial baselines decomposed, 194/194'));assert(out.includes('**Current phase:** Orange whole-file source inventory.'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.0',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.0 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.0.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.0.js','methodology-v8.0.js','project-model-v8.0.js','core-v8.0.js','app-v8.0.js','obol-v8.0.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.0.js','methodology-v8.0.js','project-model-v8.0.js','core-v8.0.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.0.js'));assert(!idx.includes('intake-v8.0.js'));assert(readme.includes('Current release: **v8.0**'));assert(releaseDoc.includes('# Obol v8.0'));});

test('sanitized export advances to v8.0 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.0.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.0 tests passed`);
