'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
run(path.join(root,'assets','core-v2-base.js'));run(path.join(root,'assets','core-v2.js'));run(path.join(root,'assets','core-v2.1.js'));run(path.join(root,'data','tools-v2.2.js'));run(path.join(root,'assets','core-v2.2.js'));run(path.join(root,'assets','core-v2.3.js'));run(path.join(root,'assets','core-v2.4.js'));
run(path.join(root,'data','lanes.js'));run(path.join(root,'assets','report-v2.js'));run(path.join(root,'assets','report-v2.1.js'));run(path.join(root,'assets','report-v2.2.js'));run(path.join(root,'assets','report-v2.3.js'));run(path.join(root,'assets','report-v2.4.js'));
const C=global.OBOL_CORE_V2,LANES=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function firstCard(){for(const l of LANES)for(const c of l.cards||[])return c;throw new Error('no cards');}
test('v2.4 state version and queue initialize',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.4.0');assert.strictEqual(s.obolVersion,'2.4.0');assert(Array.isArray(s.workQueue));});
test('queue is scoped to active context',()=>{const s=C.newState(),a=C.mergeHost(s,{ip:'10.0.0.1'}),b=C.mergeHost(s,{ip:'10.0.0.2'}),card=firstCard();C.addToQueue(s,card.id,{type:'host',id:a.id},{priority:'high',note:'test A'});assert.strictEqual(C.queueFor(s,{type:'host',id:a.id}).length,1);assert.strictEqual(C.queueFor(s,{type:'host',id:b.id}).length,0);});
test('duplicate planned queue add updates rather than duplicates',()=>{const s=C.newState(),h=C.mergeHost(s,{ip:'10.0.0.3'}),ctx={type:'host',id:h.id},card=firstCard();const a=C.addToQueue(s,card.id,ctx,{priority:'normal'}),b=C.addToQueue(s,card.id,ctx,{priority:'high',note:'promote'});assert.strictEqual(a.id,b.id);assert.strictEqual(C.queueFor(s,ctx).length,1);assert.strictEqual(b.priority,'high');assert.strictEqual(b.note,'promote');});
test('successful activity auto-completes matching planned queue work',()=>{const s=C.newState(),h=C.mergeHost(s,{ip:'10.0.0.4'}),ctx={type:'host',id:h.id},card=firstCard();C.addToQueue(s,card.id,ctx,{priority:'normal'});C.recordActivity(s,{cardId:card.id,context:ctx,result:'success',outcomeFacts:[],evidence:'proof',command:'example'});const q=C.queueFor(s,ctx)[0];assert.strictEqual(q.status,'done');assert(q.completedAt);});
test('deferred work can be reopened',()=>{const s=C.newState(),h=C.mergeHost(s,{ip:'10.0.0.5'}),ctx={type:'host',id:h.id},card=firstCard(),q=C.addToQueue(s,card.id,ctx,{});C.updateQueueItem(s,q.id,{status:'deferred'});assert.strictEqual(C.queueFor(s,ctx)[0].status,'deferred');C.updateQueueItem(s,q.id,{status:'planned'});assert.strictEqual(C.queueFor(s,ctx)[0].status,'planned');});
test('v2.4 report includes operator work queue and current version',()=>{const s=C.newState(),h=C.mergeHost(s,{ip:'10.0.0.6'}),ctx={type:'host',id:h.id},card=firstCard();C.addToQueue(s,card.id,ctx,{priority:'high',note:'preserve operator intent'});const md=global.OBOL_REPORT_V2.generate(s,LANES,'standard',{includeSecrets:false});assert(md.includes('## Operator Work Queue'));assert(md.includes('preserve operator intent'));assert(md.includes('v2.4.0'));});
console.log(`\n${passed} v2.4 tests passed`);