'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js'])run(path.join(root,'assets',f));
run(path.join(root,'assets','intake-v2.1.js'));run(path.join(root,'assets','intake-v5.3.js'));run(path.join(root,'assets','intake-v5.4.js'));run(path.join(root,'assets','intake-v5.5.js'));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V55,I=global.OBOL_INTAKE_V55,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v5.5 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.5.0');assert.strictEqual(s.obolVersion,'5.5.0');assert.strictEqual(s.ui.dashboard55.showQualityClear,true);});
test('v5.5 advances five mature partial sections without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[62,39,26,0,49,80]);assert.strictEqual(M.advancedKeys.length,5);});
test('v5.4 implemented-quality queue is cleared through delivery-ready owners',()=>{const d=C.qualityRepair55(lanes);assert.strictEqual(d.targeted,7);assert.strictEqual(d.ready,7);assert.strictEqual(d.implementedQualityRemaining,0);for(const id of M.repairedCardIds){const c=card(id),r=C.cardReadiness52(lanes).byCard[id];assert(c&&c.evidence45&&c.evidence45.source==='v5.5',id);assert(r&&r.ready,id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);}});
test('all new v5.5 canonical owners meet the delivery-ready floor',()=>{const r=C.cardReadiness52(lanes);for(const id of M.newCardIds){const c=card(id),row=r.byCard[id];assert(c&&c.evidence45&&c.evidence45.source==='v5.5',id);assert(row&&row.ready,id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);assert(c.report47&&c.report47.traceable,id);}});
test('AD CS and delegation enumeration do not manufacture control or privilege',()=>{let p=I.proof55('adcs-enumeration55','certipy find ...','Certificate Authorities\nCA Name : CORP-CA\nCertificate Templates\nTemplate Name : User');assert(p.success&&p.facts.includes('adcs.enumerated'));assert(!p.facts.includes('access.admin'));p=I.proof55('delegation-discovery55','impacket-findDelegation corp/user:pw','AccountName AccountType DelegationType DelegationRightsTo\nWEB$ Computer Constrained cifs/files.corp.local');assert(p.success&&p.facts.includes('ad.delegation_discovered'));assert(!p.facts.includes('kerberos.tickets'));});
test('domain backup-key proof requires explicit export material',()=>{let p=I.proof55('domain-backup-key55','impacket-dpapi backupkeys -t x','Preferred BackupKey found');assert(!p.success);p=I.proof55('domain-backup-key55','impacket-dpapi backupkeys -t x','Preferred BackupKey found\nbackupkey.pvk exported');assert(p.success&&p.facts.includes('dpapi.domain_backup_key'));assert(!p.facts.includes('credential.plaintext'));});
test('LSASS parsing separates collection from credential recovery',()=>{let p=I.proof55('lsass-collection55','pypykatz lsa minidump lsass.dmp','minidump opened');assert(!p.success);p=I.proof55('lsass-collection55','pypykatz lsa minidump lsass.dmp','== MSV ==\nUsername: analyst\nNT: 0123456789abcdef0123456789abcdef');assert(p.success&&p.facts.includes('loot.lsass')&&p.facts.includes('hash.ntlm'));assert(!p.facts.includes('credential.plaintext'));});
test('token impersonation requires explicit post-transition identity',()=>{let p=I.proof55('token-impersonation55','mimikatz.exe "token::list"','Token list: NT AUTHORITY\\SYSTEM');assert(!p.success);p=I.proof55('token-impersonation55','mimikatz.exe "token::elevate" "token::whoami"','token::whoami\nNT AUTHORITY\\SYSTEM');assert(p.success&&p.facts.includes('token.impersonated')&&p.facts.includes('access.system'));p=I.proof55('token-impersonation55','mimikatz.exe "token::elevate"','token elevated');assert(!p.success);});
test('dashboard exposes v5.5 canonical delta and zero implemented-quality debt',()=>{const d=C.northStarDashboard55(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance55.delta,5);assert.strictEqual(d.canonicalAdvance55.toImplemented,62);assert.strictEqual(d.qualityRepair55.implementedQualityRemaining,0);assert(d.milestones.some(x=>x.release==='v5.5'&&x.implemented===62));assert(d.milestones.some(x=>x.release==='v5.4'&&x.implemented===57));});
test('v5.5 Build Next accounting stays historical while README generation stays live',()=>{const q=C.buildNext52(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.total],[0,13,26,39]);const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('OBOL-BUILD-NEXT:START'));assert(/Canonical methodology:\*\* \d+\/127 fully implemented \(\d+%\)/.test(out));assert(out.includes('**Current live queue:**'));assert(out.includes('**Highest-priority live items:**'));});
test('v5.5 release wiring and CI hardening remain available through durable release docs',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),building=fs.readFileSync(path.join(root,'BUILDING.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),preflight=path.join(root,'tools','release-preflight.js');for(const x of ['methodology-v5.5.js','dashboard-v5.5.js','core-v5.5.js','intake-v5.5.js','app-v5.5.js','obol-v5.5.css'])assert(idx.includes(x),x);assert(wf.includes('Run release preflight'));assert(wf.includes('Run complete historical regression chain'));assert(wf.includes("github.event.pull_request.draft == false"));assert(fs.existsSync(preflight));assert(/Current release: \*\*v\d+\.\d+(?:\.\d+)?\*\*/.test(readme));assert(readme.includes('BUILDING.md'));assert(building.includes('The validation tiers are:'));assert(building.includes('node tools/scope-check.js'));assert(building.includes('node tools/run-historical-contracts.js'));assert(building.includes('exact final head is green'));assert(changelog.includes('## v5.5'));});
test('sanitized export advances to v5.5 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.5.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.5 tests passed`);