'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','review-v2.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'target-one',hostname:'box.lab',domain:'',os:'',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};return s;}
test('v3.4 initializes current release and Next Steps preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.4.0');assert.strictEqual(s.obolVersion,'3.4.0');assert.deepStrictEqual(s.ui.nextSteps34,{lane:'all',status:'all',visible:8,detailsOpen:false});});
test('primary navigation describes Next Steps as prioritized evidence-grounded work',()=>{const p=C.NAVIGATION30.primary.find(x=>x.id==='path');assert(p);assert.strictEqual(p.label,'Next Steps');assert(/Prioritized/i.test(p.help));});
test('Next Steps overview exposes active target context and compact decision metrics',()=>{const s=hostState();C.addFact(s,'scan.initial',{context:s.activeContext,source:'fixture',evidence:'scan'});C.addFact(s,'port:445',{context:s.activeContext,source:'fixture',evidence:'445 open'});const o=C.nextStepsOverview34(s,lanes,s.activeContext);assert.strictEqual(o.contextLabel,'target-one');assert(o.ranked.length>0);assert(o.rows.length>0);assert.strictEqual(o.rows[0].target.address,'10.10.10.10');assert.strictEqual(typeof o.coverage.coverage,'number');assert.strictEqual(typeof o.openHypotheses,'number');});
test('Next Steps lane and status filters narrow presentation without mutating ranking',()=>{const s=hostState();C.addFact(s,'scan.initial',{context:s.activeContext,source:'fixture',evidence:'scan'});C.addFact(s,'port:445',{context:s.activeContext,source:'fixture',evidence:'445 open'});const first=C.nextStepsOverview34(s,lanes,s.activeContext);assert(first.ranked.length>0);const lane=first.ranked[0].card.lane;s.ui.nextSteps34.lane=lane;s.ui.nextSteps34.status='untried';const filtered=C.nextStepsOverview34(s,lanes,s.activeContext);assert(filtered.rows.every(r=>r.card.lane===lane));assert(filtered.rows.every(r=>C.statusFor(s,r.card.id,s.activeContext)==='new'));assert.strictEqual(filtered.ranked.length,first.ranked.length);});
test('planned recommendations receive a visible planning signal',()=>{const s=hostState();C.addFact(s,'scan.initial',{context:s.activeContext,source:'fixture',evidence:'scan'});const first=C.nextStepsOverview34(s,lanes,s.activeContext);assert(first.rows.length>0);C.addToQueue(s,first.rows[0].card.id,s.activeContext,{priority:'normal'});const next=C.nextStepsOverview34(s,lanes,s.activeContext),row=next.rows.find(r=>r.card.id===first.rows[0].card.id);assert(row&&row.planned);assert(row.signals.some(x=>x.id==='planned'));});
test('card evidence lineage handoff uses the exact latest activity id when available',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'smb-anon-enum',context:s.activeContext,result:'tried',command:'nxc smb 10.10.10.10',evidence:'fixture'}),src=C.lineageSource34(s,'smb-anon-enum',s.activeContext,'');assert(a.id);assert.strictEqual(src.activityId,a.id);assert.strictEqual(src.cardId,'smb-anon-enum');assert.strictEqual(src.contextKey,C.contextKey(s.activeContext));});
test('current workflow copy no longer points users at the retired Boxes ingestion flow',()=>{const visible=lanes.flatMap(l=>l.cards||[]).flatMap(c=>[c.hypothesis,...(c.variants||[]).map(v=>v.summary),...(c.commands||[]).map(x=>x.note)]).filter(Boolean).join('\n');assert(!/Boxes\s*→\s*Ingest/i.test(visible));assert(/Targets\s*→\s*Scan \/ discover|Evidence\s*→\s*Import BloodHound/i.test(visible));});
test('v3.4 UI is decision-first and fixes current-version presentation',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v3.4.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v3.4.css'),'utf8');for(const x of ['Best next move','Recommendation queue','Decision context','Technical context & controls','simplifyPath34','syncVersion34','lineageSource34'])assert(app.includes(x),x);assert(app.includes("'obol-'+currentVersionLabel34()"));for(const x of ['.next-hero34','.next-layout34','.next-rec34','.next-context34','.next-technical34'])assert(css.includes(x),x);});
test('index wires v3.4 after v3.3 and displays the current version',()=>{const src=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(src.includes('Obol v3.4'));assert(src.includes('· v3.4'));assert(src.indexOf('methodology-v3.4.js')>src.indexOf('methodology-v3.3.js'));assert(src.indexOf('core-v3.4.js')>src.indexOf('core-v3.3.js'));assert(src.indexOf('app-v3.4.js')>src.indexOf('app-v3.3.js'));assert(src.indexOf('obol-v3.4.css')>src.indexOf('obol-v3.3.css'));});
test('changelog documents v3.4 Next Steps redesign and remaining agent priorities',()=>{const src=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');assert(src.includes('## v3.4'));assert(/decision-first/i.test(src));assert(/exact activity-ID/i.test(src));assert(/transcript/i.test(src));assert(/pivot/i.test(src));});
test('sanitized export retains v3.4 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.4 tests passed`);
