'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,I=global.OBOL_INTAKE_V36,R=global.OBOL_RUBEUS_V36,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'DC01',hostname:'DC01',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';s.params.user='svc_backup';s.params.hash='0123456789abcdef0123456789abcdef';s.params.hashfile='loot/rubeus.txt';return s;}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v3.6 initializes current release and Rubeus workbench state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.6.0');assert.strictEqual(s.obolVersion,'3.6.0');assert.strictEqual(s.ui.rubeus36.action,'asrep');assert(s.ui.rubeus36.values.asrep);});
test('Rubeus action catalog maps to existing methodology and registers the tool',()=>{assert.deepStrictEqual(Object.keys(R.actions),['asrep','kerberoast','asktgt','ptt','s4u']);for(const a of Object.values(R.actions))assert(card(a.cardId),a.cardId);assert(global.OBOL_TOOLS_V22.tools.rubeus);assert(/GhostPack\/Rubeus/.test(global.OBOL_TOOLS_V22.tools.rubeus.source));});
test('Rubeus builders consume context values and omit empty optional switches',()=>{const s=hostState();C.updateRubeus36(s,'asrep',{user:'svc web'});const cmd=C.rubeusCommand36(s,'asrep');assert(cmd.startsWith('Rubeus.exe asreproast'));assert(cmd.includes('/user:"svc web"'));assert(cmd.includes('/domain:corp.local'));assert(cmd.includes('/dc:10.10.10.10'));assert(cmd.includes('/outfile:loot/rubeus.txt'));assert(cmd.includes('/format:hashcat'));assert(cmd.includes('/nowrap'));assert(!cmd.includes('/spn:'));});
test('delegation methodology exposes a Rubeus S4U implementation tied to the workbench',()=>{const c=card('delegation-abuse'),cmd=(c.commands||[]).find(x=>String(x.tool).toLowerCase()==='rubeus'&&/\bs4u\b/i.test(x.run));assert(cmd);assert.strictEqual(cmd.builder36.action,'s4u');assert(cmd.run.includes('{{impersonate}}'));assert(cmd.run.includes('{{spn}}'));});
test('messy ANSI PowerShell AS-REP transcript maps to Rubeus intent and proven hash state',()=>{const s=hostState(),text='\x1b[32mPS C:\\Temp> Rubeus.exe asreproast /user:svc_backup /domain:corp.local /nowrap\x1b[0m\n[*] Action: AS-REP roasting\n$krb5asrep$23$svc_backup@CORP.LOCAL:deadbeef';const r=T.analyzeTerminal(text,lanes,s,s.activeContext),a=r.activities.find(x=>x.cardId==='asrep-roast');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.asrep_hash'));assert(!a.outcomeFacts.includes('access.admin'));});
test('partial Kerberoast output is classified without inventing a hash',()=>{const s=hostState(),text='PS C:\\Temp> Rubeus.exe kerberoast /user:svc_sql /outfile:loot.txt\n[*] Action: Kerberoasting\n[-] No roastable users found';const r=T.analyzeTerminal(text,lanes,s,s.activeContext),a=r.activities.find(x=>x.cardId==='kerberoast');assert(a);assert(!a.outcomeFacts.includes('kerberos.tgs_hash'));});
test('pass-the-ticket success establishes ticket state but not privilege state',()=>{const s=hostState(),text='PS C:\\Temp> Rubeus.exe ptt /ticket:C:\\Temp\\svc.kirbi\n[+] Ticket successfully imported!';const r=T.analyzeTerminal(text,lanes,s,s.activeContext),a=r.activities.find(x=>x.cardId==='kerberos-tickets');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.ticket'));assert(!a.outcomeFacts.includes('access.admin'));});
test('S4U success maps to delegation without assuming administrator access',()=>{const s=hostState(),text='PS C:\\Temp> Rubeus.exe s4u /user:svc_web /rc4:0123456789abcdef0123456789abcdef /impersonateuser:Administrator /msdsspn:cifs/dc01.corp.local /ptt\n[+] S4U2proxy success!\n[+] Ticket successfully imported!';const r=T.analyzeTerminal(text,lanes,s,s.activeContext),a=r.activities.find(x=>x.cardId==='delegation-abuse');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.ticket'));assert(!a.outcomeFacts.includes('access.admin'));});
test('existing activities migrate by Rubeus command intent and add only proven outcome facts',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'kerberos-tickets',context:s.activeContext,result:'success',outcomeFacts:[],command:'Rubeus.exe asreproast /user:svc_backup /nowrap',evidence:'$krb5asrep$23$svc_backup@CORP.LOCAL:deadbeef'});const n=I.repairWorkspace36(s,lanes);assert(n>=1);assert.strictEqual(a.cardId,'asrep-roast');assert(a.outcomeFacts.includes('kerberos.asrep_hash'));assert(C.hasFact(s,'kerberos.asrep_hash',s.activeContext));});
test('exact command lineage wins over timestamp proximity and ambiguous command matches stay unresolved',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'kerberos-tickets',context:s.activeContext,result:'success',command:'Rubeus.exe ptt /ticket:a.kirbi',evidence:'ok'}),b=C.recordActivity(s,{cardId:'windows-enum',context:s.activeContext,result:'success',command:'whoami',evidence:'ok'});a.at='2026-08-28T17:00:00.000Z';b.at='2026-08-28T17:00:01.000Z';const art=C.addTypedArtifact(s,'tickets','a.kirbi',{context:s.activeContext,source:'intake:v3.6',observedAt:b.at});art.producedBy=[{id:'p1',activityId:'',cardId:'',command:'Rubeus.exe ptt /ticket:a.kirbi',source:'card-evidence',contextKey:C.contextKey(s.activeContext),at:b.at}];C.reconcileActivityLineage36(s);assert.strictEqual(art.producedBy[0].activityId,a.id);const a2=C.recordActivity(s,{cardId:'kerberos-tickets',context:s.activeContext,result:'success',command:'Rubeus.exe ptt /ticket:a.kirbi',evidence:'again'}),art2=C.addTypedArtifact(s,'tickets','b.kirbi',{context:s.activeContext,source:'intake:v3.6',observedAt:a2.at});art2.producedBy=[{id:'p2',activityId:'',cardId:'',command:'Rubeus.exe ptt /ticket:a.kirbi',source:'card-evidence',contextKey:C.contextKey(s.activeContext),at:a2.at}];C.reconcileActivityLineage36(s);assert.strictEqual(art2.producedBy[0].activityId,'');});
test('v3.6 UI connects Rubeus copy, methodology, Evidence, and lineage handoffs',()=>{const src=fs.readFileSync(path.join(root,'assets','app-v3.6.js'),'utf8');for(const x of ['Rubeus workbench','lastCopiedKey','lineageSource34','Review output in Evidence','intakePrefill','ADV_PARAMS','Orange Cyberdefense AD mindmap'])assert(src.includes(x),x);});
test('index and workflow wire v3.6 after inherited v3.5 layers',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8');assert(idx.includes('Obol v3.6'));assert(idx.includes('· v3.6'));assert(idx.indexOf('methodology-v3.6.js')>idx.indexOf('methodology-v3.4.js'));assert(idx.indexOf('core-v3.6.js')>idx.indexOf('core-v3.5.js'));assert(idx.indexOf('intake-v3.6.js')>idx.indexOf('intake-v3.5.js'));assert(idx.indexOf('app-v3.6.js')>idx.indexOf('app-v3.5-runtime.js'));assert(idx.indexOf('obol-v3.6.css')>idx.indexOf('obol-v3.5.css'));assert(wf.includes('Run v3.6 regression suite'));});
test('v3.6 preserves pinned North Star provenance in its durable owner docs',()=>{const north=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v3.6.md'),'utf8');assert(north.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/AS-REP Roasting/i.test(changelog)&&/Rubeus/i.test(changelog));assert(/Rubeus workbench/i.test(notes));assert(/exact-command lineage/i.test(notes));assert(/messy terminal/i.test(notes));});
test('sanitized export retains v3.6 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.6 tests passed`);
