'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,M=global.OBOL_METHODOLOGY_V41,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v4.1 initializes current release and methodology-audit preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.1.0');assert.strictEqual(s.obolVersion,'4.1.0');assert.strictEqual(s.ui.mindmap41.filter,'all');assert.strictEqual(s.ui.mindmap41.showTools,true);});
test('Orange 2025.03 North Star is represented by an auditable source registry',()=>{assert.strictEqual(M.mindmapUrl,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');const files=M.areas.map(x=>x.sourceFile);for(const f of ['no_creds.md','valid_user.md','authenticated.md','acl.md','delegation.md','adcs.md','sccm.md','lat_move.md','persistence.md'])assert(files.includes(f),f);});
test('coverage ledger reports implemented partial and explicit gap work without claiming completion',()=>{const c=C.mindmapCoverage41(lanes);assert(c.nodes>=20);assert(c.implemented>0);assert(c.partial>0);assert(c.gap>0);assert(c.coveragePct<100);assert(c.areas.some(a=>a.id==='sccm'&&a.nodes.some(n=>n.status==='gap')));assert(c.areas.some(a=>a.id==='no-creds'&&a.nodes.some(n=>n.id==='network-scan'&&n.status==='implemented')));});
test('coverage links resolve real methodology cards while preserving missing-card audit debt',()=>{const c=C.mindmapCoverage41(lanes),scan=c.areas.find(a=>a.id==='no-creds').nodes.find(n=>n.id==='network-scan');assert(scan.linkedCards.some(x=>x.id==='nmap-builder'));const gaps=C.mindmapPriorityGaps41(lanes);assert(gaps.some(x=>x.nodeId==='timeroast'));assert(gaps.some(x=>x.nodeId==='sccm-attacks'));});
test('v4.1 adds explicit execution metadata to audited mixed-side AD implementations',()=>{const c=card('bloodhound-collect');assert(c);const nxc=(c.commands||[]).find(x=>String(x.tool||'').toLowerCase()==='nxc'),sharp=(c.commands||[]).find(x=>String(x.tool||'').toLowerCase()==='sharphound');assert(nxc);assert(sharp);assert.strictEqual(nxc.operatorSurface40,'kali');assert.strictEqual(sharp.operatorSurface40,'windows');assert.strictEqual(nxc.operatorSurface41Source,'audited-v4.1');assert.strictEqual(sharp.operatorSurface41Source,'audited-v4.1');assert.strictEqual(C.commandSurface40(nxc,c),'kali');assert.strictEqual(C.commandSurface40(sharp,c),'windows');});
test('execution metadata audit distinguishes explicit contracts from conservative fallback',()=>{const a=C.executionMetadataAudit41(lanes);assert(a.commands>0);assert(a.explicit>0);assert(a.explicitPct>0);assert(a.kali>0);assert(a.windows>0);assert(a.rows.some(x=>x.source==='audited-v4.1'));});
test('tool review tracks whether Orange tools are kept supplemented or still require review',()=>{const a=C.mindmapToolAudit41(lanes);assert(a.rows.length>10);assert(a.counts.keep>0);assert(a.counts.supplement>0);assert(a.counts.review>0);const smb=a.rows.find(x=>x.nodeId==='anonymous-smb');assert(smb&&smb.preferred.includes('nxc'));const pxe=a.rows.find(x=>x.nodeId==='pxe-naa');assert(pxe&&pxe.decision==='review');});
test('v4.1 UI keeps coverage inside Methodology and surfaces explicit metadata audit state',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v4.1.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v4.1.css'),'utf8');for(const x of ['AD methodology coverage ledger','Highest-priority audit debt','Tool decisions','audited metadata','execution metadata audit'])assert(app.includes(x),x);for(const x of ['.mindmap-shell41','.mindmap-area41','.mindmap-node41','.audit-badge41'])assert(css.includes(x),x);});
test('release wiring README and CI include v4.1 and retain historical contracts',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.1.md'),'utf8');assert(idx.includes('Obol v4.1'));assert(idx.includes('methodology-v4.1.js'));assert(idx.includes('core-v4.1.js'));assert(idx.includes('app-v4.1.js'));assert(idx.includes('obol-v4.1.css'));assert(wf.includes('Run v4.1 regression suite'));assert(readme.includes('## Obol v4.1'));assert(readme.includes('Orange Cyber Defense mind map'));assert(readme.includes('operating from Kali or from a Windows host'));assert(readme.includes('Create infrastructure to keep up with how much of the Orange Cyber Defense mind map'));assert(/coverage ledger/i.test(notes));});
test('sanitized export retains v4.1 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.1 tests passed`);