'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
global.window=globalThis;global.DOMParser=function(){};const root=path.join(__dirname,'..');function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
const data=['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js','methodology-v6.2.js','dashboard-v6.2.js','orange-fidelity-v6.4.js','methodology-v6.4.js','dashboard-v6.4.js'];
const core=['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js','core-v6.2.js','core-v6.4.js'];
for(const f of data)run(path.join(root,'data',f));for(const f of core)run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V64,F=global.OBOL_ORANGE_FIDELITY_V64,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v6.4 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'6.4.0');assert.strictEqual(s.obolVersion,'6.4.0');assert.strictEqual(s.ui.dashboard64.showSourceFidelity,true);});
test('canonical breadth remains separate and unchanged',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[93,34,0,0,73,100]);assert.deepStrictEqual(M.canonicalBaseline,{implemented:93,partial:34,gap:0,stale:0,coveragePct:73,representedPct:100});});
test('AD CS is atomized beneath the broad canonical layer',()=>{const f=C.sourceFidelity64(lanes);assert.deepStrictEqual([f.files.total,f.files.atomized,f.partialBaseline.total,f.partialBaseline.atomized,f.total,f.reviewed,f.complete],[17,1,34,7,19,0,0]);assert.strictEqual(f.adcs.families,13);assert.strictEqual(f.adcs.sourceSha,'15546463dc97a0b17be5d10267686ebdfe347b8f');});
test('AD CS ledger contains the distinct ESC families called out by the North Star',()=>{const families=new Set(F.units.map(x=>x.family));for(const x of ['ESC1','ESC2/3','ESC4','ESC5','ESC6','ESC7','ESC8','ESC9/10','ESC11','ESC13','ESC14','ESC15'])assert(families.has(x),x);assert(F.units.some(x=>x.id==='adcs.esc15-schannel'));assert(F.units.some(x=>x.id==='adcs.esc15-agent'));assert(F.units.some(x=>x.id==='adcs.esc10-case1'));assert(F.units.some(x=>x.id==='adcs.esc10-case2'));});
test('every atomic unit preserves source path, conditions, owner mapping, and canonical parent',()=>{for(const u of F.units){assert(u.sourceFile==='adcs.md',u.id);assert(u.sourcePath&&u.sourcePath.length,u.id);assert(u.branchConditions&&u.branchConditions.length,u.id);assert(u.ownerCardIds&&u.ownerCardIds.length,u.id);assert(M.atomizedCanonicalKeys.includes(u.canonicalKey),u.id);assert.strictEqual(u.auditStatus,'needs-audit',u.id);}});
test('broad owner representation is not counted as source-fidelity completion',()=>{const f=C.sourceFidelity64(lanes);assert.strictEqual(f.broadOwned,19);assert.strictEqual(f.complete,0);assert.strictEqual(f.broadOwnedPct,100);assert.strictEqual(f.completePct,0);});
test('Dashboard captures the North Star requirement matrix explicitly',()=>{const f=C.sourceFidelity64(lanes),m=Object.fromEntries(f.matrix.map(x=>[x.id,x]));for(const x of ['sourceStructure','branchConditions','toolInventory','ownerMapping'])assert.strictEqual(m[x].count,19,x);for(const x of ['toolReview','commandSurface','executionContext','evidence','nextSteps','reporting','cleanup','disposition'])assert.strictEqual(m[x].count,0,x);const compliance=C.northStarCompliance64(lanes);assert.deepStrictEqual([compliance.inventoryCaptured,compliance.inventoryPossible],[76,76]);assert.strictEqual(compliance.deliveryCaptured,0);assert.strictEqual(compliance.terminalCaptured,0);});
test('Build Next splits atomic fidelity work from sections that still need decomposition',()=>{const q=C.buildNext64(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,19,27,46]);assert.strictEqual(q.rows.filter(x=>x.kind==='source-fidelity').length,19);assert.strictEqual(q.rows.filter(x=>x.kind==='source-depth-inventory').length,27);});
test('North Star Dashboard exposes breadth, atomization, and fidelity as separate metrics',()=>{const d=C.northStarDashboard64(C.newState(),lanes);assert.strictEqual(d.sourceFidelity64.files.atomized,1);assert.strictEqual(d.sourceFidelity64.partialBaseline.atomized,7);assert.strictEqual(d.sourceFidelity64.complete,0);assert(d.metrics.some(x=>x.id==='v64-source-inventory'&&x.count===1&&x.total===17));assert(d.metrics.some(x=>x.id==='v64-adcs-fidelity'&&x.count===0&&x.total===19));assert(d.milestones.some(x=>x.release==='v6.4'&&x.implemented===93&&x.representedPct===100));});
test('release quality gate remains clean while source-fidelity debt stays visible',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});
test('v6.4 release wiring and documentation are complete',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.4.js','methodology-v6.4.js','dashboard-v6.4.js','core-v6.4.js','app-v6.4.js','obol-v6.4.css'])assert(idx.includes(x),x);assert(readme.includes('Current release: **v6.4**'));assert(readme.includes('19 atomic AD CS source units'));assert(changelog.includes('## v6.4'));assert(fs.existsSync(path.join(root,'docs','v6.4.md')));assert(fs.existsSync(path.join(root,'docs','ORANGE-SOURCE-DEPTH.md')));});
test('README Build Next generator reports atomic source fidelity',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('46 items'));assert(out.includes('0 canonical gaps'));assert(out.includes('1/17 source files atomized'));assert(out.includes('7/34 partial baselines decomposed'));assert(out.includes('0/19 inventoried atomic units fidelity-complete'));assert(out.includes('AD CS enumeration and routing'));});
test('sanitized export advances to v6.4 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v6.4 tests passed`);
