'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
global.window=globalThis;global.DOMParser=function(){};const root=path.join(__dirname,'..');function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
const data=['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js','methodology-v6.2.js','dashboard-v6.2.js','orange-fidelity-v6.4.js','methodology-v6.4.js','dashboard-v6.4.js','orange-fidelity-v6.5.js','methodology-v6.5.js','dashboard-v6.5.js'];
const core=['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js','core-v6.2.js','core-v6.4.js','core-v6.5.js'];
for(const f of data)run(path.join(root,'data',f));for(const f of core)run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V65,F=global.OBOL_ORANGE_FIDELITY_V64,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
test('v6.5 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'6.5.0');assert.strictEqual(s.obolVersion,'6.5.0');assert.strictEqual(s.ui.dashboard65.showFidelityWave,true);});
test('v6.5 promotes only fully exhausted AD CS canonical parents',()=>{const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[95,32,0,0,75,100]);assert.strictEqual(section('adcs.enumeration').status,'implemented');assert.strictEqual(section('adcs.web-enrollment').status,'implemented');assert.strictEqual(section('adcs.template-misconfig').status,'partial');assert.deepStrictEqual(M.advancedKeys,['adcs.enumeration','adcs.web-enrollment']);});
test('first five atomic AD CS units have explicit modeled dispositions',()=>{const ids=['adcs.inventory','adcs.esc8','adcs.esc1','adcs.esc2','adcs.esc3'];for(const id of ids){const u=F.units.find(x=>x.id===id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.5',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.strictEqual(global.OBOL_ORANGE_FIDELITY_V65.modeled,5);});
test('source fidelity advances while unfinished denominators stay visible',()=>{const f=C.sourceFidelity65(lanes);assert.deepStrictEqual([f.files.total,f.files.atomized,f.partialBaseline.total,f.partialBaseline.atomized,f.total,f.reviewed,f.complete,f.pending],[17,1,34,7,19,5,5,14]);assert.strictEqual(f.broadOwned,19);assert.strictEqual(f.completePct,26);});
test('North Star requirement matrix credits only the five delivered atomic units beyond inventory',()=>{const f=C.sourceFidelity65(lanes),m=Object.fromEntries(f.matrix.map(x=>[x.id,x]));for(const x of ['sourceStructure','branchConditions','toolInventory','ownerMapping'])assert.strictEqual(m[x].count,19,x);for(const x of ['toolReview','commandSurface','executionContext','evidence','nextSteps','reporting','cleanup','disposition'])assert.strictEqual(m[x].count,5,x);});
test('Build Next consumes the first five atomic audits and preserves inventory debt',()=>{const q=C.buildNext65(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,14,27,41]);assert.strictEqual(q.rows[0].key,'adcs.esc13');assert(q.rows.every(x=>!['adcs.inventory','adcs.esc8','adcs.esc1','adcs.esc2','adcs.esc3'].includes(x.key)));});
test('new AD CS owners have usable command, execution, Evidence, and reporting contracts',()=>{for(const id of ['adcs-enumeration55','adcs-esc8-65','adcs-esc1-65','adcs-esc2-65','adcs-esc3-65']){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.commands.every(x=>x.operatorSurface40),id);assert(c.evidence45&&c.evidence45.source==='v6.5',id);assert(c.report47&&c.report47.evidenceProfile,id);}assert(card('adcs-esc8-65').commands.some(x=>(x.opts||[]).length));assert(card('adcs-esc1-65').commands.some(x=>(x.opts||[]).length));assert(card('adcs-esc3-65').commands.some(x=>(x.opts||[]).length));});
test('Evidence proof remains certificate/material bounded',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};global.OBOL_INTAKE_V25={normalizeText:x=>String(x||'')};run(path.join(root,'assets','intake-v6.5.js'));const I=global.OBOL_INTAKE_V65;let p=I.proof65('adcs-enumeration55','certipy find','Certificate Authorities\nCertificate Templates\nESC1\nWeb Enrollment enabled');assert(p.facts.includes('adcs.enumerated'));assert(p.facts.includes('adcs.esc1'));assert(p.facts.includes('adcs.web_enrollment'));p=I.proof65('adcs-esc8-65','certipy relay','Listening on 0.0.0.0');assert.strictEqual(p.success,false);assert.deepStrictEqual(p.facts,[]);p=I.proof65('adcs-esc1-65','certipy req','Got certificate\nSaved certificate and private key to admin.pfx');assert.deepStrictEqual(p.facts,['credential.certificate']);assert(!p.facts.includes('access.admin'));assert(!p.facts.includes('access.system'));});
test('Dashboard exposes the v6.5 atomic delivery wave',()=>{const d=C.northStarDashboard65(C.newState(),lanes);assert.strictEqual(d.sourceFidelity65.complete,5);assert.strictEqual(d.buildNext65.total,41);assert(d.metrics.some(x=>x.id==='v65-fidelity-wave'&&x.count===5&&x.total===19));assert(d.milestones.some(x=>x.release==='v6.5'&&x.implemented===95&&x.partial===32));});
test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});
test('v6.5 release wiring and documentation are complete',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.5.js','methodology-v6.5.js','dashboard-v6.5.js','core-v6.5.js','intake-v6.5.js','app-v6.5.js','obol-v6.5.css'])assert(idx.includes(x),x);assert(readme.includes('Current release: **v6.5**'));assert(readme.includes('5 / 19'));assert(changelog.includes('## v6.5'));assert(fs.existsSync(path.join(root,'docs','v6.5.md')));});
test('README Build Next generator reports the v6.5 live queue',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('41 items'));assert(out.includes('95/127 fully implemented (75%)'));assert(out.includes('5/19 inventoried atomic units fidelity-complete'));assert(out.includes('ESC13 issuance-policy / group-link template path'));assert(!out.includes('AD CS enumeration and routing — adcs.md · source fidelity'));});
test('sanitized export advances to v6.5 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.5.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v6.5 tests passed`);
