'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
global.window=globalThis;global.DOMParser=function(){};const root=path.join(__dirname,'..');function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
const data=['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js','methodology-v6.2.js','dashboard-v6.2.js'];
const core=['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js','core-v6.2.js'];
for(const f of data)run(path.join(root,'data',f));for(const f of core)run(path.join(root,'assets',f));for(const f of ['intake-v2.1.js','intake-v5.3.js','intake-v5.4.js','intake-v5.5.js','intake-v5.6.js','intake-v5.7.js','intake-v5.8.js','intake-v5.9.js','intake-v6.0.js','intake-v6.1.js','intake-v6.2.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V62,I=global.OBOL_INTAKE_V62,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v6.2 historical model initializes its release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'6.2.0');assert.strictEqual(s.obolVersion,'6.2.0');assert.strictEqual(s.ui.dashboard62.showSourceDepth,true);});
test('v6.2 closes the final canonical gap without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[93,34,0,0,73,100]);assert.deepStrictEqual(M.advancedKeys,['trusts.parent-child']);});
test('parent-to-child owner is delivery ready',()=>{const c=card('trust-parent-child62'),ready=C.deliveryReadiness52(lanes).rows.find(x=>x.key==='trusts.parent-child');assert(c&&c.evidence45&&c.evidence45.source==='v6.2');assert((c.commands||[]).every(x=>!!x.operatorSurface40));assert(c.report47&&c.report47.traceable);assert(ready&&ready.status==='implemented'&&ready.ready);});
test('v6.2 freezes 34 partial sections as the historical source-depth baseline',()=>{assert.strictEqual(M.sourceDepthBaseline,34);assert.strictEqual(M.sourceDepthKeys.length,34);const d=C.sourceDepth62(lanes);assert.deepStrictEqual([d.total,d.reviewed,d.pending,d.reviewedPct],[34,0,34,0]);assert(d.rows.every(x=>x.auditStatus==='needs-audit'));});
test('v6.2 Build Next historical model advances from canonical gaps to source-depth audits',()=>{const q=C.buildNext62(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceDepth,q.total],[0,0,0,34,34]);assert(q.rows.every(x=>x.kind==='source-depth'));assert(q.rows.some(x=>x.file==='adcs.md'));});
test('parent-to-child trust material and tickets remain below access and privilege',()=>{let p=I.proof62('trust-parent-child62',"impacket-secretsdump -just-dc-user 'CHILD$' PARENT/u:p@dc",'trust nthash: 0123456789abcdef0123456789abcdef');assert(p.success&&p.facts.includes('trust.secret_material')&&!p.facts.includes('access.cross_domain'));p=I.proof62('trust-parent-child62','impacket-ticketer parenttrustuser','Saving ticket in parenttrustuser.ccache');assert(p.success&&p.facts.includes('kerberos.tickets')&&!p.facts.includes('access.cross_domain'));p=I.proof62('trust-parent-child62','KRB5CCNAME=parenttrustuser.ccache impacket-smbclient child/u@host','Type help for list of commands');assert(p.success&&p.facts.includes('access.cross_domain')&&!p.facts.includes('access.admin')&&!p.facts.includes('access.system'));});
test('v6.2 historical dashboard distinguishes canonical representation from source-depth exhaustion',()=>{const d=C.northStarDashboard62(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance62.toGap,0);assert.strictEqual(d.canonicalAdvance62.representedPct,100);assert.strictEqual(d.sourceDepth62.total,34);assert.strictEqual(d.sourceDepth62.reviewed,0);assert(d.sourceDepthPlan62.statement.includes('Zero canonical gaps'));assert(d.milestones.some(x=>x.release==='v6.2'&&x.implemented===93&&x.representedPct===100));});
test('live release quality gate remains structurally clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert(/Release quality gate passed: 0 implemented-quality repairs, 0 mapped-delivery repairs, \d+ canonical gaps\./.test(r.stdout||''));});
test('release PR validator accepts the current repository contract',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});
test('v6.2 historical release wiring remains present',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['methodology-v6.2.js','dashboard-v6.2.js','core-v6.2.js','intake-v6.2.js','app-v6.2.js','obol-v6.2.css'])assert(idx.includes(x),x);assert(/Current release: \*\*v\d+\.\d+\*\*/.test(readme));assert(readme.includes('Canonical breadth is not source exhaustion'));assert(changelog.includes('## v6.2'));assert(fs.existsSync(path.join(root,'docs','v6.2.md')));assert(fs.existsSync(path.join(root,'docs','ORANGE-SOURCE-DEPTH.md')));});
test('README Build Next generator remains structurally valid after v6.2',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(/\*\*Current live queue:\*\* \d+ items/.test(out));assert(/\*\*Canonical methodology:\*\* \d+\/127 fully implemented \(\d+%\)/.test(out));assert(out.includes('North Star Dashboard → Build Next'));});
test('v6.2 sanitized export retains secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.2.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v6.2 tests passed`);
