'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V81,P=global.OBOL_PROJECT_V81,F81=global.OBOL_ORANGE_FIDELITY_V81;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.1 initializes the stable current project model without canonical denominator drift',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.1.0');assert.strictEqual(s.obolVersion,'8.1.0');assert.strictEqual(C.currentProjectModel,C.projectModel81);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard81);assert.strictEqual(p.release,'v8.1');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.1 completes low_access.md as a seventeen-unit source wave',()=>{assert.strictEqual(P.sourceWave.delivered.length,17);assert.strictEqual(F81.auditedIds.length,17);assert.strictEqual(F81.modeled.length,12);assert.strictEqual(F81.superseded.length,5);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'low_access.md',id);assert.strictEqual(u.sourceSha,'8744d9b137338bb1fa99d26bc257aa50ef490e5e',id);assert.strictEqual(u.auditedIn,'8.1',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity81(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[10,17,34,34,211,211,0]);});

test('v8.1 preserves earlier low-access local exploit and WebDAV atoms while closing the file',()=>{for(const id of ['low-access.local-exploit-smbghost','low-access.local-exploit-serioussam','low-access.webdav-coercion']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditedIn,'7.9',id);assert.strictEqual(u.sourceFile,'low_access.md',id);}assert((F.atomizedFiles||[]).includes('low_access.md'));assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,[]);});

test('legacy low-access variants are explicitly superseded rather than silently dropped',()=>{for(const id of ['low-access.applocker-mshta','low-access.uac-wsreset','low-access.uac-msdt','low-access.seimpersonate-roguepotato','low-access.seimpersonate-remotepotato0']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'superseded',id);assert(u.reason&&u.reason.length>80,id);}});

test('mature owners expose the useful source-matched command deltas',()=>{assert(hasRun('applocker-bypass58',/icacls C:\\Windows\\Temp/));assert(hasRun('windows-enum',/Invoke-PrivescCheck -Extended/));assert(hasRun('stored-credentials',/findstr \/si "pass"/));assert(hasRun('seimpersonate',/PrintSpoofer64\.exe -c/));assert(hasRun('seimpersonate',/obol-printspoofer-whoami\.txt/));for(const id of P.sourceWave.delivered){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic81||[]).includes(id),owner+' lineage for '+id);}}});

test('source inventory commands keep discovery, execution, credential, and privilege boundaries separate',()=>{assert(/candidate condition/i.test(card('applocker-bypass58').commands.find(x=>/icacls C:\\Windows\\Temp/.test(String(x.run))).note));assert(/leads/i.test(card('windows-enum').commands.find(x=>/Invoke-PrivescCheck -Extended/.test(String(x.run))).note));assert(/credential candidate only/i.test(card('stored-credentials').commands.find(x=>/findstr \/si "pass"/.test(String(x.run))).note));assert(/only explicit NT AUTHORITY\\\\SYSTEM output/i.test(card('seimpersonate').commands.find(x=>/PrintSpoofer64\.exe -c/.test(String(x.run))).note));});

test('Build Next advances to seven remaining whole-file inventories',()=>{const q=C.buildNext81(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,7,7]);assert(q.rows.every(x=>x.kind==='source-file-inventory'));assert.deepStrictEqual(q.rows.map(x=>x.file),P.sourceWave.fileInventoryQueue);assert.strictEqual(q.rows[0].file,'crack_hash.md');assert(!q.rows.some(x=>x.file==='low_access.md'));});

test('project model exposes v8.1 source accounting and next file',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[211,211,0,10,34,7]);assert.strictEqual(p.phase.id,'whole-file-source-inventory');assert.strictEqual(p.next.file,'crack_hash.md');assert.strictEqual(p.recent[0].release,'v8.1');assert(p.details.sourceWave81);});

test('README generator reflects the v8.1 current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 7 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 10/17 source files atomized, 34/34 partial baselines decomposed, 211/211'));assert(out.includes('**Current phase:** Orange whole-file source inventory.'));assert(out.includes('crack_hash.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.1',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.1 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.1.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.1.js','methodology-v8.1.js','project-model-v8.1.js','core-v8.1.js','app-v8.1.js','obol-v8.1.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.1.js','methodology-v8.1.js','project-model-v8.1.js','core-v8.1.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.1.js'));assert(!idx.includes('intake-v8.1.js'));assert(readme.includes('Current release: **v8.1**'));assert(releaseDoc.includes('# Obol v8.1'));});

test('sanitized export advances to v8.1 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.1 tests passed`);
