'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js'])run(path.join(root,'assets',f));
run(path.join(root,'data','signatures.js'));run(path.join(root,'assets','app-v2-intake.js'));for(const f of ['intake-v2.5.js','intake-v2.6.js','intake-v2.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,X=global.OBOL_INTAKE_V27;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v2.7 state initializes lineage, network model and search filters',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.7.0');assert.strictEqual(s.obolVersion,'2.7.0');assert(Array.isArray(s.networkModel.observations));assert.strictEqual(s.ui.searchFilters27.kind,'all');});
test('duplicate typed artifacts merge producer lineage instead of losing provenance',()=>{const s=C.newState(),a=C.addTypedArtifact(s,'hosts','172.16.60.20',{producer:{cardId:'enum-a',source:'card-evidence'}}),b=C.addTypedArtifact(s,'hosts','172.16.60.20',{producer:{cardId:'enum-b',source:'card-evidence'}});assert.strictEqual(a.id,b.id);assert.strictEqual(a.producedBy.length,2);assert(a.producedBy.some(x=>x.cardId==='enum-a'));assert(a.producedBy.some(x=>x.cardId==='enum-b'));});
test('artifact handoff records consumption lineage',()=>{const s=C.newState(),a=C.addTypedArtifact(s,'hosts','172.16.60.20',{source:'test'}),h=C.applyArtifactHandoff(s,a);assert.strictEqual(h.param,'target');assert.strictEqual(s.params.target,'172.16.60.20');assert.strictEqual(a.consumedBy.length,1);assert.strictEqual(a.consumedBy[0].param,'target');});
test('typed artifacts bind directly into compatible command option fields',()=>{const s=C.newState(),share=C.addTypedArtifact(s,'shares','SYSVOL',{source:'test'}),card={id:'smb-demo',title:'SMB demo',commands:[{tool:'nxc',run:'nxc smb {{target}}',opts:[{id:'share-name',arg:'--share',semantic:'Share name'}]}]},bindings=C.artifactBindingsForCard(s,card,s.activeContext),b=bindings.find(x=>x.row.id===share.id&&x.fieldType==='option');assert(b);const r=C.bindArtifactToCommand(s,card,share,b),cid=C.commandId(card.commands[0],0);assert.strictEqual(r.type,'option');assert.strictEqual(s.ui.opts[card.id+':'+cid].args['share-name'],'SYSVOL');assert.strictEqual(share.consumedBy.length,1);});
test('mixed transcript fixture preserves command boundaries',()=>{const text=fs.readFileSync(path.join(__dirname,'intake-v2.7-mixed.txt'),'utf8'),segments=X.segmentTranscript(text);assert(segments.length>=6);assert(segments.some(x=>x.command.startsWith('nxc smb')));assert(segments.some(x=>x.command.startsWith('certipy find')));assert(segments.some(x=>x.command.startsWith('curl -I')));});
test('network extraction recognizes interfaces, routes and service visibility',()=>{const text=fs.readFileSync(path.join(__dirname,'intake-v2.7-mixed.txt'),'utf8'),rows=X.extractNetwork(text);assert(rows.some(x=>x.type==='interface'&&x.interface==='eth1'&&x.address==='172.16.50.10'));assert(rows.some(x=>x.type==='interface'&&x.address==='172.16.50.25'));assert(rows.some(x=>x.type==='route'&&x.network==='172.16.60.0/24'&&x.gateway==='172.16.50.1'));assert(rows.some(x=>x.type==='service'&&x.address==='172.16.60.20'&&x.destination==='smb:445'));});
test('network observation model deduplicates repeated evidence',()=>{const s=C.newState(),rows=[{type:'route',network:'172.16.60.0/24',gateway:'172.16.50.1',interface:'eth1'}];assert.strictEqual(C.recordNetworkObservations(s,rows,{source:'a'}).length,1);assert.strictEqual(C.recordNetworkObservations(s,rows,{source:'b'}).length,0);assert.strictEqual(C.networkSummary(s,s.activeContext).routes.length,1);});
test('filtered workspace search scopes by artifact family and activity result',()=>{const s=C.newState(),lanes=[{lane:'web',title:'Web',cards:[{id:'web-demo',title:'Web demo',commands:[{tool:'curl',run:'curl {{url}}'}]}]}];C.addTypedArtifact(s,'shares','SYSVOL',{source:'intake:smb'});C.addTypedArtifact(s,'urls','http://172.16.60.20/admin',{source:'intake:web'});C.recordActivity(s,{cardId:'web-demo',context:s.activeContext,result:'tried',source:'manual'});let rows=C.searchWorkspace27(s,lanes,'',s.activeContext,{kind:'artifact',artifactKind:'shares',source:'',result:'all',time:'all'});assert(rows.length>=1);assert(rows.every(x=>x.kind==='artifact'&&x.artifactKind==='shares'));rows=C.searchWorkspace27(s,lanes,'',s.activeContext,{kind:'activity',artifactKind:'all',source:'',result:'tried',time:'all'});assert(rows.length===1);assert.strictEqual(rows[0].result,'tried');});
console.log(`\n${passed} v2.7 tests passed`);
