'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','review-v2.7.js'])run(path.join(root,'assets',f));
for(const f of ['nmap-v2.js','nmap-v2.3.js','nmap-v3.1.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,N=global.OBOL_NMAP;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v3.2 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.2.0');assert.strictEqual(s.obolVersion,'3.2.0');});
test('primary navigation returns to entity-first Targets without adding destinations',()=>{assert.strictEqual(C.NAVIGATION30.primary.length,5);assert.deepStrictEqual(C.NAVIGATION30.primary.map(x=>x.label),['Home','Targets','Evidence','Next Steps','Report']);const t=C.NAVIGATION30.primary.find(x=>x.id==='boxes');assert(t);assert(!/Nmap/i.test(t.help));});
test('More menu prioritizes active work before reference material',()=>{assert.deepStrictEqual(C.NAVIGATION30.secondary.map(x=>x.id),['queue','search','lanes','tools','lineage','map','guide','settings']);});
test('empty workspace points to Targets rather than embedding a tool on Home',()=>{const s=C.newState(),o=C.workspaceOverview32(s,[],s.activeContext);assert.strictEqual(o.stage,'setup');assert.strictEqual(o.next.href,'#/boxes');assert(/target/i.test(o.next.label));});
test('manually added host still exposes baseline-scan attention without changing page ownership',()=>{const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'box',ports:[]});s.activeContext={type:'host',id:'h1'};const o=C.workspaceOverview32(s,[],s.activeContext);assert.strictEqual(o.stage,'baseline');assert.strictEqual(o.next.href,'#/boxes');assert.strictEqual(o.attention.unscanned,1);assert(o.attention.items.some(x=>x.id==='unscanned'));});
test('v3.1 Nmap planning and host-discovery functionality remain intact',()=>{const cmd=C.buildNmapCommand31({profile:'discover',target:'10.10.10.0/24'});assert(cmd.includes('-sn'));const r=N.parse('Nmap scan report for 10.10.10.2\nHost is up (0.02s latency).\n');assert.strictEqual(r.hosts.length,1);assert.strictEqual(r.hosts[0].ip,'10.10.10.2');});
test('v3.2 app consolidates Nmap into Targets and moves structured graph import to Evidence',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v3.2.js'),'utf8');for(const token of ['scanModal32','simplifyTargets32','simplifyEvidence32','target-details32','Import BloodHound','simplifyHome32'])assert(app.includes(token),token);assert(app.includes("v.querySelectorAll('.discovery31').forEach"));assert(app.includes("v.querySelectorAll('.intake-discovery31').forEach"));});
test('v3.2 CSS suppresses duplicate workflow surfaces and styles the focused scan modal',()=>{const css=fs.readFileSync(path.join(root,'assets','obol-v3.2.css'),'utf8');for(const token of ['.workflow30','.discovery31','.intake-discovery31','.scan-builder32','.target-details32','.attention-list32'])assert(css.includes(token),token);});
test('index wires v3.2 after v3.1 while retaining the v3.1 Nmap parser',()=>{const src=fs.readFileSync(path.join(root,'index.html'),'utf8');assert(src.includes('Obol v3.2'));assert(src.indexOf('core-v3.2.js')>src.indexOf('core-v3.1.js'));assert(src.indexOf('app-v3.2.js')>src.indexOf('app-v3.1.js'));assert(src.indexOf('obol-v3.2.css')>src.indexOf('obol-v3.1.css'));assert(src.includes('nmap-v3.1.js'));assert(src.includes('>Targets</a>'));});
test('sanitized export retains v3.2 state and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.2.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.2 tests passed`);
