'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V88,P=global.OBOL_PROJECT_V88,F88=global.OBOL_ORANGE_FIDELITY_V88;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}

test('v8.8 initializes the stable current project model without canonical drift',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.8.0');assert.strictEqual(s.obolVersion,'8.8.0');assert.strictEqual(C.currentProjectModel,C.projectModel88);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard88);assert.strictEqual(p.release,'v8.8');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.8 completes valid_user.md with eighteen terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,18);assert.strictEqual(F88.newAuditedIds.length,18);assert.strictEqual(F88.fileAuditedIds.length,18);assert.strictEqual(F88.newModeled.length,9);assert.strictEqual(F88.newSuperseded.length,9);for(const id of F88.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'valid_user.md',id);assert.strictEqual(u.sourceSha,'fa9ba8715ec616b468f92c47b80dee498b2fae24',id);assert.strictEqual(u.auditedIn,'8.8',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity88(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[17,17,34,34,334,334,0]);});

test('valid-user canonical parents remain implemented and mapped to mature owners',()=>{for(const key of ['valid_user.spray','valid_user.asrep']){let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key===key)s=x;assert(s,key);assert.strictEqual(s.status,'implemented',key);}for(const id of F88.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic88||[]).includes(id),owner+' lineage for '+id);}}});

test('final-file review preserves preferred mature owners and explicit supersession',()=>{for(const id of ['password-spray','asrep-roast','kerberoast','bloodhound-collect']){const c=card(id);assert(c,id);assert(c.sourceInventory88||c.sourceReview88,id);}assert.strictEqual(unit('valid-user.policy-nxc').auditStatus,'modeled');assert.strictEqual(unit('valid-user.asrep-getnpusers').auditStatus,'modeled');for(const id of ['valid-user.fgpp-powershell','valid-user.usual-password-kerbrute','valid-user.blind-kerberoast-rubeus','valid-user.blind-kerberoast-impacket','valid-user.cve-2022-33679']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'superseded',id);assert(u.reason.length>40,id);}});

test('source corrections and conservative proof boundaries remain explicit',()=>{assert(unit('valid-user.fgpp-powershell').sourceCorrection);assert(unit('valid-user.asrep-getnpusers').sourceCorrection);assert(unit('valid-user.blind-kerberoast-rubeus').sourceCorrection);for(const id of F88.newAuditedIds){const u=unit(id);assert(/prove only their own stage|separate stage-appropriate Evidence/i.test(u.evidenceBoundary),id);}assert(/separate|not.*access|proof/i.test(card('asrep-roast').sourceReview88.proofBoundary));});

test('all methodology-bearing Orange files are atomized and the live source queue is empty',()=>{const f=C.sourceFidelity88(lanes),q=C.buildNext88(lanes);assert.strictEqual(f.files.atomized,f.files.total);assert.strictEqual(f.files.total,17);assert.strictEqual(f.pending,0);assert.deepStrictEqual(P.sourceWave.fileInventoryQueue,[]);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,0,0]);assert.deepStrictEqual(q.rows,[]);});

test('project model exposes source-fidelity completion',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.filesTotal,p.source.baselinesAtomized,p.buildNext.total],[334,334,0,17,17,34,0]);assert.strictEqual(p.phase.id,'orange-source-fidelity-complete');assert.strictEqual(p.next,null);assert.strictEqual(p.recent[0].release,'v8.8');assert(p.details.sourceWave88);assert.strictEqual(p.source.inventoryComplete,true);});

test('README generator reflects the source-complete current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 0 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 17/17 source files atomized, 34/34 partial baselines decomposed, 334/334'));assert(out.includes('**Current phase:** Orange source fidelity complete.'));assert(out.includes('No queued items.'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.8',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.8 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.8.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.8.js','methodology-v8.8.js','project-model-v8.8.js','core-v8.8.js','app-v8.8.js','obol-v8.8.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.8.js','methodology-v8.8.js','project-model-v8.8.js','core-v8.8.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.8.js'));assert(!idx.includes('intake-v8.8.js'));assert(readme.includes('Current release: **v8.8**'));assert(releaseDoc.includes('# Obol v8.8'));});

test('sanitized export advances to v8.8 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.8 tests passed`);
