'use strict';

const assert=require('assert');
const fs=require('fs');
const path=require('path');
const vm=require('vm');
const cp=require('child_process');

const root=path.join(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const run=args=>cp.spawnSync(process.execPath,args.map((part,idx)=>idx===0?path.join(root,part):part),{cwd:root,encoding:'utf8'});

const sandbox={window:{},globalThis:null};
sandbox.globalThis=sandbox.window;
vm.createContext(sandbox);
for(const rel of ['data/current-release.js','data/product-hardening/product-hardening-queue.js','data/product-hardening/work-packages.js','data/product-hardening/item-test-contracts.js'])vm.runInContext(read(rel),sandbox,{filename:rel});
const release=sandbox.window.OBOL_CURRENT_RELEASE;
const identity=sandbox.window.OBOL_RELEASE_IDENTITY;
const q=sandbox.window.OBOL_PRODUCT_HARDENING;
const workPackages=sandbox.window.OBOL_PRODUCT_HARDENING_WORK_PACKAGES;
const contracts=sandbox.window.OBOL_PRODUCT_HARDENING_TEST_CONTRACTS;
assert(release&&identity&&q&&workPackages&&contracts,'current release identity, queue, work packages, and contracts load');
assert(/^9\.\d+\.\d+$/.test(release.version),'current product-hardening authority remains a v9 semver release');
assert(/^v9\./.test(release.label),'current product-hardening authority remains in v9');
assert.strictEqual(release.phase,'product-hardening');
assert.strictEqual(release.orangeBaseline,'v8.8');

for(const id of ['cc-report-version','qa-version-test']){
  const item=q.items.find(candidate=>candidate.id===id);
  assert(item,'v9.4 version trust item remains in durable queue: '+id);
  assert.strictEqual(item.status,'complete',id+' v9.4 milestone remains complete');
  const contract=contracts.contracts[id];
  assert(contract&&contract.acceptance.length&&contract.validationCommands.length&&contract.proofFiles.length,id+' keeps item-specific Definition of Done');
  for(const rel of contract.proofFiles)assert(fs.existsSync(path.join(root,rel)),id+' proof file exists: '+rel);
  assert(!q.buildNext(1000).some(candidate=>candidate.id===id),id+' never returns to Product Build Next');
}
assert(q.tracks.find(t=>t.id==='critical-correctness').complete>=3,'critical correctness preserves at least the v9.4 completion floor');
assert(q.tracks.find(t=>t.id==='testing-qa').complete>=1,'testing/QA preserves at least the v9.4 version identity gate');
assert(q.totals().complete>=4,'product-hardening total preserves the v9.4 completion floor');
assert.strictEqual(workPackages.validate(q).length,0,'coherent work-package schema remains valid after later releases');

const evidencePayload='**Obol:** v2.0\n\n\nGenerated by Obol v2.0 inside operator evidence';
const stale=[
 '# Penetration Test Report — Draft',
 '',
 '**Generated:** 2026-08-31  ',
 '**Obol:** v8.8  ',
 '**Workspace schema:** 8.8.0',
 '',
 '```text',
 evidencePayload,
 '```',
 '',
 '---',
 '_Generated by Obol v8.8 from operator-recorded ledger state. Review every statement before delivery._'
].join('\n');
const normalized=identity.normalizeReportMarkdown(stale);
assert(normalized.includes('**Obol release:** '+release.label),'report metadata uses the live current release authority');
assert(!/^\*\*Obol:\*\*\s*v8\.8\s*$/m.test(normalized),'stale report-owned version metadata is removed');
assert(normalized.includes('_Generated by Obol '+release.label+' from operator-recorded ledger state.'),'report footer uses the live current release authority');
assert(normalized.includes('**Workspace schema:** 8.8.0'),'workspace schema identity remains distinct');
assert(normalized.includes(evidencePayload),'operator evidence payload and whitespace are not rewritten');
assert.strictEqual(identity.normalizeReportMarkdown(normalized),normalized,'report normalization is idempotent');
const exported={schemaVersion:'8.8.0',obolRelease:'9.2.0',obolReleaseLabel:'v9.2'};
identity.stampState(exported);
assert.deepStrictEqual({obolRelease:exported.obolRelease,obolReleaseLabel:exported.obolReleaseLabel,schemaVersion:exported.schemaVersion},{obolRelease:release.version,obolReleaseLabel:release.label,schemaVersion:'8.8.0'});

const app=read('assets/app-v8.8.js');
const preflight=read('tools/release-preflight.js');
const readme=read('README.md');
const hardening=read('docs/PRODUCT-HARDENING.md');
const releaseDoc=read('docs/v9.4.md');
assert(app.includes('window.OBOL_RELEASE_IDENTITY')&&app.includes('i.normalizeReportMarkdown(md)')&&app.includes('i.stampState(safe)'),'live app still consumes centralized report/export release identity helpers');
assert(preflight.includes("run('version trust surfaces',['tools/validate-version-identity.js'])"),'preflight permanently gates version trust surfaces');
assert(/Current release: \*\*v9\.[0-9]+(?:\.[0-9]+)?\*\*/.test(readme),'README remains on a current v9 product-hardening release');
assert(hardening.includes('## Version trust surfaces')&&hardening.includes('v9.4 completes `cc-report-version` and `qa-version-test`'),'product-hardening docs preserve the v9.4 version trust milestone');
assert(releaseDoc.includes('# Obol v9.4')&&releaseDoc.includes('cc-report-version')&&releaseDoc.includes('qa-version-test'),'release doc preserves both v9.4 completed queue items');
for(const forbidden of ['data/project-model-v9.4.js','assets/core-v9.4.js','assets/app-v9.4.js','assets/obol-v9.4.css'])assert(!fs.existsSync(path.join(root,forbidden)),'v9.4 added no fake runtime overlay: '+forbidden);

for(const command of [
 ['tools/validate-version-identity.js'],
 ['tools/validate-current-release.js'],
 ['tools/validate-product-hardening-queue.js'],
 ['tools/validate-asset-references.js'],
 ['tools/sync-current-release.js','--check'],
 ['tools/sync-product-build-next.js','--check'],
 ['tools/validate-release-pr.js','--repo-only','--release-version=9.4']
]){
  const result=run(command);
  assert.strictEqual(result.status,0,(result.stderr||result.stdout||'').trim());
}

console.log('v9.4 Version Trust Surfaces milestone remains regression-protected without freezing mutable current queue or release state.');
