'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
run(path.join(root,'assets','core-v2-base.js'));run(path.join(root,'assets','core-v2.js'));run(path.join(root,'assets','core-v2.1.js'));run(path.join(root,'data','tools-v2.2.js'));run(path.join(root,'assets','core-v2.2.js'));run(path.join(root,'assets','core-v2.3.js'));
run(path.join(root,'data','lanes.js'));run(path.join(root,'data','methodology-v2.2.js'));run(path.join(root,'data','methodology-v2.3.js'));run(path.join(root,'assets','nmap-v2.js'));run(path.join(root,'assets','nmap-v2.3.js'));run(path.join(root,'assets','intake-v2.3.js'));
const C=global.OBOL_CORE_V2,LANES=global.OBOL_LANES,X=global.OBOL_INTAKE_V23;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function findCommand(tool){for(const l of LANES)for(const c of l.cards||[])for(const cmd of c.commands||[])if(String(cmd.tool).toLowerCase()===tool)return cmd;throw new Error('missing '+tool);}
test('v2.3 state version is current',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.3.0');assert.strictEqual(s.obolVersion,'2.3.0');});
test('Forest-style Nmap output enriches hostname OS and domain',()=>{const txt='Nmap scan report for 10.129.95.210\n445/tcp open microsoft-ds Windows Server 2016 Standard 14393 microsoft-ds\n389/tcp open ldap Microsoft Windows Active Directory LDAP (Domain: htb.local, Site: Default)\n| smb-os-discovery:\n|   OS: Windows Server 2016 Standard 14393 (Windows Server 2016 Standard 6.3)\n|   Computer name: FOREST\n|   Domain name: htb.local\n|   FQDN: FOREST.htb.local\nService Info: Host: FOREST; OS: Windows; CPE: x\n';const r=global.OBOL_NMAP.parse(txt);assert.strictEqual(r.hosts[0].hostname,'FOREST');assert(/Windows Server 2016/.test(r.hosts[0].os));assert.strictEqual(r.hosts[0].domain,'htb.local');});
test('NetExec LDAP table distills useful users and drops mailbox noise',()=>{const txt='LDAP 10.0.0.1 389 DC Administrator 2021-08-31 00:00:00 0 Built-in\nLDAP 10.0.0.1 389 DC HealthMailboxabc 2019-01-01 00:00:00 0\nLDAP 10.0.0.1 389 DC svc-alfresco 2026-08-27 20:52:13 0\nLDAP 10.0.0.1 389 DC sebastien 2019-09-20 00:29:59 0';const u=X.extractUsers(txt,'nxc');assert(u.includes('svc-alfresco'));assert(u.includes('sebastien'));assert(u.includes('Administrator'));assert(!u.some(x=>/^HealthMailbox/.test(x)));});
test('LDIF userPrincipalName and sAMAccountName become usernames',()=>{const u=X.extractUsers('sAMAccountName: lucinda\nuserPrincipalName: mark@htb.local\n','ldap');assert.deepStrictEqual(u.sort(),['lucinda','mark']);});
test('reviewed user artifacts establish ad.user_list and unlock downstream work',()=>{const s=C.newState(),h=C.mergeHost(s,{ip:'10.0.0.8',domain:'htb.local'}),ctx={type:'host',id:h.id};C.addFact(s,'kerberos.reachable',{context:ctx});const before=C.rankedApplicable(s,LANES,ctx,{showAll:true}).map(x=>x.card.id);C.applyEvidenceUpdate(s,LANES,{source:'intake:nxc',context:ctx,artifacts:{users:['svc-alfresco','sebastien']}});assert(C.hasFact(s,'ad.user_list',ctx));assert.strictEqual(s.artifacts.users.length,2);const after=C.rankedApplicable(s,LANES,ctx,{showAll:true}).map(x=>x.card.id);assert(after.length>=before.length);assert((s.ui.lastEvidenceUpdate.facts||[]).includes('ad.user_list'));});
test('Nmap commands receive v2.3 timing output and retry controls',()=>{const c=findCommand('nmap');assert(c.opts.some(x=>x.arg==='-oA'));assert(c.opts.some(x=>x.arg==='--max-retries'));assert(c.opts.some(x=>x.radio==='timing-v23'&&x.value==='-T4'));});
test('LDAP and cracking commands receive practical v2.3 controls',()=>{const l=findCommand('ldapsearch'),h=findCommand('hashcat');assert(l.opts.some(x=>x.flag==='-LLL'));assert(l.opts.some(x=>x.arg==='-E'));assert(h.opts.some(x=>x.flag==='--show'));assert(h.opts.some(x=>x.arg==='-r'));});
console.log(`\n${passed} v2.3 tests passed`);
