'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V71,P=global.OBOL_PROJECT_V71;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.1 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.1.0');assert.strictEqual(s.obolVersion,'7.1.0');assert.strictEqual(C.currentProjectModel,C.projectModel71);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard71);assert.strictEqual(p.release,'v7.1');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[102,25,0,0,80,100]);});

test('delegation.md is atomized into six complete source units',()=>{const ids=['delegation.find','delegation.unconstrained','delegation.constrained-pt','delegation.constrained-kerberos','delegation.rbcd','delegation.s4u2self'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.1',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity71(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[2,17,9,34,25,25,0]);assert.strictEqual(f.completePct,100);});

test('only the two remaining partial delegation parents advance',()=>{for(const key of ['delegation.unconstrained','delegation.constrained']){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.1',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['delegation.unconstrained','delegation.constrained']);assert.strictEqual(section('delegation.rbcd').status,'implemented');assert.strictEqual(section('delegation.find').status,'implemented');assert.strictEqual(section('delegation.s4u2self').status,'implemented');});

test('Build Next continues into ACL source inventory after delegation completion',()=>{const q=C.buildNext71(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,25,25]);assert(q.rows.length===25);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'acl.md');assert.strictEqual(q.rows[0].label,'Computer object control / RBCD');for(const key of ['delegation.unconstrained','delegation.constrained'])assert(!q.rows.some(x=>x.key===key),key);});

test('v7.1 delegation owners expose provenance, execution context, cleanup, Evidence, and reporting',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('delegation.')),id);assert(c.evidence45&&c.evidence45.source==='v7.1',id);assert(c.report47&&c.report47.evidenceProfile,id);}for(const id of ['delegation-constrained-kerberos-71','delegation-rbcd-71']){const c=card(id);assert(c.commands.some(x=>/impacket-rbcd/.test(String(x.run))),id);assert(c.commands.some(x=>/-action remove/.test(String(x.run))),id);}assert(card('delegation-unconstrained-71').commands.some(x=>/Rubeus\.exe (monitor|dump)/.test(String(x.run))));assert(card('delegation-s4u2self-71').commands.some(x=>/impacket-getTGT/.test(String(x.run))));});

test('delegation Evidence keeps mutation, ticket, access, privilege, and cleanup separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.1.js'));const I=global.OBOL_INTAKE_V71;let p=I.proof71('delegation-discovery-71',"impacket-findDelegation 'corp/user:pass' -dc-ip 10.0.0.10",'AccountName DelegationType DelegationRightsTo\nsvc constrained cifs/server');assert.deepStrictEqual(p.facts,['ad.delegation_discovered']);p=I.proof71('delegation-rbcd-71',"impacket-rbcd -delegate-from 'TEMP$' -delegate-to 'WEB$' -action write corp/user:pass",'Delegation rights modified successfully!');assert.deepStrictEqual(p.facts,['ad.rbcd_configured']);p=I.proof71('delegation-constrained-pt-71',"impacket-getST -spn cifs/web -impersonate administrator corp/svc:pass",'Saving ticket in administrator@cifs_web@CORP.LOCAL.ccache');assert.deepStrictEqual(p.facts,['kerberos.tickets']);p=I.proof71('delegation-rbcd-71',"impacket-rbcd -delegate-from 'TEMP$' -delegate-to 'WEB$' -action remove corp/user:pass",'Delegation rights removed successfully!');assert.deepStrictEqual(p.facts,['ad.rbcd_restored']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin'])assert(!p.facts.includes(x));});

test('project model exposes the v7.1 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[25,25,0,2,9,25]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'acl.md');assert.strictEqual(p.recent[0].release,'v7.1');assert(p.details.sourceWave71);});

test('README generator remains structurally synchronized with current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('Current live queue:'));assert(out.includes('Canonical methodology:'));assert(out.includes('Orange source fidelity:'));assert(out.includes('Highest-priority live items:'));assert(out.includes('source inventory and decomposition'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.1',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.1 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v7.1.js','methodology-v7.1.js','project-model-v7.1.js','core-v7.1.js','intake-v7.1.js','app-v7.1.js','obol-v7.1.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v7.1.js'));assert(readme.includes('Current release: **v7.1**'));assert(changelog.includes('## v7.1'));assert(fs.existsSync(path.join(root,'docs','v7.1.md')));});

test('sanitized export advances to v7.1 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.1 tests passed`);
