'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V82,P=global.OBOL_PROJECT_V82,F82=global.OBOL_ORANGE_FIDELITY_V82;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.2 historical milestone remains complete while the current model may advance',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.strictEqual(P.version,'8.2.0');assert.strictEqual(P.release,'v8.2');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[127,0,0,0,100,100]);assert.strictEqual(p.canonical.implemented,127);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('v8.2 completed crack_hash.md with fifteen new units plus the inherited PXE unit',()=>{assert.strictEqual(P.sourceWave.delivered.length,15);assert.strictEqual(F82.newAuditedIds.length,15);assert.strictEqual(F82.fileAuditedIds.length,16);assert.strictEqual(F82.newModeled.length,14);assert.strictEqual(F82.newSuperseded.length,1);for(const id of F82.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'crack_hash.md',id);assert.strictEqual(u.sourceSha,'22482ad7cf46a56e49ae0a5bd38ba3e4021d2448',id);assert.strictEqual(u.auditedIn,'8.2',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const inherited=unit('crack-hash.pxe-sccm-aes128');assert(inherited);assert.strictEqual(inherited.auditedIn,'8.0');assert(F82.fileAuditedIds.includes(inherited.id));});

test('v8.2 corrects the pinned NetNTLMv1 Hashcat mode and supersedes external crack.sh',()=>{const corrected=unit('crack-hash.netntlmv1-hashcat'),external=unit('crack-hash.netntlmv1-cracksh');assert(corrected&&corrected.sourceCorrection);assert.strictEqual(corrected.sourceCorrection.pinnedMode,1000);assert.strictEqual(corrected.sourceCorrection.modeledMode,5500);assert.strictEqual(corrected.auditStatus,'modeled');assert.strictEqual(external.auditStatus,'superseded');assert(/third-party|external/i.test(external.reason));assert(hasRun('hashcat-modes',/hashcat -m 5500 -a 0/));assert(card('hashcat-modes').sourceCorrection82);});

test('mature cracking owners retain the full v8.2 local command set',()=>{for(const re of [/hashcat -m 3000 -a 0/,/hashcat -m 1000 -a 0/,/hashcat -m 5500 -a 0/,/hashcat -m 5600 -a 0/,/hashcat -m 13100 -a 0/,/hashcat -m 19600 -a 0/,/hashcat -m 18200 -a 0/,/hashcat -m 2100 -a 0/,/hashcat -m 31300 -a 3/])assert(hasRun('hashcat-modes',re),re);for(const re of [/--format=lm /,/--format=nt /,/--format=netntlm /,/--format=netntlmv2 /,/--format=krb5tgs /])assert(hasRun('john-modes',re),re);assert(hasRun('pxe-naa61',/hashcat -m 19850 -a 0/));for(const id of F82.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic82||[]).includes(id),owner+' lineage for '+id);}}});

test('v8.2 cracking Evidence overlay keeps plaintext, validation, access, and privilege separate',()=>{const intake=fs.readFileSync(path.join(root,'assets','intake-v8.2.js'),'utf8');assert(intake.includes("facts.push('credential.candidate')"));assert(/service validation, authenticated access, execution, and privilege remain separate/i.test(intake));assert(/tested wordlist\/mask candidate space/i.test(intake));assert(intake.includes('Status\\.{0,8}:?\\s*Cracked'));assert(!/outcomeFacts=.*access\.admin/.test(intake));});

test('v8.2 six-file queue remains historical while the live queue may shrink',()=>{assert.deepStrictEqual(P.sourceWave.fileInventoryQueue,['low_hanging.md','persistence.md','dom_admin.md','know_vuln_auth.md','trusts.md','valid_user.md']);const q=C.currentProjectModel(C.newState(),lanes).buildNext;assert(q.total>=0);assert(q.total<=6);assert((q.rows||[]).every(x=>x.kind==='source-file-inventory'));});

test('current project model preserves v8.2 source accounting as a floor',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=226);assert(p.source.atomicTotal>=226);assert.strictEqual(p.source.atomicPending,0);assert(p.source.filesAtomized>=11);assert.strictEqual(p.source.baselinesAtomized,34);assert((p.recent||[]).some(x=>x.release==='v8.2')||P.release==='v8.2');});

test('README generator remains a structural live projection after v8.2',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.2 historical release wiring remains complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.2.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.2.js','methodology-v8.2.js','project-model-v8.2.js','core-v8.2.js','intake-v8.2.js','app-v8.2.js','obol-v8.2.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.2.js','methodology-v8.2.js','project-model-v8.2.js','core-v8.2.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.2.js'));assert(releaseDoc.includes('# Obol v8.2'));});

test('current sanitized export still redacts secrets after v8.2',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.2 historical tests passed`);
