'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V44,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
test('v4.4 initializes current release and decision-path preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.4.0');assert.strictEqual(s.obolVersion,'4.4.0');assert.strictEqual(s.ui.decision44.showGuide,true);assert.strictEqual(s.ui.decision44.showTrail,true);});
test('v4.4 preserves the pinned Orange source and v4.3 live coverage baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.upstream.northStar,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[42,39,46,0,33,64]);});
test('representative live cards map to bounded Orange decision stages',()=>{const expected={'ad-dc-identify':'identity','asrep-roast':'credential','bloodhound-collect':'authenticated','delegation-abuse':'control','lateral-exec':'movement','windows-enum':'admin','dcsync':'domain','golden-ticket':'persistence'};for(const [id,stage] of Object.entries(expected)){assert(card(id),id);assert.strictEqual(card(id).orange44.stage,stage,id);}});
test('blank context starts at identity and successful mapped work advances the active-context stage',()=>{const s=hostState();let p=C.orangeDecisionProgress44(s,lanes,s.activeContext);assert.strictEqual(p.stage.id,'identity');C.recordActivity(s,{cardId:'asrep-roast',context:s.activeContext,result:'success',outcomeFacts:['kerberos.asrep_hash'],command:'fixture',evidence:'fixture'});p=C.orangeDecisionProgress44(s,lanes,s.activeContext);assert.strictEqual(p.stage.id,'credential');assert(p.completedCards.includes('asrep-roast'));assert(p.completedCanonical.some(x=>x.includes('asrep')));C.recordActivity(s,{cardId:'bloodhound-collect',context:s.activeContext,result:'success',command:'fixture',evidence:'fixture'});assert.strictEqual(C.orangeDecisionProgress44(s,lanes,s.activeContext).stage.id,'authenticated');});
test('Orange decision progress remains isolated between target contexts',()=>{const s=hostState();s.hosts.push({id:'h2',ip:'10.10.10.20',name:'LAB2',hostname:'LAB2',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});C.recordActivity(s,{cardId:'dcsync',context:{type:'host',id:'h1'},result:'success',command:'fixture',evidence:'fixture'});assert.strictEqual(C.orangeDecisionProgress44(s,lanes,{type:'host',id:'h1'}).stage.id,'domain');assert.strictEqual(C.orangeDecisionProgress44(s,lanes,{type:'host',id:'h2'}).stage.id,'identity');});
test('next-stage canonical work receives a positive signal without becoming an applicability gate',()=>{const s=hostState();C.addFact(s,'ad.user_list',{context:s.activeContext,source:'fixture',evidence:'users'});C.addFact(s,'kerberos.reachable',{context:s.activeContext,source:'fixture',evidence:'88'});const sig=C.orangeDecisionSignal44(s,card('asrep-roast'),s.activeContext);assert.strictEqual(sig.stage.id,'credential');assert.strictEqual(sig.progress.stage.id,'identity');assert(sig.delta>0);assert(/next Orange decision stage/.test(sig.reason));const late=C.orangeDecisionSignal44(s,card('golden-ticket'),s.activeContext);assert.strictEqual(late.delta,0);assert(/later Orange stage/.test(late.reason));});
test('earlier Orange stages are never negatively penalized after later progress',()=>{const s=hostState();C.addFact(s,'hash.krbtgt',{context:s.activeContext,source:'fixture',evidence:'krbtgt'});const sig=C.orangeDecisionSignal44(s,card('ad-dc-identify'),s.activeContext);assert.strictEqual(sig.progress.stage.id,'domain');assert.strictEqual(sig.delta,0);assert(/fallback/.test(sig.reason));});
test('Next Steps overview carries the decision progress and a queue of live mapped cards',()=>{const s=hostState();C.addFact(s,'ad.user_list',{context:s.activeContext,source:'fixture',evidence:'users'});C.addFact(s,'kerberos.reachable',{context:s.activeContext,source:'fixture',evidence:'88'});const o=C.nextStepsOverview34(s,lanes,s.activeContext,{showAll:true});assert(o.orangeDecision44);assert.strictEqual(o.orangeDecision44.progress.stage.id,'identity');assert(o.orangeDecision44.queue.length>0);for(const x of o.orangeDecision44.queue){assert(card(x.cardId),x.cardId);assert(card(x.cardId).orange44,x.cardId);assert.notStrictEqual(C.statusFor(s,x.cardId,s.activeContext),'done');}});
test('Orange decision signals compose with the existing Kali Windows execution-context model',()=>{const s=hostState();C.addFact(s,'ad.user_list',{context:s.activeContext,source:'fixture',evidence:'users'});C.addFact(s,'kerberos.reachable',{context:s.activeContext,source:'fixture',evidence:'88'});C.setOperatorMode40(s,s.activeContext,'windows');const r=C.rankedApplicable(s,lanes,s.activeContext,{showAll:true}).find(x=>x.card.id==='asrep-roast');assert(r);assert(r.orangeDecision44&&r.orangeDecision44.delta>0);assert(r.operatorContext40);assert.strictEqual(r.operatorContext40.mode,'windows');});
test('v4.4 UI makes the Orange decision path visible in Next Steps Home cards and Guide',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v4.4.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v4.4.css'),'utf8');for(const x of ['Orange 2025.03 decision path','Evidence-grounded canonical directions','Current Orange decision stage','Orange decision stage','v4.4 focus'])assert(app.includes(x),x);for(const x of ['.decision-shell44','.decision-queue44','.decision-signal44','.orange-stage44'])assert(css.includes(x),x);});
test('release wiring README docs and CI include v4.4 and preserve the new North Star guidance requirement',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.4.md'),'utf8');assert(idx.includes('Obol v4.4'));assert(idx.includes('methodology-v4.4.js'));assert(idx.includes('core-v4.4.js'));assert(idx.includes('app-v4.4.js'));assert(idx.includes('obol-v4.4.css'));assert(wf.includes('Run v4.4 regression suite'));assert(readme.includes('## Obol v4.4'));assert(readme.includes('improving "Next Steps"'));assert(readme.includes('operating from Kali or from a Windows host'));assert(readme.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/decision path/i.test(notes));});
test('sanitized export retains v4.4 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.4 tests passed`);
