'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v5.1 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.1.0');assert.strictEqual(s.obolVersion,'5.1.0');assert.strictEqual(s.ui.dashboard51.debtFilter,'all');});
test('v5.1 preserves pinned methodology denominator and v5.0 coverage',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('delivery debt exposes concrete mapped workflow rows',()=>{const d=C.deliveryDebt51(lanes);assert(d.mapped>0);assert.strictEqual(d.clean+d.total,d.mapped);assert(Array.isArray(d.rows));for(const r of d.rows){assert(r.cardId);assert(r.title);assert(r.missing.length);for(const m of r.missing)assert(['run','evidence','execution','report'].includes(m));}});
test('dashboard includes v5.1 milestone and delivery debt',()=>{const d=C.northStarDashboard51(C.newState(),lanes);assert(d.deliveryDebt51);assert(d.milestones.some(x=>x.release==='v5.1'));assert.strictEqual(d.coverage.coveragePct,41);});
test('release wiring is current',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['dashboard-v5.1.js','core-v5.1.js','app-v5.1.js','obol-v5.1.css'])assert(idx.includes(x),x);assert(wf.includes('Run v5.1 regression suite'));assert(readme.includes('Current release: **v5.1**'));assert(changelog.includes('## v5.1'));});
test('sanitized export advances to v5.1 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.1.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.1 tests passed`);
