'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V67;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v6.7 initializes current state and consolidated model',()=>{const s=C.newState(),p=C.projectModel67(s,lanes);assert.strictEqual(C.VERSION,'6.7.0');assert.strictEqual(s.obolVersion,'6.7.0');assert.strictEqual(s.ui.dashboard67.showSourceWave,true);assert.strictEqual(p.release,'v6.7');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[95,32,0,0,75,100]);});

test('v6.7 completes exactly the next three inventoried AD CS source units',()=>{for(const id of ['adcs.esc13','adcs.esc15-schannel','adcs.esc15-agent']){const u=F.units.find(x=>x.id===id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.7',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity67(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[1,17,7,34,8,19,11]);assert.strictEqual(f.completePct,42);});

test('canonical template parent stays partial while source fidelity advances',()=>{let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key==='adcs.template-misconfig')s=x;assert(s);assert.strictEqual(s.status,'partial');const q=C.buildNext67(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,11,27,38]);assert.strictEqual(q.rows[0].key,'adcs.esc4');});

test('ESC13 and ESC15 owners have explicit execution, Evidence, reporting, and transition contracts',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.commands.every(x=>x.operatorSurface40),id);assert(c.evidence45&&c.evidence45.source==='v6.7',id);assert(c.report47&&c.report47.evidenceProfile,id);}assert(card('adcs-esc13-67').commands.some(x=>x.operatorSurface40==='windows'));assert(card('adcs-esc13-67').commands.some(x=>x.operatorSurface40==='kali'));assert(card('adcs-esc15-schannel-67').commands.some(x=>String(x.run).includes("Client Authentication")));assert(card('adcs-esc15-agent-67').commands.some(x=>String(x.run).includes("Certificate Request Agent")));assert(card('adcs-esc15-agent-67').produces.includes('adcs.agent_certificate'));});

test('v6.7 Evidence remains certificate-material bounded',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v6.7.js'));const I=global.OBOL_INTAKE_V67;let p=I.proof67('adcs-esc13-67','certipy req','Got certificate\nSaved certificate and private key to esc13.pfx');assert.deepStrictEqual(p.facts,['credential.certificate']);p=I.proof67('adcs-esc15-schannel-67',"certipy req --application-policies 'Client Authentication'",'Saved certificate and private key to schannel.pfx');assert(p.facts.includes('credential.certificate'));assert(p.facts.includes('adcs.esc15_schannel_certificate'));p=I.proof67('adcs-esc15-agent-67',"certipy req --application-policies 'Certificate Request Agent'",'Saved certificate and private key to agent.pfx');assert(p.facts.includes('adcs.agent_certificate'));for(const x of p.facts)assert(!['access.admin','access.system','foothold.windows','access.cross_domain'].includes(x));assert.strictEqual(I.proof67('adcs-esc13-67','certipy req','Request submitted').success,false);});

test('project model and generated Build Next snapshot reflect the v6.7 wave',()=>{const p=C.projectModel67(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.buildNext.total],[8,19,11,38]);assert.strictEqual(p.next.key,'adcs.esc4');assert.strictEqual(p.recent[0].release,'v6.7');const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('38 items'));assert(out.includes('8/19 inventoried atomic units fidelity-complete'));assert(out.includes('AD CS source-fidelity delivery'));assert(out.includes('ESC4 writable certificate-template ACL'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v6.7',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v6.7 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.7.js','methodology-v6.7.js','project-model-v6.7.js','core-v6.7.js','intake-v6.7.js','app-v6.7.js','obol-v6.7.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v6.7.js'));assert(readme.includes('Current release: **v6.7**'));assert(changelog.includes('## v6.7'));assert(fs.existsSync(path.join(root,'docs','v6.7.md')));});

test('sanitized export advances to v6.7 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.7.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v6.7 tests passed`);
