'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V68,P68=global.OBOL_PROJECT_V68;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v6.8 historical adapter and milestone remain intact',()=>{const p=C.projectModel68(C.newState(),lanes);assert.strictEqual(p.release,'v6.8');assert.strictEqual(P68.version,'6.8.0');assert.deepStrictEqual([P68.releaseMilestone.implemented,P68.releaseMilestone.partial,P68.releaseMilestone.gap,P68.releaseMilestone.stale,P68.releaseMilestone.coveragePct,P68.releaseMilestone.representedPct],[97,30,0,0,76,100]);assert.strictEqual(P68.canonicalChange,true);});

test('v6.8 delivered units remain fidelity-complete after later releases',()=>{for(const id of ['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.8',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity68(lanes);assert.strictEqual(f.files.atomized,1);assert.strictEqual(f.files.total,17);assert.strictEqual(f.partialBaseline.atomized,7);assert.strictEqual(f.partialBaseline.total,34);assert.strictEqual(f.total,19);assert(f.complete>=11);});

test('v6.8 canonical reconciliation remains intact',()=>{for(const key of ['adcs.template-misconfig','adcs.acl-misconfig']){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'6.8',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P68.sourceWave.canonicalAdvanced,['adcs.template-misconfig','adcs.acl-misconfig']);});

test('current Build Next no longer contains v6.8 delivered units',()=>{const q=C.buildNext68(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);for(const id of ['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert'])assert(!q.rows.some(x=>x.key===id),id);assert(q.sourceFidelity<=8);});

test('ESC4 owner retains reversible current Certipy template workflow and ESC1 handoff',()=>{const c=card('adcs-esc4-68'),esc1=card('adcs-esc1-65');assert(c);assert(c.commands.some(x=>x.operatorSurface40==='kali'&&String(x.run).includes('-write-default-configuration')));assert(c.commands.some(x=>x.operatorSurface40==='windows'&&String(x.run).includes('-sspi')));assert(c.commands.some(x=>String(x.run).includes('-write-configuration')&&String(x.run).includes('{{backup_file}}')));assert(c.commands.some(x=>(x.opts||[]).some(o=>o.flag==='-force')));assert(esc1&&esc1.prereq&&esc1.prereq.any.includes('adcs.esc4_template_modified'));assert(c.evidence45&&c.evidence45.source==='v6.8');assert(c.report47&&c.report47.evidenceProfile);});

test('ESC7 owners retain separate CA role, pending request, issuance, retrieval, and cleanup',()=>{const ca=card('adcs-esc7-manage-ca-68'),cert=card('adcs-esc7-manage-cert-68');assert(ca&&cert);for(const needle of ['-add-officer','-remove-officer'])assert(ca.commands.some(x=>String(x.run).includes(needle)),needle);for(const needle of ['-enable-template','-issue-request','-retrieve','-disable-template'])assert(cert.commands.some(x=>String(x.run).includes(needle)),needle);assert(cert.commands.some(x=>String(x.run).includes('-retrieve')&&(x.opts||[]).some(o=>o.arg==='-key-file')));assert(ca.commands.some(x=>x.operatorSurface40==='windows'));assert(cert.commands.some(x=>x.operatorSurface40==='windows'));assert(ca.report47&&cert.report47);});

test('v6.8 Evidence remains conservatively stage-separated',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v6.8.js'));const I=global.OBOL_INTAKE_V68;let p=I.proof68('adcs-esc4-68',"certipy template -template Vuln -write-default-configuration",'Saving current configuration to Vuln.json\nSuccessfully updated Vuln');assert.deepStrictEqual(p.facts,['adcs.esc4_template_modified']);p=I.proof68('adcs-esc7-manage-ca-68',"certipy ca -ca CORP-CA -add-officer attacker",'Successfully added officer attacker');assert.deepStrictEqual(p.facts,['adcs.esc7_officer_added']);p=I.proof68('adcs-esc7-manage-cert-68',"certipy req -ca CORP-CA -template SubCA",'Request ID is 17\nWrote private key to 17.key\nFailed to request certificate');assert.deepStrictEqual(p.facts,['adcs.esc7_request_pending']);assert(!p.facts.includes('credential.certificate'));p=I.proof68('adcs-esc7-manage-cert-68',"certipy req -ca CORP-CA -retrieve 17",'Successfully retrieved certificate\nWrote certificate and private key to administrator.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc7_certificate_retrieved']);});

test('v6.8 source-wave metadata remains historical while current Build Next output stays structurally valid',()=>{assert.deepStrictEqual(P68.sourceWave.delivered,['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert']);assert.deepStrictEqual([P68.sourceWave.fidelityBefore,P68.sourceWave.fidelityAfter,P68.sourceWave.fidelityTotal],[8,11,19]);const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('Current live queue'));assert(out.includes('inventoried atomic units fidelity-complete'));assert(out.includes('Highest-priority live items'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs'));});

test('repository release contract remains valid after v6.8',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v6.8 release wiring remains present and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.8.js','methodology-v6.8.js','project-model-v6.8.js','core-v6.8.js','intake-v6.8.js','app-v6.8.js','obol-v6.8.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v6.8.js'));assert(changelog.includes('## v6.8'));assert(fs.existsSync(path.join(root,'docs','v6.8.md')));});

test('sanitized export tracks the current release while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v6.8 tests passed`);
