'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'EDGE',hostname:'EDGE',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function key(s){return C.contextKey(s.activeContext);}
test('v3.8 initializes pivot operational history and current release',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.8.0');assert.strictEqual(s.obolVersion,'3.8.0');assert(Array.isArray(s.networkModel.pathHistory));});
test('pivot operational checks preserve source interface listener health and history',()=>{const s=hostState(),p=C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'172.16.10.0/24',status:'active'},{context:s.activeContext,source:'test'});C.updatePivotOperations38(s,p.id,{sourceInterface:'ligolo','listenerHealth':'healthy',listenerNote:'listener responding'},{verified:true,kind:'health-check',note:'listener responding'});assert.strictEqual(p.sourceInterface,'ligolo');assert.strictEqual(p.listenerHealth,'healthy');assert(p.lastVerifiedAt);assert(C.pathHistory38(s,p.id).some(x=>x.kind==='health-check'));assert(C.pathOperational38(p).operational);});
test('listener health reduces or removes pivot reachability confidence without deleting the path',()=>{const s=hostState();C.recordNetworkObservations(s,[{type:'service',address:'172.16.20.5',destination:'smb:445'}],{context:s.activeContext,source:'test'});const p=C.recordNetworkPath(s,{mode:'pivot',kind:'chisel',network:'172.16.20.0/24',status:'active',lastVerifiedAt:C.now()},{context:s.activeContext,source:'test'});C.updatePivotOperations38(s,p.id,{listenerHealth:'healthy'},{verified:true});const good=C.targetReachabilitySignal38(s,card('smb-anon-enum'),s.activeContext);C.updatePivotOperations38(s,p.id,{listenerHealth:'down'},{verified:true});const down=C.targetReachabilitySignal38(s,card('smb-anon-enum'),s.activeContext);assert(good.delta>0);assert.strictEqual(down.delta,0);assert.strictEqual(p.status,'active');assert(/listener.*down/i.test(down.reason));});
test('transition-aware compromise paths label only exact grounded activities',()=>{const s=hostState(),k=key(s),act=C.recordActivity(s,{cardId:'smb-anon-enum',context:s.activeContext,result:'success',outcomeFacts:['smb.shares'],command:'nxc smb x --shares',evidence:'share'}),a=C.addTypedArtifact(s,'hosts','172.16.30.5',{context:s.activeContext,source:'test'}),b=C.addTypedArtifact(s,'shares','backup',{context:s.activeContext,source:'test'});a.consumedBy=[{cardId:'smb-anon-enum',activityId:act.id,contextKey:k,at:act.at}];b.producedBy=[{cardId:'smb-anon-enum',activityId:act.id,contextKey:k,at:act.at}];const chains=C.compromiseTransitionChains38(s,s.activeContext,{maxDepth:4}),c=chains.find(x=>x.artifactIds.join('|')===[a.id,b.id].join('|'));assert(c);assert(c.transitionSummary[0].grounded);assert.strictEqual(c.transitionSummary[0].activityId,act.id);});
test('network proof template requires an operationally verified path',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'pivot-ligolo',context:s.activeContext,result:'success',transitions:['network'],outcomeFacts:['pivot.established'],command:'ligolo',evidence:'tunnel established'}),p=C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'172.16.40.0/24',status:'active'},{context:s.activeContext,source:'test'});let r=C.reportReadiness35(s,lanes),row=r.rows.find(x=>x.activity.id===a.id);assert(row.requirements.some(q=>q.id==='path-operational'&&!q.done));C.updatePivotOperations38(s,p.id,{listenerHealth:'healthy'},{verified:true});r=C.reportReadiness35(s,lanes);row=r.rows.find(x=>x.activity.id===a.id);assert(row.requirements.some(q=>q.id==='path-operational'&&q.done));});
test('foothold privilege and objective templates check recorded transition facts',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'windows-enum',context:s.activeContext,result:'success',transitions:['foothold','privilege','objective'],outcomeFacts:['foothold.windows','access.system','objective.proof'],command:'whoami',evidence:'SYSTEM proof'}),row=C.reportReadiness35(s,lanes).rows.find(x=>x.activity.id===a.id);assert(row.requirements.some(q=>q.id==='foothold-outcome'&&q.done));assert(row.requirements.some(q=>q.id==='privilege-outcome'&&q.done));assert(row.requirements.some(q=>q.id==='objective-outcome'&&q.done));});
test('mixed AD session keeps LDAP and ticket-import intent separated',()=>{const s=hostState(),text="PS C:\\Temp> nxc ldap 10.10.10.10 -u '' -p '' --users\nLDAP 10.10.10.10 [+] corp.local\\:\nLDAP 10.10.10.10 [*] Enumerated 3 domain users\nPS C:\\Temp> Rubeus.exe ptt /ticket:C:\\Temp\\svc.kirbi\n[+] Ticket successfully imported!";const r=T.analyzeTerminal(text,lanes,s,s.activeContext);assert(r.activities.some(x=>x.cardId==='ad-anon-ldap-enum'));assert(r.activities.some(x=>x.cardId==='kerberos-tickets'&&x.outcomeFacts.includes('kerberos.ticket')));});
test('release wiring README docs and CI include v3.8',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v3.8.md'),'utf8');assert(idx.includes('Obol v3.8'));assert(idx.includes('core-v3.8.js'));assert(idx.includes('app-v3.8.js'));assert(idx.includes('obol-v3.8.css'));assert(wf.includes('Run v3.8 regression suite'));assert(readme.includes('## Obol v3.8'));assert(readme.includes('Orange Cyber Defense mind map'));assert(/listener health/i.test(readme));assert(/transition-aware/i.test(notes));});
test('sanitized export retains v3.8 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.8 tests passed`);
