'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V75,P=global.OBOL_PROJECT_V75;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.5 historical project metadata remains available behind the stable current model',()=>{assert.strictEqual(P.version,'7.5.0');assert.strictEqual(P.release,'v7.5');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[117,10,0,0,92,100]);assert.strictEqual(typeof C.projectModel75,'function');assert.strictEqual(typeof C.currentProjectModel,'function');const p=C.currentProjectModel(C.newState(),lanes);assert(p.canonical.implemented>=117);assert(p.canonical.partial<=10);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('v7.5 SCCM source wave remains a twenty-three-unit historical ledger',()=>{assert.strictEqual(P.sourceWave.delivered.length,23);assert.strictEqual(P.sourceWave.fidelityAfter,93);assert.strictEqual(P.sourceWave.filesAtomizedAfter,6);assert.strictEqual(P.sourceWave.baselinesAtomizedAfter,24);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'sccm.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.5',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity75(lanes);assert(f.files.atomized>=6);assert(f.partialBaseline.atomized>=24);assert(f.complete>=93);assert.strictEqual(f.pending,0);});

test('only the six frozen SCCM partial parents retain the v7.5 advance milestone',()=>{const advanced=['sccm.elevate1','sccm.elevate2','sccm.elevate3','sccm.takeover2','sccm.creds2','sccm.creds5'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.5',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);for(const key of P.sourceWave.historicalCanonicalDeepened){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.notStrictEqual(s.advancedIn,'7.5',key);}});

test('current Build Next never reopens completed SCCM source-depth rows',()=>{const q=C.buildNext75(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);assert(!q.rows.some(x=>x.file==='sccm.md'));for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);});

test('SCCM source units retain mature and focused v7.5 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('sccm.')),id);assert(c.evidence45&&c.evidence45.source==='v7.5',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext75,id);}assert(unit('sccm.recon-sccmhunter').ownerCardIds.includes('sccm-enum'));assert(unit('sccm.pxe-naa').ownerCardIds.includes('pxe-naa61'));assert(unit('sccm.dp-http-policies').ownerCardIds.includes('sccm-credential-recovery'));assert(unit('sccm.admin-exec-sharpsccm').ownerCardIds.includes('sccm-admin-exec'));assert(unit('sccm.cleanup-device').ownerCardIds.includes('sccm-cleanup-post'));});

test('v7.5 SCCM Evidence contract remains conservative',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.5.js'));const I=global.OBOL_INTAKE_V75;let p=I.proof75('sccm-force-client-push-75','SharpSCCM.exe invoke client-push -mp sccm.corp.local -sc P01 -t 10.0.0.5','Client push request successfully invoked');assert.deepStrictEqual(p.facts,['sccm.client_push_requested']);p=I.proof75('sccm-site-system-relay-75','ntlmrelayx.py -tf targets.txt -smb2support','Authenticating against smb://10.0.0.20 as CORP/SCCM$ SUCCEED');assert.deepStrictEqual(p.facts,['relay.success']);p=I.proof75('sccm-policy-request-75','SharpSCCM.exe get secrets -r temp -u TEMP$ -p Pass123!','NetworkAccessUsername: CORP\\naa\nNetworkAccessPassword: Secret!');assert.deepStrictEqual(p.facts,['sccm.policy_material','credential.candidate']);p=I.proof75('sccm-site-db-creds-75','sccmdecryptpoc.exe deadbeef','Decrypted username CORP\\svc_sccm password Winter2026!');assert.deepStrictEqual(p.facts,['credential.candidate']);for(const x of ['access.admin','access.system','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('current project model preserves the v7.5 source wave as history',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=93);assert(p.source.filesAtomized>=6);assert(p.source.baselinesAtomized>=24);assert(p.details.sourceWave75);assert.strictEqual(P.sourceWave.fidelityBefore,70);assert.strictEqual(P.sourceWave.fidelityAfter,93);});

test('README generator remains structurally synchronized without historical current-value literals',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Highest-priority live items:**'));assert(out.includes('source depth inventory'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract continues to pass under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.5 historical release wiring remains present and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.5.js','methodology-v7.5.js','project-model-v7.5.js','core-v7.5.js','intake-v7.5.js','app-v7.5.js','obol-v7.5.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.5.js'));assert(runtime.includes('methodology-v7.5.js'));assert(runtime.includes('project-model-v7.5.js'));assert(!idx.includes('dashboard-v7.5.js'));assert(changelog.includes('## v7.5'));assert(fs.existsSync(path.join(root,'docs','v7.5.md')));});

test('sanitized export retains redaction under the current runtime',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.5 tests passed`);
