'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
global.window=globalThis;global.DOMParser=function(){};const root=path.join(__dirname,'..');function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
const data=['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js','methodology-v6.2.js','dashboard-v6.2.js','orange-fidelity-v6.4.js','methodology-v6.4.js','dashboard-v6.4.js','orange-fidelity-v6.5.js','methodology-v6.5.js','source-delivery-v6.5.js','dashboard-v6.5.js','methodology-v6.6.js','dashboard-v6.6.js'];
const core=['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js','core-v6.2.js','core-v6.4.js','core-v6.5.js','core-v6.6.js'];
for(const f of data)run(path.join(root,'data',f));for(const f of core)run(path.join(root,'assets',f));run(path.join(root,'assets','intake-v6.6.js'));
const C=global.OBOL_CORE_V2,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v6.6 initializes consolidated current state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'6.6.0');assert.strictEqual(s.obolVersion,'6.6.0');assert.strictEqual(s.ui.dashboard66.detailsOpen,false);});
test('projectModel66 derives canonical status instead of owning a second denominator',()=>{const s=C.newState(),p=C.projectModel66(s,lanes),c=C.mindmapCoverage42(lanes);assert.deepStrictEqual(p.canonical,{total:c.sections,implemented:c.implemented,partial:c.partial,gap:c.gap,stale:c.stale,completePct:c.coveragePct,representedPct:c.representedPct});assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[95,32,0,0,75,100]);});
test('projectModel66 derives source fidelity and keeps unfinished denominators visible',()=>{const p=C.projectModel66(C.newState(),lanes),f=C.sourceFidelity65(lanes);assert.deepStrictEqual([p.source.filesAtomized,p.source.filesTotal,p.source.baselinesAtomized,p.source.baselinesTotal,p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.atomicPct],[f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending,f.completePct]);assert.deepStrictEqual([p.source.filesAtomized,p.source.filesTotal,p.source.baselinesAtomized,p.source.baselinesTotal,p.source.atomicComplete,p.source.atomicTotal],[1,17,7,34,5,19]);});
test('projectModel66 derives quality debt Build Next and next priority from the live queue',()=>{const p=C.projectModel66(C.newState(),lanes),q=C.buildNext65(lanes);assert.deepStrictEqual([p.quality.implementedQuality,p.quality.mappedDelivery,p.quality.canonicalGaps,p.buildNext.total],[q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.total]);assert.deepStrictEqual([p.quality.totalDebt,p.buildNext.total,p.buildNext.sourceFidelity,p.buildNext.sourceInventory],[0,41,14,27]);assert.strictEqual(p.next.label,'ESC13 issuance-policy / group-link template path');assert.strictEqual(p.next.kind,'source-fidelity');});
test('v6.6 Dashboard is an overview with explicit drill-downs rather than stacked default diagnostics',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v6.6.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v6.6.css'),'utf8');assert(app.includes('C.projectModel66'));assert(app.includes('Project progress'));assert(app.includes('What to build next'));assert(app.includes('Engineering detail'));assert(app.includes('Source-fidelity detail'));assert(app.includes('Full Build Next queue'));assert(app.includes('legacy-dashboard-sentinels66'));assert(css.includes('.overview-grid66'));assert(css.includes('.detail66'));});
test('README is a compact entry point and delegates engineering contracts',()=>{const r=fs.readFileSync(path.join(root,'README.md'),'utf8');assert(r.length<16000,`README is still too large: ${r.length} bytes`);for(const x of ['docs/ARCHITECTURE.md','docs/NORTH-STAR.md','docs/PROOF-CONTRACT.md','docs/ORANGE-SOURCE-DEPTH.md','BUILDING.md','CHANGELOG.md'])assert(r.includes(x),x);assert(r.includes('Current release: **v6.6**'));assert(r.includes('Canonical breadth is not source exhaustion'));assert(r.includes('atomic source-fidelity ledger'));});
test('README Build Next generator consumes projectModel66 and preserves structural historical contracts',()=>{const src=fs.readFileSync(path.join(root,'tools','sync-readme-build-next.js'),'utf8'),out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(src.includes('projectModel66'));assert(out.includes('North Star Dashboard → Build Next'));assert(out.includes('**Current live queue:** 41 items'));assert(out.includes('**Canonical methodology:** 95/127 fully implemented (75%)'));assert(out.includes('**Orange source fidelity:** 1/17 source files atomized, 7/34 partial baselines decomposed, 5/19 inventoried atomic units fidelity-complete.'));assert(out.includes('**Next priority:** **ESC13 issuance-policy / group-link template path** — source fidelity.'));});
test('v6.6 changes no Evidence semantics',()=>{const i=global.OBOL_INTAKE_V66;assert(i);assert.strictEqual(i.version,'6.6.0');assert.strictEqual(i.semantics,'unchanged');assert(!fs.readFileSync(path.join(root,'assets','intake-v6.6.js'),'utf8').includes('facts.push'));});
test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});
test('repository release contract passes for v6.6',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});
test('v6.6 release wiring and architecture documentation are complete',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['methodology-v6.6.js','dashboard-v6.6.js','core-v6.6.js','intake-v6.6.js','app-v6.6.js','obol-v6.6.css'])assert(idx.includes(x),x);assert(idx.includes('Obol v6.6'));assert(changelog.includes('## v6.6'));for(const x of ['ARCHITECTURE.md','NORTH-STAR.md','PROOF-CONTRACT.md','v6.6.md'])assert(fs.existsSync(path.join(root,'docs',x)),x);});
test('sanitized export advances to v6.6 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v6.6 tests passed`);
