'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v5.2 initializes release state in its historical layer',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.2.0');assert.strictEqual(s.obolVersion,'5.2.0');assert.strictEqual(s.ui.dashboard52.showBuildNext,true);});
test('v5.2 preserves the pinned canonical baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('delivery-ready accounting reconciles every represented canonical section',()=>{const r=C.deliveryReadiness52(lanes);assert.strictEqual(r.implementedCanonical,52);assert.strictEqual(r.partialCanonical,49);assert.strictEqual(r.readyImplemented+r.implementedDebt,52);assert.strictEqual(r.readyPartial+r.partialDebt,49);assert.strictEqual(r.rows.length,101);assert(r.deliveryReadyCoveragePct<=41);assert(r.implementedReadinessPct<=100);});
test('build-next queue prioritizes implemented quality debt then mapped debt then gaps',()=>{const r=C.deliveryReadiness52(lanes),q=C.buildNext52(lanes);assert.strictEqual(q.implementedQuality,r.implementedDebt);assert(q.total>=q.canonicalGaps);for(let i=1;i<q.rows.length;i++)assert(q.rows[i-1].priority<=q.rows[i].priority);for(const x of q.rows)assert(['implemented-quality','mapped-delivery','canonical-gap'].includes(x.kind));});
test('dashboard adds delivery-ready metric and v5.2 milestone',()=>{const d=C.northStarDashboard52(C.newState(),lanes);assert(d.deliveryReadiness52);assert(d.buildNext52);assert(d.metrics.some(x=>x.id==='delivery-ready-implementation'));assert(d.milestones.some(x=>x.release==='v5.2'));});
test('README retains the required To-do contract while changelog owns v5.2 history',()=>{const r=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');assert(r.includes('## To-do'));assert(r.includes('### North Star objectives'));assert(r.includes('### Recent changes'));assert(r.includes('### Build next'));assert(r.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(r.includes('North Star Dashboard → Build Next'));assert(/Current release: \*\*v\d+\.\d+\*\*/.test(r));const recent=(r.split('### Recent changes')[1]||'').split('### Build next')[0]||'',versions=[...recent.matchAll(/\*\*v\d+\.\d+\*\*/g)];assert(versions.length<=3);assert(changelog.includes('## v5.2'));});
test('v5.2 release wiring remains complete',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v5.2.md'),'utf8');for(const x of ['dashboard-v5.2.js','core-v5.2.js','app-v5.2.js','obol-v5.2.css'])assert(idx.includes(x),x);assert(wf.includes('Run v5.2 regression suite'));assert(changelog.includes('## v5.2'));assert(/delivery-ready canonical/i.test(notes));});
test('sanitized export retains v5.2 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.2.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.2 tests passed`);
