'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js'])run(path.join(root,'assets',f));
run(path.join(root,'assets','intake-v2.1.js'));run(path.join(root,'assets','intake-v5.3.js'));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V53,I=global.OBOL_INTAKE_V53,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v5.3 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.3.0');assert.strictEqual(s.obolVersion,'5.3.0');assert.strictEqual(s.ui.dashboard53.showRepair,true);});
test('v5.3 preserves the pinned canonical baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('targeted implemented-quality workflows are delivery-ready after repair',()=>{const r=C.cardReadiness52(lanes);assert.strictEqual(M.repairedCardIds.length,8);for(const id of M.repairedCardIds){const c=card(id),row=r.byCard[id];assert(c&&c.evidence45&&c.evidence45.source==='v5.3',id);assert(row&&row.ready,id);assert((c.commands||[]).every(x=>!!x.operatorSurface40),id);}});
test('repair summary is complete and keeps implementation debt diagnostic',()=>{const r=C.repairSummary53(lanes);assert.strictEqual(r.total,8);assert.strictEqual(r.ready,8);assert.strictEqual(r.profileAdds,8);assert(r.executionAdds>0);assert(r.implementedSectionCount>0);assert(r.currentImplementedDebt>=0);});
test('anonymous SMB and DNS proof require explicit useful output',()=>{let p=I.proof53('smb-anon-enum','Sharename       Type      Comment\npublic          Disk      files\npublic READ');assert(p.success&&p.facts.includes('smb.shares'));p=I.proof53('smb-anon-enum','SMB 10.0.0.5 445 HOST [*] Windows');assert(!p.success);p=I.proof53('dns-enum','www.corp.local. 3600 IN A 10.0.0.20\nXFR size: 12 records');assert(p.success&&p.facts.includes('dns.zone'));p=I.proof53('dns-enum','Transfer failed.');assert(!p.success);});
test('ticket and LAPS proof stay below privilege boundaries',()=>{let p=I.proof53('kerberos-tickets','Saving ticket in analyst.ccache');assert(p.success&&p.facts.includes('kerberos.tickets'));assert(!p.facts.includes('access.admin'));p=I.proof53('laps-read','ms-Mcs-AdmPwd: Example-Only-Password!');assert(p.success&&p.facts.includes('credential.plaintext'));assert(!p.facts.includes('access.admin'));});
test('Windows privilege and credential proof remain conservative',()=>{let p=I.proof53('seimpersonate','SeImpersonatePrivilege Enabled');assert(!p.success);p=I.proof53('seimpersonate','nt authority\\system');assert(p.success&&p.facts.includes('access.system'));p=I.proof53('dpapi-secrets','UserName: corp\\analyst\nPassword: ExampleOnly!');assert(p.success&&p.facts.includes('credential.plaintext'));});
test('dashboard exposes v5.3 repair accounting and milestone',()=>{const d=C.northStarDashboard53(C.newState(),lanes);assert(d.repair53&&d.repair53.ready===8);assert(d.metrics.some(x=>x.id==='v53-repair-wave'&&x.value===100));assert(d.milestones.some(x=>x.release==='v5.3'));});
test('v5.3 release wiring remains complete after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['methodology-v5.3.js','dashboard-v5.3.js','core-v5.3.js','intake-v5.3.js','app-v5.3.js','obol-v5.3.css'])assert(idx.includes(x),x);assert(wf.includes('Run v5.3 regression suite'));assert(/Current release: \*\*v\d+\.\d+(?:\.\d+)?\*\*/.test(readme));assert(readme.includes('## Future-agent quickstart'));assert(readme.includes('Product Build Next'));assert(changelog.includes('## v5.3'));});
test('sanitized export advances to v5.3 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.3.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.3 tests passed`);
