'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V72,P=global.OBOL_PROJECT_V72,S=global.OBOL_SOURCE_DELIVERY_V72;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.2 historical project metadata remains intact under the current runtime',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(P.version,'7.2.0');assert.strictEqual(P.release,'v7.2');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[107,20,0,0,84,100]);assert(C.currentProjectModel);assert(C.currentNorthStarDashboard);assert.strictEqual(s.obolVersion,C.VERSION);assert(p.canonical.implemented>=107);assert(p.canonical.partial<=20);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('acl.md v7.2 source wave remains terminal while current source inventory may grow',()=>{const ids=['acl.dcsync','acl.shadow-credentials','acl.group-membership','acl.group-owner-dacl','acl.computer-rbcd','acl.computer-shadow','acl.user-password','acl.user-targeted-kerberoast','acl.user-shadow','acl.user-logon-script','acl.ou-inheritance','acl.ou-gplink','acl.gmsa','acl.laps','acl.gpo','acl.dns-admin'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'acl.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.2',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.deepStrictEqual([P.sourceWave.fidelityBefore,P.sourceWave.fidelityAfter,P.sourceWave.fidelityTotal,P.sourceWave.filesAtomizedBefore,P.sourceWave.filesAtomizedAfter,P.sourceWave.baselinesAtomizedBefore,P.sourceWave.baselinesAtomizedAfter],[25,41,41,2,3,9,14]);const f=(C.sourceFidelity72||C.sourceFidelity71)(lanes);assert.strictEqual(f.files.total,17);assert.strictEqual(f.partialBaseline.total,34);assert(f.files.atomized>=3);assert(f.partialBaseline.atomized>=14);assert(f.complete>=41);assert(f.total>=41);assert(f.pending>=0);});

test('the five v7.2 ACL parents remain reconciled',()=>{const advanced=['acl.group-control','acl.computer-control','acl.user-control','acl.ou-control','acl.gpo'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.2',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);assert.strictEqual(section('acl.shadow-credentials').advancedIn,'5.6');assert.strictEqual(section('acl.gmsa').advancedIn,'5.6');for(const key of ['acl.dcsync','acl.shadow-credentials','acl.gmsa','acl.laps','acl.dns-admin'])assert.strictEqual(section(key).status,'implemented',key);});

test('current Build Next never reopens completed v7.2 ACL source rows',()=>{const q=(C.buildNext72||C.buildNext71)(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);assert(q.sourceFidelity>=0);assert(q.sourceInventory>=0);assert(q.total>=0);for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);for(const id of P.sourceWave.delivered)assert(!q.rows.some(x=>x.key===id),id);});

test('v7.2 ACL owners retain provenance, execution context, Evidence, and reporting',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('acl.')),id);assert(c.evidence45&&c.evidence45.source==='v7.2',id);assert(c.report47&&c.report47.evidenceProfile,id);assert(c.executionContext72,id);}assert(card('acl-shadow-credential-72').atomic72.length===3);});

test('v7.2 source-delivery detail and cleanup markers remain available',()=>{assert(S);const area=(global.OBOL_METHODOLOGY_V41.areas||[]).find(x=>x.id==='acl');assert(area);const summary=(area.nodes||[]).find(x=>x.id==='acl-control');assert(summary&&summary.coverage==='implemented');for(const id of S.detailNodeIds){const n=(area.nodes||[]).find(x=>x.id===id);assert(n,id);assert.strictEqual(n.coverage,'implemented',id);}assert(card('acl-group-owner-dacl-72').commands.some(x=>/OBOL_ACL_OWNER_RESTORED/.test(String(x.run))));assert(card('acl-group-owner-dacl-72').commands.some(x=>/OBOL_GROUP_DACL_RESTORED/.test(String(x.run))));assert(card('acl-ou-inheritance-72').commands.some(x=>/OBOL_OU_DACL_RESTORED/.test(String(x.run))));});

test('v7.2 ACL Evidence still keeps rights, mutation, credentials, access, privilege, and cleanup separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.2.js'));const I=global.OBOL_INTAKE_V72;let p=I.proof72('acl-group-membership-72',"Add-ADGroupMember -Identity 'HelpDesk' -Members 'user1'; Get-ADGroupMember -Identity 'HelpDesk'",'Name SamAccountName objectClass\nuser1 user1 user');assert.deepStrictEqual(p.facts,['ad.group_membership_changed']);p=I.proof72('acl-group-owner-dacl-72',"impacket-owneredit -action write -new-owner original -target group domain/user:pass && echo OBOL_ACL_OWNER_RESTORED",'OwnerSid modified successfully!\nOBOL_ACL_OWNER_RESTORED');assert.deepStrictEqual(p.facts,['ad.acl_owner_restored']);p=I.proof72('acl-ou-inheritance-72',"impacket-dacledit -action restore -file old.bak domain/user:pass && echo OBOL_OU_DACL_RESTORED",'DACL restored successfully\nOBOL_OU_DACL_RESTORED');assert.deepStrictEqual(p.facts,['ad.acl_restored']);p=I.proof72('acl-gmsa-read-72',"nxc ldap 10.0.0.10 -u user -p pass --gmsa",'svc_sql$ NTLM: 0123456789abcdef0123456789abcdef');assert.deepStrictEqual(p.facts,['credential.ntlm_hash','credential.candidate']);p=I.proof72('acl-gpo-control-72',"Set-GPRegistryValue -Name Test; Write-Output OBOL_GPO_WRITE_PROVED",'OBOL_GPO_WRITE_PROVED');assert.deepStrictEqual(p.facts,['ad.gpo_modified']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('current project model preserves the v7.2 source-wave history while advancing live state',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=41);assert(p.source.atomicTotal>=41);assert(p.source.atomicPending>=0);assert(p.source.filesAtomized>=3);assert(p.source.baselinesAtomized>=14);assert(p.buildNext.total>=0);assert((p.recent||[]).some(x=>x.release==='v7.2')||p.release==='v7.2');assert(P.sourceWave.delivered.length===16);});

test('README generator remains a structural live projection',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('Current live queue:'));assert(out.includes('Canonical methodology:'));assert(out.includes('Orange source fidelity:'));assert(out.includes('Highest-priority live items:'));assert(out.includes('source inventory and decomposition'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.2 historical release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v7.2.js','methodology-v7.2.js','project-model-v7.2.js','core-v7.2.js','intake-v7.2.js','app-v7.2.js','obol-v7.2.css'])assert(idx.includes(x),x);assert(runtimeIncludesSourceDelivery());assert(!idx.includes('dashboard-v7.2.js'));assert(readme.includes('**v7.2**'));assert(changelog.includes('## v7.2'));assert(fs.existsSync(path.join(root,'docs','v7.2.md')));function runtimeIncludesSourceDelivery(){return fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8').includes('source-delivery-v7.2.js');}});

test('sanitized export tracks the current version while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.2 historical tests passed`);
