'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V74,P=global.OBOL_PROJECT_V74;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.4 historical project metadata remains intact under the current runtime',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(P.version,'7.4.0');assert.strictEqual(P.release,'v7.4');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[111,16,0,0,87,100]);assert(C.currentProjectModel);assert(C.currentNorthStarDashboard);assert.strictEqual(s.obolVersion,C.VERSION);assert(p.canonical.implemented>=111);assert(p.canonical.partial<=16);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('authenticated.md v7.4 source wave remains terminal while current source inventory may grow',()=>{assert.strictEqual(P.sourceWave.delivered.length,19);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'authenticated.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.4',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.deepStrictEqual([P.sourceWave.fidelityBefore,P.sourceWave.fidelityAfter,P.sourceWave.fidelityTotal,P.sourceWave.filesAtomizedBefore,P.sourceWave.filesAtomizedAfter,P.sourceWave.baselinesAtomizedBefore,P.sourceWave.baselinesAtomizedAfter],[51,70,70,4,5,15,18]);const f=(C.sourceFidelity74||C.sourceFidelity73)(lanes);assert.strictEqual(f.files.total,17);assert.strictEqual(f.partialBaseline.total,34);assert(f.files.atomized>=5);assert(f.partialBaseline.atomized>=18);assert(f.complete>=70);assert(f.total>=70);assert(f.pending>=0);});

test('the three v7.4 authenticated parents remain reconciled',()=>{const advanced=['authenticated.auto-scan','authenticated.coerce','authenticated.known-vulns'];for(const key of advanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.4',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,advanced);for(const key of P.sourceWave.historicalCanonicalDeepened){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.notStrictEqual(s.advancedIn,'7.4',key);}});

test('current Build Next never reopens completed v7.4 authenticated source rows',()=>{const q=(C.buildNext74||C.buildNext73)(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);assert(q.sourceFidelity>=0);assert(q.sourceInventory>=0);assert(q.total>=0);for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);for(const id of P.sourceWave.delivered)assert(!q.rows.some(x=>x.key===id),id);});

test('v7.4 authenticated owners retain provenance, execution context, Evidence, and reporting',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('authenticated.')),id);assert(c.evidence45&&c.evidence45.source==='v7.4',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext74,id);}assert(unit('authenticated.bloodhound-ce').ownerCardIds.includes('bloodhound-collect'));assert(unit('authenticated.adcs').ownerCardIds.includes('adcs-enumeration55'));assert(unit('authenticated.sccm').ownerCardIds.includes('sccm-enum'));assert(unit('authenticated.kerberoast').ownerCardIds.includes('kerberoast'));for(const id of M.knownVulnerabilityOwners){const c=card(id);assert(c,id);assert((c.atomic74||[]).includes('authenticated.known-vulns-route'),id);}});

test('v7.4 authenticated Evidence still keeps enumeration, posture, coercion, access, execution, relay, and privilege separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.4.js'));const I=global.OBOL_INTAKE_V74;let p=I.proof74('authenticated-classic-enum-74',"nxc smb 10.0.0.10 -u 'alice' -p 'pass' --users",'sAMAccountName: alice\nsAMAccountName: bob');assert.deepStrictEqual(p.facts,['ad.user_list']);p=I.proof74('ad-posture-scan-74','PingCastle.exe --healthcheck --server corp.local','PingCastle Healthcheck report saved to ad_hc_corp.local.html');assert.deepStrictEqual(p.facts,['ad.posture_assessed']);p=I.proof74('authenticated-coercion-74',"coercer.py -d corp.local -u alice -p pass -t dc01 -l 10.0.0.5",'Coercion trigger success over RPC');assert.deepStrictEqual(p.facts,['coerce.candidate']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync','relay.success','credential.available'])assert(!p.facts.includes(x));});

test('current project model preserves the v7.4 source-wave history while advancing live state',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=70);assert(p.source.atomicTotal>=70);assert(p.source.atomicPending>=0);assert(p.source.filesAtomized>=5);assert(p.source.baselinesAtomized>=18);assert(p.buildNext.total>=0);assert.strictEqual(P.releaseMilestone.release,'v7.4');assert(P.sourceWave.delivered.length===19);});

test('README generator remains a structural live projection',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('Current live queue:'));assert(out.includes('Canonical methodology:'));assert(out.includes('Orange source fidelity:'));assert(out.includes('Highest-priority live items:'));assert(out.includes('Current phase:'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.4 historical release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.4.js','methodology-v7.4.js','project-model-v7.4.js','core-v7.4.js','intake-v7.4.js','app-v7.4.js','obol-v7.4.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.4.js'));assert(runtime.includes('methodology-v7.4.js'));assert(runtime.includes('project-model-v7.4.js'));assert(!idx.includes('dashboard-v7.4.js'));assert(changelog.includes('## v7.4'));assert(fs.existsSync(path.join(root,'docs','v7.4.md')));});

test('sanitized export tracks the current version while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.4 historical tests passed`);
