'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js','intake-v3.9.js','intake-v4.5.js','intake-v4.6.js','intake-v4.8.js'])run(path.join(root,'assets',f));
for(const f of ['report-v2.js','report-v2.1.js','report-v2.2.js','report-v2.3.js','report-v2.4.js','report-v2.5.js','report-v2.6.js','report-v2.7.js','report-v2.8.js','report-v2.9.js','report-v3.5.js','report-v4.0.js','report-v4.7.js','report-v4.8.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V48,R=global.OBOL_REPORT_V2,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function section(id){const f=(O.files||[]).find(x=>x.file==='persistence.md');return f&&(f.sections||[]).find(x=>x.id===id);}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';s.params.user='student';s.params.password='Passw0rd!';return s;}
function analyze(text){const s=hostState();return T.analyzeTerminal(text,lanes,s,s.activeContext);}
test('v4.8 initializes current release and persistence preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.8.0');assert.strictEqual(s.obolVersion,'4.8.0');assert.strictEqual(s.ui.persistence48.showBranch,true);assert.strictEqual(s.ui.persistence48.showTrail,true);});
test('v4.8 preserves the pinned Orange source and advances only live persistence coverage',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.upstream.northStar,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');assert.strictEqual(O.coverageRevision,'4.8');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('canonical persistence branch gains dedicated implemented and partial owners',()=>{for(const [id,status] of [['silver-ticket','implemented'],['dsrm','implemented'],['golden-cert','implemented'],['acl-persistence','implemented'],['skeleton-key','partial'],['custom-ssp','partial'],['diamond-ticket','partial'],['sapphire-ticket','partial'],['dc-shadow','partial']])assert.strictEqual(section(id).status,status,id);for(const id of M.cards)assert(card(id),id);});
test('new persistence cards have execution Evidence and report contracts',()=>{for(const id of M.cards){const c=card(id),contract=C.orangeContractFor45(c);assert(c.orange44,id);assert(c.evidence45,id);assert(c.report47,id);assert(contract.runReady,id);assert(contract.evidenceReady,id);assert((c.commands||[]).every(x=>['kali','windows','target'].includes(x.operatorSurface40)),id);}assert(card('silver-ticket').commands.some(x=>(x.opts||[]).some(o=>o.arg==='-aesKey')));assert(card('acl-persistence-lifecycle').commands.some(x=>/-action restore/.test(x.run)));});
test('Silver Ticket requires explicit saved ticket and does not invent service access',()=>{let r=analyze("kali$ impacket-ticketer -nthash deadbeef -domain-sid S-1-5-21-1 -domain corp.local -spn cifs/ws01.corp.local student\n[*] Creating basic skeleton ticket");let a=r.activities.find(x=>x.cardId==='silver-ticket');assert(a);assert.notStrictEqual(a.result,'success');r=analyze("kali$ impacket-ticketer -nthash deadbeef -domain-sid S-1-5-21-1 -domain corp.local -spn cifs/ws01.corp.local student\n[*] Saving ticket in student.ccache");a=r.activities.find(x=>x.cardId==='silver-ticket');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('persistence.silver_ticket'));assert(a.outcomeFacts.includes('kerberos.tickets'));assert(!a.outcomeFacts.includes('access.admin'));});
test('DSRM requires explicit verification value rather than registry write text',()=>{let r=analyze("PS C:\\> reg add HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa /v DsrmAdminLogonBehavior /t REG_DWORD /d 2 /f\nThe operation completed successfully.");let a=r.activities.find(x=>x.cardId==='dsrm-persistence');assert(a);assert.notStrictEqual(a.result,'success');r=analyze("PS C:\\> reg query HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa /v DsrmAdminLogonBehavior\n    DsrmAdminLogonBehavior    REG_DWORD    0x2");a=r.activities.find(x=>x.cardId==='dsrm-persistence');assert(a&&a.result==='success');assert.deepStrictEqual(a.outcomeFacts,['persistence.dsrm']);});
test('Golden Certificate separates CA material from forged persistence material',()=>{let r=analyze("kali$ certipy ca -backup -ca CORP-CA -username student@corp.local -hashes deadbeef -dc-ip 10.10.10.10\nSaved certificate and private key to 'corp-ca.pfx'");let a=r.activities.find(x=>x.cardId==='golden-certificate');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('credential.certificate'));assert(!a.outcomeFacts.includes('persistence.golden_certificate'));r=analyze("kali$ certipy forge -ca-pfx corp-ca.pfx -upn administrator@corp.local\nSaved forged certificate to 'administrator_forged.pfx'");a=r.activities.find(x=>x.cardId==='golden-certificate');assert(a&&a.outcomeFacts.includes('persistence.golden_certificate'));assert(!a.outcomeFacts.includes('access.admin'));});
test('advanced forged ticket parser distinguishes diamond and sapphire saved artifacts',()=>{let r=analyze("kali$ impacket-ticketer -request -domain corp.local -user student -password Passw0rd! -domain-sid S-1-5-21-1 -user-id 1104 -groups 512,513 Administrator\n[*] Saving ticket in Administrator.ccache");let a=r.activities.find(x=>x.cardId==='advanced-forged-tickets');assert(a&&a.outcomeFacts.includes('persistence.diamond_ticket'));assert(!a.outcomeFacts.includes('persistence.sapphire_ticket'));r=analyze("kali$ impacket-ticketer -request -impersonate Administrator -domain corp.local -user student -password Passw0rd! -domain-sid S-1-5-21-1 ignored\n[*] Saving ticket in ignored.ccache");a=r.activities.find(x=>x.cardId==='advanced-forged-tickets');assert(a&&a.outcomeFacts.includes('persistence.sapphire_ticket'));});
test('credential subsystem and DCShadow startup text remain attempts until explicit confirmation',()=>{let r=analyze('PS C:\\> mimikatz.exe "privilege::debug" "misc::skeleton" "exit"\nmisc::skeleton');let a=r.activities.find(x=>x.cardId==='credential-subsystem-persistence');assert(a);assert.notStrictEqual(a.result,'success');r=analyze('PS C:\\> mimikatz.exe "privilege::debug" "misc::skeleton" "exit"\nSkeleton Key is in memory');a=r.activities.find(x=>x.cardId==='credential-subsystem-persistence');assert(a&&a.outcomeFacts.includes('persistence.skeleton_key'));r=analyze('PS C:\\> mimikatz.exe "lsadump::dcshadow /object:user /attribute:description /value:test"\nDCShadow initialized');a=r.activities.find(x=>x.cardId==='dcshadow-persistence');assert(a);assert.notStrictEqual(a.result,'success');});
test('ACL persistence proof remains narrow and does not manufacture privilege',()=>{const r=analyze("kali$ impacket-dacledit -action write -rights FullControl -principal student -target svc_backup 'corp.local/student:Passw0rd!'\n[+] DACL modified successfully");const a=r.activities.find(x=>x.cardId==='acl-persistence-lifecycle');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('persistence.acl'));assert(!a.outcomeFacts.includes('access.admin'));});
test('persistence progress is context scoped and Next Steps carries branch readiness',()=>{const s=hostState();s.hosts.push({id:'h2',ip:'10.10.10.20',name:'LAB2',hostname:'LAB2',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});C.recordActivity(s,{cardId:'silver-ticket',context:{type:'host',id:'h1'},result:'success',outcomeFacts:['persistence.silver_ticket'],command:'fixture',evidence:'fixture'});assert.strictEqual(C.persistenceProgress48(s,{type:'host',id:'h1'}).current,'ticket');assert.strictEqual(C.persistenceProgress48(s,{type:'host',id:'h2'}).current,'material');const o=C.nextStepsOverview34(s,lanes,{type:'host',id:'h1'},{showAll:true});assert(o.persistence48);assert(o.persistence48.coverage.current.implemented===52);});
test('generated report includes persistence lifecycle cleanup obligations',()=>{const s=hostState();C.recordActivity(s,{cardId:'silver-ticket',context:s.activeContext,result:'success',command:'impacket-ticketer -spn cifs/ws01 ...',evidence:'Saving ticket in student.ccache',outcomeFacts:['persistence.silver_ticket']});const md=R.generate(s,lanes,'standard',{});assert(md.includes('Domain Persistence Lifecycle'));assert(md.includes('Silver Ticket Persistence'));assert(md.includes('Destroy local ticket artifacts/caches'));assert(md.includes('Orange Decision Path & Reporting Traceability'));});
test('v4.8 UI release wiring and README preserve North Star reporting and operator-loop requirements',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.8.md'),'utf8'),app=fs.readFileSync(path.join(root,'assets','app-v4.8.js'),'utf8');for(const x of ['Obol v4.8','methodology-v4.8.js','core-v4.8.js','intake-v4.8.js','report-v4.8.js','app-v4.8.js','obol-v4.8.css'])assert(idx.includes(x),x);assert(wf.includes('Run v4.8 regression suite'));assert(changelog.includes('## v4.8'));assert(readme.includes('proper GUI based toggles'));assert(readme.includes('fit well into the reporting that Obol performs'));assert(readme.includes('operating from Kali or from a Windows host'));assert(readme.includes('improving "Next Steps"'));assert(readme.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/domain persistence/i.test(notes));assert(/Orange domain persistence branch/.test(app));});
test('sanitized export retains v4.8 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.8 tests passed`);
