'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js'])run(path.join(root,'assets',f));
run(path.join(root,'assets','intake-v2.1.js'));run(path.join(root,'assets','intake-v5.3.js'));run(path.join(root,'assets','intake-v5.4.js'));run(path.join(root,'assets','intake-v5.5.js'));run(path.join(root,'assets','intake-v5.6.js'));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V56,I=global.OBOL_INTAKE_V56,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
test('v5.6 initializes current release state in its historical layer',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.6.0');assert.strictEqual(s.obolVersion,'5.6.0');assert.strictEqual(s.ui.dashboard56.showDeliveryClear,true);});
test('v5.6 advances five partial sections without denominator drift',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[67,34,26,0,53,80]);assert.strictEqual(M.advancedKeys.length,5);});
test('v5.6 clears mapped delivery debt with explicit Evidence contracts',()=>{const q=C.buildNext52(lanes),r=C.cardReadiness52(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.total],[0,0,26,26]);for(const id of M.repairedCardIds){const c=card(id),row=r.byCard[id];assert(c&&c.evidence45&&c.evidence45.source==='v5.6',id);assert(row&&row.ready,id);}});
test('all five v5.6 canonical owners are delivery-ready',()=>{const ready=C.deliveryReadiness52(lanes);for(const key of M.advancedKeys){const row=ready.rows.find(x=>x.key===key);assert(row&&row.status==='implemented'&&row.ready,key);}});
test('Shadow Credentials and NTLM relay require explicit proof',()=>{let p=I.proof56('shadow-credentials','pywhisker.py --action list','Key Credentials listed',lanes);assert(!p.success);p=I.proof56('shadow-credentials','pywhisker.py --action add','Successfully updated msDS-KeyCredentialLink\nSaved certificate to device.pfx',lanes);assert(p.success&&p.facts.includes('credential.certificate')&&!p.facts.includes('access.admin'));p=I.proof56('ntlm-relay','ntlmrelayx.py -tf targets.txt','SMBD-Thread listening\nGot connection',lanes);assert(!p.success);p=I.proof56('ntlm-relay','ntlmrelayx.py -tf targets.txt','Authenticating against smb://10.0.0.5 as CORP/USER SUCCEED',lanes);assert(p.success&&p.facts.includes('relay.success'));});
test('MAQ and S4U evidence never manufacture administrator access',()=>{let p=I.proof56('ad-machine-account-quota-v25','ldapsearch ms-DS-MachineAccountQuota','ms-DS-MachineAccountQuota: 0',lanes);assert(p.success&&p.facts.includes('ad.machine_account_quota')&&!p.facts.includes('ad.computer_added'));p=I.proof56('getst-impersonation','impacket-getST -spn cifs/server -impersonate administrator x','Saving ticket in administrator.ccache',lanes);assert(p.success&&p.facts.includes('kerberos.tickets')&&!p.facts.includes('access.admin'));});
test('web, ACL, and gMSA proof stay below privilege boundaries',()=>{let p=I.proof56('website-discovery','curl -sI http://10.0.0.5','HTTP/1.1 200 OK\nServer: nginx',lanes);assert(p.success&&p.facts.includes('web.reachable')&&!p.facts.includes('access.admin'));p=I.proof56('ad-acl-abuse','Get-ObjectAcl -Identity helpdesk','SecurityIdentifier S-1-5-21-1-2-3-1105\nActiveDirectoryRights GenericAll',lanes);assert(p.success&&p.facts.includes('ad.control_paths')&&!p.facts.includes('access.admin'));p=I.proof56('gmsa-read','bloodyAD get object svc$ --attr msDS-ManagedPassword','msDS-ManagedPassword: <blob>',lanes);assert(p.success&&p.facts.includes('credential.candidate')&&!p.facts.includes('credential.plaintext'));});
test('Zerologon negative checks and ticket import are conservative',()=>{let p=I.proof56('zerologon-check','zerologon-scan DC01 10.0.0.10','Target appears patched / not vulnerable',lanes);assert(p.success&&!p.facts.includes('vuln.candidates'));p=I.proof56('zerologon-check','zerologon-scan DC01 10.0.0.10','VULNERABLE',lanes);assert(p.success&&p.facts.includes('vuln.candidates'));p=I.proof56('ticket-reuse','Rubeus.exe ptt /ticket:x.kirbi','Ticket successfully imported',lanes);assert(p.success&&p.facts.includes('kerberos.tickets')&&!p.facts.includes('access.admin'));});
test('dashboard exposes historical v5.6 delta and clean delivery queue',()=>{const d=C.northStarDashboard56(C.newState(),lanes);assert.strictEqual(d.canonicalAdvance56.delta,5);assert.strictEqual(d.canonicalAdvance56.toImplemented,67);assert.strictEqual(d.deliveryRepair56.mappedDeliveryRemaining,0);assert(d.milestones.some(x=>x.release==='v5.6'&&x.implemented===67));assert(d.milestones.some(x=>x.release==='v5.5'&&x.implemented===62));});
test('historical README generator remains structurally derived after later releases',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('OBOL-BUILD-NEXT:START'));assert(/Canonical methodology:\*\* \d+\/127 fully implemented \(\d+%\)/.test(out));assert(out.includes('**Current live queue:**'));assert(out.includes('**Highest-priority live items:**'));});
test('v5.6 release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),north=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8');for(const x of ['methodology-v5.6.js','dashboard-v5.6.js','core-v5.6.js','intake-v5.6.js','app-v5.6.js','obol-v5.6.css'])assert(idx.includes(x),x);assert(wf.includes('Run release preflight'));assert(wf.includes('Run complete historical regression chain'));assert(/Current release: \*\*v\d+\.\d+(?:\.\d+)?\*\*/.test(readme));assert(readme.includes('<!-- OBOL-PRODUCT-BUILD-NEXT:START -->'));assert(readme.includes('Product Build Next'));assert(north.includes('Build Next ordering'));assert(changelog.includes('## v5.6'));});
test('sanitized export retains historical v5.6 behavior and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.6 tests passed`);
