'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','review-v2.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v3.0 initializes shell preferences and version',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.0.0');assert.strictEqual(s.obolVersion,'3.0.0');assert.strictEqual(s.ui.shell30.sidebarCollapsed,false);});
test('workflow navigation keeps five primary destinations and preserves advanced sections',()=>{assert.deepStrictEqual(C.NAVIGATION30.primary.map(x=>x.id),['home','boxes','intake','path','report']);for(const id of ['map','lanes','tools','queue','search','lineage','guide','settings'])assert(C.NAVIGATION30.secondary.some(x=>x.id===id));});
test('empty workspace points a new user to target setup',()=>{const s=C.newState(),o=C.workspaceOverview30(s,[],s.activeContext);assert.strictEqual(o.stage,'setup');assert.strictEqual(o.next.href,'#/boxes');assert.strictEqual(o.targets,0);});
test('target with no evidence points the operator to Intake',()=>{const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'box'});s.activeContext={type:'host',id:'h1'};const o=C.workspaceOverview30(s,[],s.activeContext);assert.strictEqual(o.stage,'evidence');assert.strictEqual(o.next.href,'#/intake');});
test('workspace overview counts scoped evidence and activity without leaking another host context',()=>{const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'one'},{id:'h2',ip:'10.10.10.20',name:'two'});s.activeContext={type:'host',id:'h1'};C.addFact(s,'scan.initial',{context:s.activeContext,source:'fixture',evidence:'nmap'});C.addTypedArtifact(s,'hosts','10.10.10.11',{context:s.activeContext,source:'fixture'});C.recordActivity(s,{cardId:'recon-card',context:s.activeContext,result:'tried',command:'nmap',evidence:'scan'});const o=C.workspaceOverview30(s,[],s.activeContext);assert.strictEqual(o.facts,1);assert.strictEqual(o.artifacts,1);assert.strictEqual(o.activities,1);assert.strictEqual(o.tried,1);});
test('v3 app source includes home, collapsible sidebar, mobile navigation, and command palette',()=>{const src=fs.readFileSync(path.join(root,'assets','app-v3.0.js'),'utf8');for(const token of ['viewHome30','sidebar-toggle30','mobile-nav30','openPalette30','Ctrl/Cmd+K'])assert(src.includes(token),token);});
test('v3.0 UX layer remains in the current ordered runtime manifest after v2.9',()=>{const m=require(path.join(root,'data','runtime-manifest.js'));assert(m.styles.includes('assets/obol-v3.0.css'));assert(m.scripts.includes('assets/core-v3.0.js'));assert(m.scripts.includes('assets/app-v3.0.js'));assert(m.scripts.indexOf('assets/core-v3.0.js')>m.scripts.indexOf('assets/core-v2.9.js'));assert(m.scripts.indexOf('assets/app-v3.0.js')>m.scripts.indexOf('assets/app-v2.9.js'));});
test('sanitized export retains v3.0 release state and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.0.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.0 tests passed`);