'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
run(path.join(root,'assets','core-v2-base.js'));run(path.join(root,'assets','core-v2.js'));run(path.join(root,'assets','core-v2.1.js'));run(path.join(root,'assets','core-v2.2.js'));run(path.join(root,'assets','core-v2.3.js'));run(path.join(root,'assets','core-v2.4.js'));run(path.join(root,'assets','core-v2.5.js'));
run(path.join(root,'data','lanes.js'));run(path.join(root,'data','methodology-v2.2.js'));run(path.join(root,'data','methodology-v2.3.js'));run(path.join(root,'data','methodology-v2.5.js'));run(path.join(root,'data','scripts.js'));run(path.join(root,'data','scripts-v2.5.js'));run(path.join(root,'data','signatures.js'));run(path.join(root,'assets','intake-v2.5.js'));
const C=global.OBOL_CORE_V2,LANES=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function findCommand(tool,contains){for(const l of LANES)for(const c of l.cards||[])for(const cmd of c.commands||[])if(String(cmd.tool).toLowerCase()===tool.toLowerCase()&&(!contains||String(cmd.run).includes(contains)))return cmd;throw new Error('missing '+tool+' '+(contains||''));}
test('v2.5 state stamps version and script builder store',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.5.0');assert.strictEqual(s.obolVersion,'2.5.0');assert.deepStrictEqual(s.ui.scriptBuilders,{});});
test('script builder state initializes defaults and persists changes',()=>{const s=C.newState(),p=global.OBOL_SCRIPT_BUILDERS_V25.profiles['cradles'],st=C.scriptBuilderState(s,'cradles',p);assert.strictEqual(st.radio.method,'iwr');assert.strictEqual(st.selected.server,true);C.updateScriptBuilder(s,'cradles',{radio:{method:'certutil'},args:{port:'8080'}});assert.strictEqual(s.ui.scriptBuilders.cradles.radio.method,'certutil');assert.strictEqual(s.ui.scriptBuilders.cradles.args.port,'8080');});
test('script builders consume engagement parameters',()=>{const s=C.newState();s.params.lhost='10.10.14.77';const p=global.OBOL_SCRIPT_BUILDERS_V25.profiles['ps-rev'],st=C.scriptBuilderState(s,'ps-rev',p),code=p.build('',s.params,st);assert(code.includes('10.10.14.77'));assert(code.includes('nc -lvnp'));});
test('v2.5 AD playbook exposes staged methodology and MAQ card',()=>{const p=global.OBOL_AD_PLAYBOOK_V25;assert(p&&p.stages.length>=6);assert(p.stages.some(x=>x.cards.includes('ad-machine-account-quota-v25')));assert(LANES.some(l=>(l.cards||[]).some(c=>c.id==='ad-machine-account-quota-v25')));});
test('remaining command families receive practical toggles',()=>{const dig=findCommand('dig'),bh=findCommand('bloodhound-python'),cert=findCommand('certipy',' find ');assert(dig.opts.some(x=>x.flag==='+tcp'));assert(bh.opts.some(x=>x.flag==='--dns-tcp'));assert(cert.opts.some(x=>x.flag==='-stdout'));});
test('intake normalizer strips ANSI and common shell prompts',()=>{const X=global.OBOL_INTAKE_V25,raw='\u001b[31mkali@kali:~$\u001b[0m sudo -l\r\nUser bob may run the following commands';const n=X.normalizeText(raw);assert(!n.includes('\u001b'));assert(n.includes('sudo -l'));});
test('v2.5 user extraction understands rpcclient style output',()=>{const u=global.OBOL_INTAKE_V25.extraUsers('user:[svc_backup] rid:[0x451]\nuser:[alice] rid:[0x452]');assert(u.includes('svc_backup'));assert(u.includes('alice'));});
test('v2.5 signatures recognize privilege, routing and ADCS evidence',()=>{const S=global.OBOL_SIGNATURES;assert(S.modes.some(x=>x.id==='sudo'));assert(S.rules.some(x=>x.facts&&x.facts['privesc.seimpersonate']));assert(S.rules.some(x=>x.facts&&x.facts['network.internal']));assert(S.rules.some(x=>x.facts&&x.facts['adcs.vulnerable']));});
console.log(`\n${passed} v2.5 tests passed`);
