'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V77,P=global.OBOL_PROJECT_V77;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.7 historical project metadata remains intact',()=>{assert.strictEqual(P.version,'7.7.0');assert.strictEqual(P.release,'v7.7');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[120,7,0,0,94,100]);assert.strictEqual(P.sourceWave.fidelityAfter,149);assert.strictEqual(P.sourceWave.filesAtomizedAfter,8);assert.strictEqual(P.sourceWave.baselinesAtomizedAfter,27);});

test('v7.7 no_creds.md ledger remains thirty-one terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,31);assert.deepStrictEqual(P.sourceWave.superseded,['no-creds.scan-nmap-legacy-ping','no-creds.poison-dhcpv6-bettercap']);assert.strictEqual(P.sourceWave.modeled.length,29);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'no_creds.md',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert.strictEqual(u.auditedIn,'7.7',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}});

test('v7.7 canonical advance is still limited to poisoning and coercion',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['no_creds.poisoning','no_creds.coerce']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.7',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}for(const key of P.sourceWave.historicalCanonicalDeepened){const h=section(key);assert(h,key);assert.strictEqual(h.status,'implemented',key);assert.notStrictEqual(h.advancedIn,'7.7',key);}});

test('v7.7 no-credential source units retain mature and focused owner mappings',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('no_creds.')),id);assert(c.evidence45&&c.evidence45.source==='v7.7',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext77,id);}assert(unit('no-creds.scan-nmap-canonical').ownerCardIds.includes('nmap-builder'));assert(unit('no-creds.find-dc-srv').ownerCardIds.includes('ad-dc-identify'));assert(unit('no-creds.zone-transfer').ownerCardIds.includes('dns-enum'));assert(unit('no-creds.poison-llmnr').ownerCardIds.includes('mitm-listen-73'));assert(unit('no-creds.poison-dhcpv6-mitm6').ownerCardIds.includes('dhcpv6-poison-77'));assert(unit('no-creds.poison-arp-pcredz').ownerCardIds.includes('arp-poison-77'));assert(unit('no-creds.coerce-petitpotam').ownerCardIds.includes('unauth-coercion-77'));});

test('v7.7 Evidence keeps poison, capture, coercion, relay, access, and privilege separate',()=>{global.OBOL_INTAKE_V76={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.7.js'));const I=global.OBOL_INTAKE_V77;let p=I.proof77('dhcpv6-poison-77','sudo mitm6 -i eth0 -d corp.local','Replying to DHCPv6 request from fe80::1');assert.deepStrictEqual(p.facts,['poison.dhcpv6']);p=I.proof77('arp-poison-77',"sudo bettercap -iface eth0 -eval 'arp.spoof on'",'arp.spoof started');assert.deepStrictEqual(p.facts,['poison.arp']);p=I.proof77('arp-poison-77','sudo Pcredz -i eth0 -v','Username: CORP\\alice Password: Secret!');assert.deepStrictEqual(p.facts,['credential.candidate']);p=I.proof77('unauth-coercion-77','python3 PetitPotam.py -d corp.local 10.0.0.5 10.0.0.10','Attack worked! EfsRpcOpenFileRaw success');assert.deepStrictEqual(p.facts,['coercion.triggered']);for(const x of ['relay.success','credential.available','access.admin','access.system','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('v7.7 source wave remains available from its versioned dashboard adapter',()=>{const d=C.northStarDashboard77(C.newState(),lanes);assert(d.sourceWave77);assert.strictEqual(d.sourceWave77.fidelityAfter,149);assert.strictEqual(d.sourceWave77.filesAtomizedAfter,8);assert.strictEqual(d.sourceWave77.baselinesAtomizedAfter,27);});

test('README generator remains structurally valid under the current runtime',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('v7.7 release wiring remains present without requiring it to be current',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v7.7.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.7.js','methodology-v7.7.js','project-model-v7.7.js','core-v7.7.js','intake-v7.7.js','app-v7.7.js','obol-v7.7.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.7.js'));assert(runtime.includes('methodology-v7.7.js'));assert(runtime.includes('project-model-v7.7.js'));assert(!idx.includes('dashboard-v7.7.js'));assert(releaseDoc.includes('# Obol v7.7'));});

test('current sanitized export still redacts secrets after v7.7',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.7 historical tests passed`);
