'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V69,P=global.OBOL_PROJECT_V69;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v6.9 initializes current state and stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'6.9.0');assert.strictEqual(s.obolVersion,'6.9.0');assert.strictEqual(s.ui.dashboard69.showSourceWave,true);assert.strictEqual(C.currentProjectModel,C.projectModel69);assert.strictEqual(p.release,'v6.9');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[99,28,0,0,78,100]);});

test('v6.9 completes exactly ESC5, ESC6, and ESC11',()=>{for(const id of ['adcs.esc5','adcs.esc6','adcs.esc11']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.9',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.deepStrictEqual(P.sourceWave.delivered,['adcs.esc5','adcs.esc6','adcs.esc11']);const f=C.sourceFidelity69(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[1,17,7,34,14,19,5]);assert.strictEqual(f.completePct,74);});

test('PKI-object ACL and CA-misconfiguration parents reconcile only after their atomic inventories complete',()=>{for(const key of ['adcs.pki-object-acl','adcs.ca-misconfig']){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'6.9',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.strictEqual(section('adcs.certificate-mapping').status,'partial');});

test('Build Next advances to the five certificate-mapping units with quality debt zero',()=>{const q=C.buildNext69(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,5,27,32]);assert.strictEqual(q.rows[0].key,'adcs.mapping-shadow');assert.strictEqual(q.rows[1].key,'adcs.esc9');assert.strictEqual(q.rows[2].key,'adcs.esc10-case1');});

test('ESC5 owner separates CA backup material from forged certificate material',()=>{const c=card('adcs-esc5-69');assert(c);assert(c.commands.some(x=>String(x.run).includes('certipy ca')&&String(x.run).includes('-backup')&&x.operatorSurface40==='kali'));assert(c.commands.some(x=>String(x.run).includes('-backup')&&String(x.run).includes('-sspi')&&x.operatorSurface40==='windows'));assert(c.commands.some(x=>String(x.run).includes('certipy forge')&&String(x.run).includes('-ca-pfx')));assert(c.produces.includes('adcs.ca_private_key_material'));assert(c.produces.includes('adcs.golden_certificate'));assert(c.evidence45&&c.evidence45.source==='v6.9');assert(c.report47&&c.report47.evidenceProfile);});

test('ESC6 and ESC11 owners preserve execution-context and relay boundaries',()=>{const esc6=card('adcs-esc6-69'),esc11=card('adcs-esc11-69');assert(esc6&&esc11);assert(esc6.commands.some(x=>x.operatorSurface40==='kali'&&String(x.run).includes('-upn')));assert(esc6.commands.some(x=>x.operatorSurface40==='windows'&&String(x.run).includes('-sspi')));assert(esc11.commands.some(x=>String(x.run).includes("rpc://{{ca_target}}")&&x.tool==='certipy'));assert(esc11.commands.some(x=>x.tool==='ntlmrelayx'&&String(x.run).includes('ICPR')));assert(esc11.commands.some(x=>x.tool==='certipy'&&String(x.run).includes('auth -pfx')));assert(esc6.report47&&esc11.report47);});

test('v6.9 Evidence keeps CA keys, certificates, relay, access, and privilege separated',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v6.9.js'));const I=global.OBOL_INTAKE_V69;let p=I.proof69('adcs-esc5-69',"certipy ca -ca CORP-CA -backup",'Saved certificate and private key to CORP-CA.pfx');assert.deepStrictEqual(p.facts,['adcs.ca_private_key_material']);p=I.proof69('adcs-esc5-69',"certipy forge -ca-pfx CORP-CA.pfx -upn administrator@corp.local",'Saved forged certificate to administrator_forged.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.golden_certificate']);p=I.proof69('adcs-esc6-69',"certipy req -ca CORP-CA -template User -upn administrator@corp.local",'Got certificate\nSaved certificate and private key to administrator.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc6_certificate']);p=I.proof69('adcs-esc11-69',"certipy relay -target rpc://ca.corp.local -ca CORP-CA",'Listening on 0.0.0.0:445');assert.strictEqual(p.success,false);p=I.proof69('adcs-esc11-69',"certipy relay -target rpc://ca.corp.local -ca CORP-CA",'Got certificate\nSaved certificate and private key to dc01.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc11_relay_certificate']);for(const x of p.facts)assert(!['access.admin','access.system','foothold.windows','access.cross_domain','objective.domain_admin','capability.dcsync'].includes(x));});

test('project model and generated Build Next snapshot reflect the v6.9 wave',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.buildNext.total],[14,19,5,32]);assert.strictEqual(p.next.key,'adcs.mapping-shadow');assert.strictEqual(p.recent[0].release,'v6.9');const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('32 items'));assert(out.includes('99/127 fully implemented (78%)'));assert(out.includes('14/19 inventoried atomic units fidelity-complete'));assert(out.includes('Certificate-mapping shadow-credential bridge'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v6.9',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v6.9 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.9.js','methodology-v6.9.js','project-model-v6.9.js','core-v6.9.js','intake-v6.9.js','app-v6.9.js','obol-v6.9.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v6.9.js'));assert(readme.includes('Current release: **v6.9**'));assert(changelog.includes('## v6.9'));assert(fs.existsSync(path.join(root,'docs','v6.9.md')));});

test('sanitized export advances to v6.9 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.9.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v6.9 tests passed`);
