'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V86,P=global.OBOL_PROJECT_V86,F86=global.OBOL_ORANGE_FIDELITY_V86;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.6 initializes the stable current project model without canonical drift',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.6.0');assert.strictEqual(s.obolVersion,'8.6.0');assert.strictEqual(C.currentProjectModel,C.projectModel86);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard86);assert.strictEqual(p.release,'v8.6');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.6 completes know_vuln_auth.md with sixteen terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,16);assert.strictEqual(F86.newAuditedIds.length,16);assert.strictEqual(F86.fileAuditedIds.length,16);assert.strictEqual(F86.newModeled.length,14);assert.strictEqual(F86.newSuperseded.length,2);for(const id of F86.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'know_vuln_auth.md',id);assert.strictEqual(u.sourceSha,'fb25cc7766f1d1f169b258c0800063946071b364',id);assert.strictEqual(u.auditedIn,'8.6',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity86(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[15,17,34,34,282,282,0]);});

test('authenticated known-vulnerability canonical parents remain implemented and mapped to mature owners',()=>{for(const key of ['know_vuln_auth.ms14-068','know_vuln_auth.gpp','know_vuln_auth.privexchange','know_vuln_auth.nopac','know_vuln_auth.printnightmare','know_vuln_auth.certifried','know_vuln_auth.proxynotshell']){let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key===key)s=x;assert(s,key);assert.strictEqual(s.status,'implemented',key);}for(const id of F86.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic86||[]).includes(id),owner+' lineage for '+id);}}});

test('v8.6 completes current GPP and MS14-068 operator routes',()=>{assert(hasRun('gpp-passwords',/findstr \/S \/I cpassword/));assert(hasRun('gpp-passwords',/impacket-Get-GPPPassword/));assert(hasRun('ms14-06857',/impacket-goldenPac/));assert(card('gpp-passwords').evidence45);assert.strictEqual(card('gpp-passwords').evidence45.source,'v8.6');assert(card('gpp-passwords').sourceCorrection86);assert(card('ms14-06857').sourceCorrection86);});

test('detection-first and bounded validation remain intact for high-impact legacy branches',()=>{assert(hasRun('nopac57',/nxc smb .* -M nopac/));assert(hasRun('printnightmare58',/nxc smb .* -M printnightmare/));assert(hasRun('certifried57',/certipy account create/));assert(hasRun('certifried57',/certipy req/));assert(hasRun('certifried57',/certipy auth/));const pn=card('printnightmare58');assert(pn.sourceCorrection86);assert(/benign|operator-reviewed/i.test(pn.sourceCorrection86.corrections.join(' ')));const pns=card('proxynotshell58');assert(pns.sourceCorrection86);assert((pns.commands||[]).some(x=>/poc_aug3\.py .* whoami/.test(String(x.run||''))));});

test('redundant Metasploit routes remain explicit superseded source lineage',()=>{const ids=['know-vuln-auth.ms14-068-msf','know-vuln-auth.gpp-msf'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'superseded',id);assert(/Metasploit|direct|preferred|session/i.test(u.reason),id);}assert.deepStrictEqual(P.sourceWave.superseded,ids);});

test('authenticated known-vulnerability source accounting preserves proof boundaries',()=>{for(const id of F86.newAuditedIds){const u=unit(id);assert(/proves only its own stage|separate stage-appropriate Evidence/i.test(u.evidenceBoundary),id);}assert(/later authentication and privilege remain separate/i.test(card('gpp-passwords').commands.find(x=>/impacket-Get-GPPPassword/.test(String(x.run))).note));assert(/detection-first/i.test(card('printnightmare58').sourceCorrection86.corrections.join(' ')));});

test('Build Next advances to the two remaining whole-file inventories',()=>{const q=C.buildNext86(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,2,2]);assert(q.rows.every(x=>x.kind==='source-file-inventory'));assert.deepStrictEqual(q.rows.map(x=>x.file),P.sourceWave.fileInventoryQueue);assert.strictEqual(q.rows[0].file,'trusts.md');assert(!q.rows.some(x=>x.file==='know_vuln_auth.md'));});

test('project model exposes v8.6 source accounting and next file',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[282,282,0,15,34,2]);assert.strictEqual(p.phase.id,'whole-file-source-inventory');assert.strictEqual(p.next.file,'trusts.md');assert.strictEqual(p.recent[0].release,'v8.6');assert(p.details.sourceWave86);});

test('README generator reflects the v8.6 current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 2 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 15/17 source files atomized, 34/34 partial baselines decomposed, 282/282'));assert(out.includes('**Current phase:** Orange whole-file source inventory.'));assert(out.includes('trusts.md'));assert(out.includes('valid_user.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.6',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.6 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.6.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.6.js','methodology-v8.6.js','project-model-v8.6.js','core-v8.6.js','app-v8.6.js','obol-v8.6.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.6.js','methodology-v8.6.js','project-model-v8.6.js','core-v8.6.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.6.js'));assert(!idx.includes('intake-v8.6.js'));assert(readme.includes('Current release: **v8.6**'));assert(releaseDoc.includes('# Obol v8.6'));});

test('sanitized export advances to v8.6 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.6 tests passed`);
