'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js'])run(path.join(root,'assets',f));
for(const f of ['report-v2.js','report-v2.1.js','report-v2.2.js','report-v2.3.js','report-v2.4.js','report-v2.5.js','report-v2.6.js','report-v2.7.js','report-v2.8.js','report-v2.9.js','report-v3.5.js','report-v4.0.js','report-v4.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,R=global.OBOL_REPORT_V2,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
test('v4.7 initializes current release and report trace preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.7.0');assert.strictEqual(s.obolVersion,'4.7.0');assert.strictEqual(s.ui.report47.showTrace,true);assert.strictEqual(s.ui.report47.showGaps,true);});
test('v4.7 preserves pinned Orange source and v4.6 live coverage baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[48,45,34,0,38,73]);});
test('every live Orange-mapped card receives a report traceability contract',()=>{const cov=C.orangeReportCoverage47(lanes);assert(cov.mapped>20);assert.strictEqual(cov.traceable,cov.mapped);for(const r of cov.rows){const c=card(r.cardId);assert(c&&c.report47,r.cardId);assert(r.stage,r.cardId);assert(Array.isArray(r.canonicalKeys),r.cardId);}});
test('finding-bearing and path-only methodology stay distinct',()=>{assert(card('sccm-admin-exec').report47.reportBearing);assert.strictEqual(card('sccm-admin-exec').report47.role,'finding');assert(!card('kerberos-tickets').report47.reportBearing);assert(['path','finding-or-path','context'].includes(card('kerberos-tickets').report47.role));});
test('successful mapped activity becomes report traceability without inventing a finding',()=>{const s=hostState();C.recordActivity(s,{cardId:'kerberos-tickets',context:s.activeContext,result:'success',command:'klist',evidence:'Ticket cache: FILE:test.ccache'});const rows=C.orangeReportTrace47(s,lanes);assert.strictEqual(rows.length,1);assert.strictEqual(rows[0].card.id,'kerberos-tickets');assert.strictEqual(rows[0].contract.reportBearing,false);const md=R.generate(s,lanes,'standard',{});assert(md.includes('Orange Decision Path & Reporting Traceability'));assert(md.includes('Kerberos Ticket Hygiene'));const findings=R._findingRows?R._findingRows(s,lanes):[];assert(!findings.some(x=>x.c&&x.c.id==='kerberos-tickets'));});
test('SCCM finding activity carries canonical reporting provenance',()=>{const s=hostState();C.recordActivity(s,{cardId:'sccm-admin-exec',context:s.activeContext,result:'success',command:'SharpSCCM.exe exec -p audit.ps1 -d WS01 -sms SCCM01 -sc LAB --no-banner',evidence:'Execution request succeeded',outcomeFacts:['sccm.execution_confirmed']});const row=C.orangeReportTrace47(s,lanes)[0];assert(row.contract.canonicalKeys.some(x=>x==='sccm.exec'));assert(row.contract.reportBearing);assert.strictEqual(row.contract.evidenceFamily,'sccm-exec');const md=R.generate(s,lanes,'standard',{});assert(md.includes('SCCM Administrative Execution Path'));assert(md.includes('sccm.exec'));});
test('report readiness exposes unresolved ledger proof without changing success state',()=>{const s=hostState();C.recordActivity(s,{cardId:'sccm-admin-exec',context:s.activeContext,result:'success',command:'',evidence:''});const m=C.orangeReportReadiness47(s,lanes);assert.strictEqual(m.total,1);assert.strictEqual(m.needs,1);assert.strictEqual(m.missingEvidence,1);assert.strictEqual(m.missingCommand,1);const md=R.generate(s,lanes,'standard',{});assert(md.includes('Draft Reporting Gaps'));assert(md.includes('SCCM Administrative Execution'));});
test('OSCP report also retains Orange traceability while remaining a draft',()=>{const s=hostState();C.recordActivity(s,{cardId:'sccm-cleanup-post',context:s.activeContext,result:'success',command:'SCCMHound.exe --server SCCM01 --sitecode LAB',evidence:'SCCMHound completed'});const md=R.generate(s,lanes,'oscp',{});assert(md.includes('Orange Decision Path & Reporting Traceability'));assert(md.includes('SCCM Cleanup and Post-Exploitation Mapping'));});
test('v4.7 UI release wiring and durable reporting/product contracts preserve the North Star',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),north=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8'),proof=fs.readFileSync(path.join(root,'docs','PROOF-CONTRACT.md'),'utf8'),hardening=fs.readFileSync(path.join(root,'docs','PRODUCT-HARDENING.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.7.md'),'utf8'),app=fs.readFileSync(path.join(root,'assets','app-v4.7.js'),'utf8');for(const x of ['Obol v4.7','methodology-v4.7.js','core-v4.7.js','report-v4.7.js','app-v4.7.js','obol-v4.7.css'])assert(idx.includes(x),x);assert(wf.includes('Run v4.7 regression suite'));assert(changelog.includes('## v4.7'));assert(/report|proof/i.test(proof));assert(/GUI command-builder|GUI tool builder/i.test(hardening));assert(north.includes('Kali/Windows execution context'));assert(north.includes('Next Steps'));assert(north.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/reporting traceability/i.test(notes));assert(/Path → evidence → report/.test(app));});
test('sanitized export retains v4.7 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.7.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.7 tests passed`);
