'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V83,P=global.OBOL_PROJECT_V83,F83=global.OBOL_ORANGE_FIDELITY_V83;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.3 initializes the stable current project model without canonical denominator drift',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.3.0');assert.strictEqual(s.obolVersion,'8.3.0');assert.strictEqual(C.currentProjectModel,C.projectModel83);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard83);assert.strictEqual(p.release,'v8.3');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.3 completes low_hanging.md with seventeen new units plus inherited Zerologon accounting',()=>{assert.strictEqual(P.sourceWave.delivered.length,17);assert.strictEqual(F83.newAuditedIds.length,17);assert.strictEqual(F83.fileAuditedIds.length,19);assert.strictEqual(F83.newModeled.length,16);assert.strictEqual(F83.newSuperseded.length,1);for(const id of F83.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'low_hanging.md',id);assert.strictEqual(u.sourceSha,'e64f008bcc5a053843e17090ab2ef68586dedff2',id);assert.strictEqual(u.auditedIn,'8.3',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}for(const id of ['low-hanging.zerologon-check','low-hanging.zerologon-reset']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditedIn,'8.0',id);assert(F83.fileAuditedIds.includes(id));}const f=C.sourceFidelity83(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[12,17,34,34,243,243,0]);assert.strictEqual((F.atomizedCanonicalKeys||[]).length,34);});

test('low-hanging source families are fully represented by mature or focused owners',()=>{for(const key of ['low_hanging.zerologon','low_hanging.eternalblue','low_hanging.tomcat-jboss','low_hanging.java-rmi','low_hanging.java-deser','low_hanging.log4shell','low_hanging.database','low_hanging.exchange','low_hanging.veeam','low_hanging.glpi','low_hanging.weak-services']){let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key===key)s=x;assert(s,key);assert.strictEqual(s.status,'implemented',key);}for(const id of F83.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic83||[]).includes(id),owner+' lineage for '+id);}}});

test('quick-compromise commands preserve explicit validation before stronger claims',()=>{assert(hasRun('eternalblue-83',/smb-vuln-ms17-010/));assert(hasRun('eternalblue-83',/ms17_010_eternalblue/));assert(hasRun('tomcat-deploy',/tomcat_enum/));assert(hasRun('tomcat-deploy',/tomcat_mgr_deploy/));assert(hasRun('java-rmi-83',/java_rmi_server/));assert(hasRun('java-deser-83',/ysoserial-all\.jar/));assert(hasRun('log4shell-83',/jndi:ldap/));assert(hasRun('mssql-access',/mssql_enum_sql_logins/));assert(hasRun('exchange-proxyshell-83',/proxyshell_rce\.py/));assert(hasRun('veeam-quickwin-83',/CVE-2024-40711/));assert(hasRun('glpi-quickwin-83',/cve_2023_41320\.py/));assert(hasRun('website-discovery',/nuclei -target/));});

test('Nessus remains explicit superseded lineage rather than a default operator route',()=>{const u=unit('low-hanging.weak-services-nessus');assert(u);assert.strictEqual(u.auditStatus,'superseded');assert(/licensed scanner|Nuclei|static\/offline-capable/i.test(u.reason));assert.strictEqual(P.sourceWave.superseded.length,1);assert.strictEqual(P.sourceWave.superseded[0],u.id);});

test('v8.3 Evidence profiles keep exposure, vulnerability, callback, execution, access, and privilege separate',()=>{for(const id of M.newCardIds){const c=card(id);assert(c,id);assert(c.evidence45,id);assert(/explicit|callback|command|session|proof/i.test(c.evidence45.proof),id);}assert(/SMBv1 exposure is only context/i.test(card('eternalblue-83').hypothesis));assert(/callback proves JNDI lookup behavior; resulting command execution is a separate boundary/i.test(card('log4shell-83').hypothesis));assert(/credential recovery, auth bypass, deserialization\/callback, and resulting access as separate Evidence states/i.test(card('veeam-quickwin-83').hypothesis));});

test('Tomcat mature owner closes Evidence and execution-metadata delivery debt',()=>{const c=card('tomcat-deploy');assert(c&&c.evidence45);assert(/manager discovery and authentication remain separate/i.test(c.evidence45.proof));assert((c.commands||[]).length>0);assert((c.commands||[]).every(x=>!!x.operatorSurface40));const row=C.cardReadiness52(lanes).byCard['tomcat-deploy'];assert(row);assert.strictEqual(row.ready,true);assert.deepStrictEqual(row.missing,[]);});

test('Build Next advances to five remaining whole-file inventories',()=>{const q=C.buildNext83(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,5,5]);assert(q.rows.every(x=>x.kind==='source-file-inventory'));assert.deepStrictEqual(q.rows.map(x=>x.file),P.sourceWave.fileInventoryQueue);assert.strictEqual(q.rows[0].file,'persistence.md');assert(!q.rows.some(x=>x.file==='low_hanging.md'));});

test('project model exposes v8.3 source accounting and next file',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[243,243,0,12,34,5]);assert.strictEqual(p.phase.id,'whole-file-source-inventory');assert.strictEqual(p.next.file,'persistence.md');assert.strictEqual(p.recent[0].release,'v8.3');assert(p.details.sourceWave83);});

test('README generator reflects the v8.3 current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 5 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 12/17 source files atomized, 34/34 partial baselines decomposed, 243/243'));assert(out.includes('**Current phase:** Orange whole-file source inventory.'));assert(out.includes('persistence.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.3',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.3 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.3.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.3.js','methodology-v8.3.js','project-model-v8.3.js','core-v8.3.js','app-v8.3.js','obol-v8.3.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.3.js','methodology-v8.3.js','project-model-v8.3.js','core-v8.3.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.3.js'));assert(!idx.includes('intake-v8.3.js'));assert(readme.includes('Current release: **v8.3**'));assert(releaseDoc.includes('# Obol v8.3'));});

test('sanitized export advances to v8.3 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.3.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.3 tests passed`);
