'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js','intake-v3.9.js','intake-v4.5.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V45,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
function analyze(text){const s=hostState();return T.analyzeTerminal(text,lanes,s,s.activeContext);}
test('v4.5 initializes current release and operator-loop preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.5.0');assert.strictEqual(s.obolVersion,'4.5.0');assert.strictEqual(s.ui.contract45.showPathReadiness,true);assert.strictEqual(s.ui.contract45.showEvidenceCoverage,true);});
test('v4.5 preserves the pinned Orange source and strict v4.4 coverage baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[42,39,46,0,33,64]);});
test('Orange run/evidence contract audit catalogs mapped cards and explicit parser coverage',()=>{const c=C.orangeContractCoverage45(lanes);assert(c.mappedCards>20);assert(c.commands>0);assert(c.adjustableCommands>0);assert(c.evidenceReady>=Object.keys(M.profiles).length);assert(c.loopReady>0);assert(c.evidencePct>0);});
test('v4.5 closes GUI-control gaps for SCCMHunter and the MSSQL connection command',()=>{const s=card('sccm-enum'),m=card('mssql-access');assert(s&&m);const sh=(s.commands||[]).find(x=>/^sccmhunter\.py\s+find/i.test(x.run));assert(sh&&(sh.opts||[]).some(x=>x.flag==='-debug'));const mc=(m.commands||[]).find(x=>/^impacket-mssqlclient\s/i.test(x.run));assert(mc);for(const k of ['-k','-no-pass','-debug'])assert((mc.opts||[]).some(x=>x.flag===k),k);assert((mc.opts||[]).some(x=>x.arg==='-hashes'));});
test('Hashcat cracked output maps to the audited AD cracking card and only proves recovered plaintext',()=>{const r=analyze("kali$ hashcat -m 13100 roast.txt rockyou.txt\nStatus...........: Cracked\nRecovered........: 1/1");const a=r.activities.find(x=>x.cardId==='hashcat-modes');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('credential.plaintext'));assert(!a.outcomeFacts.includes('access.admin'));});
test('BloodHound collection proof establishes collection without inventing attack paths',()=>{const r=analyze("kali$ bloodhound-python -d corp.local -u user -p pass -ns 10.10.10.10 -c All --zip\nINFO: Compressing output into 20260828_bloodhound.zip");const a=r.activities.find(x=>x.cardId==='bloodhound-collect');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('ad.graph.collected'));assert(!a.outcomeFacts.includes('ad.attack_paths'));});
test('SCCM discovery is recognized without inventing credentials or admin access',()=>{const r=analyze("kali$ sccmhunter.py find -u user -p pass -d corp.local -dc-ip 10.10.10.10\n[+] SiteCode: LAB\n[+] Management Point: SCCM01.corp.local");const a=r.activities.find(x=>x.cardId==='sccm-enum');assert(a);assert.strictEqual(a.result,'success');assert(!a.outcomeFacts.includes('credential.available'));assert(!a.outcomeFacts.includes('access.admin'));});
test('trust enumeration explicit output establishes only the trust fact',()=>{const r=analyze("PS C:\\Temp> nltest /domain_trusts\nList of domain trusts:\n0: CORP corp.local (NT 5) (Forest Tree Root) (Primary Domain) (Native)\nTrusted Domains: partner.local");const a=r.activities.find(x=>x.cardId==='trust-enum');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('ad.trusts'));assert(!a.outcomeFacts.includes('access.admin'));});
test('AD CS explicit ESC output and MSSQL session output remain narrowly scoped',()=>{let r=analyze("kali$ certipy find -u user@corp.local -p pass -dc-ip 10.10.10.10 -vulnerable\n[*] Vulnerabilities : ESC1");let a=r.activities.find(x=>x.cardId==='adcs-esc');assert(a&&a.outcomeFacts.includes('adcs.vulnerable'));r=analyze("kali$ impacket-mssqlclient 'corp.local/user:pass'@10.10.10.20 -windows-auth\n[*] Microsoft SQL Server 2019\nSQL> select @@version");a=r.activities.find(x=>x.cardId==='mssql-access');assert(a&&a.outcomeFacts.includes('db.mssql_access'));assert(!a.outcomeFacts.includes('foothold.windows'));});
test('Golden Ticket parser requires explicit saved ccache output',()=>{let r=analyze("kali$ impacket-ticketer -nthash deadbeef -domain-sid S-1-5-21-1 -domain corp.local administrator\n[*] Creating basic skeleton ticket");let a=r.activities.find(x=>x.cardId==='golden-ticket');assert(a);assert.notStrictEqual(a.result,'success');r=analyze("kali$ impacket-ticketer -nthash deadbeef -domain-sid S-1-5-21-1 -domain corp.local administrator\n[*] Saving ticket in administrator.ccache");a=r.activities.find(x=>x.cardId==='golden-ticket');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('persistence.domain'));});
test('Next Steps overview includes run/evidence readiness beside the v4.4 decision path',()=>{const s=hostState();C.addFact(s,'ad.user_list',{context:s.activeContext,source:'fixture',evidence:'users'});C.addFact(s,'kerberos.reachable',{context:s.activeContext,source:'fixture',evidence:'88'});const o=C.nextStepsOverview34(s,lanes,s.activeContext,{showAll:true});assert(o.orangeDecision44);assert(o.orangeContracts45);assert(o.orangeContracts45.coverage.mappedCards>0);assert(o.orangeContracts45.queue.length>0);assert(o.orangeContracts45.queue.every(x=>x.contract45&&typeof x.contract45.evidenceReady==='boolean'));});
test('v4.5 UI release wiring and README preserve the North Star contracts',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.5.md'),'utf8'),app=fs.readFileSync(path.join(root,'assets','app-v4.5.js'),'utf8');assert(idx.includes('Obol v4.5'));assert(idx.includes('methodology-v4.5.js'));assert(idx.includes('core-v4.5.js'));assert(idx.includes('intake-v4.5.js'));assert(idx.includes('app-v4.5.js'));assert(idx.includes('obol-v4.5.css'));assert(wf.includes('Run v4.5 regression suite'));assert(changelog.includes('## v4.5'));assert(readme.includes('proper GUI based toggles'));assert(readme.includes('operating from Kali or from a Windows host'));assert(readme.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/Run \/ evidence contract/.test(notes));assert(/Run → paste → interpret → decide/.test(app));});
test('sanitized export retains v4.5 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.5.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.5 tests passed`);
