'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','review-v2.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v2.9 state initializes pivot lifecycle and proof-obligation state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.9.0');assert.strictEqual(s.obolVersion,'2.9.0');assert.deepStrictEqual(s.reportEvidence29,{});});
test('pivot lifecycle preserves source, note, broken state, and explicit verification',()=>{const s=C.newState(),p=C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'172.16.50.0/24',sourceHost:'10.10.10.20',note:'agent through foothold'},{source:'operator'});assert.strictEqual(p.sourceHost,'10.10.10.20');assert.strictEqual(p.note,'agent through foothold');C.updateNetworkPath(s,p.id,{status:'broken'});let l=C.pathLifecycleSummary(s,s.activeContext);assert.strictEqual(l.broken.length,1);assert.strictEqual(C.reachabilityFor(s,'172.16.50.10',s.activeContext).state,'unknown');C.verifyNetworkPath(s,p.id,{});l=C.pathLifecycleSummary(s,s.activeContext);assert.strictEqual(l.active.length,1);assert(p.lastVerifiedAt);});
test('reachability-aware card signal never promotes observed-only services',()=>{const s=C.newState(),card={id:'smb-pivot-enum',lane:'recon',title:'SMB Enumeration',commands:[{tool:'nxc',run:'nxc smb {{target}}'}]};C.recordNetworkObservations(s,[{type:'service',address:'172.16.60.20',destination:'smb:445'}],{source:'fixture'});let sig=C.cardReachabilitySignal(s,card,s.activeContext);assert.strictEqual(sig.pivotMatches,0);assert(sig.delta<=0);C.recordNetworkPath(s,{mode:'pivot',kind:'chisel',network:'172.16.60.0/24'},{source:'operator'});sig=C.cardReachabilitySignal(s,card,s.activeContext);assert.strictEqual(sig.pivotMatches,1);assert(sig.delta>0);});
test('broken pivot state raises repair relevance for pivot methodology',()=>{const s=C.newState(),card={id:'pivot-repair',lane:'pivot',title:'Pivot Tunnel',commands:[{tool:'ligolo',run:'ligolo'}]},p=C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'10.50.0.0/16'},{source:'operator'});C.updateNetworkPath(s,p.id,{status:'broken'});const sig=C.cardReachabilitySignal(s,card,s.activeContext);assert.strictEqual(sig.brokenPivotCount,1);assert(sig.delta>0);assert(/broken/.test(sig.reason));});
test('cross-artifact dependency graph links consumed evidence to artifacts produced by the same card',()=>{const s=C.newState(),a=C.addTypedArtifact(s,'hosts','10.20.30.40',{producer:{cardId:'discover-host',source:'fixture',at:'2026-08-27T10:00:00Z'}});C.recordArtifactConsumption(s,a,{cardId:'enum-smb',field:'target',source:'command-binding',at:'2026-08-27T10:05:00Z'});const b=C.addTypedArtifact(s,'shares','\\\\10.20.30.40\\public',{producer:{cardId:'enum-smb',source:'card-evidence',at:'2026-08-27T10:06:00Z'}}),g=C.lineageDependencyGraph(s,s.activeContext);assert(g.edges.some(e=>e.from===a.id&&e.to===b.id&&e.cardId==='enum-smb'));});
test('finding proof readiness requires target and identity visibility for foothold transitions',()=>{const s=C.newState(),lanes=[{lane:'web',title:'Web',cards:[{id:'foothold-card',lane:'web',title:'Foothold',report:{finding:'Remote Code Execution',severity:'high'},commands:[]}]}];C.recordActivity(s,{cardId:'foothold-card',context:s.activeContext,result:'success',outcomeFacts:['foothold.linux'],evidence:'uid=1000',command:'exploit command'});let r=C.reportReadiness(s,lanes,s.activeContext),row=r.rows[0];C.setReportProof(s,row.key,{screenshot:true});r=C.reportReadiness(s,lanes,s.activeContext);row=r.rows[0];assert.strictEqual(row.ready,false);assert(row.missing.some(q=>q.id==='target-visible'));assert(row.missing.some(q=>q.id==='identity-visible'));C.setReportProof29(s,row.key,'targetVisible',true);C.setReportProof29(s,row.key,'identityVisible',true);r=C.reportReadiness(s,lanes,s.activeContext);assert.strictEqual(r.rows[0].ready,true);});
test('credential transitions require preserved artifact provenance',()=>{const s=C.newState(),lanes=[{lane:'ad',title:'AD',cards:[{id:'credential-card',lane:'ad',title:'Credential Discovery',report:{finding:'Credential Exposure',severity:'high'},commands:[]}]}],a=C.recordActivity(s,{cardId:'credential-card',context:s.activeContext,result:'success',outcomeFacts:['credential.available'],evidence:'credential found',command:'cat config'});let r=C.reportReadiness(s,lanes,s.activeContext),row=r.rows[0];C.setReportProof(s,row.key,{screenshot:true});r=C.reportReadiness(s,lanes,s.activeContext);assert.strictEqual(r.missingProvenance,1);C.addTypedArtifact(s,'secrets','Summer2026!',{producer:{activityId:a.id,cardId:a.cardId,contextKey:a.contextKey,source:'card-evidence'}});r=C.reportReadiness(s,lanes,s.activeContext);assert.strictEqual(r.missingProvenance,0);assert.strictEqual(r.rows[0].ready,true);});
test('sanitized export retains v2.9 release state and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'2.9.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v2.9 tests passed`);
