'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V73,P=global.OBOL_PROJECT_V73,S=global.OBOL_SOURCE_DELIVERY_V73;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.3 historical project metadata remains intact under the current runtime',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(P.version,'7.3.0');assert.strictEqual(P.release,'v7.3');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[108,19,0,0,85,100]);assert(C.currentProjectModel);assert(C.currentNorthStarDashboard);assert.strictEqual(s.obolVersion,C.VERSION);assert(p.canonical.implemented>=108);assert(p.canonical.partial<=19);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('mitm.md v7.3 source wave remains terminal while current source inventory may grow',()=>{const ids=['mitm.listen','mitm.ntlm-self-relay','mitm.ntlm-ldaps','mitm.ntlm-smb','mitm.ntlm-http','mitm.ntlm-mssql','mitm.ntlm-netlogon','mitm.kerberos-http','mitm.kerberos-smb','mitm.kerberos-ldaps'];for(const id of ids){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'mitm.md',id);assert.strictEqual(u.auditedIn,'7.3',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.strictEqual(unit('mitm.ntlm-self-relay').auditStatus,'superseded');assert.deepStrictEqual([P.sourceWave.fidelityBefore,P.sourceWave.fidelityAfter,P.sourceWave.fidelityTotal,P.sourceWave.filesAtomizedBefore,P.sourceWave.filesAtomizedAfter,P.sourceWave.baselinesAtomizedBefore,P.sourceWave.baselinesAtomizedAfter],[41,51,51,3,4,14,15]);const f=C.sourceFidelity73(lanes);assert(f.files.atomized>=4);assert.strictEqual(f.files.total,17);assert(f.partialBaseline.atomized>=15);assert.strictEqual(f.partialBaseline.total,34);assert(f.complete>=51);assert(f.total>=51);assert(f.pending>=0);});

test('the v7.3 MITM canonical reconciliation remains intact',()=>{const listen=section('mitm.listen'),ntlm=section('mitm.ntlm-relay'),krb=section('mitm.kerberos-relay');assert(listen&&ntlm&&krb);assert.strictEqual(listen.status,'implemented');assert.strictEqual(listen.advancedIn,'7.3');assert.strictEqual(listen.sourceDepthAudit62.status,'modeled');assert.strictEqual(ntlm.status,'implemented');assert.strictEqual(ntlm.advancedIn,'5.6');assert.notStrictEqual(krb.advancedIn,'7.3');assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['mitm.listen']);assert.deepStrictEqual(P.sourceWave.historicalCanonicalDeepened,['mitm.ntlm-relay','mitm.kerberos-relay']);});

test('current Build Next never reopens completed v7.3 MITM source rows',()=>{const q=C.buildNext73(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);assert(q.sourceFidelity>=0);assert(q.sourceInventory>=0);assert(q.total>=0);for(const key of P.sourceWave.canonicalAdvanced)assert(!q.rows.some(x=>x.key===key),key);for(const id of P.sourceWave.delivered)assert(!q.rows.some(x=>x.key===id),id);assert(!q.rows.some(x=>x.file==='mitm.md'));});

test('MITM source units retain mature and dedicated v7.3 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('mitm.')),id);assert(c.evidence45&&c.evidence45.source==='v7.3',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext73,id);}assert(unit('mitm.ntlm-smb').ownerCardIds.includes('ntlm-relay'));assert(unit('mitm.kerberos-http').ownerCardIds.includes('kerberos-relay60'));assert(unit('mitm.ntlm-http').ownerCardIds.includes('adcs-esc8-65'));});

test('source-delivery normalization preserves historical NTLM relay and legacy-listener boundaries',()=>{assert(S);assert.deepStrictEqual(S.reconciled,[]);assert.deepStrictEqual(S.historicalCanonical,['mitm.ntlm-relay','mitm.kerberos-relay']);assert.deepStrictEqual(S.completedBaselineKeys,['mitm.listen']);assert.strictEqual(section('mitm.ntlm-relay').advancedIn,'5.6');const legacy=card('llmnr-responder');assert(legacy);assert(!(legacy.orange44&&legacy.orange44.label==='Validate MITM / relay paths'));for(const id of M.cardIds){const c=card(id);assert(c.orange44&&Array.isArray(c.orange44.canonicalKeys),id);}});

test('MITM Evidence keeps listener, relay, mutation, material, access, execution, and privilege separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.3.js'));const I=global.OBOL_INTAKE_V73;let p=I.proof73('mitm-listen-73','sudo responder -I eth0 -v','[SMB] NTLMv2-SSP Client   : 10.0.0.25\n[SMB] NTLMv2-SSP Username : CORP\\alice');assert.deepStrictEqual(p.facts,['hash.netntlm','credential.candidate']);p=I.proof73('ntlm-ldaps-relay-73','impacket-ntlmrelayx -t ldaps://dc -smb2support --add-computer TEMP$ Pass --delegate-access','Authenticating against ldaps://dc as CORP/alice SUCCEED\nAdding new computer with username TEMP$\nDelegation rights modified successfully!');assert.deepStrictEqual(p.facts,['relay.ntlm_ldaps','ad.computer_added','ad.rbcd_configured']);p=I.proof73('ntlm-http-relay-73',"certipy relay -target 'http://ca/certsrv/certfnsh.asp' -template Machine",'Saved certificate and private key to machine.pfx');assert.deepStrictEqual(p.facts,['relay.ntlm_http','certificate.material']);p=I.proof73('ntlm-mssql-relay-73','impacket-ntlmrelayx -t mssql://sql -smb2support -socks','Authenticating against mssql://sql as CORP/alice SUCCEED\nSOCKS session added');assert.deepStrictEqual(p.facts,['relay.ntlm_mssql','relay.socks']);for(const x of ['access.admin','access.system','foothold.windows','remote.execution','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('current project model preserves the v7.3 source-wave history while advancing live state',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=51);assert(p.source.atomicTotal>=51);assert(p.source.filesAtomized>=4);assert(p.source.baselinesAtomized>=15);assert((p.recent||[]).some(x=>x.release==='v7.3')||p.release==='v7.3'||P.release==='v7.3');assert(P.sourceWave.delivered.length===10);});

test('README generator remains a structural live projection',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('Current live queue:'));assert(out.includes('Canonical methodology:'));assert(out.includes('Orange source fidelity:'));assert(out.includes('Highest-priority live items:'));assert(out.includes('Current phase:'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.3 historical release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.3.js','methodology-v7.3.js','source-delivery-v7.3.js','project-model-v7.3.js','core-v7.3.js','intake-v7.3.js','app-v7.3.js','obol-v7.3.css'])assert(idx.includes(x),x);assert(runtime.includes('source-delivery-v7.3.js'));assert(readme.includes('**v7.3**')||changelog.includes('## v7.3'));assert(changelog.includes('## v7.3'));assert(fs.existsSync(path.join(root,'docs','v7.3.md')));});

test('sanitized export retains secret redaction under later runtimes',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.3 tests passed`);
