'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','review-v2.7.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v2.8 state initializes explicit network paths and report evidence state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.8.0');assert.strictEqual(s.obolVersion,'2.8.0');assert(Array.isArray(s.networkModel.paths));assert.deepStrictEqual(s.reportEvidence28,{});});
test('observed internal services stay observed until an explicit active pivot covers them',()=>{const s=C.newState();C.recordNetworkObservations(s,[{type:'service',address:'172.16.60.20',destination:'smb:445'}],{source:'fixture'});assert.strictEqual(C.reachabilityFor(s,'172.16.60.20',s.activeContext).state,'observed');const p=C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'172.16.60.0/24',name:'lab pivot'},{source:'operator'});assert(p);assert.strictEqual(C.reachabilityFor(s,'172.16.60.20',s.activeContext).state,'pivot');C.updateNetworkPath(s,p.id,{status:'inactive'});assert.strictEqual(C.reachabilityFor(s,'172.16.60.20',s.activeContext).state,'observed');});
test('explicit direct paths classify matching observed hosts as directly reachable',()=>{const s=C.newState();C.addTypedArtifact(s,'hosts','10.20.5.5',{source:'fixture'});C.recordNetworkPath(s,{mode:'direct',network:'10.20.0.0/16',name:'operator route'},{source:'operator'});const r=C.reachabilityFor(s,'10.20.5.5',s.activeContext);assert.strictEqual(r.state,'direct');assert.strictEqual(r.via.mode,'direct');});
test('network path records require valid IPv4 CIDR and deduplicate updates',()=>{const s=C.newState();assert.strictEqual(C.recordNetworkPath(s,{mode:'pivot',network:'not-a-cidr'},{}),null);const a=C.recordNetworkPath(s,{mode:'pivot',kind:'chisel',network:'192.168.50.0/24',endpoint:'127.0.0.1:1080'},{}),b=C.recordNetworkPath(s,{mode:'pivot',kind:'chisel',network:'192.168.50.0/24',endpoint:'127.0.0.1:1080',status:'inactive'},{});assert.strictEqual(a.id,b.id);assert.strictEqual(s.networkModel.paths.length,1);assert.strictEqual(b.status,'inactive');});
test('artifact lineage timeline sorts producer and consumer events and links cards',()=>{const s=C.newState(),a=C.addTypedArtifact(s,'files','/tmp/loot.txt',{producer:{cardId:'producer-card',source:'card-evidence',at:'2026-08-27T12:00:00Z'}});C.recordArtifactConsumption(s,a,{cardId:'consumer-card',field:'file',source:'command-binding',at:'2026-08-27T12:05:00Z'});const t=C.lineageTimeline(s,a);assert.strictEqual(t.length,2);assert.strictEqual(t[0].direction,'produced');assert.strictEqual(t[1].direction,'consumed');assert.strictEqual(t[0].href,'#/card/producer-card');assert.strictEqual(t[1].href,'#/card/consumer-card');});
test('report readiness requires evidence, command snapshot, and operator-confirmed screenshot',()=>{const s=C.newState();C.recordActivity(s,{cardId:'proof-card',context:s.activeContext,result:'success',outcomeFacts:[],evidence:'whoami output',command:'whoami'});let r=C.reportReadiness(s,[],s.activeContext);assert.strictEqual(r.total,1);assert.strictEqual(r.ready,0);assert.strictEqual(r.missingScreenshot,1);C.setReportProof(s,r.rows[0].key,{screenshot:true});r=C.reportReadiness(s,[],s.activeContext);assert.strictEqual(r.ready,1);assert.strictEqual(r.missingEvidence,0);assert.strictEqual(r.missingCommand,0);});
test('sanitized export retains v2.8 release state while preserving inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','Summer2026!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'2.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v2.8 tests passed`);
