'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V70,P=global.OBOL_PROJECT_V70;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.0 historical adapter and milestone remain intact',()=>{assert.strictEqual(typeof C.projectModel70,'function');assert.strictEqual(P.version,'7.0.0');assert.strictEqual(P.release,'v7.0');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[100,27,0,0,79,100]);assert.deepStrictEqual(P.sourceWave.delivered,['adcs.mapping-shadow','adcs.esc9','adcs.esc10-case1','adcs.esc10-case2','adcs.esc14']);});

test('v7.0 certificate-mapping units remain fidelity-complete after later releases',()=>{for(const id of ['adcs.mapping-shadow','adcs.esc9','adcs.esc10-case1','adcs.esc10-case2']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.0',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const e=unit('adcs.esc14');assert(e);assert.strictEqual(e.auditStatus,'superseded');assert.strictEqual(e.auditedIn,'7.0');assert((F.dimensions||[]).every(d=>e.review[d.id]===true));const f=C.sourceFidelity70(lanes);assert(f.files.atomized>=1);assert.strictEqual(f.files.total,17);assert(f.partialBaseline.atomized>=7);assert.strictEqual(f.partialBaseline.total,34);assert(f.total>=19);assert(f.complete>=19);});

test('certificate-mapping parent remains reconciled',()=>{const s=section('adcs.certificate-mapping');assert(s);assert.strictEqual(s.status,'implemented');assert.strictEqual(s.advancedIn,'7.0');assert.strictEqual(s.sourceDepthAudit62.status,'modeled');assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['adcs.certificate-mapping']);});

test('current Build Next no longer contains v7.0 delivered units',()=>{const q=C.buildNext70(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);for(const id of P.sourceWave.delivered)assert(!q.rows.some(x=>x.key===id),id);assert(Array.isArray(q.rows));});

test('v7.0 certificate-mapping owners retain source provenance, cleanup, Evidence, and reporting',()=>{for(const id of ['adcs-mapping-shadow-70','adcs-esc9-70','adcs-esc10-case1-70','adcs-esc10-case2-70','adcs-esc14-assess-70']){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>x.key==='adcs.certificate-mapping'),id);assert(c.evidence45&&c.evidence45.source==='v7.0',id);assert(c.report47&&c.report47.evidenceProfile,id);}assert(card('adcs-mapping-shadow-70').commands.some(x=>String(x.run).includes('certipy shadow auto')));for(const id of ['adcs-esc9-70','adcs-esc10-case1-70','adcs-esc10-case2-70']){const c=card(id);assert(c.commands.some(x=>String(x.run).includes('certipy account update')));assert(c.commands.some(x=>String(x.run).includes('certipy req')));assert(c.commands.filter(x=>String(x.run).includes('certipy account update')).length>=2);}assert(card('adcs-esc14-assess-70').commands.some(x=>String(x.run).includes('certipy find')));});

test('v7.0 Evidence preserves mutation, credential, cleanup, access, and privilege boundaries',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.0.js'));const I=global.OBOL_INTAKE_V70;let p=I.proof70('adcs-mapping-shadow-70',"certipy shadow auto -account victim",'NT hash for victim: 0123456789abcdef0123456789abcdef\nSuccessfully restored the old Key Credentials for victim');assert.deepStrictEqual(p.facts,['credential.ntlm_hash','adcs.mapping_shadow_restored']);p=I.proof70('adcs-esc9-70',"certipy account update -user victim -upn Administrator",'Successfully updated victim');assert.deepStrictEqual(p.facts,['adcs.mapping_identity_prepared']);p=I.proof70('adcs-esc10-case1-70',"certipy req -ca CORP-CA -template User",'Got certificate\nSaved certificate and private key to victim.pfx');assert.deepStrictEqual(p.facts,['credential.certificate']);p=I.proof70('adcs-esc14-assess-70',"certipy find -vulnerable -stdout",'ESC14: Vulnerable explicit certificate mapping');assert.deepStrictEqual(p.facts,['adcs.esc14_candidate']);for(const x of [...I.proof70('adcs-mapping-shadow-70','certipy shadow auto -account victim','NT hash for victim: 0123456789abcdef0123456789abcdef').facts,...p.facts])assert(!['access.admin','access.system','foothold.windows','access.cross_domain','objective.domain_admin','capability.dcsync'].includes(x));});

test('v7.0 source-wave metadata remains historical while live README output stays structurally valid',()=>{assert.deepStrictEqual([P.sourceWave.fidelityBefore,P.sourceWave.fidelityAfter,P.sourceWave.fidelityTotal],[14,19,19]);assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['adcs.certificate-mapping']);const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('Current live queue'));assert(out.includes('Canonical methodology'));assert(out.includes('inventoried atomic units fidelity-complete'));assert(out.includes('Highest-priority live items'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract remains valid after v7.0',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.0 release wiring remains present and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v7.0.js','methodology-v7.0.js','project-model-v7.0.js','core-v7.0.js','intake-v7.0.js','app-v7.0.js','obol-v7.0.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v7.0.js'));assert(changelog.includes('## v7.0'));assert(fs.existsSync(path.join(root,'docs','v7.0.md')));});

test('sanitized export tracks the current release while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.0 tests passed`);
