'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v4.2 initializes current release and canonical-snapshot preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.2.0');assert.strictEqual(s.obolVersion,'4.2.0');assert.strictEqual(s.ui.mindmap42.filter,'all');assert.strictEqual(s.ui.mindmap42.file,'all');});
test('canonical Orange snapshot is pinned to the complete 2025.03 AD text tree',()=>{assert.strictEqual(O.version,'2025.03');assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.upstream.northStar,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');const files=O.files.map(x=>x.file);assert.strictEqual(files.length,17);for(const f of ['acl.md','adcs.md','admin.md','authenticated.md','crack_hash.md','delegation.md','dom_admin.md','know_vuln_auth.md','lat_move.md','low_access.md','low_hanging.md','mitm.md','no_creds.md','persistence.md','sccm.md','trusts.md','valid_user.md'])assert(files.includes(f),f);assert(O.supportFiles.some(x=>x.file==='conf.yml'));assert(O.supportFiles.some(x=>x.file==='authors.md'));});
test('canonical denominator contains every normalized methodology section and produces a durable percentage',()=>{const c=C.mindmapCoverage42(lanes);assert.strictEqual(c.sections,127);assert.strictEqual(c.implemented,25);assert.strictEqual(c.partial,39);assert.strictEqual(c.gap,62);assert.strictEqual(c.stale,1);assert.strictEqual(c.coveragePct,20);assert.strictEqual(c.representedPct,50);assert.strictEqual(c.sourceFileCount,17);});
test('snapshot integrity prevents accidental denominator drift',()=>{const i=C.orangeSnapshotIntegrity42();assert.strictEqual(i.ok,true);assert.strictEqual(i.methodologyFiles,17);assert.strictEqual(i.sections,127);assert.deepStrictEqual(i.duplicates,[]);});
test('newly normalized source containers expose previously hidden audit debt',()=>{const c=C.mindmapCoverage42(lanes);const trusts=c.files.find(x=>x.file==='trusts.md'),quick=c.files.find(x=>x.file==='low_hanging.md'),crack=c.files.find(x=>x.file==='crack_hash.md');assert(trusts&&trusts.sections.length===5);assert(quick&&quick.sections.length===11);assert(crack&&crack.sections.length===10);assert(trusts.sections.every(x=>x.status==='gap'));assert(c.files.find(x=>x.file==='sccm.md').sections.length===14);});
test('existing implemented mappings remain live while gaps and stale mappings stay explicit',()=>{const c=C.mindmapCoverage42(lanes),no=c.files.find(x=>x.file==='no_creds.md');assert(no.sections.find(x=>x.id==='scan').linkedCards.some(x=>x.id==='nmap-builder'));assert(no.sections.find(x=>x.id==='pxe').status==='gap');assert(c.files.find(x=>x.file==='persistence.md').sections.every(x=>x.status==='gap'));assert(c.files.some(f=>f.sections.some(x=>x.status==='stale')));const gaps=C.mindmapPriorityGaps42(lanes);assert(gaps.some(x=>x.file==='trusts.md'));assert(gaps.some(x=>x.file==='sccm.md'));assert(gaps.some(x=>x.status==='stale'));});
test('completion badge reports canonical full implementation rather than the v4.1 audit subset',()=>{const b=C.orangeCoverageBadge42(lanes);assert.strictEqual(b.value,'20%');assert(/25\/127/.test(b.detail));assert(/50%/.test(b.represented));});
test('v4.2 UI makes completion easy to see on every page and on Home',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v4.2.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v4.2.css'),'utf8');for(const x of ['orange-progress42','% fully implemented','Local source-of-truth','data/orange-ad-2025.03.js','View coverage'])assert(app.includes(x),x);for(const x of ['.orange-progress42','.canonical-shell42','.canonical-metric42','.orange-home42'])assert(css.includes(x),x);});
test('release wiring README docs and CI include v4.2 while retaining North Star and operator-side contracts',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.2.md'),'utf8');assert(idx.includes('Obol v4.2'));assert(idx.includes('orange-ad-2025.03.js'));assert(idx.indexOf('orange-ad-2025.03.js')<idx.indexOf('core-v4.2.js'));assert(idx.includes('app-v4.2.js'));assert(idx.includes('obol-v4.2.css'));assert(wf.includes('Run v4.2 regression suite'));assert(changelog.includes('## v4.2'));assert(readme.includes('127 canonical'));assert(readme.includes('Orange Cyber Defense mind map'));assert(readme.includes('operating from Kali or from a Windows host'));assert(/canonical local snapshot/i.test(notes));});
test('sanitized export retains v4.2 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.2.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.2 tests passed`);
