'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js','intake-v3.9.js','intake-v4.5.js','intake-v4.6.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V46,M44=global.OBOL_METHODOLOGY_V44,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function section(id){const f=(O.files||[]).find(x=>x.file==='sccm.md');return f&&(f.sections||[]).find(x=>x.id===id);}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';s.params.user='student';s.params.password='Passw0rd!';return s;}
function analyze(text){const s=hostState();return T.analyzeTerminal(text,lanes,s,s.activeContext);}
test('v4.6 initializes current release and SCCM progress preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.6.0');assert.strictEqual(s.obolVersion,'4.6.0');assert.strictEqual(s.ui.sccm46.showBranch,true);assert.strictEqual(s.ui.sccm46.showTrail,true);});
test('v4.6 preserves the pinned Orange source while advancing SCCM coverage only through the overlay',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.coverageRevision,'4.6');assert.strictEqual(O.coverageOverlay,'data/methodology-v4.6.js');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[48,45,34,0,38,73]);});
test('SCCM canonical branch now has dedicated credential takeover execution cleanup and post mappings',()=>{for(const [id,status] of [['creds6','implemented'],['creds34','implemented'],['takeover1','implemented'],['exec','implemented'],['cleanup','implemented'],['post','implemented'],['takeover2','partial'],['elevate1','partial'],['elevate2','partial'],['elevate3','partial'],['creds2','partial'],['creds5','partial']])assert.strictEqual(section(id).status,status,id);for(const id of M.cards)assert(card(id),id);});
test('new SCCM cards carry explicit operator side and run evidence contracts',()=>{for(const id of M.cards){const c=card(id),contract=C.orangeContractFor45(c);assert(c.orange44,id);assert(c.evidence45,id);assert(contract.runReady,id);assert(contract.evidenceReady,id);assert((c.commands||[]).every(x=>['kali','windows'].includes(x.operatorSurface40)),id);}assert(card('sccm-relay-takeover').commands.some(x=>(x.opts||[]).some(o=>o.flag==='-socks')));assert(card('sccm-admin-exec').commands.some(x=>/SharpSCCM\.exe exec/i.test(x.run)));});
test('v4.6 SCCM cards compose with bounded Orange decision stages',()=>{assert.strictEqual(M44.cardStage(card('sccm-credential-recovery')).id,'authenticated');assert.strictEqual(M44.cardStage(card('sccm-relay-takeover')).id,'control');assert.strictEqual(M44.cardStage(card('sccm-admin-exec')).id,'movement');assert.strictEqual(M44.cardStage(card('sccm-cleanup-post')).id,'admin');});
test('SCCM credential evidence requires explicit paired credential fields',()=>{let r=analyze("kali$ SCCMSecrets.py policies -mp http://sccm.corp.local -u 'student' -p 'Passw0rd!' -cn WS01\n[*] Downloading policies");let a=r.activities.find(x=>x.cardId==='sccm-credential-recovery');assert(a);assert.notStrictEqual(a.result,'success');assert(!a.outcomeFacts.includes('credential.candidate'));r=analyze("kali$ SCCMSecrets.py policies -mp http://sccm.corp.local -u 'student' -p 'Passw0rd!' -cn WS01\nNetworkAccessUsername: CORP\\aa_svc\nNetworkAccessPassword: LabPass123!");a=r.activities.find(x=>x.cardId==='sccm-credential-recovery');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('credential.candidate'));assert(a.outcomeFacts.includes('sccm.credentials'));assert(!a.outcomeFacts.includes('access.admin'));});
test('SCCM relay proof requires explicit successful authenticated relay output',()=>{let r=analyze("kali$ ntlmrelayx.py -t mssql://10.10.10.20 -smb2support\n[*] Protocol Client MSSQL loaded");let a=r.activities.find(x=>x.cardId==='sccm-relay-takeover');assert(a);assert.notStrictEqual(a.result,'success');r=analyze("kali$ ntlmrelayx.py -t mssql://10.10.10.20 -smb2support\n[*] Authenticating against mssql://10.10.10.20 as CORP/SCCM01$ SUCCEED");a=r.activities.find(x=>x.cardId==='sccm-relay-takeover');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('relay.success'));assert(a.outcomeFacts.includes('sccm.control_path'));assert(!a.outcomeFacts.includes('access.admin'));});
test('SCCM execution proof does not manufacture a Windows foothold or SYSTEM state',()=>{const r=analyze("PS C:\\Temp> SharpSCCM.exe exec -p C:\\Temp\\audit.ps1 -d WS01 -sms SCCM01 -sc LAB --no-banner\n[+] Execution request succeeded");const a=r.activities.find(x=>x.cardId==='sccm-admin-exec');assert(a&&a.result==='success');assert(a.outcomeFacts.includes('sccm.execution_confirmed'));assert(!a.outcomeFacts.includes('foothold.windows'));assert(!a.outcomeFacts.includes('access.system'));});
test('SCCM cleanup and post mapping use separate conservative facts',()=>{let r=analyze("PS C:\\Temp> SharpSCCM.exe remove device GUID:deadbeef -sms SCCM01 -sc LAB\n[+] Successfully removed device");let a=r.activities.find(x=>x.cardId==='sccm-cleanup-post');assert(a&&a.outcomeFacts.includes('sccm.cleanup_recorded'));r=analyze("PS C:\\Temp> SCCMHound.exe --server SCCM01 --sitecode LAB\nSCCMHound completed\nUser Sessions: 3");a=r.activities.find(x=>x.cardId==='sccm-cleanup-post');assert(a&&a.outcomeFacts.includes('sccm.post_map'));assert(!a.outcomeFacts.includes('access.admin'));});
test('SCCM progress remains context scoped and advances only from successful branch evidence',()=>{const s=hostState();s.hosts.push({id:'h2',ip:'10.10.10.20',name:'LAB2',hostname:'LAB2',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});C.recordActivity(s,{cardId:'sccm-credential-recovery',context:{type:'host',id:'h1'},result:'success',outcomeFacts:['sccm.credentials'],command:'fixture',evidence:'fixture'});assert.strictEqual(C.sccmProgress46(s,{type:'host',id:'h1'}).current,'credentials');assert.strictEqual(C.sccmProgress46(s,{type:'host',id:'h2'}).current,'recon');});
test('v4.6 UI release wiring and durable product contracts preserve all North Star contracts',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),north=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8'),hardening=fs.readFileSync(path.join(root,'docs','PRODUCT-HARDENING.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.6.md'),'utf8'),app=fs.readFileSync(path.join(root,'assets','app-v4.6.js'),'utf8');for(const x of ['Obol v4.6','methodology-v4.6.js','core-v4.6.js','intake-v4.6.js','app-v4.6.js','obol-v4.6.css'])assert(idx.includes(x),x);assert(wf.includes('Run v4.6 regression suite'));assert(changelog.includes('## v4.6'));assert(/GUI command-builder|GUI tool builder/i.test(hardening));assert(north.includes('Kali/Windows execution context'));assert(north.includes('Next Steps'));assert(north.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(/SCCM branch/i.test(notes));assert(/Orange SCCM branch/.test(app));});
test('sanitized export retains v4.6 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.6 tests passed`);
