'use strict';
const assert=require('assert');
const path=require('path');
const fs=require('fs');
const vm=require('vm');
const root=path.join(__dirname,'..');
const queuePath=path.join(root,'data','product-hardening','product-hardening-queue.js');
const sandbox={window:{},globalThis:null};sandbox.globalThis=sandbox.window;vm.createContext(sandbox);vm.runInContext(fs.readFileSync(queuePath,'utf8'),sandbox,{filename:queuePath});
const q=sandbox.window.OBOL_PRODUCT_HARDENING;
assert(q,'product-hardening queue exposed');
assert.strictEqual(q.version,'9.0.0');
assert(q.tracks.length>=8,'tracks are seeded');
assert(q.items.length>=70,'work ledger is seeded');
assert.strictEqual(q.notes.privateRepo,'platocres/obol-source-notes');
assert.strictEqual(q.totals().notes,556,'all staged source notes accounted');
assert(q.buildNext(5).some(i=>i.id==='cc-version-authority'),'version authority remains top build item');
assert(q.items.some(i=>i.track==='tool-builders'&&i.id==='tb-hashcat'),'hashcat builder is queued');
assert(q.items.some(i=>i.track==='manual-outcomes'&&i.id==='manual-success-unlocks'),'manual outcome workflow is queued');
assert(q.items.some(i=>i.track==='notes-integration'&&i.id==='notes-disposition-burn-down'),'notes burn-down is queued');
const readme=fs.readFileSync(path.join(root,'README.md'),'utf8');
assert(readme.includes('OBOL-PRODUCT-BUILD-NEXT:START'),'README has Product Build Next block');
assert(readme.includes('platocres/obol-source-notes'),'README points to private notes repo');
const dashboard=fs.readFileSync(path.join(root,'product-hardening.html'),'utf8');
assert(dashboard.includes('product-hardening-dashboard'),'standalone dashboard entrypoint exists');
assert(dashboard.includes('data/product-hardening/product-hardening-queue.js'),'dashboard loads queue data');
console.log('v9.0 product-hardening foundation tests passed.');
