'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V68,P=global.OBOL_PROJECT_V68;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v6.8 initializes current state and stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'6.8.0');assert.strictEqual(s.obolVersion,'6.8.0');assert.strictEqual(s.ui.dashboard68.showSourceWave,true);assert.strictEqual(C.currentProjectModel,C.projectModel68);assert.strictEqual(p.release,'v6.8');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[97,30,0,0,76,100]);});

test('v6.8 completes exactly the next three inventoried AD CS source units',()=>{for(const id of ['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert']){const u=unit(id);assert(u,id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'6.8',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}assert.deepStrictEqual(P.sourceWave.delivered,['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert']);const f=C.sourceFidelity68(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[1,17,7,34,11,19,8]);assert.strictEqual(f.completePct,58);});

test('canonical template and ACL parents advance only after their atomic inventories are complete',()=>{const templateIds=['adcs.esc1','adcs.esc2','adcs.esc3','adcs.esc13','adcs.esc15-schannel','adcs.esc15-agent'],aclIds=['adcs.esc4','adcs.esc7-manage-ca','adcs.esc7-manage-cert'];for(const id of [...templateIds,...aclIds]){const u=unit(id);assert(u,id);assert(['modeled','superseded','rejected'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}for(const key of ['adcs.template-misconfig','adcs.acl-misconfig']){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'6.8',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}assert.strictEqual(section('adcs.pki-object-acl').status,'partial');});

test('Build Next advances to ESC5 with quality debt still zero',()=>{const q=C.buildNext68(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,8,27,35]);assert.strictEqual(q.rows[0].key,'adcs.esc5');assert.strictEqual(q.rows[1].key,'adcs.esc6');assert.strictEqual(q.rows[2].key,'adcs.esc11');});

test('ESC4 owner models reversible current Certipy template workflow and ESC1 handoff',()=>{const c=card('adcs-esc4-68'),esc1=card('adcs-esc1-65');assert(c);assert(c.commands.some(x=>x.operatorSurface40==='kali'&&String(x.run).includes('-write-default-configuration')));assert(c.commands.some(x=>x.operatorSurface40==='windows'&&String(x.run).includes('-sspi')));assert(c.commands.some(x=>String(x.run).includes('-write-configuration')&&String(x.run).includes('{{backup_file}}')));assert(c.commands.some(x=>(x.opts||[]).some(o=>o.flag==='-force')));assert(esc1&&esc1.prereq&&esc1.prereq.any.includes('adcs.esc4_template_modified'));assert(c.evidence45&&c.evidence45.source==='v6.8');assert(c.report47&&c.report47.evidenceProfile);});

test('ESC7 owners separate CA role, pending request, issuance, retrieval, and cleanup',()=>{const ca=card('adcs-esc7-manage-ca-68'),cert=card('adcs-esc7-manage-cert-68');assert(ca&&cert);for(const needle of ['-add-officer','-remove-officer'])assert(ca.commands.some(x=>String(x.run).includes(needle)),needle);for(const needle of ['-enable-template','-issue-request','-retrieve','-disable-template'])assert(cert.commands.some(x=>String(x.run).includes(needle)),needle);assert(cert.commands.some(x=>String(x.run).includes('-retrieve')&&(x.opts||[]).some(o=>o.arg==='-key-file')));assert(ca.commands.some(x=>x.operatorSurface40==='windows'));assert(cert.commands.some(x=>x.operatorSurface40==='windows'));assert(ca.report47&&cert.report47);});

test('v6.8 Evidence keeps ESC4 and ESC7 stages conservatively separated',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v6.8.js'));const I=global.OBOL_INTAKE_V68;let p=I.proof68('adcs-esc4-68',"certipy template -template Vuln -write-default-configuration",'Saving current configuration to Vuln.json\nSuccessfully updated Vuln');assert.deepStrictEqual(p.facts,['adcs.esc4_template_modified']);p=I.proof68('adcs-esc4-68',"certipy template -template Vuln -write-configuration Vuln.json -no-save",'Successfully updated Vuln');assert.deepStrictEqual(p.facts,['adcs.esc4_template_restored']);p=I.proof68('adcs-esc7-manage-ca-68',"certipy ca -ca CORP-CA -add-officer attacker",'Successfully added officer attacker');assert.deepStrictEqual(p.facts,['adcs.esc7_officer_added']);p=I.proof68('adcs-esc7-manage-cert-68',"certipy req -ca CORP-CA -template SubCA",'Request ID is 17\nWrote private key to 17.key\nFailed to request certificate');assert.deepStrictEqual(p.facts,['adcs.esc7_request_pending']);assert(!p.facts.includes('credential.certificate'));p=I.proof68('adcs-esc7-manage-cert-68',"certipy ca -ca CORP-CA -issue-request 17",'Successfully issued certificate request ID 17');assert.deepStrictEqual(p.facts,['adcs.esc7_request_issued']);p=I.proof68('adcs-esc7-manage-cert-68',"certipy req -ca CORP-CA -retrieve 17",'Successfully retrieved certificate\nWrote certificate and private key to administrator.pfx');assert.deepStrictEqual(p.facts,['credential.certificate','adcs.esc7_certificate_retrieved']);for(const x of p.facts)assert(!['access.admin','access.system','foothold.windows','access.cross_domain','objective.domain_admin'].includes(x));});

test('project model and generated Build Next snapshot reflect the v6.8 wave',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.buildNext.total],[11,19,8,35]);assert.strictEqual(p.next.key,'adcs.esc5');assert.strictEqual(p.recent[0].release,'v6.8');const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('35 items'));assert(out.includes('97/127 fully implemented (76%)'));assert(out.includes('11/19 inventoried atomic units fidelity-complete'));assert(out.includes('ESC5 vulnerable PKI-object ACL / CA key path'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v6.8',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v6.8 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['orange-fidelity-v6.8.js','methodology-v6.8.js','project-model-v6.8.js','core-v6.8.js','intake-v6.8.js','app-v6.8.js','obol-v6.8.css'])assert(idx.includes(x),x);assert(!idx.includes('dashboard-v6.8.js'));assert(readme.includes('Current release: **v6.8**'));assert(changelog.includes('## v6.8'));assert(fs.existsSync(path.join(root,'docs','v6.8.md')));});

test('sanitized export advances to v6.8 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'6.8.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v6.8 tests passed`);