'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V76,P=global.OBOL_PROJECT_V76;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.6 historical project metadata remains available behind the stable current model',()=>{assert.strictEqual(P.version,'7.6.0');assert.strictEqual(P.release,'v7.6');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[118,9,0,0,93,100]);assert.strictEqual(typeof C.projectModel76,'function');assert.strictEqual(typeof C.currentProjectModel,'function');const p=C.currentProjectModel(C.newState(),lanes);assert(p.canonical.implemented>=118);assert(p.canonical.partial<=9);assert.strictEqual(p.canonical.gap,0);assert.strictEqual(p.canonical.representedPct,100);});

test('v7.6 admin source wave remains a twenty-five-unit historical ledger',()=>{assert.strictEqual(P.sourceWave.delivered.length,25);assert.strictEqual(P.sourceWave.fidelityAfter,118);assert.strictEqual(P.sourceWave.filesAtomizedAfter,7);assert.strictEqual(P.sourceWave.baselinesAtomizedAfter,25);assert.deepStrictEqual(P.sourceWave.superseded,['admin.lsass-ppldump']);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'admin.md',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert.strictEqual(u.auditedIn,'7.6',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity76(lanes);assert(f.files.atomized>=7);assert(f.partialBaseline.atomized>=25);assert(f.complete>=118);assert.strictEqual(f.pending,0);});

test('only admin.misc retains the v7.6 canonical advance milestone',()=>{const s=section('admin.misc');assert(s);assert.strictEqual(s.status,'implemented');assert.strictEqual(s.advancedIn,'7.6');assert.strictEqual(s.sourceDepthAudit62.status,'modeled');assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['admin.misc']);for(const key of P.sourceWave.historicalCanonicalDeepened){const h=section(key);assert(h,key);assert.strictEqual(h.status,'implemented',key);assert.notStrictEqual(h.advancedIn,'7.6',key);}});

test('current Build Next never reopens completed admin source-depth rows',()=>{const q=C.buildNext76(lanes);assert.strictEqual(q.implementedQuality,0);assert.strictEqual(q.mappedDelivery,0);assert.strictEqual(q.canonicalGaps,0);assert(!q.rows.some(x=>x.file==='admin.md'));assert(!q.rows.some(x=>x.key==='admin.misc'));});

test('admin source units retain mature and focused v7.6 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('admin.')),id);assert(c.evidence45&&c.evidence45.source==='v7.6',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext76,id);}assert(unit('admin.lsass-procdump').ownerCardIds.includes('lsass-collection55'));assert(unit('admin.sam-remote').ownerCardIds.includes('dump-secrets'));assert(unit('admin.dpapi-remote').ownerCardIds.includes('dpapi-secrets'));assert(unit('admin.impersonate-incognito').ownerCardIds.includes('token-impersonation55'));assert(unit('admin.misc-keepass').ownerCardIds.includes('admin-keepass-76'));assert(unit('admin.misc-adconnect').ownerCardIds.includes('admin-adconnect-76'));});

test('v7.6 admin Evidence contract remains conservative',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.6.js'));const I=global.OBOL_INTAKE_V76;let p=I.proof76('admin-lsass-protection-76','mimikatz.exe "sekurlsa::logonpasswords"','Username : alice\nDomain : CORP\nNTLM : 0123456789abcdef0123456789abcdef');assert.deepStrictEqual(p.facts,['loot.lsass','credential.candidate']);p=I.proof76('admin-session-impersonation-76','nxc smb 10.0.0.20 -u admin -p pass --loggedon-users','USERNAME CORP\\alice SESSIONNAME rdp-tcp#2');assert.deepStrictEqual(p.facts,['session.inventory']);for(const x of ['credential.available','access.admin','access.system','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('current project model preserves the v7.6 source wave as history',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert(p.source.atomicComplete>=118);assert(p.source.filesAtomized>=7);assert(p.source.baselinesAtomized>=25);assert(p.details.sourceWave76);assert.strictEqual(P.sourceWave.fidelityBefore,93);assert.strictEqual(P.sourceWave.fidelityAfter,118);});

test('README generator remains structurally synchronized without historical current-value literals',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Highest-priority live items:**'));assert(out.includes('source depth inventory'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract continues to pass under the current release',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.6 historical release wiring remains present and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.6.js','methodology-v7.6.js','project-model-v7.6.js','core-v7.6.js','intake-v7.6.js','app-v7.6.js','obol-v7.6.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.6.js'));assert(runtime.includes('methodology-v7.6.js'));assert(runtime.includes('project-model-v7.6.js'));assert(!idx.includes('dashboard-v7.6.js'));assert(fs.existsSync(path.join(root,'docs','v7.6.md')));assert(changelog.includes('v7.6')||fs.existsSync(path.join(root,'docs','CHANGELOG-through-v7.6.md')));});

test('sanitized export retains redaction under the current runtime',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.6 tests passed`);
