'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}

test('v4.0 initializes current release and per-context operator state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.0.0');assert.strictEqual(s.obolVersion,'4.0.0');assert.strictEqual(C.operatorMode40(s,s.activeContext),'either');assert.strictEqual(s.ui.operator40.showCommandContext,true);});
test('operator execution context is scoped independently per target context',()=>{const s=hostState();C.setOperatorMode40(s,s.activeContext,'kali');assert.strictEqual(C.operatorMode40(s,s.activeContext),'kali');s.hosts.push({id:'h2',ip:'10.10.10.20',name:'LAB2',hostname:'LAB2',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});assert.strictEqual(C.operatorMode40(s,{type:'host',id:'h2'}),'either');C.setOperatorMode40(s,{type:'host',id:'h2'},'windows');assert.strictEqual(C.operatorMode40(s,{type:'host',id:'h2'}),'windows');assert.strictEqual(C.operatorMode40(s,{type:'host',id:'h1'}),'kali');});
test('command-side classification distinguishes Kali, Windows, target-local, and neutral implementations',()=>{assert.strictEqual(C.commandSurface40({tool:'rubeus',run:'Rubeus.exe kerberoast'},{}),'windows');assert.strictEqual(C.commandSurface40({tool:'impacket-GetUserSPNs',run:'impacket-GetUserSPNs corp.local/user:pw -request'},{}),'kali');assert.strictEqual(C.commandSurface40({tool:'sh',run:'sudo -l'},{lane:'linux-privesc'}),'target');assert.strictEqual(C.commandSurface40({tool:'curl',run:'curl -s http://example/'},{}),'either');});
test('mixed methodology preserves both Kali and Windows choices',()=>{const card={id:'mixed',commands:[{tool:'impacket-getTGT',run:'impacket-getTGT corp.local/user:pw'},{tool:'rubeus',run:'Rubeus.exe asktgt /user:user'}]};const s=C.cardSurfaceSummary40(card);assert.strictEqual(s.kali,1);assert.strictEqual(s.windows,1);assert.strictEqual(s.total,2);});
test('explicit operator context adds a small preference signal without hiding methodology',()=>{const s=hostState(),card={id:'win-only',title:'Windows-only demo',commands:[{tool:'rubeus',run:'Rubeus.exe asktgt /user:user'}]};C.setOperatorMode40(s,s.activeContext,'windows');let sig=C.operatorSignal40(s,card,s.activeContext);assert(sig.delta>0);assert(/Windows-side/.test(sig.reason));C.setOperatorMode40(s,s.activeContext,'kali');sig=C.operatorSignal40(s,card,s.activeContext);assert(sig.delta<0);assert(/technique remains applicable/.test(sig.reason));});
test('target-local implementations remain neutral across operator platforms',()=>{const s=hostState(),card={id:'local',lane:'linux-privesc',commands:[{tool:'sh',run:'sudo -l'}]};C.setOperatorMode40(s,s.activeContext,'windows');const sig=C.operatorSignal40(s,card,s.activeContext);assert.strictEqual(sig.delta,0);assert.strictEqual(sig.matchCount,1);});
test('new activities snapshot planning mode and inferred execution side',()=>{const s=hostState();C.setOperatorMode40(s,s.activeContext,'windows');const a=C.recordActivity(s,{cardId:'kerberoast',context:s.activeContext,result:'tried',command:'Rubeus.exe kerberoast /nowrap',evidence:'operator ran command'});assert.strictEqual(a.operatorMode40,'windows');assert.strictEqual(a.executionSurface40,'windows');C.setOperatorMode40(s,s.activeContext,'kali');const b=C.recordActivity(s,{cardId:'kerberoast',context:s.activeContext,result:'tried',command:'impacket-GetUserSPNs corp.local/user:pw -request',evidence:'operator ran command'});assert.strictEqual(b.operatorMode40,'kali');assert.strictEqual(b.executionSurface40,'kali');});
test('release wiring, report provenance, README priorities, and CI include v4.0',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.0.md'),'utf8'),report=fs.readFileSync(path.join(root,'assets','report-v4.0.js'),'utf8'),app=fs.readFileSync(path.join(root,'assets','app-v4.0.js'),'utf8');assert(idx.includes('Obol v4.0'));assert(idx.includes('core-v4.0.js'));assert(idx.includes('report-v4.0.js'));assert(idx.includes('app-v4.0.js'));assert(idx.includes('obol-v4.0.css'));assert(wf.includes('Run v4.0 regression suite'));assert(changelog.includes('## v4.0'));assert(readme.includes('Orange Cyber Defense mind map'));assert(readme.includes('operating from Kali or from a Windows host'));assert(/Operator Execution Context/.test(report));assert(/Working from/.test(app));assert(/execution context/i.test(notes));});
test('sanitized export retains v4.0 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.0.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.0 tests passed`);
