'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V84,P=global.OBOL_PROJECT_V84,F84=global.OBOL_ORANGE_FIDELITY_V84;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}function unit(id){return(F.units||[]).find(x=>x.id===id);}function hasRun(id,re){const c=card(id);return!!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v8.4 initializes the stable current project model without canonical denominator drift',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'8.4.0');assert.strictEqual(s.obolVersion,'8.4.0');assert.strictEqual(C.currentProjectModel,C.projectModel84);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard84);assert.strictEqual(p.release,'v8.4');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[127,0,0,0,100,100]);});

test('v8.4 completes persistence.md with fifteen new units plus inherited Add Domain Admin accounting',()=>{assert.strictEqual(P.sourceWave.delivered.length,15);assert.strictEqual(F84.newAuditedIds.length,15);assert.strictEqual(F84.fileAuditedIds.length,16);assert.strictEqual(F84.newModeled.length,14);assert.strictEqual(F84.newRejected.length,1);for(const id of F84.newAuditedIds){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'persistence.md',id);assert.strictEqual(u.sourceSha,'a652fea306b91f887bb7b0deec751d9f6d711d5d',id);assert.strictEqual(u.auditedIn,'8.4',id);assert(['modeled','rejected'].includes(u.auditStatus),id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const inherited=unit('persistence.add-da-membership');assert(inherited);assert.strictEqual(inherited.auditedIn,'8.0');assert(F84.fileAuditedIds.includes(inherited.id));const f=C.sourceFidelity84(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[13,17,34,34,258,258,0]);assert.strictEqual((F.atomizedCanonicalKeys||[]).length,34);});

test('persistence source families remain implemented and mapped to mature owners',()=>{for(const key of ['persistence.add-da','persistence.golden-ticket','persistence.silver-ticket','persistence.dsrm','persistence.skeleton-key','persistence.custom-ssp','persistence.golden-cert','persistence.diamond-ticket','persistence.sapphire-ticket','persistence.dc-shadow','persistence.acl-persistence']){let s=null;for(const f of O.files||[])for(const x of f.sections||[])if(x.key===key)s=x;assert(s,key);assert.strictEqual(s.status,'implemented',key);}for(const id of F84.fileAuditedIds){const u=unit(id);for(const owner of u.ownerCardIds||[]){const c=card(owner);assert(c,owner);assert((c.atomic84||[]).includes(id),owner+' lineage for '+id);}}});

test('Golden and Silver Ticket source variants are corrected rather than copied blindly',()=>{assert(hasRun('golden-ticket',/impacket-ticketer -aesKey .* -domain-sid .* -domain /));assert(hasRun('golden-ticket',/kerberos::golden \/user:.* \/domain:.* \/sid:.* \/aes256:/));assert(hasRun('silver-ticket',/kerberos::golden \/sid:.* \/domain:.* \/target:.* \/service:.* \/aes256:/));assert(hasRun('silver-ticket',/impacket-ticketer -nthash .* -domain-sid .* -domain .* -spn /));assert(card('golden-ticket').sourceCorrection84);assert(card('silver-ticket').sourceCorrection84);const imp=unit('persistence.silver-impacket-nthash');assert(imp&&imp.sourceCorrection);assert.strictEqual(imp.sourceCorrection.pinnedOmission,'-spn');});

test('DSRM, Custom SSP, and Golden Certificate source details have explicit verification or artifact handling',()=>{assert(hasRun('dsrm-persistence',/New-ItemProperty .*DsrmAdminLogonBehavior/));assert(hasRun('dsrm-persistence',/Get-ItemProperty .*DsrmAdminLogonBehavior/));assert(hasRun('dsrm-persistence',/Set-ItemProperty .*prior_value/));assert(hasRun('credential-subsystem-persistence',/type C:\\Windows\\System32\\kiwissp\.log/));assert(hasRun('credential-subsystem-persistence',/del C:\\Windows\\System32\\kiwissp\.log/));assert(hasRun('golden-certificate',/certipy forge .* -subject/));});

test('advanced ticket source authentication inputs are explicitly treated as alternatives',()=>{const diamond=unit('persistence.diamond-ticket'),sapphire=unit('persistence.sapphire-ticket');assert(diamond&&diamond.sourceCorrection);assert(sapphire&&sapphire.sourceCorrection);assert(/alternative/i.test(diamond.sourceCorrection.authentication));assert(/alternative/i.test(sapphire.sourceCorrection.authentication));assert(card('advanced-forged-tickets').sourceCorrection84);});

test('source-empty DCShadow and ACL headings are modeled while the trailing ellipsis is rejected',()=>{const dc=unit('persistence.dcshadow-heading'),acl=unit('persistence.acl-manipulation-heading'),tail=unit('persistence.trailing-ellipsis');assert.strictEqual(dc.auditStatus,'modeled');assert.strictEqual(acl.auditStatus,'modeled');assert.strictEqual(tail.auditStatus,'rejected');assert.deepStrictEqual(tail.ownerCardIds,[]);assert(/non-actionable placeholder/i.test(tail.reason));assert.strictEqual(P.sourceWave.rejected.length,1);});

test('persistence proof boundaries keep artifacts below authentication, execution, and privilege',()=>{for(const id of F84.newAuditedIds){const u=unit(id);assert(/not authenticated access|not.*execution|separate/i.test(u.evidenceBoundary),id);}assert(/saved ccache proves forged ticket material only/i.test(card('golden-ticket').commands.find(x=>/impacket-ticketer -aesKey/.test(String(x.run))).note));assert(/registry state is persistence configuration only/i.test(card('dsrm-persistence').commands.find(x=>/Get-ItemProperty/.test(String(x.run))).note));assert(/certificate material only/i.test(card('golden-certificate').commands.find(x=>/-subject/.test(String(x.run))).note));});

test('Build Next advances to four remaining whole-file inventories',()=>{const q=C.buildNext84(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,4,4]);assert(q.rows.every(x=>x.kind==='source-file-inventory'));assert.deepStrictEqual(q.rows.map(x=>x.file),P.sourceWave.fileInventoryQueue);assert.strictEqual(q.rows[0].file,'dom_admin.md');assert(!q.rows.some(x=>x.file==='persistence.md'));});

test('project model exposes v8.4 source accounting and next file',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[258,258,0,13,34,4]);assert.strictEqual(p.phase.id,'whole-file-source-inventory');assert.strictEqual(p.next.file,'dom_admin.md');assert.strictEqual(p.recent[0].release,'v8.4');assert(p.details.sourceWave84);});

test('README generator reflects the v8.4 current project model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('**Current live queue:** 4 items'));assert(out.includes('**Canonical methodology:** 127/127 fully implemented (100%)'));assert(out.includes('**Orange source fidelity:** 13/17 source files atomized, 34/34 partial baselines decomposed, 258/258'));assert(out.includes('**Current phase:** Orange whole-file source inventory.'));assert(out.includes('dom_admin.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v8.4',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v8.4 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v8.4.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v8.4.js','methodology-v8.4.js','project-model-v8.4.js','core-v8.4.js','app-v8.4.js','obol-v8.4.css'])assert(idx.includes(x),x);for(const x of ['orange-fidelity-v8.4.js','methodology-v8.4.js','project-model-v8.4.js','core-v8.4.js'])assert(runtime.includes(x),x);assert(!idx.includes('dashboard-v8.4.js'));assert(!idx.includes('intake-v8.4.js'));assert(readme.includes('Current release: **v8.4**'));assert(releaseDoc.includes('# Obol v8.4'));});

test('sanitized export advances to v8.4 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'8.4.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v8.4 tests passed`);
