'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V78,P=global.OBOL_PROJECT_V78;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
function hasRun(id,re){const c=card(id);return !!(c&&(c.commands||[]).some(x=>re.test(String(x.run||''))));}

test('v7.8 historical project metadata remains intact',()=>{assert.strictEqual(P.version,'7.8.0');assert.strictEqual(P.release,'v7.8');assert.deepStrictEqual([P.releaseMilestone.implemented,P.releaseMilestone.partial,P.releaseMilestone.gap,P.releaseMilestone.stale,P.releaseMilestone.coveragePct,P.releaseMilestone.representedPct],[122,5,0,0,96,100]);assert.strictEqual(P.sourceWave.fidelityAfter,187);assert.strictEqual(P.sourceWave.filesAtomizedAfter,9);assert.strictEqual(P.sourceWave.baselinesAtomizedAfter,29);});

test('v7.8 lat_move.md ledger remains thirty-eight terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,38);assert.deepStrictEqual(P.sourceWave.superseded,[]);assert.strictEqual(P.sourceWave.modeled.length,38);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'lat_move.md',id);assert.strictEqual(u.auditStatus,'modeled',id);assert.strictEqual(u.auditedIn,'7.8',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}});

test('v7.8 canonical advance remains limited to SOCKS and certificate parents',()=>{assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['lat_move.socks','lat_move.certificate']);for(const key of P.sourceWave.canonicalAdvanced){const s=section(key);assert(s,key);assert.strictEqual(s.status,'implemented',key);assert.strictEqual(s.advancedIn,'7.8',key);assert.strictEqual(s.sourceDepthAudit62.status,'modeled',key);}for(const key of P.sourceWave.historicalCanonicalDeepened){const h=section(key);assert(h,key);assert.strictEqual(h.status,'implemented',key);assert.notStrictEqual(h.advancedIn,'7.8',key);}assert.strictEqual(section('lat_move.mssql').advancedIn,'4.3');});

test('v7.8 lateral-movement units retain mature and focused owner mappings',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('lat_move.')),id);assert(c.evidence45&&c.evidence45.source==='v7.8',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext78,id);}assert(unit('lat-move.plain-psexec').ownerCardIds.includes('lateral-exec'));assert(unit('lat-move.opth-gettgt').ownerCardIds.includes('kerberos-tickets'));assert(unit('lat-move.kerb-proxychains').ownerCardIds.includes('relay-socks-78'));assert(unit('lat-move.socks-dcsync').ownerCardIds.includes('dcsync'));assert(unit('lat-move.cert-certipy-unpac').ownerCardIds.includes('certificate-movement-78'));assert(unit('lat-move.mssql-links').ownerCardIds.includes('mssql-access'));assert(hasRun('lateral-exec',/impacket-dcomexec/));assert(hasRun('ticket-reuse',/impacket-ticketConverter/));assert(hasRun('mssql-access',/^enum_links$/));});

test('v7.8 Evidence keeps material, authentication, access, execution, and privilege separate',()=>{const saved=global.OBOL_INTAKE_V77;global.OBOL_INTAKE_V77={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.8.js'));const I=global.OBOL_INTAKE_V78;let p=I.proof78('relay-socks-78',"proxychains impacket-mssqlclient -windows-auth 'corp/alice'@10.0.0.10 -no-pass",'SQL>');assert.deepStrictEqual(p.facts,['db.mssql_access']);p=I.proof78('certificate-movement-78','certipy auth -pfx alice.pfx -dc-ip 10.0.0.5','Got TGT\nSaved credential cache to alice.ccache');assert.deepStrictEqual(p.facts,['kerberos.tickets']);p=I.proof78('certificate-movement-78','certipy auth -pfx alice.pfx -ldap-shell -dc-ip 10.0.0.5','Type help for list of commands');assert.deepStrictEqual(p.facts,['ldap.authenticated']);for(const x of ['objective.domain_admin','capability.dcsync','access.admin'])assert(!p.facts.includes(x));global.OBOL_INTAKE_V77=saved;});

test('v7.8 source wave remains available from its versioned dashboard adapter',()=>{const d=C.northStarDashboard78(C.newState(),lanes);assert(d.sourceWave78);assert.strictEqual(d.sourceWave78.fidelityAfter,187);assert.strictEqual(d.sourceWave78.filesAtomizedAfter,9);assert.strictEqual(d.sourceWave78.baselinesAtomizedAfter,29);});

test('README generator remains structurally valid under the current runtime',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:**'));assert(out.includes('**Canonical methodology:**'));assert(out.includes('**Orange source fidelity:**'));assert(out.includes('**Current phase:**'));});

test('v7.8 release wiring remains present without requiring it to be current',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),releaseDoc=fs.readFileSync(path.join(root,'docs','v7.8.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.8.js','methodology-v7.8.js','project-model-v7.8.js','core-v7.8.js','intake-v7.8.js','app-v7.8.js','obol-v7.8.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.8.js'));assert(runtime.includes('methodology-v7.8.js'));assert(runtime.includes('project-model-v7.8.js'));assert(!idx.includes('dashboard-v7.8.js'));assert(releaseDoc.includes('# Obol v7.8'));});

test('current sanitized export still redacts secrets after v7.8',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,C.VERSION);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.8 historical tests passed`);
