'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,M=global.OBOL_METHODOLOGY_V43,M41=global.OBOL_METHODOLOGY_V41,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(file,id){const f=(O.files||[]).find(x=>x.file===file);return f&&(f.sections||[]).find(x=>x.id===id);}
test('v4.3 initializes current release state',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'4.3.0');assert.strictEqual(s.obolVersion,'4.3.0');assert.strictEqual(s.ui.mindmap43.showAdvanced,true);});
test('v4.3 preserves the pinned Orange 2025.03 source snapshot while layering current coverage',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');assert.strictEqual(O.upstream.northStar,'https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg');assert.strictEqual(O.snapshotFormat,'v4.2');assert.strictEqual(O.coverageRevision,'4.3');assert.strictEqual(O.coverageOverlay,'data/methodology-v4.3.js');});
test('live v4.3 canonical coverage is 42 implemented 39 partial 46 gaps and zero stale',()=>{const c=C.mindmapCoverage42(lanes);assert.strictEqual(c.sections,127);assert.strictEqual(c.implemented,42);assert.strictEqual(c.partial,39);assert.strictEqual(c.gap,46);assert.strictEqual(c.stale,0);assert.strictEqual(c.coveragePct,33);assert.strictEqual(c.representedPct,64);});
test('v4.3 exposes an exact delta from the validated v4.2 live baseline',()=>{const d=C.coverageDelta43(lanes);assert.strictEqual(d.implementedDelta,17);assert.strictEqual(d.partialDelta,0);assert.strictEqual(d.gapDelta,-16);assert.strictEqual(d.staleDelta,-1);assert.strictEqual(d.coveragePointDelta,13);assert.strictEqual(d.representedPointDelta,14);assert(d.advanced.length>=20);});
test('RBCD stale mapping is repaired to the actual live Obol workflow cards',()=>{const c=C.mindmapCoverage42(lanes),f=c.files.find(x=>x.file==='delegation.md'),s=f.sections.find(x=>x.id==='rbcd');assert.strictEqual(s.status,'implemented');assert.deepStrictEqual(s.missingCardIds,[]);for(const id of ['delegation-abuse','getst-impersonation','ad-machine-account-quota-v25'])assert(s.linkedCards.some(x=>x.id===id),id);assert(!s.cardIds.includes('rbcd'));});
test('existing methodology is reconciled into canonical DC SCCM GPP MSSQL trust persistence and database sections',()=>{const expected=[['no_creds.md','find-dc','ad-dc-identify'],['authenticated.md','sccm-enum','sccm-enum'],['know_vuln_auth.md','gpp','gpp-passwords'],['lat_move.md','mssql','mssql-access'],['persistence.md','golden-ticket','golden-ticket'],['sccm.md','recon','sccm-enum'],['trusts.md','enumeration','trust-enum'],['trusts.md','mssql-links','mssql-access']];for(const [file,id,cardId] of expected){const s=section(file,id);assert.strictEqual(s.status,'implemented',file+':'+id);assert(s.cardIds.includes(cardId),cardId);}const db=section('low_hanging.md','database');assert.strictEqual(db.status,'implemented');for(const id of ['mssql-access','mysql-enum','postgres-enum'])assert(db.cardIds.includes(id),id);});
test('broad or risky source branches remain partial instead of inflating completion',()=>{for(const [file,id] of [['authenticated.md','known-vulns'],['low_hanging.md','zerologon'],['persistence.md','add-da'],['persistence.md','acl-persistence'],['crack_hash.md','pxe']])assert.strictEqual(section(file,id).status,'partial',file+':'+id);});
test('Hashcat AD reference uses current audited modes and keeps PXE external-module semantics explicit',()=>{const c=card('hashcat-modes');assert(c);const runs=(c.commands||[]).map(x=>String(x.run||''));for(const x of ['-m 3000','-m 5500','-m 19600','-m 2100','-m 31300','-m 19850'])assert(runs.some(r=>r.includes(x)),x);const h=C.hashModeAudit43();assert.strictEqual(h.external,1);assert.strictEqual(h.rows.find(x=>/NetNTLMv1/.test(x.format)).mode,5500);assert.strictEqual(h.rows.find(x=>x.mode===19850).stock,false);assert.strictEqual(section('crack_hash.md','ntlmv1').status,'implemented');assert.strictEqual(section('crack_hash.md','timeroast').status,'implemented');});
test('reconciled commands carry explicit Kali Windows or neutral execution metadata',()=>{const trust=card('trust-enum'),nl=(trust.commands||[]).find(x=>/nltest/.test(String(x.run||''))),sid=(trust.commands||[]).find(x=>/lookupsid/i.test(String(x.tool||'')+' '+String(x.run||'')));assert.strictEqual(nl.operatorSurface40,'windows');assert.strictEqual(sid.operatorSurface40,'kali');const dc=card('ad-dc-identify'),nxc=(dc.commands||[]).find(x=>String(x.tool||'').toLowerCase()==='nxc'),ns=(dc.commands||[]).find(x=>/nslookup/i.test(String(x.tool||'')+' '+String(x.run||'')));assert.strictEqual(nxc.operatorSurface40,'kali');assert.strictEqual(ns.operatorSurface40,'neutral');assert(card('hashcat-modes').commands.every(x=>x.operatorSurface40==='kali'));});
test('retained v4.1 tool audit no longer references the stale rbcd card and recognizes SCCM recon',()=>{const d=(M41.areas||[]).find(x=>x.id==='delegation').nodes.find(x=>x.id==='delegation-abuse');assert(!d.cardIds.includes('rbcd'));for(const id of ['delegation-abuse','getst-impersonation','ad-machine-account-quota-v25'])assert(d.cardIds.includes(id));const s=(M41.areas||[]).find(x=>x.id==='sccm').nodes.find(x=>x.id==='sccm-attacks');assert.deepStrictEqual(s.cardIds,['sccm-enum']);assert.strictEqual(s.coverage,'partial');assert.strictEqual(s.toolReview.decision,'supplement');});
test('canonical provenance is attached to live cards for traceable UI mappings',()=>{const c=card('mssql-access');assert(c.orange43&&c.orange43.some(x=>x.key==='lat_move.mssql'));assert(c.orange43.some(x=>x.key==='trusts.mssql-links'));assert(card('golden-ticket').orange43.some(x=>x.key==='persistence.golden-ticket'));});
test('v4.3 UI surfaces reconciliation delta Hashcat audit and card provenance',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v4.3.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v4.3.css'),'utf8');for(const x of ['v4.3 canonical reconciliation','Hashcat contract audit','Orange 2025.03 mapping','fully implemented sections since the validated v4.2 baseline'])assert(app.includes(x),x);for(const x of ['.reconcile-shell43','.reconcile-metric43','.reconcile-contract43','.orange-card43'])assert(css.includes(x),x);});
test('release wiring README docs and CI include v4.3 while retaining North Star and operator-side contracts',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v4.3.md'),'utf8');assert(idx.includes('Obol v4.3'));assert(idx.includes('methodology-v4.3.js'));assert(idx.includes('core-v4.3.js'));assert(idx.includes('app-v4.3.js'));assert(idx.includes('obol-v4.3.css'));assert(idx.indexOf('orange-ad-2025.03.js')<idx.indexOf('methodology-v4.3.js'));assert(wf.includes('Run v4.3 regression suite'));assert(changelog.includes('## v4.3'));assert(readme.includes('42 / 127'));assert(readme.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(readme.includes('operating from Kali or from a Windows host'));assert(/canonical reconciliation/i.test(notes));});
test('sanitized export retains v4.3 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'4.3.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v4.3 tests passed`);
