'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
run(path.join(root,'assets','core-v2-base.js'));run(path.join(root,'assets','core-v2.js'));run(path.join(root,'assets','core-v2.1.js'));run(path.join(root,'assets','core-v2.2.js'));run(path.join(root,'assets','core-v2.3.js'));run(path.join(root,'assets','core-v2.4.js'));run(path.join(root,'assets','core-v2.5.js'));run(path.join(root,'assets','core-v2.6.js'));
run(path.join(root,'data','signatures.js'));run(path.join(root,'assets','app-v2-intake.js'));run(path.join(root,'assets','intake-v2.5.js'));run(path.join(root,'assets','intake-v2.6.js'));
const C=global.OBOL_CORE_V2,X=global.OBOL_INTAKE_V26;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
test('v2.6 state initializes typed artifact stores',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'2.6.0');assert.strictEqual(s.obolVersion,'2.6.0');for(const k of C.TYPED_ARTIFACT_KINDS)assert(Array.isArray(s.typedArtifacts[k]));});
test('typed artifact extraction finds operational objects in noisy transcripts',()=>{const r=X.extractTypedArtifacts('PS C:\\Users\\bob> curl http://10.10.10.20/a\nroute 10.20.30.0/24\n\\\\dc01\\SYSVOL\nSaved to C:\\Temp\\admin.ccache\ncert C:\\Temp\\user.pfx\npassword: Summer2026!');assert(r.hosts.includes('10.10.10.20'));assert(r.urls.some(x=>x.includes('http://10.10.10.20/a')));assert(r.subnets.includes('10.20.30.0/24'));assert(r.shares.some(x=>x.includes('SYSVOL')));assert(r.tickets.some(x=>/admin\.ccache/i.test(x)));assert(r.certificates.some(x=>/user\.pfx/i.test(x)));assert(r.secrets.includes('Summer2026!'));});
test('typed artifacts deduplicate and hand off into compatible parameters',()=>{const s=C.newState(),a=C.addTypedArtifact(s,'hosts','10.10.10.20',{source:'test'}),b=C.addTypedArtifact(s,'hosts','10.10.10.20',{source:'test2'});assert.strictEqual(a.id,b.id);const h=C.applyArtifactHandoff(s,a);assert.strictEqual(h.param,'target');assert.strictEqual(s.params.target,'10.10.10.20');});
test('sanitized export redacts typed candidate secrets',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','Summer2026!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
test('negative evidence preserves failure class on activity records',()=>{const s=C.newState(),a=C.recordActivity(s,{cardId:'demo',context:s.activeContext,result:'tried',assessment:'refuted',failureClass:'refuted',reason:'underlying condition absent'});assert.strictEqual(a.failureClass,'refuted');assert.strictEqual(a.assessment,'refuted');});
test('refuted hypotheses disappear from normal Path but remain visible in show-all',()=>{const s=C.newState(),lanes=[{lane:'recon',title:'Recon',cards:[{id:'demo',title:'Demo',lane:'recon',hypothesis:'test',prereq:{all:['scope.defined']},produces:['demo.fact'],commands:[]}]}];C.recordActivity(s,{cardId:'demo',context:s.activeContext,result:'tried',assessment:'refuted',failureClass:'refuted'});assert.strictEqual(C.rankedApplicable(s,lanes,s.activeContext,{showAll:false}).some(x=>x.card.id==='demo'),false);assert.strictEqual(C.rankedApplicable(s,lanes,s.activeContext,{showAll:true}).some(x=>x.card.id==='demo'),true);});
test('tool failures remain retryable rather than refuting the technique',()=>{const s=C.newState(),lanes=[{lane:'recon',title:'Recon',cards:[{id:'retry',title:'Retry',lane:'recon',hypothesis:'test',prereq:{all:['scope.defined']},produces:['retry.fact'],commands:[]}]}];C.recordActivity(s,{cardId:'retry',context:s.activeContext,result:'tried',assessment:'tool_failed',failureClass:'tool_failed'});const rows=C.rankedApplicable(s,lanes,s.activeContext,{showAll:true});assert(rows.some(x=>x.card.id==='retry'));assert(rows.find(x=>x.card.id==='retry').why.includes('tool/environment'))});
test('workspace search spans facts, typed artifacts, queue notes, cards and commands',()=>{const s=C.newState(),lanes=[{lane:'web',title:'Web',cards:[{id:'web-demo',title:'Web probe',lane:'web',hypothesis:'look for admin',prereq:{all:['scope.defined']},produces:[],commands:[{tool:'curl',run:'curl http://{{target}}/admin'}]}]}];C.addTypedArtifact(s,'urls','http://10.10.10.20/admin',{});s.workQueue.push({id:'w1',cardId:'web-demo',contextKey:'global:global',contextLabel:'Engagement',priority:'normal',note:'check admin portal',status:'planned',createdAt:C.now(),updatedAt:C.now(),completedAt:null});const rows=C.searchWorkspace(s,lanes,'admin',s.activeContext);assert(rows.some(x=>x.kind==='artifact'));assert(rows.some(x=>x.kind==='queue'));assert(rows.some(x=>x.kind==='command'));});
console.log(`\n${passed} v2.6 tests passed`);
