'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js'])run(path.join(root,'assets',f));
for(const f of ['report-v2.js','report-v2.1.js','report-v2.2.js','report-v2.3.js','report-v2.4.js','report-v2.5.js','report-v2.6.js','report-v2.7.js','report-v2.8.js','report-v2.9.js','report-v3.5.js','report-v4.0.js','report-v4.7.js','report-v4.8.js','report-v5.0.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,O=global.OBOL_ORANGE_AD_2025_03,R=global.OBOL_REPORT_V2,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'LAB',hostname:'LAB',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};return s;}
test('v5.0 initializes current release and dedicated-dashboard preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'5.0.0');assert.strictEqual(s.obolVersion,'5.0.0');assert.strictEqual(s.ui.dashboard50.compactHome,true);});
test('v5.0 preserves the pinned canonical source and v4.9 methodology baseline',()=>{assert.strictEqual(O.upstream.commit,'6d16ca0d1434875e0617f2f3cfa825fad0bc7d7e');assert.strictEqual(O.upstream.adTree,'51b414fc0c0a1a4414e86986ec5e2b5225a6d698');const c=C.mindmapCoverage42(lanes);assert.deepStrictEqual([c.implemented,c.partial,c.gap,c.stale,c.coveragePct,c.representedPct],[52,49,26,0,41,80]);});
test('Dashboard lives once under More while primary workflow remains five items',()=>{const nav=C.NAVIGATION30;assert.strictEqual(nav.primary.length,5);assert.deepStrictEqual(nav.primary.map(x=>x.id),['home','boxes','intake','path','report']);const dashboards=nav.secondary.filter(x=>x.id==='dashboard');assert.strictEqual(dashboards.length,1);assert.strictEqual(dashboards[0].href,'#/dashboard');});
test('UI policy audit reports hard pass counts and allowed brand surfaces',()=>{const a=C.uiPolicyAudit50();assert.strictEqual(a.total,5);assert.strictEqual(a.passed,5);assert.strictEqual(a.pct,100);const d=C.northStarDashboard50(C.newState(),lanes);assert.deepStrictEqual(d.allowedBrandRoutes,['dashboard','home']);assert(d.metrics.some(x=>x.id==='ui-hygiene'&&x.value===100));assert(d.milestones.some(x=>x.release==='v5.0'));});
test('changelog owns release history from v2 foundation through v5.0',()=>{const c=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['## v2.0','## v3.0','## v4.0','## v4.9','## v5.0'])assert(c.includes(x),x);assert(/README is intentionally reserved/i.test(c));});
test('README remains current-state handoff documentation rather than a multi-version changelog',()=>{const r=fs.readFileSync(path.join(root,'README.md'),'utf8'),c=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');assert(/Current release: \*\*v\d+\.\d+(?:\.\d+)?\*\*/.test(r));assert(c.includes('## v5.0'));assert(r.includes('[`CHANGELOG.md`](CHANGELOG.md)'));assert(r.includes('[`BUILDING.md`](BUILDING.md)'));for(const x of ['## Obol v4.9','## Obol v4.8','## Obol v4.7'])assert(!r.includes(x),x);assert(r.includes('The README is not a changelog'));assert(r.includes('## Future-agent quickstart'));assert(r.includes('## Active product queue'));assert(!r.includes('<!-- OBOL-BUILD-NEXT:START -->'));});
test('permanent North Star and execution-side requirements live in durable docs',()=>{const n=fs.readFileSync(path.join(root,'docs','NORTH-STAR.md'),'utf8'),p=fs.readFileSync(path.join(root,'docs','PRODUCT-HARDENING.md'),'utf8');assert(n.includes('https://orange-cyberdefense.github.io/ocd-mindmaps/img/mindmap_ad_dark_classic_2025.03.excalidraw.svg'));assert(n.includes('https://github.com/Orange-Cyberdefense/ocd-mindmaps/tree/main'));assert(n.includes('Kali/Windows execution context'));assert(n.includes('Next Steps'));assert(n.includes('command controls'));assert(n.includes('reporting'));assert(p.includes('Product-hardening queue items are not allowed to drift into vibes'));});
test('Home is compact and dedicated Dashboard owns the full project-health surface',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v5.0.js'),'utf8');assert(app.includes('northstar-home50'));assert(app.includes('viewDashboard50'));assert(app.includes('Project health in one place'));assert(app.includes("v.querySelectorAll('.northstar-dashboard49"));assert(app.includes("page50()==='dashboard'"));});
test('Methodology and Guide remove duplicated release/project-health surfaces',()=>{const app=fs.readFileSync(path.join(root,'assets','app-v5.0.js'),'utf8'),css=fs.readFileSync(path.join(root,'assets','obol-v5.0.css'),'utf8');assert(app.includes('.dash-methodology49,.reconcile-shell43,.mindmap-shell41'));assert(app.includes('Project health and history'));assert(css.includes('.canonical-shell42 .canonical-hero42'));assert(css.includes('.orange-progress42{display:none!important}'));});
test('generated reports use neutral North Star wording outside Dashboard/Home',()=>{const s=hostState();C.recordActivity(s,{cardId:'kerberos-tickets',context:s.activeContext,result:'success',command:'klist',evidence:'Ticket cache: FILE:test.ccache'});const md=R.generate(s,lanes,'standard',{});assert(md.includes('North Star Decision Path & Reporting Traceability'));assert(!/Orange Cyber ?Defense/i.test(md));assert(!/Orange Decision Path/i.test(md));});
test('v5.0 release wiring remains present after later releases',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v5.0.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');for(const x of ['dashboard-v5.0.js','core-v5.0.js','report-v5.0.js','app-v5.0.js','obol-v5.0.css'])assert(idx.includes(x),x);assert(wf.includes('Run v5.0 regression suite'));assert(/information-architecture/i.test(notes));assert(/changelog/i.test(notes));assert(changelog.includes('## v5.0'));});
test('sanitized export retains v5.0 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'5.0.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v5.0 tests passed`);
