'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path');global.window=globalThis;global.DOMParser=function(){};
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}const root=path.join(__dirname,'..');
for(const f of ['lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js'])run(path.join(root,'data',f));
for(const f of ['core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js'])run(path.join(root,'assets',f));
for(const f of ['intake-v2.1.js','intake-v2.5.js','intake-v3.5.js','intake-v3.6.js'])run(path.join(root,'assets',f));
const C=global.OBOL_CORE_V2,T=global.OBOL_INTAKE_V21,lanes=global.OBOL_LANES;let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function hostState(){const s=C.newState();s.hosts.push({id:'h1',ip:'10.10.10.10',name:'EDGE',hostname:'EDGE',domain:'corp.local',os:'Windows',notes:'',ports:[],flags:[],creds:[]});s.activeContext={type:'host',id:'h1'};s.params.target='10.10.10.10';s.params.domain='corp.local';return s;}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function ctxKey(s){return C.contextKey(s.activeContext);}
test('v3.7 initializes current release and lineage preferences',()=>{const s=C.newState();assert.strictEqual(C.VERSION,'3.7.0');assert.strictEqual(s.obolVersion,'3.7.0');assert.strictEqual(s.ui.lineage37.maxDepth,6);});
test('target-specific reachability separates same-service observations by address',()=>{const s=hostState();C.recordNetworkObservations(s,[{type:'service',address:'172.16.10.5',destination:'smb:445'},{type:'service',address:'172.16.10.25',destination:'smb:445'}],{context:s.activeContext,source:'test'});C.recordNetworkPath(s,{mode:'pivot',kind:'ligolo',network:'172.16.10.0/28',status:'active',lastVerifiedAt:C.now()},{context:s.activeContext,source:'test'});const sig=C.targetReachabilitySignal37(s,card('smb-anon-enum'),s.activeContext);assert.strictEqual(sig.service,'smb');assert.strictEqual(sig.targets.length,2);assert.strictEqual(sig.targets.find(x=>x.address==='172.16.10.5').state,'pivot');assert.strictEqual(sig.targets.find(x=>x.address==='172.16.10.25').state,'observed');assert(sig.delta>0);assert(sig.reason.includes('172.16.10.5'));});
test('stale pivot verification does not receive a full service reachability boost',()=>{const s=hostState(),old=new Date(Date.now()-8*60*60*1000).toISOString();C.recordNetworkObservations(s,[{type:'service',address:'172.16.20.7',destination:'ldap:389'}],{context:s.activeContext,source:'test'});C.recordNetworkPath(s,{mode:'pivot',kind:'chisel',network:'172.16.20.0/24',status:'active',lastVerifiedAt:old},{context:s.activeContext,source:'test'});const sig=C.targetReachabilitySignal37(s,card('ad-anon-ldap-enum'),s.activeContext),target=sig.targets[0];assert.strictEqual(target.state,'pivot');assert.strictEqual(target.verification.state,'stale');assert.strictEqual(sig.delta,0);assert(/stale|unverified/.test(sig.reason));});
test('broken paths never promote matching observed targets',()=>{const s=hostState();C.recordNetworkObservations(s,[{type:'service',address:'172.16.30.9',destination:'smb:445'}],{context:s.activeContext,source:'test'});C.recordNetworkPath(s,{mode:'pivot',kind:'ssh',network:'172.16.30.0/24',status:'broken',lastVerifiedAt:C.now()},{context:s.activeContext,source:'test'});const sig=C.targetReachabilitySignal37(s,card('smb-anon-enum'),s.activeContext);assert.strictEqual(sig.targets[0].state,'observed');assert(sig.targets[0].brokenPath);assert(sig.delta<=0);});
test('consumer lineage repairs exact activity IDs only when correlation is unique',()=>{const s=hostState(),a=C.recordActivity(s,{cardId:'smb-anon-enum',context:s.activeContext,result:'success',command:'nxc smb 172.16.10.5 -u "" -p ""',evidence:'shares'}),art=C.addTypedArtifact(s,'hosts','172.16.10.5',{context:s.activeContext,source:'intake:test',observedAt:a.at});art.consumedBy=[{id:'c1',activityId:'',cardId:'smb-anon-enum',source:'command-binding',contextKey:ctxKey(s),at:a.at}];assert.strictEqual(C.reconcileConsumerLineage37(s),1);assert.strictEqual(art.consumedBy[0].activityId,a.id);const b=C.recordActivity(s,{cardId:'smb-anon-enum',context:s.activeContext,result:'tried',command:'nxc smb 172.16.10.5 --shares',evidence:'again'});b.at=a.at;art.consumedBy.push({id:'c2',activityId:'',cardId:'smb-anon-enum',source:'command-binding',contextKey:ctxKey(s),at:a.at});C.reconcileConsumerLineage37(s);assert.strictEqual(art.consumedBy[1].activityId,'');});
test('multi-hop compromise chains traverse recorded artifact dependencies',()=>{const s=hostState(),key=ctxKey(s),a=C.addTypedArtifact(s,'hosts','172.16.40.10',{context:s.activeContext,source:'test'}),b=C.addTypedArtifact(s,'shares','backup',{context:s.activeContext,source:'test'}),c=C.addTypedArtifact(s,'files','config.ini',{context:s.activeContext,source:'test'});a.consumedBy=[{id:'ab-c',cardId:'smb-anon-enum',contextKey:key,at:'2026-08-28T10:00:00Z'}];b.producedBy=[{id:'ab-p',cardId:'smb-anon-enum',contextKey:key,at:'2026-08-28T10:00:01Z'}];b.consumedBy.push({id:'bc-c',cardId:'smb-share-loot',contextKey:key,at:'2026-08-28T10:01:00Z'});c.producedBy=[{id:'bc-p',cardId:'smb-share-loot',contextKey:key,at:'2026-08-28T10:01:01Z'}];const chains=C.compromiseChains37(s,s.activeContext,{maxDepth:6});const chain=chains.find(x=>x.artifactIds.join('|')===[a.id,b.id,c.id].join('|'));assert(chain);assert.strictEqual(chain.hops,2);});
test('artifact neighborhood exposes upstream and downstream multi-hop context',()=>{const s=hostState(),key=ctxKey(s),a=C.addTypedArtifact(s,'hosts','172.16.50.10',{context:s.activeContext,source:'test'}),b=C.addTypedArtifact(s,'shares','ops',{context:s.activeContext,source:'test'}),c=C.addTypedArtifact(s,'files','secret.txt',{context:s.activeContext,source:'test'});a.consumedBy=[{cardId:'one',contextKey:key,at:'2026-08-28T10:00:00Z'}];b.producedBy=[{cardId:'one',contextKey:key,at:'2026-08-28T10:00:01Z'}];b.consumedBy.push({cardId:'two',contextKey:key,at:'2026-08-28T10:01:00Z'});c.producedBy=[{cardId:'two',contextKey:key,at:'2026-08-28T10:01:01Z'}];const n=C.artifactNeighborhood37(s,b.id,s.activeContext,3);assert(n.upstream.artifactIds.includes(a.id));assert(n.downstream.artifactIds.includes(c.id));});
test('full AD transcript regression keeps command intent separated across one operator session',()=>{const s=hostState(),text="PS C:\\Temp> nxc ldap 10.10.10.10 -u '' -p '' --users\nLDAP 10.10.10.10 [+] corp.local\\:\nLDAP 10.10.10.10 [*] Enumerated 3 domain users\nPS C:\\Temp> Rubeus.exe asreproast /user:svc_backup /domain:corp.local /nowrap\n[*] Action: AS-REP roasting\n$krb5asrep$23$svc_backup@CORP.LOCAL:deadbeef";const r=T.analyzeTerminal(text,lanes,s,s.activeContext);assert(r.activities.some(x=>x.cardId==='ad-anon-ldap-enum'));assert(r.activities.some(x=>x.cardId==='asrep-roast'&&x.outcomeFacts.includes('kerberos.asrep_hash')));});
test('release wiring, README priorities, and CI include v3.7',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),wf=fs.readFileSync(path.join(root,'.github','workflows','tests.yml'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),notes=fs.readFileSync(path.join(root,'docs','v3.7.md'),'utf8');assert(idx.includes('Obol v3.7'));assert(idx.includes('core-v3.7.js'));assert(idx.includes('app-v3.7.js'));assert(idx.includes('obol-v3.7.css'));assert(wf.includes('Run v3.7 regression suite'));assert(changelog.includes('## v3.7'));assert(readme.includes('Orange Cyber Defense mind map'));assert(/target-specific reachability/i.test(changelog));assert(/multi-hop/i.test(notes));});
test('sanitized export retains v3.7 and inherited secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'3.7.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});
console.log(`\n${passed} v3.7 tests passed`);
