'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),path=require('path'),cp=require('child_process');
const root=path.join(__dirname,'..');
const {loadCurrent}=require(path.join(root,'tools','current-runtime.js'));
const {C,lanes}=loadCurrent(root);const O=global.OBOL_ORANGE_AD_2025_03,F=global.OBOL_ORANGE_FIDELITY_V64,M=global.OBOL_METHODOLOGY_V76,P=global.OBOL_PROJECT_V76;
let passed=0;function test(n,f){try{f();console.log('ok - '+n);passed++;}catch(e){console.error('FAIL - '+n);throw e;}}
function card(id){for(const l of lanes)for(const c of l.cards||[])if(c.id===id)return c;return null;}
function section(key){for(const f of O.files||[])for(const s of f.sections||[])if(s.key===key)return s;return null;}
function unit(id){return (F.units||[]).find(x=>x.id===id);}
function run(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}

test('v7.6 initializes the stable current project model',()=>{const s=C.newState(),p=C.currentProjectModel(s,lanes);assert.strictEqual(C.VERSION,'7.6.0');assert.strictEqual(s.obolVersion,'7.6.0');assert.strictEqual(C.currentProjectModel,C.projectModel76);assert.strictEqual(C.currentNorthStarDashboard,C.northStarDashboard76);assert.strictEqual(p.release,'v7.6');assert.deepStrictEqual([p.canonical.implemented,p.canonical.partial,p.canonical.gap,p.canonical.stale,p.canonical.completePct,p.canonical.representedPct],[118,9,0,0,93,100]);});

test('admin.md is atomized into twenty-five terminal source units',()=>{assert.strictEqual(P.sourceWave.delivered.length,25);assert.deepStrictEqual(P.sourceWave.superseded,['admin.lsass-ppldump']);assert.strictEqual(P.sourceWave.modeled.length,24);for(const id of P.sourceWave.delivered){const u=unit(id);assert(u,id);assert.strictEqual(u.sourceFile,'admin.md',id);assert(['modeled','superseded'].includes(u.auditStatus),id);assert.strictEqual(u.auditedIn,'7.6',id);assert((F.dimensions||[]).every(d=>u.review[d.id]===true),id);}const f=C.sourceFidelity76(lanes);assert.deepStrictEqual([f.files.atomized,f.files.total,f.partialBaseline.atomized,f.partialBaseline.total,f.complete,f.total,f.pending],[7,17,25,34,118,118,0]);assert.strictEqual(f.completePct,100);});

test('only admin.misc advances while five historical admin parents retain their milestones',()=>{const s=section('admin.misc');assert(s);assert.strictEqual(s.status,'implemented');assert.strictEqual(s.advancedIn,'7.6');assert.strictEqual(s.sourceDepthAudit62.status,'modeled');assert.deepStrictEqual(P.sourceWave.canonicalAdvanced,['admin.misc']);for(const key of P.sourceWave.historicalCanonicalDeepened){const h=section(key);assert(h,key);assert.strictEqual(h.status,'implemented',key);assert.notStrictEqual(h.advancedIn,'7.6',key);}});

test('Build Next leaves admin.md and proceeds into no_creds.md source inventory',()=>{const q=C.buildNext76(lanes);assert.deepStrictEqual([q.implementedQuality,q.mappedDelivery,q.canonicalGaps,q.sourceFidelity,q.sourceInventory,q.total],[0,0,0,0,9,9]);assert.strictEqual(q.rows.length,9);assert(q.rows.every(x=>x.kind==='source-depth-inventory'));assert.strictEqual(q.rows[0].file,'no_creds.md');assert(!q.rows.some(x=>x.file==='admin.md'));assert(!q.rows.some(x=>x.key==='admin.misc'));});

test('admin source units reuse mature owners and add focused v7.6 owners',()=>{for(const id of M.cardIds){const c=card(id);assert(c,id);assert(c.commands&&c.commands.length,id);assert(c.orange43&&c.orange43.some(x=>String(x.key).startsWith('admin.')),id);assert(c.evidence45&&c.evidence45.source==='v7.6',id);assert((c.report47&&c.report47.evidenceProfile)||c.report,id);assert(c.executionContext76,id);}assert(unit('admin.lsass-procdump').ownerCardIds.includes('lsass-collection55'));assert(unit('admin.sam-remote').ownerCardIds.includes('dump-secrets'));assert(unit('admin.dpapi-remote').ownerCardIds.includes('dpapi-secrets'));assert(unit('admin.impersonate-incognito').ownerCardIds.includes('token-impersonation55'));assert(unit('admin.misc-keepass').ownerCardIds.includes('admin-keepass-76'));assert(unit('admin.misc-adconnect').ownerCardIds.includes('admin-adconnect-76'));});

test('admin Evidence keeps artifacts, credentials, sessions, access, privilege, and cleanup separate',()=>{global.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[],segments:[]})};run(path.join(root,'assets','intake-v7.6.js'));const I=global.OBOL_INTAKE_V76;let p=I.proof76('admin-lsass-protection-76','mimikatz.exe "sekurlsa::logonpasswords"','Username : alice\nDomain : CORP\nNTLM : 0123456789abcdef0123456789abcdef');assert.deepStrictEqual(p.facts,['loot.lsass','credential.candidate']);p=I.proof76('admin-session-impersonation-76','nxc smb 10.0.0.20 -u admin -p pass --loggedon-users','USERNAME CORP\\alice SESSIONNAME rdp-tcp#2');assert.deepStrictEqual(p.facts,['session.inventory']);p=I.proof76('admin-adcs-impersonation-76','masky -d corp.local -u alice -p pass -ca CORP-CA 10.0.0.20','Saved certificate to alice.pfx');assert.deepStrictEqual(p.facts,['certificate.material']);p=I.proof76('admin-keepass-76','KeePwn.py trigger add -u admin -p pass -d corp.local -t 10.0.0.20','Username: vaultuser\nPassword: VaultSecret!');assert.deepStrictEqual(p.facts,['credential.candidate']);p=I.proof76('admin-adconnect-76','nxc smb 10.0.0.20 -u admin -p pass -M msol','MSOL_123456 password: SyncSecret!');assert.deepStrictEqual(p.facts,['adconnect.msol_material','credential.candidate']);for(const x of ['credential.available','access.admin','access.system','objective.domain_admin','capability.dcsync'])assert(!p.facts.includes(x));});

test('project model exposes the v7.6 source wave without a second status owner',()=>{const p=C.currentProjectModel(C.newState(),lanes);assert.deepStrictEqual([p.source.atomicComplete,p.source.atomicTotal,p.source.atomicPending,p.source.filesAtomized,p.source.baselinesAtomized,p.buildNext.total],[118,118,0,7,25,9]);assert.strictEqual(p.phase.id,'source-inventory-decomposition');assert.strictEqual(p.next.file,'no_creds.md');assert.strictEqual(p.recent[0].release,'v7.6');assert(p.details.sourceWave76);});

test('README generator remains synchronized with the v7.6 current model',()=>{const out=cp.execFileSync(process.execPath,[path.join(root,'tools','sync-readme-build-next.js'),'--print'],{encoding:'utf8'});assert(out.includes('<!-- OBOL-BUILD-NEXT:START -->'));assert(out.includes('**Current live queue:** 9 items'));assert(out.includes('**Canonical methodology:** 118/127 fully implemented (93%)'));assert(out.includes('**Orange source fidelity:** 7/17 source files atomized, 25/34 partial baselines decomposed, 118/118 inventoried atomic units fidelity-complete'));assert(out.includes('no_creds.md'));});

test('release quality gate remains clean',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-quality.js')],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);assert((r.stdout||'').includes('0 implemented-quality repairs, 0 mapped-delivery repairs, 0 canonical gaps'));});

test('repository release contract passes for v7.6',()=>{const r=cp.spawnSync(process.execPath,[path.join(root,'tools','validate-release-pr.js'),'--repo-only'],{cwd:root,encoding:'utf8'});assert.strictEqual(r.status,0,r.stderr||r.stdout);});

test('v7.6 release wiring is complete and delta-based',()=>{const idx=fs.readFileSync(path.join(root,'index.html'),'utf8'),readme=fs.readFileSync(path.join(root,'README.md'),'utf8'),changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8'),runtime=fs.readFileSync(path.join(root,'tools','current-runtime.js'),'utf8');for(const x of ['orange-fidelity-v7.6.js','methodology-v7.6.js','project-model-v7.6.js','core-v7.6.js','intake-v7.6.js','app-v7.6.js','obol-v7.6.css'])assert(idx.includes(x),x);assert(runtime.includes('orange-fidelity-v7.6.js'));assert(runtime.includes('methodology-v7.6.js'));assert(runtime.includes('project-model-v7.6.js'));assert(!idx.includes('dashboard-v7.6.js'));assert(readme.includes('Current release: **v7.6**'));assert(changelog.includes('## v7.6'));assert(fs.existsSync(path.join(root,'docs','v7.6.md')));});

test('sanitized export advances to v7.6 while retaining secret redaction',()=>{const s=C.newState();C.addTypedArtifact(s,'secrets','DoNotExport!',{});const safe=C.sanitizedCopy(s);assert.strictEqual(safe.obolVersion,'7.6.0');assert.strictEqual(safe.typedArtifacts.secrets[0].value,'[REDACTED SECRET]');});

console.log(`\n${passed} v7.6 tests passed`);
