'use strict';
const fs=require('fs');const path=require('path');
const root=path.join(__dirname,'..');
const p=rel=>path.join(root,rel);const read=rel=>fs.readFileSync(p(rel),'utf8').replace(/\r\n/g,'\n');const write=(rel,text)=>fs.writeFileSync(p(rel),text);
function replaceOne(rel,from,to){let text=read(rel);if(text.includes(to))return false;if(!text.includes(from))throw new Error(rel+' missing expected patch target: '+from.slice(0,120));write(rel,text.replace(from,to));return true;}
function replaceRange(rel,start,end,replacement){let text=read(rel);if(text.includes(replacement.trim()))return false;const a=text.indexOf(start),b=text.indexOf(end,a+start.length);if(a<0||b<0)throw new Error(rel+' missing range '+start+' ... '+end);write(rel,text.slice(0,a)+replacement+text.slice(b));return true;}
function insertBefore(rel,marker,addition,guard){let text=read(rel);if(guard&&text.includes(guard))return false;const at=text.indexOf(marker);if(at<0)throw new Error(rel+' missing insertion marker '+marker);write(rel,text.slice(0,at)+addition+text.slice(at));return true;}
function appendOnce(rel,heading,section){let text=read(rel);if(text.includes(heading))return false;write(rel,text.replace(/\s*$/,'')+'\n\n'+section.replace(/^\s+|\s+$/g,'')+'\n');return true;}
let changed=0;const c=v=>{if(v)changed++;};

c(replaceOne('data/current-release.js'," version:'9.46.0',\n label:'v9.46',"," version:'9.47.0',\n label:'v9.47',"));

c(replaceOne('data/runtime-manifest.js'," ['app','assets/obol-app-current.js','Report base and application UI','Base report owner, application prelude, and historical workflow/UI overlays.','ordered-fragment-concatenation']"," ['app','assets/obol-app-current.js','Report base and application UI','Base report owner, application prelude, and historical workflow/UI semantic deltas.','semantic-delta-replay']"));
c(replaceOne('data/runtime-manifest.js',"operatorRoutes:Object.freeze({policy:'current-owner+compatibility-decorated',owner:'assets/operator-route-current.js',reason:'Path, Card, and Tools keep historical compatibility code available while current route owners replace visible presentation. v9.46 adds a boot visibility barrier so exact-owned application compatibility may initialize but cannot expose historical intermediate route paints before the current workflow claims first paint.'})","operatorRoutes:Object.freeze({policy:'semantic-current-application+current-route-owners',owner:'assets/operator-route-current.js',reason:'v9.47 gives the application layer one stable current router. The surviving historical rendering deltas remain only as the frozen semantic ledger compiled into assets/obol-app-current.js; their timers, hashchange listeners, intervals, and MutationObservers no longer run autonomously. Current workflow/operator owners commit visible presentation last.'})"));
c(replaceOne('data/runtime-manifest.js',"Remaining application compatibility still executes through an exact owner, but v9.46 prevents its intermediate historical renders from becoming visible while deeper semantic retirement remains future work.","The application area is semantically current-owned as of v9.47: its 43 surviving historical rendering deltas remain traceable in the frozen ledger but no longer execute as autonomous browser layers. v9.43 remains the request/stale-overlay retirement milestone and v9.46 remains the first-paint barrier milestone."));
const appBlock=`/* v9.47 application semantic retirement. v9.43 proved which release-wave overlays were\n   inert and reduced the surviving ledger to 43 load-bearing fragments; v9.46 added a\n   first-paint barrier. v9.47 changes execution ownership: the surviving rendering\n   deltas are generated into one stable current router, historical scheduler/listener\n   side effects are suppressed, and current workflow/operator owners commit last. */\nconst appCurrent=Object.freeze({\n owner:'assets/obol-app-current.js',\n strategy:'semantic-delta-replay',\n sourceRelease:'v9.47',\n requestRetirementRelease:'v9.43',\n firstPaintRelease:'v9.46',\n historicalFragments:bundleAreas.find(area=>area.id==='app').fragments,\n retiredFragments:retiredReleaseWaveOverlays,\n retirementGate:'C.VERSION',\n retirementGateValue:'8.8.0',\n retainedGateOwner:'assets/app-v8.8.js',\n generator:'tools/sync-app-current.js',\n semanticValidator:'tools/validate-app-semantic-current.js',\n equivalenceValidator:'tools/validate-app-current-equivalence.js',\n domEquivalenceValidator:'tools/validate-app-dom-equivalence.js'\n});\n`;
c(replaceRange('data/runtime-manifest.js','/* The application area stays an exact ordered concatenation','const coreCurrent=',appBlock));

c(replaceOne('data/runtime-consolidation-current.js',"const generatedOwner=area=>area.id==='domain'&&manifest.domainCurrent?manifest.domainCurrent:area.id==='core'&&manifest.coreCurrent?manifest.coreCurrent:null;","const generatedOwner=area=>area.id==='domain'&&manifest.domainCurrent?manifest.domainCurrent:area.id==='core'&&manifest.coreCurrent?manifest.coreCurrent:area.id==='app'&&manifest.appCurrent?manifest.appCurrent:null;"));

c(replaceOne('data/product-hardening/product-hardening-queue.js','["architecture-runtime","Architecture / runtime","Compact the sedimentary runtime without breaking historical behavior.",18,21]','["architecture-runtime","Architecture / runtime","Compact the sedimentary runtime without breaking historical behavior.",19,22]'));
c(replaceOne('data/product-hardening/product-hardening-queue.js','This item is additive so prior runtime-app-flattening completion and historical metrics remain intact.','This item is additive so prior runtime-app-flattening completion and historical metrics remain intact. v9.47 later proved that first-paint hiding did not retire post-commit historical scheduling; runtime-app-semantic-retirement owns that separate correction without rewriting this milestone.'));
let queue=read('data/product-hardening/product-hardening-queue.js');
if(!queue.includes('"runtime-app-semantic-retirement"')){
 const marker='],["ux-home-user-first"';const at=queue.indexOf(marker);if(at<0)throw new Error('queue insertion marker missing');
 const item='],["runtime-app-semantic-retirement","architecture-runtime","complete",18.86,"Retire autonomous historical application execution","v9.47 converts assets/obol-app-current.js from exact ordered concatenation into a semantic current application/router owner. The 43 surviving historical fragments remain the frozen semantic ledger, but historical startup timers, intervals, hashchange listeners, MutationObservers, and repeated route repaint schedules no longer run autonomously. One deterministic current route transaction drains surviving historical decorator intent before stable current workflow/operator owners commit visible presentation; browser startup must not request versioned application fragments directly. v9.43 request retirement and v9.46 first-paint metrics remain intact."]';
 queue=queue.slice(0,at)+item+queue.slice(at+1);write('data/product-hardening/product-hardening-queue.js',queue);changed++;
}

const contract=` 'runtime-app-semantic-retirement':{\n  acceptance:[\n   'The application ownership area uses a stable non-versioned semantic-delta-replay owner rather than an exact historical concatenation, while all 43 v9.43 surviving fragments remain traceable as the frozen semantic ledger.',\n   'Historical application startup timers, intervals, hashchange listeners, MutationObservers, and delayed route repaint schedules are suppressed; one current router owns navigation and drains surviving historical decorator intent before current workflow/operator presentation commits.',\n   'Cold boot and route navigation do not directly request versioned historical application files and do not expose a historical Home or Next Steps frame across the complete former timer horizon.',\n   'README, Product Build Next, Dashboard, runtime consolidation projection, architecture guidance, and historical v9.43/v9.46 milestones distinguish request flattening, first-paint protection, and semantic application retirement without rewriting earlier completion counts.'\n  ],\n  validationCommands:['node tools/sync-app-current.js --check','node tools/validate-app-semantic-current.js','node tools/validate-app-current-equivalence.js','node tools/validate-app-dom-equivalence.js','node tools/validate-app-semantic-boot-browser.js','node tests/run-v9.47-tests.js'],\n  proofFiles:['data/runtime-manifest.js','assets/obol-app-current.js','tools/sync-app-current.js','tools/validate-app-semantic-current.js','tools/validate-app-semantic-boot-browser.js','data/product-hardening/product-hardening-queue.js','assets/product-hardening-dashboard.js','README.md','BUILDING.md','docs/RUNTIME-COMPACTION.md','docs/ARCHITECTURE.md','tests/run-v9.47-tests.js','docs/v9.47.md']\n },\n`;
c(insertBefore('data/product-hardening/item-test-contracts.js'," 'runtime-app-single-paint':{",contract,"'runtime-app-semantic-retirement':{"));

const oldRow="  {area:'Home / Path workflow',historical:consolidatedBy('app'),current:queueStatus('runtime-app-single-paint')==='complete'?'yes — current first-paint gate over exact-owned compatibility':'partial',proof:queueStatus('runtime-app-single-paint')==='complete'?'throttled Chromium first-visible-paint proof':(queueStatus('runtime-historical-equivalence')==='complete'?'shared equivalence':'open'),tests:queueStatus('runtime-app-single-paint')==='complete'?'currentized; historical app ledger retained':'not yet'},";
const newRow="  {area:'Home / Path workflow',historical:consolidatedBy('app'),current:queueStatus('runtime-app-semantic-retirement')==='complete'?'yes — semantic current application/router owner':(queueStatus('runtime-app-single-paint')==='complete'?'first-paint protected':'partial'),proof:queueStatus('runtime-app-semantic-retirement')==='complete'?'semantic replay + long-horizon Chromium ownership proof':(queueStatus('runtime-app-single-paint')==='complete'?'throttled first-visible-paint proof':'open'),tests:queueStatus('runtime-app-semantic-retirement')==='complete'?'historical app fragments fixture-ledger only; autonomous schedulers retired':'not yet'},";
c(replaceOne('assets/product-hardening-dashboard.js',oldRow,newRow));
c(replaceOne('assets/product-hardening-dashboard.js','Application, Evidence, Nmap, report-overlay, and tool-reference compatibility remain exact-owned where not yet semantically retired; v9.46 additionally prevents exact-owned application history from becoming visible during first paint.','Application is semantically current-owned as of v9.47; its 43 surviving historical rendering fragments remain the frozen source/equivalence ledger but no longer own timers, navigation listeners, or delayed visible route paints. Evidence, Nmap, report-overlay, and tool-reference compatibility remain exact-owned where not yet semantically retired.'));

const buildingNote=`**Critical application-ownership distinction for future agents:** do not use \"flattened\" as a synonym for semantic retirement. v9.43 consolidated application requests and retired 21 stale overlays but deliberately kept 43 surviving fragments in exact historical execution order. v9.46 added a first-visible-paint barrier but did not stop those survivors from scheduling later route repaints. v9.47 is the separate semantic application-ownership milestone: the 43 survivors remain the frozen regression/equivalence ledger, while one stable current application/router owner suppresses their autonomous schedulers/listeners and commits current presentation last. Future compaction metrics must preserve all three milestones additively rather than retroactively relabeling an earlier one.\n\nA generated owner is not semantically retired merely because the browser makes one request. For application work, require proof of **execution ownership**: versioned fragments must not be requested directly, historical scheduling/listener side effects must not remain autonomous, and long-horizon browser proof must show that a current-owned route cannot be replaced by a historical paint after commit.\n\n`;
let building=read('BUILDING.md');if(!building.includes('Critical application-ownership distinction for future agents')){building=building.replace('## Historical runtime compaction\n\n','## Historical runtime compaction\n\n'+buildingNote);write('BUILDING.md',building);changed++;}

c(appendOnce('docs/RUNTIME-COMPACTION.md','## v9.47 — Semantic application execution ownership',`## v9.47 — Semantic application execution ownership\n\nv9.43 and v9.46 are intentionally preserved as narrower milestones. v9.43 reduced the application request layer to 43 load-bearing historical fragments behind one exact owner and retired 21 stale C.VERSION-gated overlays. v9.46 added a boot visibility barrier that proved the first visible Home frame was current. Neither milestone removed the surviving historical route wrappers, timers, hashchange listeners, or delayed decorators from execution.\n\nv9.47 changes the ownership category itself. \`assets/obol-app-current.js\` is generated by \`tools/sync-app-current.js\` as a semantic delta replay. The 43 source fragments stay on disk and remain listed as the frozen semantic/equivalence ledger, but their autonomous startup schedulers and navigation listeners are suppressed. One stable current route transaction invokes the surviving rendering semantics, drains the historical decorator queue synchronously, runs stable current workflow/operator renderers last, and owns the single live hashchange listener.\n\nThis moves all 43 application fragments from the \"still exact-owned\" runtime bucket into the semantically flattened bucket without changing the 327-fragment frozen ledger or the 21-fragment v9.43 retirement result. The metric change is additive: v9.43 request retirement, v9.46 first-paint protection, and v9.47 semantic execution ownership are three different completed contracts.\n\nThe browser proof intentionally observes beyond the old 5.2-second historical timer horizon and exercises forced reroutes plus Home → Next Steps → Home navigation. A future agent must not replace that with a short first-frame check.`));
c(appendOnce('docs/ARCHITECTURE.md','## Application ownership boundary (v9.47)',`## Application ownership boundary (v9.47)\n\nThe browser application has one stable execution owner: \`assets/obol-app-current.js\`. Historical \`app-v*\`, v2 base/view, and related application fragments are source/equivalence fixtures, not autonomous browser layers. The current owner may replay their still-required rendering deltas as generated semantic input, but historical code may not install live navigation listeners, timers, intervals, MutationObservers, or delayed repaint schedules.\n\nNavigation is owned by the current application router. For non-Dashboard routes it executes the surviving rendering transaction, drains captured historical decorator intent before paint, then invokes \`OBOL_CURRENT_WORKFLOW\` and \`OBOL_OPERATOR_ROUTES\` last. Dashboard retains its dedicated current-route hydration owner. Runtime lazy hydration may call \`window.route()\`, but that symbol now resolves to the stable current router rather than the historical wrapper chain.\n\nDo not regress this boundary by changing the application area back to \`ordered-fragment-concatenation\`, loading \`assets/app-v*.js\` directly, or reintroducing version-specific route scheduling. Historical files remain valuable regression evidence; they are not the current presentation authority.`));
c(appendOnce('docs/UX-QUALITY.md','## v9.47 startup and navigation paint ownership',`## v9.47 startup and navigation paint ownership\n\nA route is not considered current merely because its first visible frame is current. Once a current route is visible, historical presentation must never reclaim the view on a later timer, lazy-hydration rerender, or hash navigation callback. v9.47 therefore extends visual ownership testing across the complete former application timer horizon and repeated navigation. Home must retain \`data-current-home-owner=\"workflow-current\"\`; Next Steps must retain \`data-operator-route-owner=\"path-current\"\` whenever those routes are visible.`));
c(appendOnce('docs/PRODUCT-HARDENING.md','## v9.47 semantic application-retirement accounting',`## v9.47 semantic application-retirement accounting\n\nApplication runtime hardening now records three separate completed contracts instead of collapsing them into one ambiguous \"flattening\" claim: v9.43 request/stale-overlay retirement, v9.46 first-visible-paint protection, and v9.47 semantic execution ownership. The new \`runtime-app-semantic-retirement\` item is additive. Architecture/runtime advances by one completed item and one total item; overall Product Hardening advances by the same +1/+1 through the generated queue projection. Earlier completion denominators are historical facts and are not rewritten.`));

let changelog=read('CHANGELOG.md');if(!changelog.includes('## v9.47 —')){const entry=`## v9.47 — Semantic application ownership\n\n- Replaced the exact-concatenation application runtime with a generated semantic current application/router owner while preserving all 43 surviving historical fragments as the frozen semantic/equivalence ledger.\n- Retired autonomous historical application timers, intervals, hashchange listeners, MutationObservers, and delayed route repaint scheduling; current workflow/operator renderers now commit last behind one current navigation owner.\n- Added long-horizon Chromium proof spanning the former 5.2-second historical timer window plus forced reroutes and Home → Next Steps → Home navigation, and forbade direct versioned application requests.\n- Preserved v9.43 request/stale-overlay retirement and v9.46 first-paint protection as separate completed historical milestones; added \`runtime-app-semantic-retirement\` so Architecture/runtime and overall Product Hardening metrics advance additively instead of being rewritten.\n\n`;
 changelog=changelog.replace('# Obol Changelog\n\n','# Obol Changelog\n\n'+entry);write('CHANGELOG.md',changelog);changed++;}

c(replaceOne('.github/workflows/browser-smoke.yml',"      - name: Prove the v9.46 single-paint current boot in a browser\n        env:\n          OBOL_SMOKE_BASE_URL: http://127.0.0.1:4173/index.html\n        run: node tools/validate-single-paint-boot-browser.js\n","      - name: Prove the v9.46 single-paint current boot in a browser\n        env:\n          OBOL_SMOKE_BASE_URL: http://127.0.0.1:4173/index.html\n        run: node tools/validate-single-paint-boot-browser.js\n\n      - name: Prove v9.47 semantic application ownership across the historical timer horizon\n        env:\n          OBOL_SMOKE_BASE_URL: http://127.0.0.1:4173/index.html\n        run: node tools/validate-app-semantic-boot-browser.js\n"));

let preflight=read('tools/release-preflight.js');
if(!preflight.includes("'tools/sync-app-current.js'")){preflight=preflight.replace("'tools/validate-core-current-equivalence.js','tools/validate-app-current-equivalence.js'","'tools/validate-core-current-equivalence.js','tools/sync-app-current.js','tools/validate-app-semantic-current.js','tools/validate-app-current-equivalence.js'");}
if(!preflight.includes("run('application current-owner synchronization'")){preflight=preflight.replace("  run('core semantic equivalence',['tools/validate-core-current-equivalence.js']);\n  run('application retirement equivalence'","  run('core semantic equivalence',['tools/validate-core-current-equivalence.js']);\n  run('application current-owner synchronization',['tools/sync-app-current.js','--check']);\n  run('application semantic execution ownership',['tools/validate-app-semantic-current.js']);\n  run('application retirement equivalence'");}
write('tools/release-preflight.js',preflight);changed++;

let scope=read('tools/scope-check.js');
if(!scope.includes("['tools/sync-app-current.js','--check']")){scope=scope.replace(" ['tools/validate-core-current-equivalence.js'],\n ['tools/sync-runtime-bundles.js','--check'],"," ['tools/validate-core-current-equivalence.js'],\n ['tools/sync-app-current.js','--check'],\n ['tools/validate-app-semantic-current.js'],\n ['tools/sync-runtime-bundles.js','--check'],");}
if(!scope.includes("['tests/run-v9.47-tests.js']"))scope=scope.replace(" ['tests/run-v9.46-tests.js']\n"," ['tests/run-v9.46-tests.js'],\n ['tests/run-v9.47-tests.js']\n");
write('tools/scope-check.js',scope);changed++;

let bundles=read('tools/validate-runtime-bundles.js');
if(!bundles.includes("const appCurrent=require('./sync-app-current');"))bundles=bundles.replace("const coreCurrent=require('./sync-core-current');","const coreCurrent=require('./sync-core-current');\nconst appCurrent=require('./sync-app-current');");
bundles=bundles.replace("assert.strictEqual(semanticDeltaAreas.length,1,'v9.42 has exactly one semantic delta-replay runtime area');\nassert.strictEqual(semanticDeltaAreas[0].id,'core','the core area is the semantic delta-replay owner');\nassert.strictEqual(exactAreas.length,5,'the remaining runtime areas stay exact ordered concatenations');","assert.strictEqual(semanticDeltaAreas.length,2,'core and application are semantic delta-replay runtime areas');\nassert(semanticDeltaAreas.some(area=>area.id==='core'),'the core area is a semantic delta-replay owner');\nassert(semanticDeltaAreas.some(area=>area.id==='app'),'the application area is a semantic delta-replay owner');\nassert.strictEqual(exactAreas.length,4,'the remaining runtime areas stay exact ordered concatenations');");
bundles=bundles.replace('const core=semanticDeltaAreas[0];',"const core=semanticDeltaAreas.find(area=>area.id==='core');");
if(!bundles.includes('/* ---- semantic application owner')){
 const marker='/* ---- exact areas: strict leakage, exact concatenation, parse isolation ----- */';const at=bundles.indexOf(marker);if(at<0)throw new Error('validate-runtime-bundles app insertion marker missing');
 const section=`/* ---- semantic application owner ------------------------------------------ */\n\nconst app=semanticDeltaAreas.find(area=>area.id==='app');\nassert(app&&manifest.appCurrent,'semantic application owner declares manifest metadata');\nassert.strictEqual(manifest.appCurrent.owner,app.owner,'appCurrent owner matches the application area owner');\nassert.strictEqual(manifest.appCurrent.strategy,'semantic-delta-replay','appCurrent records the semantic delta strategy');\nassert.strictEqual(manifest.appCurrent.generator,'tools/sync-app-current.js','application semantic owner declares its generator');\nassert.strictEqual(manifest.appCurrent.semanticValidator,'tools/validate-app-semantic-current.js','application semantic owner declares its ownership validator');\nassert.deepStrictEqual(Array.from(manifest.appCurrent.historicalFragments),Array.from(app.fragments),'appCurrent records the frozen application semantic ledger');\nassert.strictEqual(app.fragments.length,43,'application semantic owner retains the 43 v9.43 surviving source fragments');\nconst appOwner=read(app.owner);\nassert.strictEqual(appOwner,appCurrent.expected(),app.owner+' is out of sync with its semantic application generator');\nassert(!appOwner.includes('obol-runtime-fragment:'),'semantic application owner is not an exact historical concatenation bundle');\nassert(appOwner.includes('obol-app-delta: assets/app-v8.8.js'),'semantic application owner preserves the live v8.8 bridge semantics as generated input');\nassert(appOwner.includes('__OBOL_HISTORICAL_APP_SCHEDULERS_DISABLED__'),'semantic application owner retires autonomous historical scheduling');\nfor(const forbidden of ['vm.runInContext','vm.runInThisContext','fs.readFile','document.write(manifest'])assert(!appOwner.includes(forbidden),'semantic application owner must not dynamically load historical fragments: '+forbidden);\nnew vm.Script(appOwner,{filename:app.owner});\n\n`;
 bundles=bundles.slice(0,at)+section+bundles.slice(at);
}
bundles=bundles.replace("console.log('Runtime owners valid: '+areas.length+' ownership areas cover '+seen.size+' historical fragments ('+semanticAreas.length+' semantic snapshot, '+semanticDeltaAreas.length+' semantic delta replay, '+exactAreas.length+' exact concatenations); core semantic equivalence surface sha256 '+sha(bundleSurface).slice(0,16)+'.');","console.log('Runtime owners valid: '+areas.length+' ownership areas cover '+seen.size+' historical fragments ('+semanticAreas.length+' semantic snapshot, '+semanticDeltaAreas.length+' semantic delta replay, '+exactAreas.length+' exact concatenations); core semantic equivalence surface sha256 '+sha(bundleSurface).slice(0,16)+'.');");
write('tools/validate-runtime-bundles.js',bundles);changed++;

let appEq=read('tools/validate-app-current-equivalence.js');
if(!appEq.includes("require('./validate-app-semantic-current').main();return;"))appEq=appEq.replace('function main(){\n /* ---- manifest metadata',"function main(){\n const currentArea=(manifest.bundles&&manifest.bundles.areas||[]).find(candidate=>candidate.id==='app');\n if(currentArea&&currentArea.strategy==='semantic-delta-replay'){require('./validate-app-semantic-current').main();return;}\n /* ---- manifest metadata");
write('tools/validate-app-current-equivalence.js',appEq);changed++;

let v943=read('tests/run-v9.43-tests.js');
v943=v943.replace("assert.strictEqual(area.strategy,'ordered-fragment-concatenation','the surviving application chain stays exact-owned so no behavior is rewritten');","assert(['ordered-fragment-concatenation','semantic-delta-replay'].includes(area.strategy),'later releases may semantically retire the surviving v9.43 ledger without rewriting the v9.43 retirement fact');");
v943=v943.replace("assert.strictEqual(app.sourceRelease,'v9.43','appCurrent declares the retirement release');","assert.strictEqual(app.requestRetirementRelease||app.sourceRelease,'v9.43','appCurrent preserves v9.43 as the request/stale-overlay retirement release');");
const ownerStart="test('v9.43 application owner concatenates only the surviving fragments'";const ownerEnd="test('v9.43 proves every retired overlay is inert, not merely unused-looking'";
if(v943.includes(ownerStart)){const a=v943.indexOf(ownerStart),b=v943.indexOf(ownerEnd,a);if(b<0)throw new Error('v9.43 owner test end missing');const replacement=`test('v9.43 surviving application ledger remains traceable after later semantic retirement',()=>{\n const area=manifest.bundles.areas.find(area=>area.id==='app'),app=manifest.appCurrent,owner=read(area.owner);\n assert.strictEqual(area.fragments.length,43,'v9.43 keeps the 43 load-bearing survivors as the frozen semantic ledger');\n assert.strictEqual(app.requestRetirementRelease||app.sourceRelease,'v9.43','v9.43 remains the recorded request/stale-overlay retirement milestone');\n for(const rel of area.fragments)assert(owner.includes((area.strategy==='semantic-delta-replay'?'obol-app-delta: ':'obol-runtime-fragment: ')+rel),'current application owner keeps the v9.43 surviving source trace: '+rel);\n});\n\n`;v943=v943.slice(0,a)+replacement+v943.slice(b);}
v943=v943.replace("assert.strictEqual(p.flattenedHistoricalFragments,172,'domain and core stay semantically flattened');","assert(p.flattenedHistoricalFragments>=172,'later semantic retirement may grow the flattened bucket without rewriting v9.43');");
v943=v943.replace("assert.strictEqual(p.liveStartupHistoricalFragments,43,'projection counts only the surviving application fragments as exact-owned startup runtime');","assert(p.liveStartupHistoricalFragments<=43,'later semantic application retirement may reduce exact-owned startup history below the v9.43 value');");
v943=v943.replace("assert(/\\*\\*Current runtime ownership areas:\\*\\* 7 owners account for \\d+ historical fragments — 172 semantically flattened, \\d+ still exact-owned; \\d+ fragments stay retired in the frozen ledger\\./.test(readme),'README Product Build Next reports semantic flattening plus retirement');","assert(/\\*\\*Current runtime ownership areas:\\*\\* 7 owners account for \\d+ historical fragments — \\d+ semantically flattened, \\d+ still exact-owned; \\d+ fragments stay retired in the frozen ledger\\./.test(readme),'README Product Build Next reports semantic flattening plus retirement');");
v943=v943.replace("assert(readme.includes('Report base and application UI (43, ordered-fragment-concatenation)'),'README reports the post-retirement application owner');","assert(readme.includes('Report base and application UI (43, '),'README keeps the 43-fragment application source ledger visible regardless of later execution strategy');");
write('tests/run-v9.43-tests.js',v943);changed++;

let boot=read('tools/validate-current-boot.js');
boot=boot.replace("const track=q.tracks.find(t=>t.id==='architecture-runtime');assert(track&&track.complete===18&&track.total===21,'architecture metrics add the corrective item instead of rewriting history');","const track=q.tracks.find(t=>t.id==='architecture-runtime');assert(track&&track.complete>=18&&track.total>=21,'architecture metrics preserve the v9.46 additive correction even as later items are added');");
boot=boot.replace("const app=m.bundles.areas.find(a=>a.id==='app');assert(app&&app.strategy==='ordered-fragment-concatenation'&&app.fragments.length===43,'app compatibility remains honestly exact-owned at 43 fragments');","const app=m.bundles.areas.find(a=>a.id==='app');assert(app&&app.fragments.length===43,'v9.46 boot proof keeps the 43-fragment application ledger even if a later release semantically retires its execution strategy');");
boot=boot.replace("console.log('Current boot ownership valid: compatibility startup is hidden until the explicit stable current route owner commits first paint; app fragment accounting remains 43 exact-owned.');","console.log('Current boot ownership valid: startup is hidden until the explicit stable current route owner commits first paint; the v9.46 43-fragment application ledger remains accounted even when later semantic retirement changes execution ownership.');");
write('tools/validate-current-boot.js',boot);changed++;

let v946=read('tests/run-v9.46-tests.js');
v946=v946.replace("assert(track&&track.complete===18&&track.total===21);","assert(track&&track.complete>=18&&track.total>=21);");
v946=v946.replace("assert(readme.includes('**Current product-hardening queue:** 207/650 complete'),'generated Product Build Next preserves additive overall accounting');","assert(/\\*\\*Current product-hardening queue:\\*\\* \\d+\\/\\d+ complete/.test(readme),'generated Product Build Next preserves additive overall accounting as later items are added');");
v946=v946.replace("test('v9.46 fixes visible boot without claiming semantic app retirement',()=>{const app=manifest.bundles.areas.find(a=>a.id==='app');assert(app&&app.strategy==='ordered-fragment-concatenation');assert.strictEqual(app.fragments.length,43);const output=run(['tools/validate-current-boot.js']);assert(output.includes('app fragment accounting remains 43 exact-owned'));});","test('v9.46 preserves its first-paint contract after later semantic app retirement',()=>{const app=manifest.bundles.areas.find(a=>a.id==='app');assert(app&&app.fragments.length===43);assert(/deeper semantic retirement remains future work|semantic retirement/i.test(read('docs/v9.46.md')));const output=run(['tools/validate-current-boot.js']);assert(output.includes('43-fragment application ledger remains accounted'));});");
v946=v946.replace("assert(dash.includes('current first-paint gate over exact-owned compatibility'));assert(read('README.md').includes('18/21 complete'));assert(read('README.md').includes('207/650 complete'));","assert(dash.includes('runtime-app-single-paint'));assert(dash.includes('runtime-app-semantic-retirement'));assert(/Architecture \\/ runtime.*\\d+\\/\\d+ complete/.test(read('README.md')));assert(/Current product-hardening queue:\\*\\* \\d+\\/\\d+ complete/.test(read('README.md')));");
write('tests/run-v9.46-tests.js',v946);changed++;

console.log('v9.47 migration patches applied: '+changed+' file mutation groups.');
