'use strict';

const fs=require('fs');
const path=require('path');
const vm=require('vm');

const DATA=[
  'lanes.js','methodology-v2.2.js','methodology-v2.3.js','methodology-v2.5.js','tools-v2.2.js','methodology-v3.3.js','methodology-v3.4.js','methodology-v3.6.js','methodology-v4.1.js','orange-ad-2025.03.js','methodology-v4.3.js','methodology-v4.4.js','methodology-v4.5.js','methodology-v4.6.js','methodology-v4.7.js','methodology-v4.8.js','dashboard-v4.9.js','dashboard-v5.0.js','dashboard-v5.1.js','dashboard-v5.2.js','methodology-v5.3.js','dashboard-v5.3.js','methodology-v5.4.js','dashboard-v5.4.js','methodology-v5.5.js','dashboard-v5.5.js','methodology-v5.6.js','dashboard-v5.6.js','methodology-v5.7.js','dashboard-v5.7.js','methodology-v5.8.js','dashboard-v5.8.js','methodology-v5.9.js','dashboard-v5.9.js','methodology-v6.0.js','dashboard-v6.0.js','methodology-v6.1.js','dashboard-v6.1.js','methodology-v6.2.js','dashboard-v6.2.js','orange-fidelity-v6.4.js','methodology-v6.4.js','dashboard-v6.4.js','orange-fidelity-v6.5.js','methodology-v6.5.js','source-delivery-v6.5.js','dashboard-v6.5.js','project-model-v6.6.js','orange-fidelity-v6.7.js','methodology-v6.7.js','project-model-v6.7.js','orange-fidelity-v6.8.js','methodology-v6.8.js','project-model-v6.8.js','orange-fidelity-v6.9.js','methodology-v6.9.js','project-model-v6.9.js','orange-fidelity-v7.0.js','methodology-v7.0.js','project-model-v7.0.js','orange-fidelity-v7.1.js','methodology-v7.1.js','project-model-v7.1.js','orange-fidelity-v7.2.js','methodology-v7.2.js','source-delivery-v7.2.js','project-model-v7.2.js','orange-fidelity-v7.3.js','methodology-v7.3.js','source-delivery-v7.3.js','project-model-v7.3.js','orange-fidelity-v7.4.js','methodology-v7.4.js','project-model-v7.4.js','orange-fidelity-v7.5.js','methodology-v7.5.js','project-model-v7.5.js','orange-fidelity-v7.6.js','methodology-v7.6.js','project-model-v7.6.js','orange-fidelity-v7.7.js','methodology-v7.7.js','project-model-v7.7.js','orange-fidelity-v7.8.js','methodology-v7.8.js','project-model-v7.8.js','orange-fidelity-v7.9.js','methodology-v7.9.js','project-model-v7.9.js','orange-fidelity-v8.0.js','methodology-v8.0.js','project-model-v8.0.js','orange-fidelity-v8.1.js','methodology-v8.1.js','project-model-v8.1.js','orange-fidelity-v8.2.js','methodology-v8.2.js','project-model-v8.2.js'
];

const CORE=[
  'core-v2-base.js','core-v2.js','core-v2.1.js','core-v2.2.js','core-v2.3.js','core-v2.4.js','core-v2.5.js','core-v2.6.js','core-v2.7.js','core-v2.8.js','core-v2.9.js','core-v3.0.js','core-v3.1.js','core-v3.2.js','core-v3.3.js','core-v3.4.js','core-v3.5.js','core-v3.6.js','core-v3.7.js','core-v3.8.js','core-v3.9.js','core-v4.0.js','core-v4.1.js','core-v4.2.js','core-v4.3.js','core-v4.4.js','core-v4.5.js','core-v4.6.js','core-v4.7.js','core-v4.8.js','core-v4.9.js','core-v5.0.js','core-v5.1.js','core-v5.2.js','core-v5.3.js','core-v5.4.js','core-v5.5.js','core-v5.6.js','core-v5.7.js','core-v5.8.js','core-v5.9.js','core-v6.0.js','core-v6.1.js','core-v6.2.js','core-v6.4.js','core-v6.5.js','core-v6.6.js','core-v6.7.js','core-v6.8.js','core-v6.9.js','core-v7.0.js','core-v7.1.js','core-v7.2.js','core-v7.3.js','core-v7.4.js','core-v7.5.js','core-v7.6.js','core-v7.7.js','core-v7.8.js','core-v7.9.js','core-v8.0.js','core-v8.1.js','core-v8.2.js'
];

function execute(file){vm.runInThisContext(fs.readFileSync(file,'utf8'),{filename:file});}
function loadCurrent(root){root=root||path.join(__dirname,'..');if(global.OBOL_CORE_V82&&global.OBOL_CORE_V2&&global.OBOL_LANES)return{C:global.OBOL_CORE_V2,lanes:global.OBOL_LANES,project:global.OBOL_PROJECT_V82};global.window=globalThis;if(!global.DOMParser)global.DOMParser=function(){};for(const name of DATA)execute(path.join(root,'data',name));for(const name of CORE)execute(path.join(root,'assets',name));if(!global.OBOL_CORE_V82||!global.OBOL_CORE_V2||!global.OBOL_LANES)throw new Error('Current Obol runtime failed to initialize');return{C:global.OBOL_CORE_V2,lanes:global.OBOL_LANES,project:global.OBOL_PROJECT_V82};}
module.exports={DATA,CORE,loadCurrent};
