'use strict';
const assert=require('assert');
const path=require('path');
const root=path.join(__dirname,'..');
const dims=['path-bindings','tool-cards','gui-controls','scripts-one-liners','command-templates','terminal-analyzers','evidence-expectations','path-movement','lesson-boxes','examples','troubleshooting','cleanup','report-guidance','product-mechanics','product-gaps','orange-baseline'];
globalThis.OBOL_NOTE_INTEGRATION={publicFieldNotes:[],reviewedDispositions:[],ledger:{expectedNotes:556,reviewedCount:135},validate:()=>[]};
globalThis.OBOL_PRODUCT_HARDENING={tracks:[{id:'notes-integration',complete:55,total:556}],items:[{id:'notes-mechanic-backfill',status:'queued'},{id:'notes-disposition-burn-down',status:'queued'}]};
globalThis.OBOL_PRODUCT_HARDENING_NOTE_PROGRESS={reviewed:135,total:556,remining:{reminedNoteCount:127,audited:127,oldRubricOnlyRemaining:8,auditRows:[]}};
globalThis.OBOL_LANES=[{id:'linux-privesc',lane:'linux-privesc',title:'Linux Privilege Escalation',cards:[]}];
globalThis.CARDS={};
globalThis.OBOL_INTAKE_V21={analyzeTerminal:()=>({activities:[]})};
globalThis.liveCardById=(id)=>globalThis.CARDS[id]||null;
const mod=require(path.join(root,'data/product-hardening/linux-final-remine-batch-v9.72.js'));
assert.deepStrictEqual(mod.validate(),[]);
assert.strictEqual(mod.remineAuditRows.length,8,'v9.72 should close the final 8 old-rubric rows');
assert.strictEqual(mod.publicNotes.length,5,'v9.72 should publish five public-safe notes');
assert.strictEqual(mod.FOLDED_CARD,'linux-service-footprint-secret-review','service footprint must be tracked as folded, not primary');
for(const row of mod.remineAuditRows){
 assert.strictEqual(row.selectorBatch,'notes-batch-old-rubric-reviewed-remine-004');
 assert.strictEqual(row.originalSourceReread,true);
 assert.ok(row.productChanges.includes('folded-card:linux-service-footprint-secret-review'),row.noteId+' should record folded service-footprint disposition');
 assert.ok(row.productChanges.includes('live-card:linux-privesc-boundary-sweep'),row.noteId+' should bind to the merged Linux boundary card');
 for(const dimension of dims) assert.ok(row.decisions&&row.decisions[dimension],row.noteId+' missing '+dimension);
}
for(const note of mod.publicNotes){
 assert.ok((note.cardIds||[]).includes('linux-privesc-boundary-sweep'),note.id+' should bind to merged boundary card');
 assert.ok(!(note.cardIds||[]).includes('linux-service-footprint-secret-review'),note.id+' must not bind to folded standalone card');
}
const card=globalThis.CARDS['linux-privesc-boundary-sweep'];
assert.ok(card,'linux-privesc-boundary-sweep should exist');
assert.ok(!globalThis.CARDS['linux-service-footprint-secret-review'],'linux-service-footprint-secret-review should be folded away, not primary');
assert.ok(Array.isArray(card.foldedFrom)&&card.foldedFrom.includes('linux-service-footprint-secret-review'),'merged card should record folded origin');
assert.ok(Array.isArray(card.commands)&&card.commands.length>=9,'merged Linux card should have a broad command spine');
assert.ok(card.commands.every(command=>command.tool&&command.run&&command.when&&command.evidence),'command schema should be tool/run/when/evidence');
const commandText=card.commands.map(command=>command.run).join('\n');
assert.match(commandText,/ps auxww/,'merged card should include service-process review');
assert.match(commandText,/tcpdump/,'merged card should include bounded tcpdump review');
assert.match(commandText,/sudo -l/,'merged card should include sudo boundary review');
assert.match(commandText,/getcap/,'merged card should include capability review');
assert.match(commandText,/uname -a/,'merged card should include kernel context review');
assert.ok(Array.isArray(card.expectedEvidence)&&card.expectedEvidence.length>=6,'merged card needs paste-back evidence guidance');
assert.ok(Array.isArray(card.failureModes)&&card.failureModes.length>=5,'merged card needs decision/failure guidance');
assert.ok(Array.isArray(card.nextSteps)&&card.nextSteps.length>=5,'merged card needs path movement guidance');
assert.ok(card.lesson&&/folds service-footprint/i.test(card.lesson),'lesson should explain why service-footprint was folded');
assert.strictEqual(globalThis.OBOL_PRODUCT_HARDENING_NOTE_PROGRESS.remining.reminedNoteCount,135);
assert.strictEqual(globalThis.OBOL_PRODUCT_HARDENING_NOTE_PROGRESS.remining.oldRubricOnlyRemaining,0);
assert.strictEqual(globalThis.OBOL_PRODUCT_HARDENING.nextNotesBatch.id,'notes-disposition-pending-review-001');
assert.strictEqual(globalThis.OBOL_PRODUCT_HARDENING.items.find(i=>i.id==='notes-mechanic-backfill').status,'complete');
const intake=globalThis.OBOL_INTAKE_V21.analyzeTerminal('ps auxww root sshpass password env SCRIPT_CREDENTIALS sudo -l NOPASSWD find / -perm -4000 -type f -ls getcap cap_setuid+ep cron ExecStart uname -a PRETTY_NAME tcpdump packet');
assert.ok(intake.activities.some(activity=>activity.analyzerId==='linux-footprint-evidence-analyzer'));
assert.ok(intake.activities.some(activity=>activity.analyzerId==='linux-privesc-boundary-analyzer'));
console.log('v9.72 folded Linux final source re-mining validator passed.');
